### ISSUE TITLE
How to groupBy the result of a function call (and maybe, how to use arbitrary PG functions) 

### ISSUE THREAD

**Issue by dbp** [tomjaguarpaw/haskell-opaleye#100]
Here's a simple query that I'd like to be able to write:

select sum(quantity * price_in_cents), to_char(updated_at, 'YYYY-MM') from line_items group by to_char(updated_at, 'YYYY-MM');

I added two Column -> Column functions for `*` and `to_char` (qualified import names match those in the operators module):

```
(.*) :: Column T.PGInt4 -> Column T.PGInt4 -> Column T.PGInt4
(.*) = C.binOp HPQ.OpMul

getYearMonth :: Column T.PGTimestamptz -> Column T.PGText
getYearMonth (C.Column d) = C.Column (HPQ.FunExpr "to_char" [d, HPQ.ConstExpr (HPQ.StringLit "YYYY-MM")])
```

And then I have a query:

```
revenueByMonths :: Query (Column PGText, Column PGInt4)
revenueByMonths =
  aggregate (p2 (groupBy, sum)) $ proc () ->
    do (LineItem (_ :: Column PGInt4) upd q pr) <- queryAll -< ()
       returnA -< (getYearMonth upd, q .* pr)
```

Which produces SQL that doesn't work. The SQL generated is:

```
SELECT "result0_2" as "result1_3",
       "result1_2" as "result2_3"
FROM (SELECT *
      FROM (SELECT to_char("updated_at1_1",E'YYYY-MM') as "result0_2",
                   SUM(("quantity2_1") * ("price_in_cents3_1")) as "result1_2"
            FROM (SELECT *
                  FROM (SELECT "id" as "id0_1",
                               "updated_at" as "updated_at1_1",
                               "quantity" as "quantity2_1",
                               "price_in_cents" as "price_in_cents3_1"
                        FROM "line_items" as "T1") as "T1") as "T1"
            GROUP BY COALESCE (to_char("updated_at1_1",E'YYYY-MM'))) as "T1") as "T1"
```

Where the problem is the COALESCE (if it's removed, the query works as expected).

Is there a way to do this that works?

**Comment by tomjaguarpaw** [comment]
I can remove the `COALESCE` for non-literals (in fact that's the sensible thing to do and I've been meaning to do it anyway) but I don't understand *why* it doesn't work.  What error do you get?

**Comment by dbp** [comment]
The error it gives is:

```
ERROR:  column "T1.updated_at1_1" must appear in the GROUP BY clause or be used in an aggregate function
LINE 4:       FROM (SELECT to_char("updated_at1_1",E'YYYY-MM') as "r...
```

Which makes it seem like with the `COALESCE`, it no longer sees what is being grouped by and what is being selected as the same thing...

**Comment by tomjaguarpaw** [comment]
By the way, doesn't the `Num` instance of `Column PGInt4` do what you want?

**Comment by tomjaguarpaw** [comment]
For `*` I mean.

**Comment by dbp** [comment]
@tomjaguarpaw Ahh, yes. I didn't realize there was a `Num` instance!

**Comment by tomjaguarpaw** [comment]
Can you understand that error?  `"updated_at1_1"` *does* appear in the `GROUP BY` clause.

**Comment by tomjaguarpaw** [comment]
Yeah, the documentation could be clearer: tracking as https://github.com/tomjaguarpaw/haskell-opaleye/issues/101

**Comment by dbp** [comment]
I don't understand postgres well enough to say exactly, but my guess is that the wrapping `COALESCE` makes it treated as distinct. Because I guess if the `COALESCE` had multiple arguments, then the grouping wouldn't work (as if the first argument was non-null, the later arguments could vary arbitrarily within the same group). Obviously, with one argument `COALESCE` is an identity, but I guess postgres doesn't treat it that way (this is on 9.4.4, btw). Or at least, that's my best guess!

**Comment by tomjaguarpaw** [comment]
Ah, I guess it doesn't quite mean "appear".  The non-aggregate values in the SELECT must be equal within groups and, without checking further, it can't guarantee that in this case.

I might need to spend more time thinking through the semantics of `Aggregator`s.  Until then feel free to try the below.  I will test and merge shortly.

````haskell
--- a/src/Opaleye/Internal/HaskellDB/Sql/Print.hs
+++ b/src/Opaleye/Internal/HaskellDB/Sql/Print.hs
@@ -31,8 +31,8 @@ import Text.PrettyPrint.HughesPJ (Doc, (<+>), ($$), (<>), comma, doubleQuotes,
 -- Silliness to avoid "ORDER BY 1" etc. meaning order by the first column
 -- Any identity function will do
 deliteral :: SqlExpr -> SqlExpr
-deliteral c@(ColumnSqlExpr (SqlColumn _)) = c
-deliteral expr = FunSqlExpr "COALESCE" [expr]
+deliteral expr@(ConstSqlExpr _) = FunSqlExpr "COALESCE" [expr]
+deliteral expr                  = expr
 
 ppWhere :: [SqlExpr] -> Doc
 ppWhere [] = empty
````

**Comment by tomjaguarpaw** [comment]
Seems to work.  Enjoy!

**Comment by tomjaguarpaw** [comment]
By the way, with my Clippy hat on: "It looks like you're trying to `GROUP BY` year and month."  I would *guess* you're better off by projecting the year and month out as integers and grouping on those rather than trying to do something symbolic.

**Comment by dbp** [comment]
@tomjaguarpaw Thanks! Re: Clippy: :) Having actual values rather than serialized into strings is definitely more useful once this actually gets combined with other stuff (and at that point, it'll be a lot more complicated _anyway_.

**Comment by benkolera** [comment]
I just hit this bug too with a very similar thing. Thanks for doing all the hard work already. :) 

Any chance of this fix being in a hackage release soon?  If not, that's ok but what's the state of master? Would it be best to:
- Just build from master?
- Download a sdist 0.4.0.0 and apply this patch?

**Comment by tomjaguarpaw** [comment]
@benkolera http://hackage.haskell.org/package/opaleye-0.4.1.0

If you ever need a release just file an issue.

**Comment by benkolera** [comment]
Oh, that's wonderful! Thank you @tomjaguarpaw !! :)
