### ISSUE TITLE
Add some instances for types of the form C a => C (Column a)

### ISSUE THREAD

**Issue by djeik** [tomjaguarpaw/haskell-opaleye#107]
For instance, if we have `C = IsString`, then we can use the OverloadedStrings extensions to insert `String`, `Text`, and `ByteString` values in user-defined product types, rather than have to use `pgString` . 
There is already an instance like this for Num, which is what lets the tutorial look like it can directly insert integers, whereas in reality the Num instance for columns is doing some work that's not immediately clear in the tutorial.

**Comment by bergmark** [comment]
Also see #80 #81

**Comment by tomjaguarpaw** [comment]
`IsString (Column PGText)` certainly makes sense.  I don't see what you mean "we can use the OverloadedStrings extensions to insert `String`, `Text`, and `ByteString` values in user-defined product types" though.  `IsString` will only help for literals.

**Comment by djeik** [comment]
@tomjaguarpaw I meant that we would be able to use literals to insert those types of values. My wording was pretty unclear though; sorry.

**Comment by tomjaguarpaw** [comment]
Well, technically it wouldn't be a literal of those types, it would be a literal of type `Column (PGText)`.  But yes, this is a good idea.  Feel free to add it next to the `Num` instance.

**Comment by tomjaguarpaw** [comment]
@mitchellwrosen has started off this work on #129.  Feel free to file a new issue if you want to discuss support for further types.
