### ISSUE TITLE
deriving adaptor instances for newtypes now allowed

### ISSUE THREAD

**Issue by andrewthad** [tomjaguarpaw/haskell-opaleye#114]
In the documentation here https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/Doc/Tutorial/TutorialBasic.lhs#L759
You mention that you can't automatically get the instances for a newtype. The release of product-profunctors-0.6.3.1 appears to have fixed this issue.

**Comment by tomjaguarpaw** [comment]
Good point.  Thanks for filing the issue.  I'll fix it when I get round to it, or feel free to make a PR.
