### ISSUE TITLE
equality with newtype wrappers

### ISSUE THREAD

**Issue by andrewthad** [tomjaguarpaw/haskell-opaleye#115]
The tutorial gives a pretty good explanation of how to add a newtype wrapper for primary/foreign keys, and then it gives an example of a query that is prevented by this extra safety. However, I can't figure out how to actually use it. I'm trying to do something like this:

    restrict -< reportCustomer report .== customerId customer

But, since `.==` only accepts `Column`s:

    (.==) :: Column a -> Column a -> Column PGBool 

This doesn't work. What is the intended way to do this?

**Comment by andrewthad** [comment]
For the time being, I'm doing this:

    (.==.) :: Coercible b (Column a) => b -> b -> Column PGBool                                           
    (.==.) x y = coerce x .== coerce y                                                                    

Which seems to work alright.

**Comment by bergmark** [comment]
Why is it a problem that `.==` only accepts `Column`s? I don't see how anything else makes sense.

FWIW we have defined safe coercions like so: https://github.com/silkapp/silk-opaleye/blob/master/src/Silk/Opaleye/ShowConstant.hs#L48

**Comment by andrewthad** [comment]
I agree that it is really only sensible that it should work with `Column`s. However, this means that the recommendation in the tutorial leaves you with a WarehouseId that there's no obvious way to do anything with. The understanding I have after working through the tutorial is that primary key `Column`s should be wrapped in a newtype (in the tutorial it shows `data` instead, but using `newtype` is now allowed):

    data WarehouseId' a = WarehouseId a
    $(makeAdaptorAndInstance "pWarehouseId" ''WarehouseId')
    
    type WarehouseIdColumn = WarehouseId' (Column PGInt4)   
    type GoodWarehouseColumn = Warehouse' WarehouseIdColumn
                                           (Column PGText)
                                           (Column PGInt4)
    
    goodWarehouseTable :: Table GoodWarehouseColumn GoodWarehouseColumn
    goodWarehouseTable = Table "warehouse_table"
            (pWarehouse Warehouse { wId       = pWarehouseId (WarehouseId (required "id"))
                                  , wLocation = required "location"
                                  , wNumGoods = required "num_goods" })

If I'm using `WarehouseId' (Column PGInt4)` as the primary key column type, I need to be able to compare it to other columns of the same type. But I can't do that with `.==`, so I'm wondering if opaleye provides some way to do this or if everyone just comes up with their own way to hack around it.

**Comment by bergmark** [comment]
I'm not familiar with the tutorial but there's certainly more than one way to do it.

I've never considered defining keys like that, we simply do `newtype Id = Id Int` and then we get `Column Id`. Then we can safely coerce between Column Id, Column Int, and Column PgInt4.

**Comment by andrewthad** [comment]
That seems way more sensible.

**Comment by tomjaguarpaw** [comment]
This has been conspicuously missing for some time, but I recently added the polymorphic equality operators `.===` and `./==` for just this use case https://github.com/tomjaguarpaw/haskell-opaleye/commit/5267c38da08866506817052230a4f34e839a23dd

**Comment by tomjaguarpaw** [comment]
This is only on the master branch at the moment.  If you need a Hackage release then please file an issue.

**Comment by andrewthad** [comment]
Thanks for letting me know. I can wait for a release and make do with my custom equality operator in the meantime. Also, just out of curiosity, what advantage does your method of wrapping the column provide? It seems like it is harder to use with the standard opaleye equality operator, so I assume that there's something that is more natural with it as well.

**Comment by andrewthad** [comment]
When compared to @bergmark's approach, that is.

**Comment by tomjaguarpaw** [comment]
I'm not sure I'd say it's harder.  I just haven't generalised the "standard" equality operator because it's a potentially breaking change.

The product polymorphic `.===` is useful for reasons other than wrapping key fields in newtypes, it just so happens it solves that case *as well*, so it makes sense to use it for that rather than inventing another technique.

One question that suggests the newtype wrapping is the right way, and changing the type of the column is the wrong way, is "What would you do if your key consisted of more that one column?".

**Comment by tomjaguarpaw** [comment]
Now uploaded to Hackage http://hackage.haskell.org/package/opaleye-0.4.2.0

Please let me know how you get on.

**Comment by andrewthad** [comment]
Thanks. That works perfectly.
