### ISSUE TITLE
semijoin and antijoin

### ISSUE THREAD

**Issue by andrewthad** [tomjaguarpaw/haskell-opaleye#118]
Is it possible to create queries that correspond to SQL queries that use `EXISTS` or `NOT EXISTS`. Just grepping through the source, it would seem that the answer is no, but I was wondering if there's a workaround using another operator.

**Comment by tomjaguarpaw** [comment]
`EXISTS` doesn't exist (!) though I don't think it should be hard to add.  However, in many cases it's possible to do without `EXISTS` at all.  Could you share the query you're trying to write?  I will see if I can write it in another way.

**Comment by andrewthad** [comment]
I've basically got three levels that can be used to override the information associated with a plugin (the information is known as the `plugdata`). The SQL that I've written for this (which uses a few CTEs):

    WITH
    pids AS (
      SELECT DISTINCT item.plugin_ident as plugin_ident
      FROM report
        INNER JOIN host ON report.id = host.report
        INNER JOIN item ON (host.ip = item.ip) AND (host.report = item.report)
      WHERE report.customer = ?
    ),  
    host_info AS (
      SELECT pids.plugin_ident as plugin_ident, hostplug.plugdata as plugdata, 'Host'::text as override_level
      FROM pids INNER JOIN hostplug ON hostplug.plugin_ident = pids.plugin_ident
      WHERE hostplug.customer = ?
        AND hostplug.ip = ?
    ),  
    customer_info AS (
      SELECT pids.plugin_ident as plugin_ident, custoplug.plugdata as plugdata, 'Customer'::text as override_level
      FROM pids INNER JOIN custoplug ON custoplug.plugin_ident = pids.plugin_ident
      WHERE custoplug.customer = ?
        AND NOT EXISTS (SELECT 1 FROM host_info WHERE pids.plugin_ident = host_info.plugin_ident)
    ),  
    global_info AS (
      SELECT pids.plugin_ident as plugin_ident, plugin.plugdata as plugdata, 'Global'::text as override_level
      FROM pids INNER JOIN plugin ON plugin.ident = pids.plugin_ident
        AND NOT EXISTS (SELECT 1 FROM host_info WHERE pids.plugin_ident = host_info.plugin_ident)
        AND NOT EXISTS (SELECT 1 FROM customer_info WHERE pids.plugin_ident = customer_info.plugin_ident)
    ),  
    all_info as (
      SELECT * FROM host_info UNION ALL (SELECT * FROM customer_info) UNION ALL (SELECT * FROM global_info)
    )   
    SELECT all_info.plugin_ident, ??, all_info.override_level
      FROM all_info INNER JOIN plugdata ON plugdata.id = all_info.plugdata
      ORDER BY plugdata.severity DESC, plugdata.name
    ;   

There's a lot in that query, but the main thing to focus on is the `host_info`, `customer_info`, and `global_info` CTEs. Notice how `customer_info` checks (with the `AND NOT EXISTS` line) that we didn't already get information for this plugin in the `host_info` CTE. And then we do something similar in `global_info`. The entirety of the data model is going to be too time-consuming to explain, but if you can show me an example of simulating `NOT EXISTS`, I could probably get it figured out.

**Comment by andrewthad** [comment]
I've made a branch to try adding support for this. I thought you might be able to look at what I added and tell me if it is actually a step in the right direction or not: https://github.com/andrewthad/haskell-opaleye/tree/add_support_for_exists_not_exists

**Comment by tomjaguarpaw** [comment]
Those are the right places to be changing the AST.  I don't understand why it has all the constructors you've given it though.  I would have thought it would be just `Exists PrimQuery`.

**Comment by andrewthad** [comment]
The `Bool` is to distinguish `EXISTS` from `NOT EXISTS`. It's got two `PrimQuery`s because one is the existing query and one would be the one that get added in a clause that says `WHERE [NOT] EXISTS (subquery goes here)`.

I was originally thinking about doing it with only one `PrimQuery` and then grafting it on with the `Product` data constructor (which seems to be the way to generate `WHERE` clauses). But, `Product` can only accept `HPQ.PrimExpr` as it's conditions, not `PrimQuery`. Was there a different way that you were thinking of?

**Comment by tomjaguarpaw** [comment]
OK, I can see where you were going then.  I'd encourage you to press on with what you've got.  I'll also have to have a think about what the semantics of this actually are.

**Comment by andrewthad** [comment]
I'm going to try to build out the rest of it tomorrow and see what happens. But yeah, just keep thinking on it.

**Comment by tomjaguarpaw** [comment]
The following is valid in Postgres, which suggests that `exists` should have the following type

    select (exists (values (1))) as hi;

    exists :: Query a -> Query (Column PGBool)

and 

     | Exists PrimQuery Bool

(In fact I'd also get rid of the `Bool` since we already have not)

**Comment by andrewthad** [comment]
Thanks, that's very helpful. And yeah, I will get rid of the Boolean sense we should be able to do that already with the not combinator.

**Comment by tomjaguarpaw** [comment]
You should now be able to implement this in terms of `Operators.inQuery`.

**Comment by tomjaguarpaw** [comment]
This ticket seems to have been resolved.  Please reopen it or file a new one if it is still an issue.
