### ISSUE TITLE
Include query identifier with generated SQL

### ISSUE THREAD

**Issue by thomasvnoort** [tomjaguarpaw/haskell-opaleye#123]
Right now it's pretty hard to link generated SQL found in the Postgres logs to the original Opaleye query. I'd like to improve this to make it easier to, for instance, debug slow queries. This information should be included in the generated SQL to end up in the Postgres logs, so something like this would work:

`select res.* from (select 'my_opaleye_identifier') as debug, (<complicated_opaleye_query>) as res;`

This is quite hacky but has little to none impact on the actual query. You can argue that the generated query becomes even more complex, but it's hard to read already :)

Do you have any ideas on how to do this?

**Comment by tomjaguarpaw** [comment]
Would a comment work?

**Comment by thomasvnoort** [comment]
Wonderful! I forgot about comments completely, that would be very nice to have.

**Comment by tomjaguarpaw** [comment]
Well this certainly sounds like a reasonable request.  I am open to suggestions as to what the API should look like!
