### ISSUE TITLE
Algebra for execute/query

### ISSUE THREAD

**Issue by srijs** [tomjaguarpaw/haskell-opaleye#125]
I find the manipulation interface a still a little lacking compared to the query part. I would like to be able to compose queries and manipulations in a single algebra, without needing to pass connections around and running inside IO.

This is roughly what I have in mind (using an operational monad):

```
data Insert a where
    InsertOne :: Table columns columns' -> columns -> Insert Int64
    InsertMany :: Table columns columns' -> [columns] -> Insert Int64
    InsertReturning :: Table columns columns' -> columns -> Insert [columns']
    ...

data Op a where
    OpQuery :: Query columns -> Op [columns]
    OpInsert :: Insert a -> Op a
    OpUpdate :: ...
    OpDelete :: ...

newtype Operation a = Operation (Program Op a)
    deriving (Functor, Applicative, Monad)

run :: Operation a -> Connection -> IO a

-- maybe also this, using resource-pool
runWithPool :: Operation a -> Pool Connection -> IO a
```

Thoughts?

**Comment by bergmark** [comment]
I agree, it feels strange that there isn't a uniform interface. It was pretty much the first thing I wrote myself: https://github.com/silkapp/silk-opaleye/blob/master/src/Silk/Opaleye/Query.hs

Also +1 for resource-pool, the only reason I can think of to use Connection directly is if you are just playing around, it makes it slightly easier to get started. For serious purposes you'll want a pool.

**Comment by tomjaguarpaw** [comment]
I'm certainly happy to improve this if we come up with some good ideas.  Could you show an example of how you want to be able to *use* the API?

**Comment by WraithM** [comment]
I wrote a thing sort of similar to @bergmark 's package. It uses STM-style transactions (so you can't nest transactions) with explicit types instead of a type-class.

```haskell
runOpaleyeT :: PSQL.Connection -> OpaleyeT m a -> m a
transaction :: MonadBase IO m => Transaction a -> OpaleyeT m a -- BEGIN; ...; COMMIT
run :: MonadBase IO m => Transaction a -> OpaleyeT m a -- Run without a transaction
query :: Default QueryRunner a b => Query a -> Transaction [b]
insert :: Table w r -> w -> Transaction Int64
```

https://github.com/WraithM/opaleye-trans/blob/master/src/Opaleye/Trans.hs

I'd be curious what this algebra would look like with modelling transactions.

**Comment by lippling** [comment]
Any news on this issue?

**Comment by tomjaguarpaw** [comment]
No news from me, sorry.  This isn't something I'm planning to work on in the near future.

**Comment by lippling** [comment]
How do you use Opaleye with transactions? I'm not sure what's a sensible, pragmatic approach.

**Comment by tomjaguarpaw** [comment]
Probably the others in this thread are better placed to answer that than me.

**Comment by WraithM** [comment]
There are a number of ways to do it! The best way that I've found is using STM style transactions with Opaleye. What I mean by that is having a separate type that has no ability to execute IO actions, like STM. Then you have a function which commits that transaction, like `atomically` in STM. This saves you from messing up nesting transactions. If you use `postgresql-simple`'s `withTransaction`, there's nothing stopping you from writing:
```
someFunction = withTransaction $ withTransaction $ ...
```
and you'll get a bunch of errors.

I wrote a library specifically for doing STM style transactions with Opaleye: 
https://hackage.haskell.org/package/opaleye-trans
https://github.com/WraithM/opaleye-trans

There's a `Transaction` type which can be transformed into a `BEGIN ... COMMIT` postgresql action with the function `transaction`, just like `STM` and `atomically`.

I was inspired to write that library from Reid Draper's `postgresql-transactional`, which does the same thing only for postgresql-simple: https://github.com/helium/postgresql-transactional

You could also adapt @reiddraper's library to opaleye.

**Comment by lippling** [comment]
@WraithM Thanks for your response!

I think I'll base my implementation on your approach. I have to add several features (like read-only transactions - and I want them typesafe) so I'll copy&paste for now. Maybe I can share my results later, if you are interested.

**Comment by WraithM** [comment]
I'll happily take pull requests or even feature requests if you want me to implement it.

**Comment by lippling** [comment]
Ok. I'll get in touch with you later, when I'm done.

**Comment by tomjaguarpaw** [comment]
I'm closing this because it's very old and I don't have any concrete plans to address it. If you think it still needs addressing or have any further details to add then please reopen or file a new issue.
