### ISSUE TITLE
aggregate, count, limit, and offset do not take arrow input

### ISSUE THREAD

**Issue by thomasvnoort** [tomjaguarpaw/haskell-opaleye#130]
We're having a hard time writing some seemingly simple queries in Opaleye. 

Consider the following contrived example:

``` sql
select t1.column1
from table1 t1 
where 
  (select count(t2.column1) 
   from table2 t2 
   where t2.column1 = t1.column1
  ) > 1;
```

In Opaleye this turns out to be something like this (in pseudo code):

``` haskell
query =
  proc () -> do
    t1  <- queryTable table1 -< ()
    cnt <- countTable2       -< t1
    where_ (\cnt -> cnt .> constant 1) -< cnt
    arr column1 -< t1
  where
    --countTable2 :: QueryArr Object Int64
    countTable2 :: Query Int64
    countTable2 = aggregate count $
      proc t1 -> do
        t2 <- queryTable table2 -< ()
        restrict -< column1 t2 .== column1 t1
        arr column1 -< t2
```

This isn't type correct since `aggregate` doesn't allow any input to the arrow since it takes a `Query` as second argument instead of a `QueryArr`. 

We run into a similar problem with `orderBy` (and `limit` and `offset`):

``` sql
select t1.column1
from table1 t1 
where 1 = 
  (select t2.column2 
   from table2 t2 
   where t2.column1 = t1.column1
   order by t2.column2 desc
  );
```

In Opaleye we end up with:

``` haskell
query =
  proc () -> do
    t1 <- queryTable table1 -< ()
    c2 <- orderTable2       -< t1
    where_ (\c2 -> constant 1 .== c2) -< c2
    arr column -< t1
  where
    --orderTable2 :: QueryArr Object Column2
    orderTable2 :: Query Column2
    orderTable2 = orderBy (desc column2) $
      proc t1 -> do
        t2 <- queryTable table2 -< ()
        restrict -< column t2 .== column t1
        arr column -< t2
```

This suffers from the same type error, `orderBy` takes a `Query` instead of a `QueryArr`.

Is there any particular why these functions do not allow any arrow input?

**Comment by tomjaguarpaw** [comment]
I'm pretty sure that if they allowed input then you could write invalid queries.  This is tied in to `QueryArr` being an arrow and not a monad.

Do you have non-contrived examples?  Both of these seem (at least at first glance) easy to rewrite in an alternative way.

**Comment by thomasvnoort** [comment]
Do you have examples of invalid queries if they would allow arrow input?

I don't think the above examples are that contrived, here's an example that is much closer to the actual query we're trying to define in Opaleye:

```sql
select * 
from objects o
where 
  not exists 
    (select * 
     from object_transformations t 
     where t.object_id = o.id 
     and t.transformation_id >= 1
    )
  and 1 = 
    (select v.format 
     from object_versions v 
     where v.object_id = o.id 
     order by v.id desc 
     limit 1
    ) 
```

The first where clause uses `not exists`, but Opaleye doesn't support that so you can rewrite that to use a `count(*)` like in the first example. The second where clause is a bit trickier since it uses `order by` to get the latest object version. Alternatively we could probably define that second clause using a join on the top-level but then you'd have to use `group by` which gives a far less efficient query plan I think. Do you have any suggestion on how to rewrite this?

**Comment by tomjaguarpaw** [comment]
Hi Thomas, thanks, that's a great example.  I can't respond right now, but will do as soon as I can.

**Comment by tomjaguarpaw** [comment]
As an example of an invalid query that could be generated, let's look at something similar to your original example, but using the aggregation in a joined subselect rather than in a `WHERE` clause.

    query =
      proc () -> do
        t1  <- queryTable table1 -< ()
        cnt <- countTable2       -< t1
        returnA  -< (t1, cnt)
      where
        countTable2 :: QueryArr Object Int64
        countTable2 = aggregate count $
          proc t1 -> do
            t2 <- queryTable table2 -< ()
            restrict -< column1 t2 .== column1 t1
            arr column1 -< t2

This would generate (roughly, syntax not quite valid)

    SELECT * FROM
        (SELECT table1.column1 FROM table1),
        (SELECT COUNT(table2.column1) FROM table2
         WHERE table2.column1 = table1.column1)

But `table1.column1` is not in scope in the second subselect (in the absense of a `LATERAL JOIN`).  In fact, I'm surprised to learn that it is in scope in your examples, where the subselect lives in a `WHERE` clause.

If we want to allow columns to be in scope in subselects in `WHERE` clauses, but statically forbid them being present in joins, then this is going to have to involve introducing at least one extra type (something like `QueryWhere`) and a special way of using it that means it will only generate code into a `WHERE` clause and not a join.  That sounds like it will require a lot of extra thinking and will probably be quite awkward.

In the first instance I would encourage you to rewrite your queries in an alternate way, perhaps using `LEFT/RIGHT JOIN`.  You should be able to take advantage of Haskell's abstraction abilities to make this fairly painless. If you profile and find that the rewritten versions pay a significant performance penalty then please come back and we'll discuss it further.

**Comment by tomjaguarpaw** [comment]
By the way, [`inQuery`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Operators.hs#L126) does exist now, but it won't help you as it doesn't take arrow input either.

**Comment by thomasvnoort** [comment]
I managed to rewrite our actual query to use joins only, but it isn't trivial. The example query rewrites to:

```sql
select * 
from objects o
join object_versions v on v.object_id = o.id
left join 
  (select o1.id
   from objects o1
   join object_transformations t on t.object_id = o1.id
   where t.transformation_id >= 1
  ) as transformed on transformed.id = o.id
join
  (select o2.id, max(v2.object_id) as object_id
   from objects o2
   join object_versions v2 on v2.object_id = o2.id
   group by o2.id
  ) as latest on latest.id = o.id and latest.object_id = v.object_id
where transformed.id is null and 1 = v.format
```

We don't want to use a specific `o` in the subquery here, so the subqueries must return results for all (and hence join on) `objects`. The first subquery then uses a `left join` and a condition on `transformed.id` being `null` to model the `not exists`. The second subquery must use a `group by` since it should return results for all `objects`. Because the result of the second subquery used to be the `format` field, we have to join again on `object_versions` on the top-level to be able to condition on that.

Our original query used to join on two more tables and had a condition on the field of one of those two tables. I had to pusht those tables and that condition into the subqueries, otherwise these subqueries would end up doing sequential scans of million rows which performs terrible for obvious reasons. The query plan of the rewritten query still uses indexes only, which is good, but doubled the time of our original query from 150ms to 300ms. For now this is acceptabel for us, so I can move on and use that rewritten query.

I can see that allowing arrow input would allow us to define bad queries, but I do think that it would be good to support such queries since the transformation is non-trivial and you likely end up with a slower query.

**Comment by thomasvnoort** [comment]
By the way, let me know if you need to see query plans before and after.

**Comment by tomjaguarpaw** [comment]
Thanks for the specifics and the details about performance.  I think this means in the long run that we need to support arrow input into where clauses.  However, doing so in a typesafe way is not a trivial undertaking.

**Comment by thomasvnoort** [comment]
A small addition, the rewritten query above performs very poorly on large tables even though it uses indexes. Where my original (plain-text) query takes a couple of seconds, the rewritten query takes about 10 minutes. I don't have an exact cause, but I can imagine not using `not exists` or a subquery can cause Postgres to miss some optimisations.

**Comment by tomjaguarpaw** [comment]
OK, it seems like I will have to work out how to get this valid (Postgres) SQL to be accepted by the type system.  I won't have much time to do this for a couple of months but if you need this urgently please let me know.

**Comment by hesselink** [comment]
I just ran into this again (in a completely different use case). Have you thought about a solution to this some more?

**Comment by tomjaguarpaw** [comment]
I haven't thought about it at all, I'm afraid.  Can you show the SQL equivalent that you are trying to acheive?

**Comment by hesselink** [comment]
Very briefly, it looks like this:

```
SELECT
  (SELECT array_agg(...) FROM bar b where f.id = b.foo_id and ...)
, (SELECT array_agg(...) FROM bar b where f.id = b.foo_id and ...)
, (SELECT array_agg(...) FROM bar b where f.id = b.foo_id and ...)
...
FROM foo f
WHERE ...
ORDER BY
(SELECT array_agg(...) FROM bar b where f.id = b.foo_id GROUP BY 
```

**Comment by tomjaguarpaw** [comment]
Hmm, I think this is even more complicated than the previous version.  It seems that `f` can be referenced in scalar subselects, not just in the `WHERE` clause.

**Comment by hesselink** [comment]
You're right, I hadn't even realized that.

**Comment by xnmp** [comment]
A workaround is to define

```haskell
instance ArrowApply QueryArr where
  app    = O.QueryArr (f) 
    where f ((O.QueryArr g, b), pq, t) = g (b, pq, t)
```

and use `-<<` instead of `-<` every time you need an arrow to depend on previous output. Of course then it's up to you to not to write invalid queries.

**Comment by tomjaguarpaw** [comment]
Sure, but that's equivalent to writing a monad instance.

**Comment by tomjaguarpaw** [comment]
Closing as stale.
