### ISSUE TITLE
Add support for PostgreSQL "SELECT ... FOR UPDATE"

### ISSUE THREAD

**Issue by bitc** [tomjaguarpaw/haskell-opaleye#134]
There doesn't seem to be a way to add a SQL locking clause to a SELECT query run with `Opaleye.runQuery`

http://www.postgresql.org/docs/current/static/sql-select.html#SQL-FOR-UPDATE-SHARE

**Comment by tomjaguarpaw** [comment]
Hi @bitc, thanks for the feature request.  You are correct that this is not yet supported.  I'm afraid I don't have time to work on this right now but I'm happy to guide you (or anyone else) through implementing it.

**Comment by DanBurton** [comment]
@tomjaguarpaw I'm only interested in `lockingFor Update` at the moment, but yes, that API looks reasonable to me.

**Comment by remeike** [comment]
Also wanted to express continued interest in this feature!

**Comment by tomjaguarpaw** [comment]
What functionality do people want here?  The full grammar is

```
FOR lock_strength [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ]
```

where `lock_strength` can be one of

```
UPDATE
NO KEY UPDATE
SHARE
KEY SHARE
```

I've only heard requests for `lock_strength` of `UPDATE` so far. Does anyone want anything else?  Do people want  `OF table_name [, ...]` or `[ NOWAIT | SKIP LOCKED ]` support?

**Comment by remeike** [comment]
Not sure how much others are looking for an API covering that whole spec, but my specific case also happens to just be for `UPDATE` so just covering `lock_strength` would be enough for me.

**Comment by tomjaguarpaw** [comment]
Is it sufficient to just be able to add `FOR UPDATE` after a `SELECT`?  So what would normally be

```
SELECT
...
```

becomes

```
SELECT
...
FOR UPDATE
```

And if so, is it fine if this is done in a nested sub-select, i.e.

```
SELECT * FROM
(SELECT
 ...)
FOR UPDATE
```

If so then this is quite easy to add as a function `forUpdate :: Select a -> Select a`.

(Sorry if this is a somewhat naive question. I've never used this functionality of Postgres.)

**Comment by remeike** [comment]
I'm certainly none the wiser about this! I've just been refactoring an older Haskell codebase that contains a lot of raw SQL queries and stumbled on one with a `FOR UPDATE` clause. I'm pretty much just trying to use Opaleye wherever possible.

So I looked at the documentation and it appears that using `FOR UPDATE` with nested sub queries shouldn't be a problem at all. I even tried it out myself and it worked just fine. 

One thing to note is that in the case that one has has a `FOR UPDATE` clause nested in another `SELECT`, i.e.
```
SELECT * FROM (SELECT .... FOR UPDATE) WHERE id = 1
```
the rows that get locked are the ones returned to the outer query. In any case, I think this is the behavior that one would expect/want anyway?

Perhaps a bigger concern is that row locking does not work with aggregation. So if there is a `GROUP BY` or aggregate function anywhere in your query then you'll get an error. Maybe having a warning in the Opaleye documentation would suffice for this?

**Comment by tomjaguarpaw** [comment]
Please try https://github.com/tomjaguarpaw/haskell-opaleye/tree/for-update and see if it works for your purposes.

@remeike tangentially, I'd be really interested to learn more about how you are using Opaleye, how satisfactory it has been for you and whether there's any more help that you need.  If you'd be happy to share that information with me I'd love to receive an email from you.  [My contact details can be obtained via the README](https://github.com/tomjaguarpaw/haskell-opaleye/#contact-the-author).

**Comment by tomjaguarpaw** [comment]
> Please try https://github.com/tomjaguarpaw/haskell-opaleye/tree/for-update and see if it works for your purposes.

Specifically, I added https://github.com/tomjaguarpaw/haskell-opaleye/blob/for-update/src/Opaleye/Internal/Locking.hs

**Comment by remeike** [comment]
I just tried it out and it works great. I should note that my particular use case is very basic as I only need to query a single table, but it definitely works.

And yes, I'll definitely send you an email soon. Opaleye's been a delight, so I'd be happy to share my thoughts.

**Comment by tomjaguarpaw** [comment]
> I just tried it out and it works great. I should note that my particular use case is very basic as I only need to query a single table, but it definitely works.

Great to know, thanks!

> And yes, I'll definitely send you an email soon. Opaleye's been a delight, so I'd be happy to share my thoughts.

Looking forward to it :)

**Comment by tomjaguarpaw** [comment]
This will be in the next release. Please open a new issue if you need a new release.
