### ISSUE TITLE
Type of aggregators (sum, max, ...) is incorrect without groupBy

### ISSUE THREAD

**Issue by hesselink** [tomjaguarpaw/haskell-opaleye#138]
If you use most of the aggregation functions (I think it's everything but `groupBy` and `count`) without using `groupBy`, they can return `NULL` when there are no rows in the input. Since the Haskell types don't reflect this, this will cause a runtime crash like:

```
*** Exception: UnexpectedNull {errSQLType = "int4", errSQLTableOid = Nothing, errSQLField = "result1_7", errHaskellType = "Int", errMessage = ""}
```

I'm not sure about a fix for this, though. The type of the aggregators could be changed to reflect the nulls, but then you'd be forced to deal with them even if you add a group by to the aggregation. Another option (which we're going to use locally for now) is to have two combinators (e.g. `max` and `maxGrouped`) where the first returns a nullable result and the second doesn't (and is still unsafe if you use it without also grouping).

**Comment by tomjaguarpaw** [comment]
Thanks for this.  The `NULL` issue is actually an inconsistency in SQL (and indeed I consider it a design bug).  The default value appears for zero rows in the group only when you group by zero columns, and never at any other time.  I believe `max` (like count) has a default value of `0` and the others have a default value of `NULL`.

Rather than provide two different versions of the aggregators (or even just the one correct `Nullable` one) I've actually considered detecting when you are grouping by zero columns and aggregating zero rows and explicitly emitting zero rows in response.  That's much more consistent.

What do you think about that?  Are there cases where you really need the inconsistant behaviour?

**Comment by hesselink** [comment]
Returning 0 rows is tricky, since the number of rows returned is not indicated in a type safe way. So in many cases you have to do unsafe calls like `head` to get the actual result (say if you're doing a `count`, you always know you'll get exactly one result) or less unsafe calls like `listToMaybe`/`headMay` (say when you're selecting by a primary key and you know you'll get 0 or 1 results). So that might not improve the situation much: you might still do the obvious thing (use `head`), it will typecheck and go right in all tests (since you test with data in expected cases) and then get a crash later when there happen to be 0 rows in some corner case.

I don't know what you mean by "need" the inconsistent behavior. I don't *need* the `NULL`, zero rows is just as good an indication of what happened. I would like a solution that makes it unlikely for this to result in a runtime crash because you're not aware of this issue when writing the code. But I think that's very hard. There might be fancy type level tricks to detect this and insert the `Nullable`s only when not grouping, but it feels to me like that would include too much complexity. Having the default return `Nullable` and having a second aggregator works, since that forces you to think about the issue but I can see how you dislike the duplication. I feel like returning 0 rows will just introduce other runtime crashes in corner cases, though perhaps I'm wrong about that.

P.S. I don't think the remark about `max` returning `0` is correct, at least not for postgresql. The documentation is unclear or even wrong for many of the aggregation operators in what they return in this case, but testing shows that all of them (except `count`) return `NULL` when no rows are returned.

**Comment by tomjaguarpaw** [comment]
> P.S. I don't think the remark about max returning 0 is correct, at least not for postgresql. The documentation is unclear or even wrong for many of the aggregation operators in what they return in this case, but testing shows that all of them (except count) return NULL when no rows are returned.

You're right.  I meant `sum`.

**Comment by hesselink** [comment]
`sum` also returns `NULL` for me...

**Comment by tomjaguarpaw** [comment]
Fair enough. I had some memory it was `0`.

**Comment by tomjaguarpaw** [comment]
Given https://github.com/tomjaguarpaw/haskell-opaleye/issues/159 I think that this bug report does not apply to 0.4.  0.4 does actually return 0 rows for an empty query.

**Comment by hesselink** [comment]
Hmm, I wasn't aware of that change, and I must say I find that very counterintuitive. This means an aggregation without grouping will always return a single row, *unless* there are no rows in the thing you're selecting from, in which case you'll get zero rows. It's a case where opaleye clearly is not a mapping to the underlying SQL. But you're probably right that given that change, this issue doesn't apply anymore.
