### ISSUE TITLE
Support for PostgreSQL INSERT ... ON  CONFLICT statements

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#139]
As documented at http://www.postgresql.org/docs/9.5/interactive/sql-insert.html#SQL-ON-CONFLICT

**Comment by tomjaguarpaw** [comment]
I've never heard of this.  I'll have to look into it ...

**Comment by ocharles** [comment]
It's very new, came out in 9.5

**Comment by tomjaguarpaw** [comment]
I've never heard of 9.5 either ... :)

**Comment by hvr** [comment]
Fwiw, the  `ON CONFLICT DO NOTHING` variant sounds like it should be easiest to implement as it's really just like a boolean flag you turn for an `INSERT`. But what should the API look like? Would we just duplicate all `runInsert*` operations...?

**Comment by ocharles** [comment]
I doubt it's just a Boolean, you have to specify which unique index to
search, and what to do when a conflict occurs.

**Comment by hvr** [comment]
@ocharles I'm confused, I've been using the `DO NOTHING` conflict-resolution myself without having to specify any index. Can you describe an example where an ordinary `INSERT` operation that can't be simply augmented by merely adding the keywords  `ON CONFLICT DO NOTHING`?

**Comment by ocharles** [comment]
Why make the assumption to DO NOTHING? There are plenty of reasons to
instead update

**Comment by hvr** [comment]
Well, my hope was that we could start somewhere with the really simple  `DO NOTHING` flavour and get something implemented useful much sooner, rather than to go straight for implementing the rather complex `DO UPDATE` variant. That being said, how would we want the API to look like for covering both? Do we want the same API to cover `DO UPDATE` and `DO NOTHING`, or are they different enough to warrant separate APIs?

**Comment by ocharles** [comment]
I'm thinking of an API like this:

```haskell
data ConflictMaker columns where
  ConflictMaker :: (columns -> [PrimExpr]) -> ConflictMaker columns

instance Monoid (ConflictMaker columns) where
  mempty = ConflictMaker (\_ -> [])
  ConflictMaker f `mappend` ConflictMaker g =
    ConflictMaker (\columns -> f columns <> g columns)

data Specifity
  = OneConflictTarget
  | AnyConflictTarget

data ConflictTarget :: * -> Specifity -> * where
  AnyConflict :: ConflictTarget columns 'AnyConflictTarget
  OnConstraint :: String -> ConflictTarget columns 'OneConflictTarget
  ForExpressions ::
    ConflictTargetMaker columns -> ConflictTarget columns 'OneConflictTarget

data OnConflict columns where
  IgnoreConflict :: ConflictTarget columns anySpecifity -> OnConflict columns
  InsteadUpdate :: ConflictTarget columns 'UniqueTarget -> OnConflict columns

runInsertOnConflict :: Connection
                    -> OnConflict columns
                    -> Table columns _
                    -> [columns]
                    -> IO ()
```

There will also be injections into `ConflictMaker` from table column names. Usage would then look like:

```haskell
runInsertOnConflict conn (IgnoreConflict AnyConflict)
runInsertOnConflict conn (IgnoreConflict (OnConstraint "index_name"))
runInsertOnConflict conn (IgnoreConflict (ForExpressions (column foo)))
runInsertOnConflict conn (InsteadUpdate (OnConstraint "index_name") (\old new -> old { tBar = tBar new ++ " duplicate" })
```

Do you think that could work? `ConflictMaker` might just go away in favour of a normal function or something, I'm still thinking out loud at the moment.

**Comment by typedrat** [comment]
I don't really know much about Opaleye internals, but I'll look at implementing something like this, since I need it right now.

**Comment by centromere** [comment]
Is this ticket blocked by something?

**Comment by ocharles** [comment]
It's blocked on someone doing the work 🙃

**Comment by tomjaguarpaw** [comment]
> It's blocked on someone doing the work 🙃
Indeed

**Comment by centromere** [comment]
I am willing to do the work, but this would be my first experience using advanced type-level features to this degree, and I don't necessarily know what API design would be best.

Is a design similar to what @ocharles posted above acceptable?

**Comment by ocharles** [comment]
It might be a case that we will only find out when we get going. I'm more than happy to help mentor you if you want to take a stab at it.

**Comment by tomjaguarpaw** [comment]
That sounds like a great arrangement. 

NB I'd very much like an implementation that doesn't use GADTs, if possible.

**Comment by ocharles** [comment]
Could you elaborate as to why?

**Comment by centromere** [comment]
@ocharles Great, thanks. `runInsertOnConflict` doesn't seem like a good idea because I may want to return rows as well as specify a conflict action. A more composable solution might be best.

**Comment by tomjaguarpaw** [comment]
> Could you elaborate as to why?

In general I prefer to start with low-tech approaches and only upgrade to high-tech approaches when  it really bring massive benefits.

**Comment by ocharles** [comment]
Right. I guess the low tech approach is to rip `runInsertOnConflict` into multiple different functions then. Basically pushing the GADT down into the function itself. (At least, in my proposed design).

**Comment by tomjaguarpaw** [comment]
Yes exactly.  At the very least that would mean I could understand it better.  I don't use GADTs much.  Anyway, it doesn't really matter.  The user-facing API is the important thing.

**Comment by ocharles** [comment]
> Anyway, it doesn't really matter. The user-facing API is the important thing.

Well that's a contradiction, as my proposed solution used GADTs *in* the public interface :wink: I think we can drop 'em though.

**Comment by tomjaguarpaw** [comment]
Aha, that makes my previous comment more understandable.  Yes, I prefer not to have them in the public interface.

**Comment by tomjaguarpaw** [comment]
Or at least let's have proposed versions with and without and we'll see which seems better.

**Comment by centromere** [comment]
For reference: https://www.postgresql.org/docs/10/static/sql-insert.html#SQL-ON-CONFLICT

I use this feature in a production microservice. The service pops elements off of a RabbitMQ queue, sprinkles in a bit of business logic, and `INSERT`s the result in to postgres. If the value already exists, I simply want nothing to happen (`DO NOTHING`). Without this feature, I need to start a transaction, check for existence, either abort or insert, and commit.

**Comment by centromere** [comment]
Another way of doing it is as follows:

```haskell
let q = arrangeInsertManySql fooTable $ fromList $ fmap constant foos
void . execute_ conn . fromString $ q <> " ON CONFLICT DO NOTHING"
```

However this won't be supported in 0.7.

**Comment by tomjaguarpaw** [comment]
Is it worth having a version that allows only `DO NOTHING` and trying to iterate towards a more featured version later?

**Comment by centromere** [comment]
Yes.

**Comment by tomjaguarpaw** [comment]
I don't understand what "conflict_target" does so I will leave that out for now unless anyone desperately wants it.

In a `DO UPDATE SET` can the values to set depend on the values that currently exist in the row?  Can the columns in the `WHERE` clause?  (I assume the latter must since I can't see what else they can depend on.)

**Comment by tomjaguarpaw** [comment]
The minimum useful thing we could do is introduce this.

```haskell
runInsertOnConflictDoNothing
:: Connection
-> Table columns columns'
-> [columns]
-> IO Int64
```

Is this sufficiently useful to someone that we should go ahead and do it?  Hopefully that will start the ball rolling and then we can add some more functionality.

**Comment by centromere** [comment]
It is sufficiently useful to me right now, however it doesn't allow me to combine `ON CONFLICT` with `RETURNING` (which I don't need at the moment).

**Comment by tomjaguarpaw** [comment]
I suggest we augment [`SqlInsert`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/ddcee2f2ba0d20ab7f8e1d2bf09e940d23f04942/src/Opaleye/Internal/HaskellDB/Sql.hs#L67
) from

```Haskell
data SqlInsert  = SqlInsert SqlTable [SqlColumn] (NEL.NonEmpty [SqlExpr])
```

to

```
data OnConflict = DoNothing

data SqlInsert  = SqlInsert SqlTable [SqlColumn] (NEL.NonEmpty [SqlExpr]) (Maybe OnConflict)
```

From there it should be easy to write `runInsertOnConflictDoNothing` by adapting [`arrangeInsertManyReturning`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Manipulation.hs#L322).  The type checker will tell you which other bits to fix up.  In particular you will need to add some code to generate the string `"ON CONFLICT DO NOTHING"`!

If anyone wants to go ahead and do this please do, otherwise I'll do it when I get around to it.

**Comment by tomjaguarpaw** [comment]
Can someone please explain what is the difference between specifying `ON CONFLICT DO NOTHING` and just not having any `ON CONFLICT` clause at all?

**Comment by tomjaguarpaw** [comment]
Perhaps `DO NOTHING` suppresses an error?

**Comment by mithrandi** [comment]
Yes, exactly; no `ON CONFLICT` clause produces an error / transaction abort when a conflict occurs, `ON CONFLICT DO NOTHING` simply silently does not insert the conflicting row(s).

**Comment by tomjaguarpaw** [comment]
I would be interested to know what people think of the API here https://github.com/tomjaguarpaw/haskell-opaleye/commit/cbceff32b141e24fae20e8a7a64db69d3ec3e3f2

**Comment by tomjaguarpaw** [comment]
And an even better version 41e7f632fa592edc1d8418c396d74ac818669abe

**Comment by tomjaguarpaw** [comment]
Probably most interesting to look at the API changes in the manipulation tutorial:

https://github.com/tomjaguarpaw/haskell-opaleye/compare/master...41e7f#diff-bac8cd364e8b820bb8d100103ae631a5R50

**Comment by tomjaguarpaw** [comment]
That link got garbled.  Here's [better link](https://github.com/tomjaguarpaw/haskell-opaleye/compare/master...41e7f#diff-bac8cd364e8b820bb8d100103ae631a5L45).

**Comment by bitonic** [comment]
@tomjaguarpaw what's the status of this? the new api would be very useful to us.

**Comment by tomjaguarpaw** [comment]
Currently hoping some people will review the API before I release it: https://github.com/tomjaguarpaw/haskell-opaleye/blob/76e035fbc655f304ff7290f77ad26b4711fd9408/Doc/Tutorial/TutorialManipulation.lhs

**Comment by tomjaguarpaw** [comment]
I've released this to Hackage in a sort of "prerelease" for 0.7.  I'd be grateful for any testing and comments.

https://hackage.haskell.org/package/opaleye-0.6.7000.0

**Comment by delanoe** [comment]
Hello, instead of doing Nothing that does not return the id of existing row on conflicts (as far as I know), how can we test null returning id ? Here is the trick to get all ids (insterted or not inserted) : http://fmcgeough.github.io/postgres-upsert/ ?

**Comment by tomjaguarpaw** [comment]
That seems to require `DO UPDATE`, which is not supported yet.

**Comment by delanoe** [comment]
yes, ok, thanks
