### ISSUE TITLE
Aggregate min on Bool column generates invalid query

### ISSUE THREAD

**Issue by coubeatczech** [tomjaguarpaw/haskell-opaleye#14]
Running `Aggregate.min` function on boolean column generates an invalid query that will fail when ran.

    select id, min(closed) from
    No function matches the given name and argument types. You might need to add explicit type casts.

Some other functions from the same module might have the same problem, like `avg` for string fields etc.

------------------------

**Idea:** It could be solved by restricting the `a` type of `min` with a methodless typeclass. All the datatypes that can be applied to the function would be instances of the typeclass.

**Comment by tomjaguarpaw** [comment]
https://github.com/tomjaguarpaw/haskell-opaleye/commit/be092f3948c56be419f1fec93f2554e5049c0d8c
