### ISSUE TITLE
How to order by nullable column

### ISSUE THREAD

**Issue by hesselink** [tomjaguarpaw/haskell-opaleye#141]
How is ordering by a nullable column supposed to work? I see `ascNullsFirst` and `descNullsLast`, but there's no instance `PGOrd a => PGOrd (Nullable a)`. So for example, this gives an error:

```
λ :t Opaleye.orderBy (desc id) (undefined :: Query (Column (Nullable PGInt8)))

<interactive>:1:18:
    No instance for (PGOrd (Nullable PGInt8))
      arising from a use of ‘desc’
    In the first argument of ‘Opaleye.orderBy’, namely ‘(desc id)’
    In the expression:
      Opaleye.orderBy
        (desc id) (undefined :: Query (Column (Nullable PGInt8)))
```

Am I doing this wrong?

**Comment by tomjaguarpaw** [comment]
I think you are doing the right thing but the needed instance is just missing as you guessed.  It seems no one ever needed to sort nulls after all!  Feel free to just add

    PGOrd a => PGOrd (Nullable a)

**Comment by hesselink** [comment]
OK, that seems to work. I've added it locally for now and sent a PR with the addition.

**Comment by ocharles** [comment]
I wonder if it's better to not have that instance and instead of:

`nullsFirst :: Column a -> Column (NullsFirst a)`
`nullsLast :: Column a -> Column (NullsLast a)`

or something, with

`PGOrd a => PGOrd (NullsFirst a)`

and so on.

**Comment by hesselink** [comment]
What would the advantage be?

**Comment by ocharles** [comment]
Oh, I see that we already have `ascNullsFirst`, but I think this is a little cleaner. It's somewhat redundant to specify `NULLS FIRST` on a column that isn't even nullable. But it does look like it would achieve less than I thought (I thought we might kill two birds with one stone, but I forgot that we already implemented null sorting).

**Comment by hesselink** [comment]
Ah, I see. @bergmark suggested changing the type of `ascNullsFirst` etc to something like `(a -> Column (Nullable b)) -> Order a`. That would make it clear to that it's only useful on nullable columns. But I think that something like your solution is perhaps cleaner, although I'm not sure if it's worth the breaking change of removing `ascNullsFirst` and `descNullsLast`.
