### ISSUE TITLE
Support for JSON functions and operators in Postgres

### ISSUE THREAD

**Issue by drwebb** [tomjaguarpaw/haskell-opaleye#143]
I'm just learning Opaleye, and liking it so far. In a project I'm working on I'm considering using Postgres as a JSON document store. As an example, assume I have a table with two columns: `id :: integer, data :: jsonb`. Opaleye support for inserting `Values` into the `jsonb` column is working as expected. However, in recent versions of Postgres (>9.4) you are able to use operators on the JSON types for example: `SELECT* FROM posts WHERE data -> 'postPriority' > '50'`. `postPriority` is a attribute of the json objects stored in the data column.

This sounds like a nice enhancement to the Opaleye's Query language. It would be nice to have some set of the operators defined in
http://www.postgresql.org/docs/9.5/static/functions-json.html,
once an GIN index is defined on the jsonb column as in
http://www.postgresql.org/docs/9.5/static/datatype-json.html.

Any thoughts?

**Comment by tomjaguarpaw** [comment]
They'd be fairly easy to add, with the caveat that they all (or at least most) produce nullable results making things a little bit fiddly.

**Comment by tomjaguarpaw** [comment]
(Fiddly to use that is, not to add to Opaleye)

**Comment by drwebb** [comment]
That seems reasonable, a `jsonb` is going right into schema-less database territory. We're still evaluating our needs for future flexibility, i.e. do we want a `jsonb` column or to just go with a relational model. If we decide on the JSON route I'll be happy to take a stab at this.

**Comment by tomjaguarpaw** [comment]
If you take a stab feel free to contact me if I can be of any assistance.

**Comment by tomjaguarpaw** [comment]
Hi @drwebb, have you seen the changes in https://github.com/tomjaguarpaw/haskell-opaleye/issues/193?  They may be useful for you.

**Comment by tomjaguarpaw** [comment]
Closing as stale and probably fixed.
