### ISSUE TITLE
Doubles serialize Infinity and NaN incorrectly

### ISSUE THREAD

**Issue by hesselink** [tomjaguarpaw/haskell-opaleye#144]
If you have a table with e.g. a `double precision` type in postgres, and you insert a `Double` into it which is `Infinity` or `NaN`, these strings are not quoted in the generated SQL. This generates an error saying there is no column "Infinity"/"NaN". They should be surrounded by single quotes. See also [the postgres documentation](http://www.postgresql.org/docs/9.3/static/datatype-numeric.html#DATATYPE-FLOAT).

**Comment by tomjaguarpaw** [comment]
Ooh thanks, that's a solid bug.

**Comment by tomjaguarpaw** [comment]
Please test this https://github.com/tomjaguarpaw/haskell-opaleye/commit/fafbc2831d71aab423962ac6eef731e8386a216b

**Comment by tomjaguarpaw** [comment]
(i.e. the latest master)

**Comment by hesselink** [comment]
It's a bit tricky to test for me in our application, since:

* We're still on 0.3.
* We removed the cases where we were generating `NaN` or `Infinity`.

The change looks good and simple though, and I assume you've tested it, so I don't think there can be much wrong with it.

**Comment by tomjaguarpaw** [comment]
I haven't tested it but let's just be crazy and and assume it works :)
