### ISSUE TITLE
Support for tstzrange

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#156]
Is there any support for the `tstzrange` type?

(We use temporal tables - http://clarkdave.net/2015/02/historical-records-with-postgresql-and-temporal-tables-and-sql-2011/)

**Comment by tomjaguarpaw** [comment]
I don't think so but it doesn't sound hard to add.  You can add a type here

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/PGTypes.hs

and perhaps functions for working with them like `timestamptzAtTimeZone` here

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Operators.hs

If you want to run queries that return them, an `instance QueryRunnerColumnDefault` needs to be added here

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/RunQuery.hs

(You can only run queries if postgresql-simple already supports them.  I'm not sure if it does.)

**Comment by lippling** [comment]
Haven't checked it, but there seems to be some support (https://hackage.haskell.org/package/postgresql-simple-0.5.1.2/docs/Database-PostgreSQL-Simple-Range.html).

What would be the recommended approach (roughly) to add operators like http://www.postgresql.org/docs/9.5/static/functions-range.html#RANGE-OPERATORS-TABLE for the range type(s)?

**Comment by tomjaguarpaw** [comment]
You should probably implement them like `.<`

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Operators.hs#L76

Firstly you'll add a constructor in `Opaleye.Internal.HaskellDB.PrimQuery` and then chase through all the things that that implies (SQL generation etc.).  The type checker should point you to the right places.

**Comment by lippling** [comment]
Thanks!
I'll give it a try in the next couple of weeks.

**Comment by xldenis** [comment]
This is fixed by #221 and this issue should be closed.

**Comment by tomjaguarpaw** [comment]
Thanks!
