### ISSUE TITLE
Support for COUNT(DISTINCT x)

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#164]
I can only see the `count` aggregate, but that doesn't let me apply the distinct condition on the expression being counted.

**Comment by tomjaguarpaw** [comment]
It's not currently implemented but should be easy.

**Comment by ocharles** [comment]
Would you do it with a new `AggrOp`?

**Comment by ocharles** [comment]
http://www.postgresql.org/docs/9.5/interactive/sql-expressions.html#SYNTAX-AGGREGATES it looks like there is rather a lot of syntax that is supported in an aggregate function call that might be worth more general consideration.

**Comment by tomjaguarpaw** [comment]
Yes, it should be a new `AggrOp`, but because the syntax is to have `DISTINCT` inside the parens it will require a bit of fiddling.

**Comment by tomjaguarpaw** [comment]
In fact given that Postgres aggregate documentation you may just want to add a field to `AggrOp` which does `DISTINCT`.
