### ISSUE TITLE
Maybe vs Nullable

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#167]
I'm trying to model:

```haskell
CREATE TABLE exercise_runs
    ( id SERIAL PRIMARY KEY
    , exercise_id INT NOT NULL REFERENCES exercises ON DELETE CASCADE
    , user_id INT NOT NULL REFERENCES users ON DELETE CASCADE
    , start_date timestamptz NOT NULL
    , end_date timestamptz
    );
```

```haskell
newtype Id' a = Id { unId :: a } deriving Show
type IdR = Id' Int
type IdW = Id' (Maybe Int)
type IdColumnR = Id' (Column PGInt4)
type IdColumnW = Id' (Maybe (Column PGInt4))
$(makeAdaptorAndInstance "pId" ''Id')

newtype Start' a = Start { unStart :: a } deriving Show
type Start = Start' UTCTime
type StartColumn = Start' (Column PGTimestamptz)
$(makeAdaptorAndInstance "pStart" ''Start')

newtype End' a = End { unEnd :: a } deriving Show
type End = End' (Maybe UTCTime)            -- <<<<<<<<<<<< here
type EndColumn = End' (Nullable PGTimestamptz) -- <<<<<<<<<<<< here
$(makeAdaptorAndInstance "pEnd" ''End')

data Entity' a b c d e = Entity
    { entityId   :: a
    , exerciseId :: b
    , userId     :: c
    , start      :: d
    , end        :: e
    } deriving Show
type EntityR = Entity' IdR Content.IdR User.IdR Start End
type EntityW = Entity' IdW Content.IdR User.IdR Start End
type EntityColumnsR = Entity' IdColumnR Content.IdColumnR User.IdColumnR StartColumn EndColumn
type EntityColumnsW = Entity' IdColumnW Content.IdColumnR User.IdColumnR StartColumn EndColumn
$(makeAdaptorAndInstance "pEntity" ''Entity')

table :: Table EntityColumnsW EntityColumnsR
table =
    Table "exercise_runs" $ pEntity Entity
        { entityId = pId (Id $ optional "id")
        , exerciseId = Content.pId (Content.Id $ required "exercise_id")
        , userId = User.pId (User.Id $ required "user_id")
        , start = pStart (Start $ required "start_date")
        , end = pEnd (End $ optional "end_date")      -- <<<<<<<<<<<< here
        }
```

But I cannot get it working. `end_date` is a column that is `NULL` until an event happens. How can I implement that?

I'm also not sure how `Maybe` and `Nullable` correlate exactly. Maybe someone could give me some hints. The documentation was not helpful for me here.

**Comment by lippling** [comment]
Ok, I made a mistake

```haskell
type EndColumn = End' (Nullable PGTimestamptz)
...
end = pEnd (End $ optional "end_date")
```

should be

```haskell
type EndColumn = End' (Column (Nullable PGTimestamptz))
...
end = pEnd (End $ required "end_date")
```

So `required` and `optional` only "control" the Haskell side?

Still not totally clear to me.

**Comment by tomjaguarpaw** [comment]
Sorry, what's not clear to you?

**Comment by lippling** [comment]
How Maybe and Nullable correlate exactly.

For example, why do I have to say `required "end_date"`? Shouldn't `optional` be enough?
And it makes no difference for the compiler if I say `type End = End' (Maybe UTCTime)` or `type End = End' UTCTime`.

Maybe I can't see the forest for the trees, sorry :-).

**Comment by tomjaguarpaw** [comment]
> For example, why do I have to say `required "end_date"`? Shouldn't `optional` be enough?

`"end_date"` is `required` because you must provide it on writes.   Columns that are `optional` are things that you can omit on writes, such as those columns that have defaults or those which are `SERIAL`.  Does that make sense?

> And it makes no difference for the compiler if I say `type End = End' (Maybe UTCTime)` or type `End = End' UTCTime`

Have you actually tried writing a `runQuery' with `End = End' (Maybe UTCTime)`?  It shouldn't work.  If it does please report a bug!

**Comment by tomjaguarpaw** [comment]
(By the way, the type `End` is ultimately unused in that file so you would never be able to see a type error caused by changing it.)

**Comment by lippling** [comment]
Ok thanks. Makes more sense now.

> Have you actually tried writing a runQuery' withEnd = End' (Maybe UTCTime)`? It shouldn't work. If it does please report a bug!

Running a query with `type End = End' (Maybe UTCTime)` works and `type End = End' UTCTime` does not. That should be right.

**Comment by tomjaguarpaw** [comment]
> Ok thanks. Makes more sense now.

Great.  Can you think of a way I can better explain this in the docs to avoid confusion for others?

> Running a query with type `End = End' (Maybe UTCTime)` works and type `End = End' UTCTime` does not. That should be right.

Ah yes, because it's nullable.

**Comment by lippling** [comment]
Some thing that is missing in the Nullable chapter is an example with a `newtype` like above.

Also, it could make sense to add a description for `required` and `optional` like this
> Columns that are optional are things that you can omit on writes, such as those columns that have defaults or those which are SERIAL.

**Comment by tomjaguarpaw** [comment]
I opened an issue for `required`/`optional`.

Can you explain more about what you'd like to see regarding nullable?

**Comment by lippling** [comment]
Maybe a stripped down example of the problem above (also using `newtypes`), with
- `SERIAL` column -> use of `Maybe`
- `NOT NULL` column
- `NULL` column -> use of `Nullable`

So one can see all three cases together - with `newtypes`.

**Comment by tomjaguarpaw** [comment]
That's great thanks.  I will explain that when I get a chance to improve the docs.

**Comment by lippling** [comment]
You're welcome!

**Comment by tomjaguarpaw** [comment]
Migrated the remnants of this to https://github.com/tomjaguarpaw/haskell-opaleye/issues/218
