### ISSUE TITLE
Sum Field Type

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#168]
How can I have a sum type like
```haskell
data ContentType = Image | Video
```
that has a corresponding `PGText` column?

Is this directly supported? If not, is it otherwise possible?

**Comment by tomjaguarpaw** [comment]
I'm not sure what you mean.  Do you mean the `PGText` column contains either the string `'Image'` or the string `'Video'`?

**Comment by lippling** [comment]
Right now I have
```haskell
newtype ContentType' a = ContentType { unContentType :: a } deriving Show
type ContentType = ContentType' Text
type ContentTypeColumn = ContentType' (Column PGText)
$(makeAdaptorAndInstance "pContentType" ''ContentType')

contentTypeCategory :: ContentType
contentTypeCategory = ContentType "category"

contentTypeExercise :: ContentType
contentTypeExercise = ContentType "exercise"

contentTypeFile :: ContentType
contentTypeFile = ContentType "file"

contentTypeImage :: ContentType
contentTypeImage = ContentType "image"

contentTypeLesson :: ContentType
contentTypeLesson = ContentType "lesson"

contentTypeQuestion :: ContentType
contentTypeQuestion = ContentType "question"

contentTypeVideo :: ContentType
contentTypeVideo = ContentType "video"
```

Bit I would prefer to use a sum type for that.

**Comment by tomjaguarpaw** [comment]
OK.  This sort of thing is not *directly* supported but should not be too hard to deal with.

I would recommend storing all the categories in the database as `int4`.  You can write functions

    toInt :: ContentType -> Int
    fromInt :: Int -> ContentType

(which are trivial if you derive a compatible `Enum` instance).

You can define a dummy type `data PGContentType` and use `Column PGContentType` (or just use `Column ContentType` if you are feeling lazy).

Then you will need to define some instances like

    instance QueryRunnerColumnDefault PGContentType ContentType where
        queryRunnerColumnDefault = fmap fromInt fieldQueryRunnerColumn

    adaptContentType :: Profunctor p => p Int (Column PGInt4) -> p ContentType (Column PGContentTYpe)
    adaptContentType = dimap (unsafeCoerceColumn :: Column PGInt4 -> Column PGContentType) toInt

    instance Default Constant ContentType (Column PGContentType) where
        def = adaptContentType def

(I hope those work.  I haven't tested them.)  Any missing instances should be flagged by the compiler and should be easy to add.  Please post back if you have any problems.

Given a setup like this you should be able to program as though there's a Postgres type `PGContentType` which maps to your Haskell type `ContentType`.

**Comment by lippling** [comment]
Good to know.

I meant it a bit differently.

I have the following table:

```sql
CREATE TABLE content_types
    ( id SERIAL PRIMARY KEY
    , type TEXT NOT NULL UNIQUE
    );

CREATE TABLE contents
    ( id SERIAL PRIMARY KEY
    ...
    , content_type_id INT NOT NULL REFERENCES content_types
    ...
    );
```
and a type

```haskell
newtype ContentType' a = ContentType { unContentType :: a }
```

and what I want to use in my non database code is

```haskell
data ContentType = Image | Video | ...
```

Any hints how I can do this?

**Comment by tomjaguarpaw** [comment]
I think the simplest way is just to have those two distinct types and (partial) functions that map between them.  Is that too awkward or inconvenient?

**Comment by lippling** [comment]
The disadvantage is that I'd always have to use a mapping function then. I use polymorphic `get`, `insert`, ... functions and I thought there would be a generic way with the existing Opaleye "machinery".

**Comment by tomjaguarpaw** [comment]
What machinery were you hoping to use?  Will `Constant` and `QueryRunnerColumnDefault` instances not be enough?

**Comment by lippling** [comment]
The example you showed above uses an `int` column with a hardcoded value. I want to use a foreign key to another table with known `type`s (`type TEXT NOT NULL UNIQUE`) and map that to the sum type.

Sorry, maybe I cannot explain my problem in a way that makes sense ;-).

**Comment by tomjaguarpaw** [comment]
You could use a hardcoded *string* value.  There's no way of associating Haskell constructors to strings in a database that just happen to look like those constructors though.

**Comment by lippling** [comment]
Ok, I had time to think about your suggestions again and came up with this:

```haskell
newtype Id' a = Id { unId :: a } deriving Show
type Id = Id' Int
type IdMaybe = Id' (Maybe Int)
type IdColumn = Id' (Column PGInt4)
type IdColumnMaybe = Id' (Maybe (Column PGInt4))
$(makeAdaptorAndInstance "pId" ''Id')

data ContentType = Category | Exercise | File | Image | Lesson | Question | Video
type ContentTypeColumn = Column PGContentType
newtype PGContentType = PGContentType PGContentType

instance Default Constant ContentType ContentTypeColumn where
    def = dimap toText unsafeCoerceColumn (def :: Constant Text (Column PGText))
        where
            toText :: ContentType -> Text
            toText Category = "category"
            toText Exercise = "exercise"
            toText File = "file"
            toText Image = "image"
            toText Lesson = "lesson"
            toText Question = "question"
            toText Video = "video"

instance QueryRunnerColumnDefault PGContentType ContentType where
    queryRunnerColumnDefault = fromText <$> fieldQueryRunnerColumn
        where
            fromText :: Text -> ContentType
            fromText "category" = Category
            fromText "exercise" = Exercise
            fromText "file" = File
            fromText "image" = Image
            fromText "lesson" = Lesson
            fromText "question" = Question
            fromText "video" = Video
            fromText t = error $ "Unsupported content type " ++ repack t -- <<<< better way to handle this?

data Entity' a b = Entity
    { entityId    :: a
    , contentType :: b
    } deriving Show
type EntityR = Entity' Id ContentType
type EntityW = Entity' IdMaybe ContentType
type EntityColumnsR = Entity' IdColumn ContentTypeColumn
type EntityColumnsW = Entity' IdColumnMaybe ContentTypeColumn
$(makeAdaptorAndInstance "pEntity" ''Entity')
```

How to I incorporate that into my existing table function (what is pContentType now, that I used before):

```haskell
table :: Table EntityColumnsW EntityColumnsR
table =
    Table "content_types" $ pEntity Entity
        { entityId = pId (Id $ optional "id")
        , contentType = pContentType (ContentType $ required "type") -- <<<< here
        }
```

**Comment by tomjaguarpaw** [comment]
`required "type"` has type `TableProperties (Column a) (Column a)` which unifies with `TableProperties (Column PGContentType) (Column PGContentType.)`.  Is that what you want?

(I would also suggest that `PGContentType` be an empty data declaration `data PGContentType`, but it doesn't really matter.)

**Comment by lippling** [comment]
Sorry, I don't understand what you mean.

I had a `pContentType` which I could use:

```haskell
newtype ContentType' a = ContentType { unContentType :: a } deriving Show
type ContentType = ContentType' Text
type ContentTypeColumn = ContentType' (Column PGText)
$(makeAdaptorAndInstance "pContentType" ''ContentType')

data Entity' a b = Entity
    { entityId    :: a
    , contentType :: b
    } deriving Show
type EntityR = Entity' Id ContentType
type EntityW = Entity' IdMaybe ContentType
type EntityColumnsR = Entity' IdColumn ContentTypeColumn
type EntityColumnsW = Entity' IdColumnMaybe ContentTypeColumn
$(makeAdaptorAndInstance "pEntity" ''Entity')

table :: Table EntityColumnsW EntityColumnsR
table =
    Table "content_types" $ pEntity Entity
        { entityId = pId (Id $ optional "id")
        , contentType = pContentType (ContentType $ required "type")
        }
```

Now I have
```haskell
data ContentType = Category | Exercise | File | Image | Lesson | Question | Video
type ContentTypeColumn = Column PGContentType
newtype PGContentType = PGContentType PGContentType

table :: Table EntityColumnsW EntityColumnsR
table =
    Table "content_types" $ pEntity Entity
        { entityId = pId (Id $ optional "id")
        , contentType =  -- <<<< here
        }
```
and I don't know how to assign to `contentType` so that I can use it with my table

```sql
CREATE TABLE content_types
    ( id SERIAL PRIMARY KEY
    , type TEXT NOT NULL UNIQUE
    );
```
because I cannot use `makeAdaptorAndInstance` anymore.

**Comment by tomjaguarpaw** [comment]
Isn't it just `contentType = required "type"`?

**Comment by lippling** [comment]
Yep, you are right.

I thought it would be more complicated, because I don't understand (Product)Profunctors, yet. Thanks for your patience.

**Comment by tomjaguarpaw** [comment]
You're welcome.  Feel free to reopen or file a new issue if you need any more help.

**Comment by rvl** [comment]
I'm having trouble implementing the `data ContentType` solution, specifically defining `instance Functor (QueryRunnerColumn PGContentType`.

```haskell
data Colour = Fuschia | Magenta | Mauve  deriving (Show, Read, Enum)

data PGColour = PGColour { unColour :: PGText }
data PGColourNum = PGColourNum { unColourNum :: PGInt4 }

instance QueryRunnerColumnDefault PGColour Colour where
  queryRunnerColumnDefault = fmap (read . T.unpack) fieldQueryRunnerColumn

adaptColour :: Profunctor p => p Text (Column PGText) -> p Colour (Column PGColour)
adaptColour = dimap (T.pack . show) (unsafeCoerceColumn :: Column PGText -> Column PGColour)

instance QueryRunnerColumnDefault PGColourNum Colour where
  queryRunnerColumnDefault = fmap toEnum fieldQueryRunnerColumn

adaptColourNum :: Profunctor p => p Int (Column PGInt4) -> p Colour (Column PGColourNum)
adaptColourNum = dimap fromEnum (unsafeCoerceColumn :: Column PGInt4 -> Column PGColourNum)

instance D.Default Constant Colour (Column PGColour) where
  def = adaptColour D.def

instance Functor (QueryRunnerColumn PGColour)
-- where fmap f (QueryRunnerColumn s h) = fmap f (QueryRunnerColumn (unColour s) h)
instance Functor (QueryRunnerColumn PGColourNum)
-- where ???

data ColourTest' a b = ColourTest
  { colourA :: a
  , colourB :: b
  } deriving (Generic, Show)

type ColourTest = ColourTest' Colour Colour
type ColourTestColumns = ColourTest' (Column PGColour) (Column PGColourNum)

$(makeAdaptorAndInstance "pColourTest" ''ColourTest')

{-
-- PostgreSQL table looks like this:
CREATE TYPE colour AS ENUM ('Fuschia', 'Magenta', 'Mauve');
CREATE TABLE colours
( colour_a colour NOT NULL
, colour_b INTEGER NOT NULL
);
-}

colourTestTable :: Table ColourTestColumns ColourTestColumns
colourTestTable = Table "colours" $ pColourTest ColourTest
  { colourA = required "colour_a"
  , colourB = required "colour_b"
  }

colourTestQuery :: Query ColourTestColumns
colourTestQuery = queryTable colourTestTable
```
Do you have any suggestions @tomjaguarpaw ?

**Comment by tomjaguarpaw** [comment]
Hmm, `QueryRunnerColumn u` already has a `Functor` instance

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/RunQuery.hs#L69

Does that solve your problem?

**Comment by rvl** [comment]
Ahh thanks! The reason I wasn't getting that instance was because I was using 0.4.2 from Stackage LTS, not 0.5.0.

**Comment by tomjaguarpaw** [comment]
On Thu, Jun 09, 2016 at 01:57:50AM -0700, Rodney Lorrimar wrote:
> Ahh thanks! The reason I wasn't getting that instance was because I was
> using 0.4.2 from Stackage LTS, not 0.5.0.

You're welcome.  Opaleye 0.5.0.0 isn't in Stackage any more.  I don't know
why ...

**Comment by tomjaguarpaw** [comment]
Looks like it was disabled when it didn't build of GHC 8.  I've reenabled it: https://github.com/fpco/stackage/pull/1577
