### ISSUE TITLE
move upper bounds for time

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tomjaguarpaw/haskell-opaleye#173]
The current upper bounds break with stackage nightly, GHC 8.0.1
```
      time: needed (>=1.4 && <1.6), 1.6.0.1 found (latest applicable is 1.5.0.1)
    needed for package opaleye-0.4.2.0
```

**Comment by tomjaguarpaw** [comment]
Thanks.  I updated the cabal metadata to accept 1.6.

https://hackage.haskell.org/package/opaleye-0.4.2.0
