### ISSUE TITLE
GHC 8 compile error

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tomjaguarpaw/haskell-opaleye#174]
I get the following with the latest stackage nightly:
```
    [ 8 of 42] Compiling Opaleye.Internal.PackMap ( src/Opaleye/Internal/PackMap.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Opaleye/Inte
rnal/PackMap.o )

    /tmp/stack20475/opaleye-0.4.2.0/src/Opaleye/Internal/PackMap.hs:43:45: error:
        Not in scope: type variable ‘f’

    /tmp/stack20475/opaleye-0.4.2.0/src/Opaleye/Internal/PackMap.hs:44:39: error:
        Not in scope: type variable ‘f’

    /tmp/stack20475/opaleye-0.4.2.0/src/Opaleye/Internal/PackMap.hs:44:52: error:
        Not in scope: type variable ‘f’
```

**Comment by tomjaguarpaw** [comment]
Thanks. I released 0.5.0.0 to Hackage which (according to Travis) builds on GHC 8.  Please reopen if you see any further problems.

**Comment by lippling** [comment]
@tomjaguarpaw I cannot see 0.5.0.0 in an LTS snapshot on Stackage. Is this intentional?

**Comment by bergmark** [comment]
LTS6 was created with opaleye 0.4.*. The point is for LTS to not contain breaking changes, thus opaleye 0.5 won't be in LTS until LTS7.

**Comment by lippling** [comment]
Thanks for clearing that up! That makes sense.

**Comment by tomjaguarpaw** [comment]
Thanks @bergmark
