### ISSUE TITLE
IN query

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#175]
How can I write a query like this:

``` sql
SELECT id FROM contents WHERE title_id IN
    (SELECT content_string_id FROM content_string_translations
        WHERE legacy_type = ? AND legacy_Id = ?)
```

I tried to start with something like this, but that doesn't typecheck:

``` haskell
q :: OE.Query Content.IdColumn
q = proc () -> do
    content <- Content.query -< ()
    OE.restrict -< OE.inQuery (Content.titleId content) subQ    -- <<<<< here
    returnA -< Content.entityId content

subQ :: OE.Query ContentString.IdColumn
subQ = ...
```

``` haskell
Couldn't match type ‘OE.QueryArr () (OE.Column OE.PGBool)’
                   with ‘OE.Column OE.PGBool’
    Expected type: OE.Column OE.PGBool
      Actual type: OE.Query (OE.Column OE.PGBool)
    In the expression: OE.inQuery (Content.titleId content) subQ
    In the command: OE.restrict -< OE.inQuery
                                     (Content.titleId content) subQ
```

**Comment by tomjaguarpaw** [comment]
On Mon, May 30, 2016 at 06:58:31AM -0700, Alexander Lippling wrote:
> ```sql
> SELECT id FROM contents WHERE title_id IN
>     (SELECT content_string_id FROM content_string_translations
>         WHERE legacy_type = ? AND legacy_Id = ?)
> ```
 
Isn't this just a restrict on content_string_id = title_id?

**Comment by lippling** [comment]
Yes, but those are from a different table and I want to avoid joining.
Apart from that I haven't found suitable examples for queries with `IN` and I'll need those in the future for sure.

**Comment by tomjaguarpaw** [comment]
On Mon, May 30, 2016 at 09:42:16AM -0700, Alexander Lippling wrote:
> Yes, but those are from a different table and I want to avoid joining.

Presumably the database engine has to do a join either way ...

**Comment by lippling** [comment]
Ok thanks. Could you post a usage example anyway?

**Comment by tomjaguarpaw** [comment]
An example of `inQuery`?  I guess you need to unwrap the resulting query, so

    q :: OE.Query Content.IdColumn
    q = proc () -> do
        content <- Content.query -< ()
        subquery <- OE.inQuery (Content.titleId content) subQ -< ()
        OE.restrict -< subquery
        returnA -< Content.entityId content

**Comment by lippling** [comment]
Ah I see, so simple, thanks.

I cannot use `content` in the line `subquery <- OE.inQuery (Content.titleId content) subQ -< ()`, because it's an Arrow and not a Monad (`Not in scope: ‘content’`)?

How would I do that instead?

**Comment by tomjaguarpaw** [comment]
That's a very good point.  I think I'll have to change `inQuery`.

**Comment by tomjaguarpaw** [comment]
Hmm, actually it might require a big change.  For your current use case I would suggest restrict on content_string_id = title_id since it will be some time before I can get to this.

**Comment by lippling** [comment]
@tomjaguarpaw, I very often stumble upon this issue, honestly.

I tried to circumvent it by using `runQuery` two times (see 1).

```haskell
getCourseRanking :: User.Id -> Transaction ReadOnly [(User.Id, UserCredit.Credits)]
getCourseRanking userId =
    -- (1)
    runQuery . sumCreditsAndOrderDesc . courseCreditsQuery =<< runQuery userCoursesQuery
    where
        userCoursesQuery :: Query Course.IdColumn
        userCoursesQuery = proc () -> do
            courseUser <- CourseUser.query -< ()
            restrict -< CourseUser.userId courseUser .=== constant userId
            returnA -< CourseUser.courseId courseUser

        courseCreditsQuery :: [Course.Id] -> Query (User.IdColumn, UserCredit.CreditsColumn)
        courseCreditsQuery courseIds = proc () -> do
            credit <- UserCredit.query -< ()

            user <- User.query -< ()
            restrict -< User.entityId user .=== UserCredit.userId credit

            courseUser <- CourseUser.query -< ()
            restrict -< CourseUser.userId courseUser .=== User.entityId user

            -- (2)
            restrict -< (constant . field <$> courseIds) `in_` field (CourseUser.courseId courseUser)

            returnA -< (UserCredit.userId credit, UserCredit.credits credit)

sumCreditsAndOrderDesc :: Query (User.IdColumn, UserCredit.CreditsColumn) -> Query (User.IdColumn, UserCredit.CreditsColumn)
sumCreditsAndOrderDesc = orderBy (desc $ field . snd) . aggregate (p2 (pNewtype OE.groupBy, pNewtype OE.sum))
```

a) Can you think of a way to combine the two queries given that `inQuery` doesn't accept input? Or is this the only possibility?

b) Is there a way to write a literal for expressions like (`WHERE id IN (SELECT id FROM ....)`) (or for any other unsupported feature in Opaleye e.g. `tstzrange` operators) and incoporate it into a `QueryArr`? I don't want to write the whole query by dropping down to `postgresql-simple` when Opaleye does not support a feature.

c) Is there a way to make (2) simpler? `in_` expects `Column`s and I'm using `newtype`s.

**Comment by tomjaguarpaw** [comment]
a) This still looks like an inner join to me.  Does something go wrong if you try to rewrite it as an inner join?

b) There is no such "escape hatch" but I have often considered writing one.  I would rather add missing functionality though.  Feel free to keep asking me about whatever you need.

c) Can you try `in_ hs w = ors . fmap (w .===) $ hs` and tell me how that works out?  You should be able to write 

````haskell
(constant <$> courseIds) `in` CourseUser.courseId courseUser
````

(assuming I understand your setup correctly).

**Comment by lippling** [comment]
a) I'm not quite sure what you mean. If I rewrite the query as an inner join, I'd get multiple rows, because User and Courses have an m:n relationship. Also, a subselect with IN is often faster than a join (in my experience). It would be great if "true" IN support could be added sometime.
b) This is a bit suboptimal, because often there is no time to implement such features or wait for someone else to implement them. The client doesn't care ;-). For example, I need support for `tstzrange ` and it's operators, but I don't have time to implement these. There is also no support for `FOR UPDATE`, which I use regularly, so I work around that by locking the whole table.
c) Yes, that works, do you plan to add/change it? This pattern occurs often, because (nearly?) all operators apart from .=== and ./== work with `Column`s instead of wrapped `Column`s.

Maybe I should document my best practices when my current project is done (in a few months)...

**Comment by tomjaguarpaw** [comment]
a1) I couldn't tell whether you'd get multiple rows because I didn't fully understand your query, but presumably you can get around that with a `DISTINCT`.

a2) It would indeed be great to get "true" `IN` support but often there is no time to implement such features :)

b1) `tztrange` and its operations should be *really* easy to add.  Feel free to open a ticket.

b2) An escape hatch would be great but again, often there is no time to implement such features

c) I haven't planned to add or change it because I've only just thought of it but if you file a ticket I am more likely to, especially if others join in and say that's what they want :)

> Maybe I should document my best practices when my current project is done (in a few months)...

That would be great!

**Comment by lippling** [comment]
a2, b2) I know that only too well...
b1) https://github.com/tomjaguarpaw/haskell-opaleye/issues/156 :-)
c) It is not high priority, but maybe it should be noted in the docs somewhere. "If you want to use these function with your `newtype`s, you can use `field` and `constructor`..."

Maybe we'll have some time to talk about that at HaskellX after I buy you a beer for all the support you've given me :).

**Comment by tomjaguarpaw** [comment]
b1) Looks like someone is already assigned to that one :) I thought `tztrange` sounded familiar!  I can give you a hand with it.

> Maybe we'll have some time to talk about that at HaskellX

You're coming to HaskellX?  Fantastic!

**Comment by lippling** [comment]
Yep, it's my first Haskell conference. I'll be in London October 5th through the 9th.

**Comment by saurabhnanda** [comment]
Jumping into this discuss - even I have run across instances where it is not possible to rewrite an "IN with a subselect" as a JOIN query. Especially if the sub-select itself has a bunch of JOINs, GROUPs, or DISTINCT clauses.

**Comment by saurabhnanda** [comment]
chiming-in to say that I've been hit by the exact same issue as https://github.com/tomjaguarpaw/haskell-opaleye/issues/175#issuecomment-222565523

```
offlinePayments = proc () -> do
  p <- queryTable payTable -< ()
  restrict -< in_ [constant "xxx", constant "yyy"] (p ^. processor)
  returnA -< p

onlinePayments = proc () -> do
  allPay <- queryTable payTable -< ()
  ofPay <- offlinePayments -< ()
  subQ <- Opaleye.not inQuery (ofPay ^. key) (allPay ^. key) -< ()
  restrict -< subQ
  returnA -< allPay
```

**Comment by saurabhnanda** [comment]
I'm wondering if the [technique mentioned here](https://github.com/tomjaguarpaw/haskell-opaleye/issues/175#issuecomment-222518340) can be used to implement a `NOT IN` ?

**Comment by tomjaguarpaw** [comment]
Closing as stale.  Feel free to reopen by providing more information.
