### ISSUE TITLE
compile failure with GHC 7.4

### ISSUE THREAD

**Issue by hvr** [tomjaguarpaw/haskell-opaleye#176]
Since `opaleye` doesn't declare the LANGUAGE pragmas it needs via `other-extensions` (which does not enable those extensions yet!), cabal's solver has no way to know that `opaleye-0.5.0.0` requires a compiler which provides `LambdaCase`:

```
src/Opaleye/Internal/Optimize.hs:1:14:
    Unsupported extension: LambdaCase
xcabal: Error: some packages failed to install:
opaleye-0.5.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

There's 2 ways out of this:

 - make compatible with GHC 7.4 again, or
 - declare the features required from the compiler (i.e. by using `other-extensions`, cabal 1.24's solver uses this information for backtracking), and optionally tighten the lower bound to `base >= 4.6`

and you should bump to `cabal-version: >= 1.10`, as the feature-set of  `cabal-version: >= 1.8` predates GHC 7.0 and has some minor subtle issues

I've done the latter in https://hackage.haskell.org/package/opaleye-0.5.0.0/revisions/
Note that the revision report is buggy as it omits the full list of extensions I added, which was

```
other-extensions: Arrows, EmptyDataDecls, FlexibleContexts, FlexibleInstances, LambdaCase, MultiParamTypeClasses, Rank2Types, ScopedTypeVariables, TupleSections
```

**Comment by tomjaguarpaw** [comment]
I've depended on `base >= 4.6`.  I'm not keen to change `other-extensions` since that is liable to get out of sync.  Really it should be generated by `cabal sdist`.  Feel free to try to convince me I'm wrong about that!

https://github.com/tomjaguarpaw/haskell-opaleye/commit/e414cc449edbd177a7fc92402a0467ae156ad4da

**Comment by tomjaguarpaw** [comment]
Depended on `cabal >= 1.10`

https://github.com/tomjaguarpaw/haskell-opaleye/commit/d8f26c0f8289326ab3a415a206925b40f86a80a4
