### ISSUE TITLE
Call a stored procedure

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#181]
I want to run the following query:

```sql
SELECT hws_get_deleted_ids('questions', '2016-06-13 12:00:00'::TIMESTAMPTZ, 'content_id', ARRAY []::TEXT[], 1)
```

I drafted this function:

```haskell
getDeletedIds :: Table writerColumns readerColumns -> Column PGTimestamptz -> Language.IdColumn -> Column PGInt4
getDeletedIds table (Column sinceWhen) (Language.Id (Column languageId)) = Column
    ( HPQ.FunExpr "hws_get_deleted_ids"
        [ HPQ.ConstExpr . HPQ.StringLit . HPQ.tiTableName . T.tableIdentifier $ table
        , sinceWhen
        , HPQ.ConstExpr . HPQ.StringLit $ "content_id"
        , HPQ.ArrayExpr []
        , languageId
        ]
    )
```

1. How can I run it to get the `[Int]`?
2. How can I tell Postgres the correct type for the empty array or does this happen automatically in Opaleye?
3. What's the best way to get a column name (`content_id` is a string now, but should be provided to `getDeletedIds` in a type-safe way later)?

**Comment by lippling** [comment]
Ok, I came up with this:

```haskell
getDeletedQuestionIds :: UTCTime -> Language.Id -> Query Content.IdColumn
getDeletedQuestionIds sinceWhen languageId = proc () -> returnA -< Content.Id $ getDeletedIds Question.table "content_id" [] sinceWhen languageId

getDeletedIds :: Table writerColumns readerColumns -> Text -> [Text] -> UTCTime -> Language.Id -> Column a
getDeletedIds table idColumnName textColumnNames sinceWhen languageId =
    mkCol (constant idColumnName) (pgArray constant textColumnNames) (constant sinceWhen) (constant languageId)
    where
        mkCol :: Column PGText -> Column (PGArray PGText) -> Column PGTimestamptz -> Language.IdColumn -> Column a
        mkCol (Column idColumnName') (Column textColumnNames') (Column sinceWhen') (Language.Id (Column languageId')) =
            Column $ HPQ.FunExpr "hws_get_deleted_ids"
                [ HPQ.ConstExpr . HPQ.StringLit . HPQ.tiTableName . T.tableIdentifier $ table
                , sinceWhen'
                , idColumnName'
                , textColumnNames'
                , languageId'
                ]
```

Im still interested in 3) above.

**Comment by tomjaguarpaw** [comment]
I think 3) might be outside the scope of Opaleye.  In what way are you anticipating it changing?

**Comment by lippling** [comment]
I have a lot of tables and the column name may differ from table to table.
I thought it would be possible to get the column name back somehow, because I use `ContentType.pId (ContentType.Id $ required/optional "content_type_id")`, for example.

**Comment by tomjaguarpaw** [comment]
I see.  Opaleye doesn't support getting the column names out of a table definition.  I don't think you need any Opaleye specific features to come up with a nice solution that removes duplication, though.  For a start you could try

    theColumnNameOfInterest = "content_type_id"

    personTable = Table ...
          required/optional theColumnNameOfInterest

**Comment by lippling** [comment]
Ok thanks!

**Comment by lippling** [comment]
@tomjaguarpaw I've a new issue:

I have the following stored procedure:
```sql
CREATE FUNCTION hws_get_user_content_ids(v_user_id users.id%TYPE, v_language_id languages.id%TYPE)
    RETURNS SETOF contents.id%TYPE AS $$
    BEGIN
        RETURN QUERY
....
```

And I tried to plug it into Opaleye.

```haskell
getUserContentIds :: User.Id -> Language.Id -> Query IdColumn
getUserContentIds userId languageId = proc () -> do
    let (User.Id (Column userIdCol)) = constant userId :: User.IdColumn
        (Language.Id (Column languageIdCol)) = constant languageId :: Language.IdColumn
    returnA -< Id . Column $ HPQ.FunExpr "hws_get_user_content_ids" [userIdCol, languageIdCol]
```

Unfortunately this doesn't work as expected, because `Query IdColumn` seems to be incorrect. I get runtime errors like this, when I use it:
```SqlError {sqlState = "42804", sqlExecStatus = FatalError, sqlErrorMsg = "argument of AND must not return a set", sqlErrorDetail = "", sqlErrorHint = ""}```

Any idea how this can be solved?

**Comment by tomjaguarpaw** [comment]
Do you want `inQuery`?

**Comment by tomjaguarpaw** [comment]
"hws_get_user_content_ids" returns multiple rows so it can't be of type `Column <something>`.  It needs to be of type `Query (Column <something>)`.  It'll take me a while to work out how to write this so I'll have to get back to you another time.

**Comment by lippling** [comment]
You mean this?

```haskell
content <- Content.query -< ()
sub <- content `inQuery` Content.getUserContentIds (uiUserId userInfo) (uiLanguageId userInfo) -< ()
restrict -< sub
```

That doesn't work, because

**Comment by lippling** [comment]
You mean this?

```haskell
...
content <- Content.query -< ()
sub <- content `inQuery` Content.getUserContentIds (uiUserId userInfo) (uiLanguageId userInfo) -< ()
restrict -< sub
...
```

That doesn't work, because I cannot access `content` and when I try
```haskell
sub <- Content.Id 1 `inQuery` Content.getUserContentIds (uiUserId userInfo) (uiLanguageId userInfo) -< ()
restrict -< sub
```
it says:
```SqlError {sqlState = "42804", sqlExecStatus = FatalError, sqlErrorMsg = "argument of WHERE must not return a set", sqlErrorDetail = "", sqlErrorHint = ""}```

**Comment by tomjaguarpaw** [comment]
I think you have to make it of type `Query (Column <something>)` and then use `inQuery`.  I'll try to write something for you later.

**Comment by tomjaguarpaw** [comment]
What columns are in `hws_get_user_content_ids`?  I'll need to know them in order to know how to wrap it.

**Comment by lippling** [comment]
It's only a `Content.Id`:

```sql
CREATE FUNCTION hws_get_user_content_ids(v_user_id users.id%TYPE, v_language_id languages.id%TYPE) RETURNS SETOF contents.id%TYPE AS $$
    BEGIN
        RETURN QUERY
            WITH RECURSIVE contents_of_user AS (
                    SELECT ch.child_content_id AS content_id
                    FROM content_hierarchies ch
                    JOIN contents c ON c.id = ch.child_content_id
                    JOIN text_translations tt ON tt.text_id = c.title_text_id AND tt.language_id = $2
                    WHERE child_content_id IN (SELECT content_id FROM users_contents WHERE user_id = $1)
                UNION
                    SELECT ch.child_content_id AS content_id
                    FROM content_hierarchies ch
                    JOIN contents c ON c.id = ch.child_content_id
                    JOIN text_translations tt ON tt.text_id = c.title_text_id AND tt.language_id = $2
                    JOIN contents_of_user cou ON ch.parent_content_id = cou.content_id
            )
            SELECT * FROM contents_of_user;
    END;
$$ LANGUAGE plpgsql;
```

**Comment by tomjaguarpaw** [comment]
And it looks like its name is `content_id`.  Is that right?

**Comment by tomjaguarpaw** [comment]
By the way, you can probably write this in Opaleye using this branch https://github.com/tomjaguarpaw/haskell-opaleye/pull/58

**Comment by lippling** [comment]
Maybe you mean this:
```sql
select child_content_id from hws_get_user_content_ids(1,1) -- does not work
select content_id from hws_get_user_content_ids(1,1) -- does not work
select hws_get_user_content_ids from hws_get_user_content_ids(1,1) -- works
```

**Comment by tomjaguarpaw** [comment]
I mean if you do `select * from hws_get_user_content_ids from hws_get_user_content_ids(1,1)` what names of columns do you get back?

**Comment by lippling** [comment]
Your example does not work, in case you meant `select * from hws_get_user_content_ids(1,1)` I get `hws_get_user_content_ids`.

**Comment by tomjaguarpaw** [comment]
Right, that's what I meant, thanks.

Tangentially, can you tell me how the column name `hws_get_user_content_ids` arises?  Naively I would have thought `child_content_id` would be the name.

**Comment by lippling** [comment]
Honestly, I don't know. That's what Postgres told me ;-). I think it's the `SELECT * FROM contents_of_user;` - without a specific column name (alias) - within the stored procedure.

**Comment by tomjaguarpaw** [comment]
So the hacky way to do this -- since I'm yet to write an official way -- is to create a table whose name is `hws_get_user_content_ids(<x>,<y>)` where `x` and `y` are some function parameters.  If you need help working out what I mean by that I can help you at the weekend.

**Comment by lippling** [comment]
Thanks! I'll look at it tomorrow...
I'll work on this weekend, so that would be cool. Maybe it makes sense to use a messenger and only post results here...

**Comment by lippling** [comment]
Do mean something hacky likes this?
```haskell
Table "hws_get_user_content_ids(1,1)" (pId (Id $ required "T1"))
```
This does not work, because the table name gets quoted in Opaleye and Postgres expects a relation then.

**Comment by tomjaguarpaw** [comment]
Aha!  I guess we need a special form in Opaleye then.  I will have to think about how to do this.  

Thanks for checking.

**Comment by tomjaguarpaw** [comment]
Can you try the latest master?  The following works.  It would be good if you could check that it works for you.

````haskell
{-# LANGUAGE Arrows #-}

import Opaleye
import qualified Opaleye.Internal.Column as C
import qualified Opaleye.Internal.HaskellDB.PrimQuery as HPQ
import qualified Opaleye.Internal.Operators as O
import Data.Profunctor (lmap)
import Control.Arrow (returnA)

hwsGetUserContentIds :: QueryArr (Column PGInt4, Column PGInt4) (Column PGInt4)
hwsGetUserContentIds = O.relationValuedExpr "hws_get_user_content_ids" expr
  where expr (C.Column userIdCol, C.Column languageIdCol) =
          HPQ.FunExpr "hws_get_user_content_ids" [userIdCol, languageIdCol]

table :: Table (Column PGInt4) (Column PGInt4)
table = Table "table" (required "myColumn")

foo :: Query (Column PGInt4, Column PGInt4)
foo = proc () -> do
  content  <- hwsGetUserContentIds -< (2, 3)
  myColumn <- queryTable table     -< ()

  returnA -< (content, myColumn)
  
main = let Just sql = showSqlForPostgres foo
       in putStrLn sql

-- > main
-- SELECT "hws_get_user_content_ids0_1" as "result1_3",
--        "myColumn0_2" as "result2_3"
-- FROM (SELECT *
--       FROM (SELECT "hws_get_user_content_ids" as "hws_get_user_content_ids0_1"
--             FROM hws_get_user_content_ids(2,3) as "T1") as "T1",
--           (SELECT "myColumn" as "myColumn0_2"
--             FROM "table" as "T1") as "T2") as "T1"
````

**Comment by lippling** [comment]
Cool, I'll try it tomorrow.

**Comment by lippling** [comment]
Seems to work for me as well. Thanks!

I had to change the name of the return column to `T1` and ended up with this:

```haskell
getUserContentIds :: QueryArr (User.IdColumn, Language.IdColumn) Content.IdColumn
getUserContentIds = Content.Id <$> (O.relationValuedExpr ("T1"::String) $
    \(userId, languageId) -> HPQ.FunExpr "hws_get_user_content_ids" [getExpr userId, getExpr languageId])
    where
        getExpr :: Newtype a => a (Column b) -> HPQ.PrimExpr
        getExpr = unColumn . field
```

**Comment by tomjaguarpaw** [comment]
OK, that's some puzzling Postgres behaviour that I don't yet understand.  Please report back when you've used this in more examples.

**Comment by lippling** [comment]
Ok, have you seen my other comment (https://github.com/tomjaguarpaw/haskell-opaleye/issues/175)?

**Comment by tomjaguarpaw** [comment]
I think this is done.  Feel free to reopen or file a new issue if necessary.
