### ISSUE TITLE
Tool for dumping schema

### ISSUE THREAD

**Issue by singpolyma** [tomjaguarpaw/haskell-opaleye#186]
It would be very useful to have a code-generator like tool that would dump an existing DB schema (created using whatever migration tool) into Opaleye Table definitions.

**Comment by tomjaguarpaw** [comment]
This is a very good idea.

**Comment by tomjaguarpaw** [comment]
Interested parties may want to try https://github.com/folsen/opaleye-gen

**Comment by tomjaguarpaw** [comment]
Closing as stale.
