### ISSUE TITLE
Type inference: No instance for (Default QueryRunner RunQuestion.PositionColumn haskells)

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#188]
What are recommended approaches to prevent:

```
No instance for (product-profunctors-0.7.1.0:Data.Profunctor.Product.Default.Class.Default
                       Opaleye.Internal.RunQuery.QueryRunner
                       RunQuestion.PositionColumn
                       haskells0)
```

I have a query like

``` haskell
getMaxPosition :: Run.Id -> OE.Query RunQuestion.PositionColumn
getMaxPosition runId = aggregate (pNewtype OE.max) q

q :: OE.Query RunQuestion.PositionColumn
q = proc () -> do
    question <- RunQuestion.query -< ()
    restrict -< RunQuestion.runId question .=== constant runId
    returnA -< RunQuestion.position question
```

This of course works:

``` haskell
maxPosition <- runQueryFirst (getMaxPosition runId) :: Transaction ReadOnly (Maybe RunQuestion.Position)

-- -OR-

run :: Transaction ReadOnly (Maybe RunQuestion.Position)
run = runQueryFirst (getMaxPosition runId)
```

but this not, because `Position` cannot be deferred.

``` haskell
maxPosition <- runQueryFirst (getMaxPosition runId)
```

Is it possible that callers don't have to provide the destination type (e.g. type families, ...)?

**Comment by tomjaguarpaw** [comment]
This is a hard problem because there is not always a unique Haskell-side type.  What do you map `PGText` to, for example?  It can be `String`, lazy `Text`, or strict `Text`.

What you could do is to define your own opinionated `runQuery` which maps each Opaleye-side type to a unique Haskell-side type.  I believe silk.co do this.  Specifically, you could write

````haskell
runQuery :: D.Default QueryRunner columns haskells
         => PGS.Connection
         -> Query columns
         -> IO [Haskells columns]

type family Haskells

type instance Haskells (Column PGText) = String
type instance Haskells (Column PGInt4) = Int
...

type instance Haskells (a, b) = (Haskells a, Haskells b)
type instance (Foo a b c) = Foo (Haskells a) (Haskells b) (Haskells c)
...
````

I don't have any plans to include such a thing in Opaleye but if you try it and you like it please let me know.  I might consider merging it.

**Comment by bergmark** [comment]
We use a type family to get a one (opaleye) to many (haskell) mapping, in other words we only have the `haskells -> columns` functional dependency. This means you have to add type signatures sometimes, notably if you are not using all fields of a query result. Here's our type family if you want some inspiration https://github.com/silkapp/silk-opaleye/blob/master/src/Silk/Opaleye/Conv.hs, and our "run" functions look like this https://github.com/silkapp/silk-opaleye/blob/master/src/Silk/Opaleye/Query.hs#L174

**Comment by lippling** [comment]
I think Tom's approach would be a pragmatic way for us, without changing much. I'll look into that later. Thanks to both of you!

**Comment by tomjaguarpaw** [comment]
I'm closing this because it's old and I don't have any concrete plans to address it. If you think it still needs addressing or have any further details to add then please reopen or file a new issue.
