### ISSUE TITLE
Is opaleye-sqlite not being actively developed?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#190]
I'm planning to try Opaleye, but need to work with Sqlite (the app will be deployed on a Raspberry Pi). I noticed that opaleye-sqlite is not on [LTS-6.12](https://www.stackage.org/lts-6.12), nor has it received any commit since a year. Hence this question.

**Comment by tomjaguarpaw** [comment]
It's not being actively developed.  It was an experimental branch which worked for at least one user.  I'm not sure if they're still using it.

**Comment by saurabhnanda** [comment]
Unfortunate. I was really warming-up to Opaleye and wanted to switch over from Yesod+Persistent to Servant+Opaleye. Any idea if Postgres can work comfortable on Raspberry Pi?

**Comment by tomjaguarpaw** [comment]
No idea, but it seems unlikely!  You may as well play with Opaleye to see if you prefer it to Yesod.  If you do, and you are willing to work with me on opaleye-sqlite, then we can bring it up to scratch.

FYI though, as far as I am aware, Persistent is used much more than Opaleye in the web space.

**Comment by lippling** [comment]
To add my two cents, I used Yesod+Persistent in a project and I was not very happy with it. I also tried to use Servant, but it felt very limited to me for commercial projects.

For a current project I use Yesod+Opaleye. It is not supported out of the box, but I replaced Persistent with Opaleye entirely and it works. Yesod may not be very pretty, but it is pragmatic, gets the job done efficiently and is fun.

**Comment by saurabhnanda** [comment]
@lippling do you have a write-up about what you didn't like in Yesod and Servant? If not, may I request you to document your experience?

I'm leaning towards Servant because ultimately I want to replace my API backend, which is currently written in Rails, in Haskell. Servant's type-safety is focused in the request/response area which seems like it will be an advantage for my use-case. Yesod doesn't seem to be foxusing on this sort of type-safety. 

On the DB front, here's my gripe list with Persistent so far:

* No clear way to deal with values originating from the DB, eg primary keys and created/updated timestamps. 
* no clear way of how to write a low-level DB access API. If I want to make sure some invariants hold every time a record is written to the DB (some variant that cannot be lifted to the type level) where do I do it? I have to write my own function and make sure everyone on the team uses that function and not Persistsent's update/replace/insert. 
* because of the previous point, implementing an audit log at the app-level (instead of the DB level, via triggers) is needlessly tough. 
* no ability to deal with associations at the DB level and automatically convert them into nested records. Have ranted quite a lot about this point. 

And I don't know how both, Yesod and Servant, deal with validations. Remains to be seen.

**Comment by saurabhnanda** [comment]
Also, not clear how to implement life-cycle callbacks in Persistent, eg before-save, after-save, before-create, after-create, before-update, after-update. Very useful if you have a Redis cache which needs to be busted every time a record in the DB js updated.

**Comment by lippling** [comment]
@saurabhnanda No I don't have a write-up.
I evaluated Servant several months ago, because I liked the idea of having type-safe requests/responses, but to me that was all it could do. It lacked everything else, it didn't even have simple basic auth or file uploads (that may have changed by now).
I have to deliver a commercial product and don't have time to implement such "low-level" things. So I 
went down the Warp/Yesod road, implemented an oauth2 lib (resource owner workflow) and replaced Persistent with Opaleye.
This works for me.

**Comment by bergmark** [comment]
Our [rest library](https://silkapp.github.io/rest/) does support things like basic auth/file uploads, a bit in the direction of servant, but with less type-hackery (which is good and bad...).

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.

**Comment by lynnard** [comment]
I'm also investigating DB choices and am leaning towards opaleye as well for my application. Not having sqlite would be a real shame as the concepts of opaleye look really good to me (compared with persistent), but my platform doesn't support postgres as well (android).

As a start I think I'll try the unmaintained version of opaleye-sqlite first, see how it goes and maybe in future there will be opportunities to contribute to make it more updated.

@saurabhnanda Just curious - did you end up using `opaleye` in the end?

**Comment by tomjaguarpaw** [comment]
@lynnard The unmaintained version of Opaleye probably still works but bringing it up-to-date would probably be a lot of work.  (And yes, @saurabhnanda is one of the heaviest users of Opaleye, at least in terms of communication with me!)
