### ISSUE TITLE
Possible TutorialManipulation.lhs discrepancy.

### ISSUE THREAD

**Issue by oddvars** [tomjaguarpaw/haskell-opaleye#191]
Hi

I've begun replacing my current database code (postgres-simple and persistent) with Opaleye, and while playing around with the update side of things I came across a slight discrepancy with the update example from the manipulation tutorial. 

The tutorial states that the sql generated by 'putStrLn update' should be:

_UPDATE tablename
SET x = (x) + (y),
    y = (x) - (y)
WHERE ((id) = 5)_

When I try to run the same example, it comes out as:

_UPDATE "tablename"
SET "id" = DEFAULT,
    "x" = ("x") + ("y"),
    "y" = ("x") - ("y"),
    "s" = "s"
WHERE (("id") = 5)_

Am I doing something wrong since the "id" = DEFAULT appears as one of the columns to be updated at my end?

Regards, 
Oddvar

**Comment by tomjaguarpaw** [comment]
The tutorial is incorrect and the output that you are seeing is the correct version.

**Comment by tomjaguarpaw** [comment]
Thanks for filing the ticket.  I will correct that.

**Comment by oddvars** [comment]
No worries. If I did want to generate a query where the columns in the WHERE clause don't appear in the SET section, how would I express that in an update function?

I thought about making a different table definition, but I can't seem to easily create a table definition where the write type has a different number of columns to the read type. I assume this is down to profunctor product wanting to pair up read and write parameters.

**Comment by tomjaguarpaw** [comment]
You can't omit columns from the SET section.  If you want to leave their values unchanged then just set them to themselves.  Does that solve your problem?

**Comment by oddvars** [comment]
Yeah, that's fine, thank you for your reply.
