### ISSUE TITLE
Request for documentation: Records

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#196]
I'm referring to https://github.com/tomjaguarpaw/haskell-opaleye/tree/master/Doc/Tutorial and wasn't able to find how to do the following:

write the following to DB:

```
data Tenant = Tenant {
  name :: Text
  ,ownerId :: Maybe OwnerId 
  ,backofficeDomain :: Text
}
```

Read back the following from DB:

```
data Tenant = Tenant {
  id :: TenantId
  ,createdAt :: UTCTime
  ,updatedAt :: UTCTime
  name :: Text
  ,status :: Text -- actually this is not Text, see other issue on Github
  ,ownerId :: Maybe OwnerId 
  ,backofficeDomain :: Text
}
```

**Comment by saurabhnanda** [comment]
Is it even possible to have `Table` where the number of `writerColumns` is different from the number of `viewColumns`?

**Comment by tomjaguarpaw** [comment]
Is `status` autogenerated?

**Comment by saurabhnanda** [comment]
I'm still working out the mechanics of my domain API. Right now, I'm thinking that a tenant will always be created in an 'inactive' state, and a `activateTenant` function will need to be called to flip the status (it will also do a bunch of other things, like populate initial data, send out welcome email, etc)

**Comment by saurabhnanda** [comment]
A comment related to the practical applicability of this issue -- https://github.com/nomicflux/servant-opaleye-blog/issues/3

If that tutorial is using optional columns/fields in the correct manner, then isn't it type-unsafe to allow users to pass-in an ID and timestamp in the write-record, only to be ignored? Isn't removing the ID and timestamp fields from the write-record the type-safe way of doing it?

**Comment by tomjaguarpaw** [comment]
If it's type unsafe it's certainly amongst the least unsafe of type unsafe things.  Still, I agree it's bad practice to require parameters that are going to be ignored.  Nothing in Opaleye forces you to provide those parameters though.

**Comment by tomjaguarpaw** [comment]
> Is it even possible to have Table where the number of writerColumns is different from the number of viewColumns?

Yes.  You can use `lmap` to remove `Maybe`-typed columns from your `writerColumns`, if you like.

**Comment by tomjaguarpaw** [comment]
Closing as stale.
