### ISSUE TITLE
Request for docs: Handling nullable and optional columns

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#198]
From the tutorials it is not very clear how to handle the following cases:
- Not null, value required during writes
- not null, value optional during writes (ie default value provided by DB)
- Nullable, value required during writes (not sure what the uae-case for this would be)
- Nullable, value optional during writes

**Comment by tomjaguarpaw** [comment]
Yes, I should copy the contents of this comment to the docs:

https://www.reddit.com/r/haskell/comments/4xceqz/why_building_webapps_in_haskell_is_harder_than_it/d6etq9f
