### ISSUE TITLE
Request for docs: Difference between tutorials?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#199]
What's the difference between the various tutorials:
- Basic
- Monomorphic
- TypeFamilies

When should one be using what?

**Comment by tomjaguarpaw** [comment]
The simplest answer is that you should be using `TutorialBasic`.  The others are works in progress.

**Comment by saurabhnanda** [comment]
What's the rationale for the naming convention, for example: https://github.com/tomjaguarpaw/haskell-opaleye/blob/079dae557bf116a2293e4f09596487801f61aabf/Doc/Tutorial/TutorialBasicMonomorphic.lhs#L182-L187

Doesn't that data-type doesn't represent a *widget row* instead *widget column*?

**Comment by tomjaguarpaw** [comment]
It's called `WidgetColumn` because it is a widget-container-thing that stores Postgres columns rather than Haskell types.

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.
