### ISSUE TITLE
Aggregate QueryArr a b

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#202]
Is it possible to aggregate a Query like

```haskell
q :: QueryArr (ArenaRun.IdColumn, User.IdColumn) ArenaRunResult.ScoreColumn
q = proc (runId, userId) -> do
    result <- ArenaRunResult.query -< ()
    restrict -< ArenaRunResult.runId result .=== runId
        .&& ArenaRunResult.userId result .=== userId
    returnA -< ArenaRunResult.score result
```

with

```haskell
aggregate (pNewtype OE.sum)
```
?

Or does 

> By design there is no aggregation function of type Aggregator b b' -> QueryArr a b -> QueryArr a b'. Such a function would allow violation of SQL's scoping rules and lead to invalid queries.

means: no?

**Comment by tomjaguarpaw** [comment]
Indeed, it means no.  If it's acceptable to use

    q :: (ArenaRun.IdColumn, User.IdColumn) -> Query ArenaRunResult.ScoreColumn

then you can aggregate that.  The downside is that the input must be statically known (i.e. it can't be the result of a part of another query).

**Comment by lippling** [comment]
Mmh, so I was right, I'll need two queries. Thanks for the clarification!
