### ISSUE TITLE
Request for docs: runInsertReturning

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#204]
Going by the name, my assumption is that `runInsertReturning` is used to insert a new record and read it back from the DB. If that's the case, here are a bunch of questions:

```runInsertReturning :: Default QueryRunner returned haskells => Connection -> Table columnsW columnsR -> columnsW -> (columnsR -> returned) -> IO [haskells]```

* Why do I need to provide a `columnsR -> returned` mapping function? Haven't I already declared the mapping when setting up the table write & read column types?
* It seems that this function can insert only one record at a time. Why is the return type an array of `[haskells]`?

**Comment by tomjaguarpaw** [comment]
Firstly, `runInsertReturning` will be deprecated.  Use `runInsertManyReturning` instead.

> Why do I need to provide a columnsR -> returned mapping function? Haven't I already declared the mapping when setting up the table write & read column types?

Sure, but Postgres's `INSERT RETURNING` allows you to apply and additional function to the inserted rows.  If you simply want the rows themselves just use `id` for this argument.

> It seems that this function can insert only one record at a time. Why is the return type an array of [haskells]?

Because an SQL query always returns a list of rows.

**Comment by tomjaguarpaw** [comment]
Fixed in 0.5.1.0.  See https://hackage.haskell.org/package/opaleye-0.5.1.0/docs/Opaleye-Manipulation.html

**Comment by saurabhnanda** [comment]
> Firstly, runInsertReturning will be deprecated. 

Any reason why? Isn't it a nice convenience function for a common use-case -- inserting one row?

> Sure, but Postgres's INSERT RETURNING allows you to apply an additional function to the inserted rows. If you simply want the rows themselves just use id for this argument.

Where can I read more about this? Wouldn't "applying function on rows" be a Haskell (postgres-simple or opaleye) thing, and not a PG thing?

Also, what function do I pass in the fourth argument (`columnsR -> returned`) if I want (presumably) the most obvious behaviour of giving me back the default "read data-structure" that `queryTable` also returns?

**Comment by tomjaguarpaw** [comment]
> > Firstly, runInsertReturning will be deprecated.

> Any reason why? Isn't it a nice convenience function for a common use-case -- inserting one row?

The "common use-case" is a pretty trivial special case of `runInsertManyReturning` and I'd rather keep the API as small as possible.  If you really think `runInsertReturning` is useful I'm happy to hear arguments for it.

> Where can I read more about this? Wouldn't "applying function on rows" be a Haskell (postgres-simple or opaleye) thing, and not a PG thing?

No, it's a PG thing.  What if you want to apply a function that doesn't exist Haskell-side?

> Also, what function do I pass in the fourth argument (columnsR -> returned) if I want (presumably) the most obvious behaviour of giving me back the default "read data-structure" that queryTable also returns?

I hope it's obvious that it should be `id`.  If not please explain why!

**Comment by saurabhnanda** [comment]
> The "common use-case" is a pretty trivial special case of runInsertManyReturning and I'd rather keep the API as small as possible. If you really think runInsertReturning is useful I'm happy to hear arguments for it.

I agree that it's a trivial use-case, but fairly common. Either the API docs should have an example of the recommended way to insert a single record, or we could probably retain the helper function itself. Missing all these small niceties leads to a sub-par programmer experience and more boilerplate code.

Another way to look at is, if 80% of the projects using Opaleye are going to first define similar helper functions, then it probably makes sense to support those use-cases out-of-the-box.

> No, it's a PG thing. What if you want to apply a function that doesn't exist Haskell-side?

Is this possible in PG? Any links that I can go through? I never knew this was possible in an `INSERT` statement.

> I hope it's obvious that it should be id. If not please explain why!

No, it was not obvious to me at all. In fact, the entire PG<=>Haskell mapping is not obvious from the tutorials. I think this is primarily because the tutorials delve a lot with ad-hoc SQL queries and not the use-case that I'm looking for -- row<=>record mapping. It's not obvious from the API docs, which function will convert an SQL row into a Haskell record/type, and how it knows which type to convert to.

**Comment by tomjaguarpaw** [comment]
> Another way to look at is, if 80% of the projects using Opaleye are going to first define similar helper functions, then it probably makes sense to support those use-cases out-of-the-box.

Fair enough.  I'll bear it in mind.

> > No, it's a PG thing. What if you want to apply a function that doesn't exist Haskell-side?

> Is this possible in PG? Any links that I can go through? I never knew this was possible in an INSERT statement.

Absolutely.  That's what `INSERT RETURNING` does: https://www.postgresql.org/docs/9.5/static/sql-insert.html  (and `UPDATE RETURNING`).

> No, it was not obvious to me at all.

OK, thanks.  Good to know.
