### ISSUE TITLE
Lacking `in` operator

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#21]
I had a stab at this with:

```haskell
in_ :: Column a -> [Column a] -> Column PGBool
in_ x ys =
  Opaleye.binOp HPQ.OpIn
                x
                (Opaleye.Column (HPQ.ListExpr [y | Opaleye.Column y <- ys]))
```

However this produces:

```sql
WHERE ((id0_2) IN ((10025,10355)))) as T1
```

Which isn't correct, as there are one too many levels of parenthesis, which changes the semantics to be a list of records, rather than list of integers.

**Comment by bergmark** [comment]
This is what we've been using, is it good enough?

```haskell
ors :: Foldable f => f (Column PGBool) -> Column PGBool
ors = foldr (.||) (constant False)

ands :: Foldable f => f (Column PGBool) -> Column PGBool
ands = foldr (.&&) (constant True)

inE :: [Column o] -> Column o -> Column PGBool
inE hs w = ors . map (w .==) $ hs

notIn :: [Column a] -> Column a -> Column PGBool
notIn hs w = ands . map (w ./=) $ hs
```

**Comment by ocharles** [comment]
It's definitely good enough, but it might be nice to have something that maps directly to the `or` operator. If we don't do that, we should get @bergmark's functions added.

**Comment by tomjaguarpaw** [comment]
@ocharles What do you mean "maps directly to the `or` operator"?

**Comment by bergmark** [comment]
I'm guessing he meant `s/or/in`...

**Comment by ocharles** [comment]
Bleh, I did indeed. I would expect the compiled query to be:

```sql
x IN (a, b, c)
```

or

```sql
x IN null
```

**Comment by tomjaguarpaw** [comment]
Is there a particular benefit to that beyond the stylistic?

**Comment by ocharles** [comment]
I don't have a good argument for that, so if you think folding `OR` is better than we can do that. My main desire is that this exists in `opaleye` itself. I probably lean towards `IN` because that's being even more declarative to the query planner about what you want, which may give it an easier job finding an efficient plan. I have nothing to back that up, however.

**Comment by tomjaguarpaw** [comment]
Folding `OR` is easier to implement, since, as you have seen, parenthesising an SQL expression can cause a change in meaning.  As you say, `IN` might lead to better performance.

I can add a version that folds `OR` and later change the implementation to `IN` without breaking the API.  The remaining question is what the name and type should be.  I prefer your version `in_ :: Column a -> [Column a] -> Column PGBool` to the other argument order and to the name `inE`.  Does anyone have any strong opinions?

**Comment by ocharles** [comment]
I've actually been using `inE` as @bergmark provides, and have found this order to be quite nice:

```haskell
getClassTypesById ids =
  fmap (HashMap.fromList .
        fmap ((key &&& value) .
              interpretClassTypesResult))
       (runOpaleye
          (restrictWith
             (inE (map pgClassTypeId ids) .
              classTypesId)
             classTypes))

**Comment by bergmark** [comment]
`in_` is probably a better name.

I'm only using it in one place so it's hard for me to say which argument order is nicer, my usage is similar to @ocharles so there what I have is nicer. If support is added for the `value IN (SELECT value FROM tbl_name);` form the other order might be nicer for that use case.

**Comment by bergmark** [comment]
Or wait, is that already possible? :)

**Comment by tomjaguarpaw** [comment]
@ocharles I will be happy to accept a pull request.  I will let you decide on your preferred signature!

**Comment by WraithM** [comment]
I know this is sort of an old issue.

It'd be really great if there was a query like:

```haskell
in' :: Column a -> Query (Column a) -> Query ()
notIn :: Column a -> Query (Column a) -> Query ()

-- Used like this (very loosely)
proc () -> do
    row@(Person personId name) <- queryTable personTable -< ()
    personId `in'` queryTable randomPersonIdsTable
    returnA -< row
```
which would produce SQL like this:
```sql
WHERE column IN (SELECT column FROM tbl_name);
WHERE column NOT IN (SELECT column FROM tbl_name);
```

What does everybody think about this? Is this possible?

**Comment by tomjaguarpaw** [comment]
The original issue has been closed for some time, and @WraithM's extension is closed by https://github.com/tomjaguarpaw/haskell-opaleye/commit/1df1ad3fdd40b4e19850badc870918217338d340
