### ISSUE TITLE
Nesting & flattening columns?

### ISSUE THREAD

**Issue by iand675** [tomjaguarpaw/haskell-opaleye#213]
I'm just experimenting with Opaleye so far, so apologies if this should seem obvious:

I'd like to be able to insert / query things with the basic shape of `(keyColumn, (value1, value2, ...))` where there's 1 or more keys that can be 'peeled off' of the rest of the selected values easily.

As a concrete example, consider the Entity type provided by persistent. There's an `Entity` abstraction that separates the primary key from the rest of the data type. So for a user, the entity is something (loosely) like `Entity Int User`, where it's easy to just take a `User` without holding onto the `Int` key.

Is there a way to do that sort of abstraction with Opaleye?

**Comment by tomjaguarpaw** [comment]
Do you mean something like this?

````haskell
personTable :: Table (Column PGInt4, (Column PGText, Column PGInt4, Column PGText))
                     (Column PGInt4, (Column PGText, Column PGInt4, Column PGText))
personTable = Table "personTable" (p2 ( required "id"
                                      , (p3 ( required "name"
                                            , required "age"
                                            , required "address" )))
````

Opaleye supports this without futher ado.  What part are you having trouble with?

**Comment by iand675** [comment]
Oh, that turned out to be surprisingly simple! I didn't realise that the `p3` needed to be used on the nested portion.

Thanks for the quick help.
