### ISSUE TITLE
Idiomatic way of getting a table larger than 62 columns?

### ISSUE THREAD

**Issue by folsen** [tomjaguarpaw/haskell-opaleye#216]
If i wanted to create a table with a larger size than 35 columns (the default max of `p35` in the library) I could do something like this, which I'm not sure if it's the recommended way of doing it or not, but it seems to work.

```
{-# LANGUAGE TemplateHaskell #-}
module Main where

import Data.Profunctor.Product
import Data.Profunctor.Product.Flatten
import Data.Profunctor.Product.Tuples
import Data.Profunctor.Product.Tuples.TH

mkFlattenNs [36..62]
mkUnflattenNs [36..62]
mkTs [36..62]
pTns [36..62]
pNs [36..62]
```

However, if I try to increase this limit (62) I will run into a GHC limitation.

```
    A 63-tuple is too large for GHC
      (max size is 62)
      Workaround: use nested tuples or define a data type
```

Is there any way to work around this in Opaleye? Having more than 62 columns is the norm (at least in the world I work in) so it would be great if there was a clean and easy way to do this. Perhaps there is a straightforward way that I'm missing, if so then it would be great to add that to a code sample in the tutorial or otherwise in some documentation.

**Comment by tomjaguarpaw** [comment]
Nested data types work fine.  Have you tried them?

**Comment by tomjaguarpaw** [comment]
If you really want flat records bigger than 62 fields then I can probably tweak the product-profunctors TH to generate instances that don't go via the tuple instances.

**Comment by tomjaguarpaw** [comment]
Here's an example of nested datatypes

````haskell
table = Table "tablename"
              (pFoo Foo { bar = pBar Bar { bar1 = required ...
                                         , bar2 = required ...
                                         }
                        , foo = pFoo Foo { foo1 = required ...
                                         , foo2 = required ...
                                         }
                        , baz = required ...
                        }
              )
````

**Comment by folsen** [comment]
I'm trying to make the generator that will spit out all the table definitions for an arbitrary database, thus I want to impose as few assumptions on the tables themselves (such as any potential nested structure that only makes sense to the table author).

**Comment by tomjaguarpaw** [comment]
> I'm trying to make the generator that will spit out all the table definitions for an arbitrary database

Great!

Sounds like I need to fix that TH then.

**Comment by tomjaguarpaw** [comment]
By the way, if you're familiar with TH and can't wait for me to do it it shouldn't be too hard to do yourself.

**Comment by tomjaguarpaw** [comment]
Can you try the `fieldnames` branch of `product-profunctors` and see if that  works for you?  It should work with flat records of any size

https://github.com/tomjaguarpaw/product-profunctors/tree/fieldnames

**Comment by folsen** [comment]
I have a working generator now, and can confirm that when I generate code and then try to compile the generated code with the Hackage version of the profunctor library it says:

```
    Exception when trying to run compile-time code:
      Data.Profunctor.Product.TH: 38 is too many type variables for me!
```

When I use the github branch above, it gives me no errors, compiles and runs a sample query successfully. So the above patch seems to work for my purpose.

**Comment by tomjaguarpaw** [comment]
That's great!

My branch to `product-profunctors` is not quite suitable for merging into `master`.  I'll find a suitable way of merging in the future.  If it becomes an urgent issue for you let me know.

**Comment by saurabhnanda** [comment]
Just ran into this issue:

```
        Exception when trying to run compile-time code:
          Data.Profunctor.Product.TH: 46 is too many type variables for me!
```

Is there a fix available somewhere?

**Comment by tomjaguarpaw** [comment]
Which version of `product-profunctors` are you using?  [0.8.0.3 seems to support up to 62](https://hackage.haskell.org/package/product-profunctors-0.8.0.3/docs/src/Data-Profunctor-Product-Internal-TH.html#makeAdaptorAndInstanceI).

**Comment by tomjaguarpaw** [comment]
If you're writing your datatype by hand it's probably better to split it into smaller nested datatypes instead.

If you're automatically generating it and it's still bigger than 62 let's talk further.

**Comment by saurabhnanda** [comment]
I was using LTS-8.16 which was giving this issue. I switched to a nightly, and it seemed to work.
