### ISSUE TITLE
`PGLift` idea

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#22]
At Fynder we have a lot of custom types. In fact, every table gives rise to (at least) one `newtype` wrapper around its surrogate id. The following type is useful to "lift" coercions in `postgresql-simple` to `opaleye`:

```haskell
data PGLift a

instance PG.FromField a => Opaleye.QueryRunnerColumnDefault (PGLift a) a where
  queryRunnerColumnDefault = fieldQueryRunnerColumn
```

Maybe this is something that would fit nicely in `opaleye` itself?

**Comment by bergmark** [comment]
I'm going to try this out and see how it fits in with our setup. Currently we just use newtypes and derive a bunch of instances with TH.

**Comment by tomjaguarpaw** [comment]
@ocharles Can you give an explicit example of how you use this?

**Comment by ocharles** [comment]
An associated useful type class is:

```haskell
class Literal a where
  lit :: a -> Column (PGLift a)
```

**Comment by ocharles** [comment]
@tomjaguarpaw You use it just like you would use `PGInt4` or `PGUTCTime`:

```haskell
type AuthFacebookColumn = AuthFacebook (Column (PGLift AuthFacebookId)) (Column (PGLift UserId)) (Column (PGLift AuthFacebook.FacebookUserId))
type AuthFacebookResult = AuthFacebook AuthFacebookId UserId AuthFacebook.FacebookUserId

fynderAuthFacebook :: Table AuthFacebookColumn AuthFacebookColumn
fynderAuthFacebook =
  Table "fynder_auth_facebook" ...

authFacebook :: Query AuthFacebookColumn
authFacebook = queryTable fynderAuthFacebook

-- later...

getAuthFacebookById :: AuthFacebookId -> Query AuthFacebookColumn
getAuthFacebookById = 
  fmap (kvListToMaybe Db.interpretAuthFacebookResult)
       (runOpaleye
          (restrictWith ((lit afId Op..==) . Db.authFacebookId)
                        Db.authFacebook))

```

**Comment by ocharles** [comment]
I would go so far as to say `PGLift` is the *only* type `Opaleye` needs to provide - otherwise you're just eternally playing catch up.

**Comment by bergmark** [comment]
I forgot, but we actually do something very smilar,

```haskell
class ShowConstant h where
  type PGRep h :: *
  constant :: h -> Column (PGRep h)

instance ShowConstant [Char] where
  type PGRep String = PGText
  constant = pgString
instance ShowConstant (CI S.Text) where
  type PGRep (CI S.Text) = PGCitext
  constant = pgCiStrictText

showConstant :: ShowConstant h => h -> Column (PGRep h)
showConstant = constant
```

**Comment by ocharles** [comment]
Right, but that still requires you to write a load of `PGText` `PGCitext` types, etc. But yea, `ShowConstant` has the same goal as `Literal`.

**Comment by tomjaguarpaw** [comment]
If this turns out to be particularly useful then I can include it in Opaleye.  For now I would suggest it belongs in an `fynder-opaleye-extras` package that everyone can use and see how it works out in practice.  One particular issue with it is that it is going to be `postgresql-simple` specific.  At some point I will want to add a `hasql` query runner, for example.

This idea basically harks back to the old HaskellDB way of doing things which I moved away from in the public release of Opaleye.  In HaskellDB you had database columns represented by `Expr Int`, `Expr Bool`, `Expr String` etc. i.e. they contained the name of the Haskell type they were expected to convert to.  I ended up not liking this for a few different reasons which all boil down to the same thing: there simply isn't a direct correspondence between Haskell types and Opaleye types.  For example, a Postgres `integer` has more precision (typically) than a Haskell `Int`, and what converts to Haskell as `Lazy.Text`, `Strict.Text` and `String` should all be interchangeable Opaleye-side.

For this reason I like to be explicit about the underlying Postgres types and I think it is necessary that Opaleye can be this explicit on some level.  However, building higher-level, less explicit structures on top is very much encouraged!  If they have wide utility then I am very happy to include them in the package.

As a point of information, if I were writing your `AuthFacebookId` example I think I would do

    newtype AuthFacebookId' a = AuthFacebookId
    type AuthFacebookId = AuthFacebookId Int
    type AuthFacebookIdColumn = AuthFacebookId (Column Int)

but this is a matter of personal taste, since I don't think any compelling argument for any particular structure has been made yet.

**Comment by ocharles** [comment]
The many-types problem you describe doesn't seem to be a problem though. You're not trying to describe bijections, so having one PG type to potentially many Haskell types seems fine. I don't see anyone asking for many PG types to one Haskell type, so I would think we are ok.

Your suggestion about `AuthFacebook` is not one I agree with - Opaleye's somewhat requirement on making all data types extremely polymorphic is not idiomatic Haskell, and I remain unconvinced that it's the only way to go.

If you want `PGLift` to support multiple backends though, you could use `ConstraintKinds` to add a little more information:

```
data PGLift (c :: Constraint) a = PGLift

type PGSimple a = PGLift PGSimple.FromField Int
type Hasql backend a = PGLift (Hasql.CxValue backend) a
```

**Comment by tomjaguarpaw** [comment]
> Opaleye's somewhat requirement on making all data types extremely polymorphic is not idiomatic Haskell

Opaleye does not require you to use fully polymorphic datatypes.

**Comment by tomjaguarpaw** [comment]
And furthermore I agree it's not the only way to go!

**Comment by ocharles** [comment]
It certainly doesn't *require* it, but it sure is painful to use if you don't :) At least, from what we've found so far. Having named accessors into parts of a row is essential.

**Comment by tomjaguarpaw** [comment]
To clarify what I am trying to say: If you find a way of defining a datatype that is more to your taste then it won't require any changes to the internals of Opaleye to use it. (Or if it does that is a bug in Opaleye.  Please file an issue.)

In particular, this is not an Opaleye-specific problem but a generic problem of datatype representation in Haskell.  Of course, I would like to find a universally satisfactory representation and make Opaleye particularly easy to use with it, but the former may have to be done by someone with more available time than I have.

**Comment by tomjaguarpaw** [comment]
Regarding the question of a single Postgres type mapping to multiple Haskell types:

Would you expect `PGLift String` and `PGLift Lazy.Text` to be interchangeable?  Would you expect something like the following to be well-typed?

    let name = (firstName :: Column (PGLift String)) .++ (surname :: Column (PGLift Lazy.Text))

If not, why not?  The two underlying types are exactly the same to Postgres and moreover are intended to represent exactly the same thing.  If so, how would you set up `PGLift` so this is well-typed?

**Comment by bergmark** [comment]
This seems to be related to #27.

I would expect your example with `.++` to be ill-typed, if you want to combine different types like this use `unsafeCoerce`.

**Comment by jhickner** [comment]
@ocharles I'm trying out this idea but getting stuck on how to write instances of `Literal` for my newtypes.

    class Literal a where
      lit :: a -> Column (PGLift a)

It doesn't seem like it's possible to construct a value of `Column (PGLift a)` since `PGLift` has no constructor and `Column` doesn't have one exposed. No doubt I'm missing something simple. Can you post an example instance?

**Comment by ocharles** [comment]
Sure thing @jhickner, here is the relevant code from work:

```haskell
data PGLift a

instance PG.FromField a => Opaleye.QueryRunnerColumnDefault (PGLift a) a where
  queryRunnerColumnDefault = fieldQueryRunnerColumn

type PGAdminProfileId = PGLift AdminProfileId
type PGAuthFacebookId = PGLift AuthFacebookId
type PGAuthPasswordId= PGLift  AuthPasswordId
type PGAuthSweatyBettyId = PGLift AuthSweatyBettyId
type PGBusinessId = PGLift BusinessId
type PGBusinessProfileStripeId = PGLift BusinessProfileStripeId
type PGClassBookingId = PGLift ClassBookingId
type PGClassId = PGLift ClassId
type PGClassNotificationSubId = PGLift ClassNotificationSubId
type PGClassTemplateId = PGLift ClassTemplateId
type PGClassTypeId = PGLift ClassTypeId
type PGClassWaitQueueEntryId = PGLift ClassWaitQueueEntryId
type PGColourRGB8 = PGLift ColourRGB8
type PGCreditPackOfferId = PGLift CreditPackOfferId
type PGCurrency = PGLift Currency
type PGCustomerActivity = PGLift CustomerActivity.Activity
type PGCustomerActivityId = PGLift CustomerActivityId
type PGCustomerClassCreditId = PGLift CustomerClassCreditId
type PGCustomerNoteId = PGLift CustomerNoteId
type PGCustomerProfileId = PGLift CustomerProfileId
type PGEmailAddress = PGLift EmailAddress
type PGEncryptedPassword = PGLift Model.EncryptedPassword
type PGFacebookUserId = PGLift AuthFacebook.FacebookUserId
type PGGender = PGLift Gender
type PGInitialCreditPackOfferId = PGLift InitialCreditPackOfferId
type PGJSON = PGLift Aeson.Value
type PGLocationId = PGLift LocationId
type PGLocationSweatyBettyId = PGLift LocationSweatyBettyId
type PGNonNegative a = PGLift (NonNegative a)
type PGPositive a = PGLift (Positive a)
type PGPaymentSubscriptionId = PGLift PaymentSubscriptionId
type PGRoleTag = PGLift RoleTag
type PGSlug = PGLift Slug
type PGStripeCustomerId = PGLift StripeCustomerProfile.StripeCustomerId
type PGStripeCustomerProfileId = PGLift StripeCustomerProfileId
type PGStripePaymentPlanId = PGLift StripePaymentPlanId
type PGStripeUserId = PGLift BusinessProfileStripe.StripeUserId
type PGStudioId = PGLift StudioId
type PGSweatyBettyId = PGLift AuthSweatyBetty.SweatyBettyId
type PGTZInfoId = PGLift TZInfoId
type PGTexty = PGLift Texty
type PGTrainerProfileId = PGLift TrainerProfileId
type PGURI = PGLift Model.URI
type PGUserId = PGLift UserId
type PGUserProfileBusinessStaffId = PGLift UserProfileBusinessStaffId
type PGUserProfileLocationAdminId = PGLift UserProfileLocationAdminId

class Literal a where
  lit :: a -> Column (PGLift a)

wrappedLiteral :: (Literal (Unwrapped a), Rewrapped a a) => a -> Column (PGLift a)
wrappedLiteral = C.unsafeCoerce . lit . review _Unwrapped

instance Literal LocationId where lit = wrappedLiteral
instance Literal StudioId where lit = wrappedLiteral
instance Literal PaymentSubscriptionId where lit = wrappedLiteral
instance Literal LocationSweatyBettyId where lit = wrappedLiteral
instance Literal AdminProfileId where lit = wrappedLiteral
instance Literal AuthFacebook.FacebookUserId where lit = wrappedLiteral
instance Literal AuthFacebookId where lit = wrappedLiteral
instance Literal AuthPasswordId where lit = wrappedLiteral
instance Literal AuthSweatyBetty.SweatyBettyId where lit = wrappedLiteral
instance Literal AuthSweatyBettyId where lit = wrappedLiteral
instance Literal BusinessId where lit = wrappedLiteral
instance Literal BusinessProfileStripe.StripeUserId where lit = wrappedLiteral
instance Literal BusinessProfileStripeId where lit = wrappedLiteral
instance Literal ClassBookingId where lit = wrappedLiteral
instance Literal ClassId where lit = wrappedLiteral
instance Literal ClassNotificationSubId where lit = wrappedLiteral
instance Literal ClassTemplateId where lit = wrappedLiteral
instance Literal ClassTypeId where lit = wrappedLiteral
instance Literal ClassWaitQueueEntryId where lit = wrappedLiteral
instance Literal CreditPackOfferId where lit = wrappedLiteral
instance Literal CustomerClassCreditId where lit = wrappedLiteral
instance Literal CustomerNoteId where lit = wrappedLiteral
instance Literal CustomerProfileId where lit = wrappedLiteral
instance Literal StripeCustomerProfile.StripeCustomerId where lit = wrappedLiteral
instance Literal StripePaymentPlanId where lit = wrappedLiteral
instance Literal TZInfoId where lit = wrappedLiteral
instance Literal TrainerProfileId where lit = wrappedLiteral
instance Literal UserId where lit = wrappedLiteral
instance Literal UserProfileBusinessStaffId where lit = wrappedLiteral
instance Literal UserProfileLocationAdminId where lit = wrappedLiteral
instance Literal (NonNegative Int32) where lit = C.unsafeCoerce . lit . review _NonNegative

instance Literal Texty where
  lit = literalColumn . HPQ.StringLit . Text.unpack . review Model.texty

instance Literal Int32 where
  lit = literalColumn . HPQ.IntegerLit . fromIntegral

instance Literal Int64 where
  lit = literalColumn . HPQ.IntegerLit . fromIntegral

instance Literal EmailAddress where
  lit = literalColumn . HPQ.StringLit . Text.unpack . decodeUtf8 . review Model.emailAddress

instance Literal CreditPackOffer.SalesStrategy where
  lit = literalColumn . HPQ.IntegerLit . fromIntegral . review CreditPackOffer._SalesStrategy

nullValuesspec :: Valuesspec columns (Column a)
nullValuesspec = Valuesspec (PM.PackMap (\f () -> fmap C.Column (f (HPQ.ConstExpr HPQ.NullLit))))

instance Default Valuesspec (C.Column (Nullable a)) (C.Column (Nullable a)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift ClassId)) (C.Column (PGLift ClassId)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift ClassTypeId)) (C.Column (PGLift ClassTypeId)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift EmailAddress)) (C.Column (PGLift EmailAddress)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift LocationId)) (C.Column (PGLift LocationId)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift StudioId)) (C.Column (PGLift StudioId)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift TZInfoId)) (C.Column (PGLift TZInfoId)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift Texty)) (C.Column (PGLift Texty)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGLift UserId)) (C.Column (PGLift UserId)) where def = nullValuesspec
instance Default Valuesspec (C.Column (PGNonNegative a)) (C.Column (PGNonNegative a)) where def = nullValuesspec
instance Default Valuesspec (C.Column PGBool) (C.Column PGBool) where def = nullValuesspec
instance Default Valuesspec (C.Column PGBusinessId) (C.Column PGBusinessId) where def = nullValuesspec
instance Default Valuesspec (C.Column PGTimestamptz) (C.Column PGTimestamptz) where def = nullValuesspec
```

**Comment by jhickner** [comment]
Thanks @ocharles! That helps a lot! 

I managed to get things going by using `GeneralizedNewtypeDeriving` and then deriving both `FromField` and `Literal` for my newtypes. Then I just wrote `Literal` instances (now that I see how from your code) for the primitives I'm newtyping. 

That seems to work, but I'd like to understand what your `wrappedLiteral` is doing. Would you mind describing it a bit?

**Comment by ocharles** [comment]
@jhickner Well we use `lens` at work, so we have a lot of things like:

```haskell
newtype UserId = UserId Int
makeWrapped ''UserId
```

This means that `UserId` is isomorphic to `Int` - so I write a "base case" `Literal` instance for `Int`, and then `LiteralUser Id` just unwraps that `UserId` to get an `Int` and then uses the `Literal Int` instance. It's mostly just a polymorphic way of unwrapping a newtype.

**Comment by ocharles** [comment]
Unlikely to contribute this back to `opaleye`, but I am exploring similar ideas in my https://github.com/ocharles/opaleye-tf project. I'll close this and carry on there - maybe some ideas will flow back when it's more battle tested.

**Comment by tomjaguarpaw** [comment]
Sounds good.  Looking forward to hearing about any progress.
