### ISSUE TITLE
like and PGArray

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#220]
``` haskell
restrictTitle :: Text -> Column (PGArray PGText) -> Column PGBool
restrictTitle titleFilter title = undefined
```

How can I check if an array element in `title` is `Opaleye.Operators.like` `titleFilter`?

**Comment by tomjaguarpaw** [comment]
Not sure.  How would you do it in SQL?

**Comment by lippling** [comment]
I'm not sure either. Maybe I hoped Opaleye had some PGArray fairy dust. :-)

**Comment by tomjaguarpaw** [comment]
Sadly not.

**Comment by tomjaguarpaw** [comment]
I'm closing this because it's very old and I don't have any concrete plans to address it. If you think it still needs addressing or have any further details to add then please reopen or file a new issue.
