### ISSUE TITLE
What insight about product-profunctors am I missing?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#225]
Going by **just the Opaleye tutorials** and no category-theory stuff about profunctors (and product-profunctors), I wrote the following code with the product-profunctor that `makeAdaptorAndInstance` gives:

```
newTenantToPg :: NewTenant -> TenantPGWrite
newTenantToPg = pTenant Tenant{
  tenantKey = const Nothing
  ,tenantCreatedAt = const Nothing
  ,tenantUpdatedAt = const Nothing
  ,tenantName = pgStrictText
  ,tenantStatus = const $ pgString "new"
  ,tenantOwnerId = maybeToNullableColumn pgUserId
  ,tenantBackofficeDomain = pgStrictText
  }
```

How is this materially different from the non-profunctor version that I would have normally written:

```
newTenantToPg :: NewTenant -> TenantPGWrite
newTenantToPg newTenant = Tenant{ tenantKey = Nothing
                                , tenantCreatedAt = Nothing
                                , tenantUpdatedAt = Nothing
                                , tenantName = pgStrictText (newTenant ^. name)
                                , tenantStatus = pgString "new"
                                , tenantOwnerId = maybeToNullableColumn pgUserId (newTenant ^. ownerId)
                                , tenantBackofficeDomain = pgStrictText (newTenant ^. backofficeDomain)
  }
```

**Am I using profunctors incorrectly? Is there any other example which demonstrates the power of these profunctors?**

-----
Basic data-types are given below to give some context to the code snippet above:

```
data TenantPoly key createdAt updatedAt name status ownerId backofficeDomain = Tenant {
  tenantKey :: key
  ,tenantCreatedAt :: createdAt
  ,tenantUpdatedAt :: updatedAt
  ,tenantName :: name
  ,tenantStatus :: status
  ,tenantOwnerId :: ownerId
  ,tenantBackofficeDomain :: backofficeDomain
  } deriving Show

type TenantPGWrite = TenantPoly
  (Maybe (Column PGInt8)) -- key
  (Maybe (Column PGTimestamptz)) -- createdAt
  (Maybe (Column PGTimestamptz)) -- updatedAt
  (Column PGText) -- name
  (Column PGText) -- status
  (Column (Nullable PGInt8)) -- ownerId
  (Column PGText) -- backofficeDomain

type NewTenant = TenantPoly
  () -- key
  () -- createdAt
  () -- updatedAt
  Text -- name
  () -- status
  (Maybe UserId) -- ownerId
  Text -- backofficeDomain

$(makeAdaptorAndInstance "pTenant" ''TenantPoly)
$(makeLensesWith abbreviatedFields ''TenantPoly)
```

**Comment by tomjaguarpaw** [comment]
I think your normal version is clearer.  Why would you use product profunctors for this?

**Comment by tomjaguarpaw** [comment]
Constructing functions without product profunctor operations is easy.  On the other hand, try to construct a `QueryRunner` without them!

**Comment by saurabhnanda** [comment]
[Straight out of the basic tutorial](https://github.com/tomjaguarpaw/haskell-opaleye/blob/77400e65c209b06c97690d456c63701526f9a7e0/Doc/Tutorial/TutorialBasic.lhs#L131-L148)

```
> birthdayTable :: Table BirthdayColumn BirthdayColumn
> birthdayTable = Table "birthdayTable"
>                        (pBirthday Birthday { bdName = required "name"
>                                            , bdDay  = required "birthday" })
```

I didn't know what I was doing. Just following the tutorial's way of doing things.

Btw, over at https://github.com/vacationlabs/haskell-webapps another person working with Opaleye got stuck with profunctors. The basic idea of how to convert Hask->PG and PG->Hask is not well understood based on the tutorials.

**Comment by saurabhnanda** [comment]
> Constructing functions without product profunctor operations is easy. On the other hand, try to construct a QueryRunner without them!

Please elaborate. What happens if I don't call `makeAdaptorAndInstance` on the `TenantPoly` type?

/cc @sras

**Comment by tomjaguarpaw** [comment]
Yeah, but that's not to create a function!  It's to create something of type `TableProperties`, which you cannot do without product profunctors.

**Comment by tomjaguarpaw** [comment]
> Btw, over at https://github.com/vacationlabs/haskell-webapps another person working with Opaleye got stuck with profunctors. The basic idea of how to convert Hask->PG and PG->Hask is not well understood based on the tutorials.

OK, feel free to open another issue to discuss that.

**Comment by tomjaguarpaw** [comment]
> Please elaborate. What happens if I don't call makeAdaptorAndInstance on the TenantPoly type?

You won't be able to use `pTenant` and you won't be able to use the `Default` instance for `TenantPoly`.

**Comment by tomjaguarpaw** [comment]
`pTenant` and the `Default` instance for `TenantPoly` are created by `makeAdaptorAndInstance`.

**Comment by saurabhnanda** [comment]
> Yeah, but that's not to create a function! It's to create something of type TableProperties, which you cannot do without product profunctors.

You're right. Now I'm not sure what prompted me to write that function using a profunctor in the first place.

So, can one happily keep using Opaleye without really understanding profunctors?

**Comment by sras** [comment]
@tomjaguarpaw It would be nice to include code that uses runQuery that actually fetches from the db, (raw tuples and user defined records, if that is possible), instead of code that just prints out sql statements.

**Comment by saurabhnanda** [comment]
Continuing this question a little more, is it possible to define a `tenantTable :: Table TenantPGWrite Tenant` in the following code snippet? That is, whenever I read from the `tenants` table, I get a `Tenant` back (with Haskell types) not a a `TenantPGRead` (with PG types)?

```
type TenantPGRead = TenantPoly
  (Column PGInt8) -- key
  (Column PGTimestamptz) -- createdAt
  (Column PGTimestamptz) -- updatedAt
  (Column PGText) -- name
  (Column PGText) -- status
  (Column (Nullable PGInt8)) -- ownerId
  (Column PGText) -- backofficeDomain

type Tenant = TenantPoly
  TenantId -- key
  UTCTime -- createdAt
  UTCTime -- updatedAt
  Text -- name
  TenantStatus -- status
  (Maybe UserId) -- ownerId
  Text -- backofficeDomain

$(makeAdaptorAndInstance "pTenant" ''TenantPoly)
$(makeLensesWith abbreviatedFields ''TenantPoly)


tenantTable :: Table TenantPGWrite TenantPGRead
tenantTable = Table "tenants" (pTenant Tenant{
                                  tenantKey = optional "id"
                                  ,tenantCreatedAt = optional "created_at"
                                  ,tenantUpdatedAt = optional "updated_at"
                                  ,tenantName = required "name"
                                  ,tenantStatus = required "status"
                                  ,tenantOwnerId = required "owner_id"
                                  ,tenantBackofficeDomain = required "backoffice_domain"
                                  })
```

**Comment by tomjaguarpaw** [comment]
> So, can one happily keep using Opaleye without really understanding profunctors?

I hope so!

**Comment by tomjaguarpaw** [comment]
> It would be nice to include code in the tutorial that uses runQuery/ runInsertManyReturing, that actually fetches/write to the db (raw tuples and user defined records, if that is possible), instead of code that just prints out sql statements.

OK, good point.  I filed this: https://github.com/tomjaguarpaw/haskell-opaleye/issues/226

**Comment by tomjaguarpaw** [comment]
> Continuing this question a little more, is it possible to define a tenantTable :: Table TenantPGWrite Tenant in the following code snippet? That is, whenever I read from the tenants table, I get a Tenant back (with Haskell types) not a a TenantPGRead (with PG types)?

No, that doesn't make sense.  The only way you can get Haskell types is by running the query with `runQuery`.

**Comment by saurabhnanda** [comment]
> No, that doesn't make sense. The only way you can get Haskell types is by running the query with runQuery.

Which means I **still** don't understand the basic working of Opaleye. 

Doesn't `runQuery` return a record with PG data types (due to the `Table` definition I was mentioning above)? My question was how to make `runQuery` (or anything that maps to a `SELECT`) to return Haskell types by default?

**Comment by tomjaguarpaw** [comment]
`runQuery` does return Haskell types!

**Comment by tomjaguarpaw** [comment]
Here's the type signature of `runQuery`.

````haskell
runQuery :: Default QueryRunner columns haskells => Connection -> Query columns -> IO [haskells]
````

You can interpret it as follows:

1. Forget the `Default` instance because that comes for free
2. Pass it a `Connection`
3. Then it turns a `Query` containing `columns` (Postgres types) into `[haskells]`, a list of Haskell types.

**Comment by tomjaguarpaw** [comment]
It's the `QueryRunner` `Default` instance that is responsible for turning Postgres values into Haskell values.

**Comment by tomjaguarpaw** [comment]
Oh, I've just noticed the documentation for `runQuery` is badly wrong!

https://www.stackage.org/haddock/lts-5.16/opaleye-0.4.2.0/Opaleye-RunQuery.html#v:runQuery

Perhaps that's what confused you?  It should say

````haskell
runQuery :: Query (Column PGInt4, Column PGText) -> IO [(Int, String)]
````

**Comment by tomjaguarpaw** [comment]
(Corrected that doc bug here: https://github.com/tomjaguarpaw/haskell-opaleye/commit/148638289258eadaf858ad706003aa4f7eecec39)

**Comment by saurabhnanda** [comment]
Basically, I don't understand the following (for which the document is *partly* responsible):

* How exactly does Opaleye know how to convert PG -> Haskell? The `Table` definition only associates `TenantPGRead` and `TenantPGWrite`
* Why cant the same magic be used to get Haskell -> PG? 
* Which opalaye functions do this automatic conversion? Insert? Update? Select?
* how can one tweak these conversion functions for custom behaviour?

**Comment by tomjaguarpaw** [comment]
> How exactly does Opaleye know how to convert PG -> Haskell? The Table definition only associates TenantPGRead and TenantPGWrite 

The `QueryRunner` (which typically comes from the `Default` `QueryRunner` instance)

> Why cant the same magic be used to get Haskell -> PG? 

It is.  It's in `Constant`: https://hackage.haskell.org/package/opaleye-0.5.1.1/docs/Opaleye-Constant.html

> Which opalaye functions do this automatic conversion? Insert? Update? Select?

You can tell by the typeclass constraint they have on them.

* `runQuery` uses `QueryRunner`
* `runInsert` and `runUpdate` don't use any "magic" because they have no typeclass constraint.
* `runInsertManyReturning` uses `QueryRunner` because it has to return Haskell values.

> how can one tweak these conversion functions for custom behaviour?

Could you tell me what sort of custom behaviour you are thinking of?

**Comment by tomjaguarpaw** [comment]
It might help to look at `runQueryExplicit`.  You can see there (explicitly!) that the `QueryRunner` is used in converting `columns` to `haskells`:

````haskell
runQueryExplicit :: QueryRunner columns haskells -> Connection -> Query columns -> IO [haskells]
````

https://www.stackage.org/haddock/lts-7.7/opaleye-0.5.1.1/Opaleye-RunQuery.html

**Comment by saurabhnanda** [comment]
* So, `runQuery` can be used with records instead of tuples?
* Can the queryRunner magic be used for **any** type defined over the polymorphic/parameterised base type? In this case `NewTenant`. Which means, do I really need to define the `newTenantToPg` function manually? (And vice versa, for `Constant`)

**Comment by tomjaguarpaw** [comment]
> So, runQuery can be used with records instead of tuples?

Absolutely!

> Can the queryRunner magic be used for any type defined over the polymorphic/parameterised base type? In this case NewTenant. Which means, do I really need to define the newTenantToPg function manually?

No, only ones with matching types.  `Constant` doesn't know to fill in `Nothing` for the key and `"new"` for the status, for example.

**Comment by tomjaguarpaw** [comment]
> No, only ones with matching types.

(I mean ones that "match" based on the `Default` instances they have.)

**Comment by saurabhnanda** [comment]
@tomjaguarpaw sorry to press this even further. But even now things are not obvious. This code following fails to compile with the following error:

```
   140  26 error           Couldn't match type ‘Column PGInt8’ with ‘TenantId’
     Expected type: Table TenantPGWrite Tenant
       Actual type: Table TenantPGWrite TenantPGRead
     In the first argument of ‘queryTable’, namely ‘tenantTable’
     In the expression: queryTable tenantTable (intero)
```

```
data TenantPoly key createdAt updatedAt name status ownerId backofficeDomain = Tenant {
  tenantKey :: key
  ,tenantCreatedAt :: createdAt
  ,tenantUpdatedAt :: updatedAt
  ,tenantName :: name
  ,tenantStatus :: status
  ,tenantOwnerId :: ownerId
  ,tenantBackofficeDomain :: backofficeDomain
  } deriving Show

type TenantPGWrite = TenantPoly
  (Maybe (Column PGInt8)) -- key
  (Maybe (Column PGTimestamptz)) -- createdAt
  (Maybe (Column PGTimestamptz)) -- updatedAt
  (Column PGText) -- name
  (Column PGText) -- status
  (Column (Nullable PGInt8)) -- ownerId
  (Column PGText) -- backofficeDomain

type TenantPGRead = TenantPoly
  (Column PGInt8) -- key
  (Column PGTimestamptz) -- createdAt
  (Column PGTimestamptz) -- updatedAt
  (Column PGText) -- name
  (Column PGText) -- status
  (Column (Nullable PGInt8)) -- ownerId
  (Column PGText) -- backofficeDomain

type Tenant = TenantPoly
  TenantId -- key
  UTCTime -- createdAt
  UTCTime -- updatedAt
  Text -- name
  TenantStatus -- status
  (Maybe UserId) -- ownerId
  Text -- backofficeDomain

$(makeAdaptorAndInstance "pTenant" ''TenantPoly)
$(makeLensesWith abbreviatedFields ''TenantPoly)


tenantTable :: Table TenantPGWrite TenantPGRead
tenantTable = Table "tenants" (pTenant Tenant{
                                  tenantKey = optional "id"
                                  ,tenantCreatedAt = optional "created_at"
                                  ,tenantUpdatedAt = optional "updated_at"
                                  ,tenantName = required "name"
                                  ,tenantStatus = required "status"
                                  ,tenantOwnerId = required "owner_id"
                                  ,tenantBackofficeDomain = required "backoffice_domain"
                                  })

tenantQuery :: Query Tenant
tenantQuery = queryTable tenantTable
```

What I understand from this error message is that the `Table` definition needs to change for `Query` to be able to work with `Tenant` instaed of `TenantPGRead`. Is that correct?

**Comment by tomjaguarpaw** [comment]
If you write

````haskell
tenantQuery = queryTable tenantTable
````

and let the compiler infer the type it will tell you it is

````haskell
tenantQuery :: Query TenantPGRead
tenantQuery = queryTable tenantTable
````

It's Postgres types, not Haskell types, that come out of `queryTable`.  Can you tell me why you thought that Haskell types come out of `queryTable`?  Fixing that misunderstanding is probably important for helping you understand Opaleye.

**Comment by saurabhnanda** [comment]
> Can you tell me why you thought that Haskell types come out of queryTable? Fixing that misunderstanding is probably important for helping you understand Opaleye.

My original understanding was that the following code snippet decides what goes into, and what comes out of the Opaleye table-interface. In this case, Opaleye will need a `TenantPGWrite` during `INSERT` and `UPDATE` and will give back a `TenantPGRead` after a `SELECT`. Based on the examples given in the tutorials, my understanding was that, both, the read and the write types given to `Table` need to be built out of PG types. Therefore, if I want to use `Tenant` or `NewTenant` types (ie Haskell types), I need PG->Hask and Hask->PG conversion functions (which is the boilerplate I've been trying to get rid of, in the first place!)

```
tenantTable :: Table TenantPGWrite TenantPGRead
tenantTable = Table "tenants" (pTenant Tenant{
                                  tenantKey = optional "id"
                                  ,tenantCreatedAt = optional "created_at"
                                  ,tenantUpdatedAt = optional "updated_at"
                                  ,tenantName = required "name"
                                  ,tenantStatus = required "status"
                                  ,tenantOwnerId = required "owner_id"
                                  ,tenantBackofficeDomain = required "backoffice_domain"
                                  })
```

However, in this thread you mentioned the following, which made me believe that it is possible to get a Haskell type out of `queryTable`

>> How exactly does Opaleye know how to convert PG -> Haskell? The Table definition only associates TenantPGRead and TenantPGWrite

> The QueryRunner (which typically comes from the Default QueryRunner instance)

**Comment by tomjaguarpaw** [comment]
> in this thread you mentioned the following, which made me believe that it is possible to get a Haskell type out of queryTable

It's more than possible!  It's what *always* happens.  `queryTable` always returns a list of Haskell values.

**Comment by saurabhnanda** [comment]
> It's more than possible! It's what always happens. queryTable always returns a list of Haskell values.

We seem to be going round in circles! I just tried that, and failed, in https://github.com/tomjaguarpaw/haskell-opaleye/issues/225#issuecomment-258114308

What do you mean by "Haskell values"? Here are my definitions:

* Any record or tuple built out of `PG*` types, eg. `PGInt8` or `PGTimestamptz` is a PG type.
* Any record of tuple build of `Int`, `Text`, a custom ADT, etc. is a Haskell type.

All the tutorial examples deal with PG types going in, or coming out of, the API surface that Opaleye exposes.

**Comment by tomjaguarpaw** [comment]
>    It's more than possible! It's what always happens. queryTable always returns a list of Haskell values.

> We seem to be going round in circles! I just tried that, and failed, in #225 (comment)

Oh sorry!  I made a thinking error.

`queryTable` *never* returns Haskell values.  Why do you want it to.

It's `runQuery` that *always* returns Haskell values.

**Comment by tomjaguarpaw** [comment]
> What do you mean by "Haskell values"? Here are my definitions:

Those are good definitions.  I agree.

> All the tutorial examples deal with PG types going in, or coming out of, the API surface that Opaleye exposes. 

No, both `runTwentiesQuery` and `runWarehouseQuery` in [`TutorialBasic`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/Doc/Tutorial/TutorialBasic.lhs) deal with Haskell types coming out.

By the way, I admire your dedication to this project!  I'm happy to keep helping you as much as I can and hopefully you efforts in understanding will help me improve the tutorials for future users.

**Comment by tomjaguarpaw** [comment]
> However, in this thread you mentioned the following, which made me believe that it is possible to get a Haskell type out of queryTable

Coming back to this comment, what I mentioned should make you believe it's possible to get a Haskell type out of `runQuery` (not `queryTable`!).

**Comment by saurabhnanda** [comment]
> It's runQuery that always returns Haskell values.

Okay, and the one thing that always confuses me is **how** does Opaleye know which Haskell value to return? Unlike `Table TenantPGWrite TenantPGRead`, I haven't told Opaleye the Haskell value/type associated with a table. How does `runQuery` know which function to use for PG->Hask conversion?

**Comment by tomjaguarpaw** [comment]
> How does runQuery know which function to use for PG->Hask conversion? 

OK, good question.  It's the `Default QueryRunner` instance that specifies the type to return.

The `Default QueryRunner` instances come from `QueryRunnerColumnDefault a b => Default QueryRunner (Column a) b` and the `QueryRunnerColumnDefault` instances specify how the Postgres columns map to Haskell values.

For example `QueryRunnerColumnDefault PGText String` means a `PGText` can map to a Haskell `String`.  `QueryRunnerColumnDefault PGText Text` means a `PGText` can *also* map to a Haskell `Text`.  `QueryRunnerColumnDefault PGInt4 Int` means `PGInt4` maps to a Haskell `Int`.

See here for all those instances: https://www.stackage.org/haddock/nightly-2016-11-02/opaleye-0.5.1.1/Opaleye-Internal-RunQuery.html

**Comment by saurabhnanda** [comment]
I can confirm that the following indeed type-checks:

```
tenantQuery :: Query TenantPGRead
tenantQuery = queryTable tenantTable

tenantById :: TenantId -> Query TenantPGRead
tenantById (TenantId tid) = proc () -> do
  tenant <- tenantQuery -< ()
  restrict -< (tenant ^. key) .== (pgInt8 tid)
  returnA -< tenant

testHarness = do
  conn <- PGS.connect PGS.defaultConnectInfo{
    PGS.connectUser = "servant_opaleye"
    ,PGS.connectPassword = "123"
    ,PGS.connectDatabase = "servant_opaleye"
    }
  runReaderT (myTenantById $ TenantId 1) AppConfig{appConfigDbPool=conn}

myTenantById :: TenantId -> AppM (Tenant)
myTenantById tid = do
  conn <- askDbConnection
  liftIO $ fmap head $ runQuery conn $ tenantById $ tid
```

This brings me to the next question. **What is the purpose of the interim `Query TenantPGRead` value?**

**Comment by tomjaguarpaw** [comment]
> What is the purpose of the interim Query TenantPGRead value?

You have to know the Postgres types of things in your table in order to be able to do Postgres things on them!

**Comment by tomjaguarpaw** [comment]
Frequently one doesn't simply read the whole record out of the database without combining it with other records in the database!

**Comment by saurabhnanda** [comment]
> OK, good question. It's the Default QueryRunner instance that specifies the type to return.

Thanks for clarifying. Was expecting some typeclass magic. However, I haven't actually defined an instance of `Default QueryRunner Tenant`. Where is that coming from?

**Comment by tomjaguarpaw** [comment]
From the `Default` instance generated by `makeAdaptorAndInstance`.

**Comment by saurabhnanda** [comment]
> You have to know the Postgres types of things in your table in order to be able to do Postgres things on them!

> Frequently one doesn't simply read the whole record out of the database without combining it with other records in the database!

This, actually, is a very important thing that has been vexing me since I started my crusade to build webapps with Haskell. 

What should be the type signatures of a domain API built on top of Opaleye? Especially APIs that are fetching stuff out of the DB? Should the domain API return `Query *` objects so that they can be chained and composed by the calling function, or should the domain API do a `runQuery` and return the Haskell/domain objects (and not the PG objects)?

**Comment by tomjaguarpaw** [comment]
> What should be the type signatures of a domain API built on top of Opaleye?

I don't think I can help you answer that one.

**Comment by saurabhnanda** [comment]
> From the Default instance generated by makeAdaptorAndInstance.

Is there any example of defining the `Default` instance manually? Also, how does the following work, given that I'm passing in `TenantPoly` and not a concrete type?

`$(makeAdaptorAndInstance "pTenant" ''TenantPoly)`

**Comment by tomjaguarpaw** [comment]
> Is there any example of defining the Default instance manually? Also, how does the following work, given that I'm passing in TenantPoly and not a concrete type? 

Does this explain enough for you?  Hopefully it should answer both your questions.

https://hackage.haskell.org/package/product-profunctors-0.7.1.0/docs/Data-Profunctor-Product-TH.html

**Comment by saurabhnanda** [comment]
> Does this explain enough for you? Hopefully it should answer both your questions.

> https://hackage.haskell.org/package/product-profunctors-0.7.1.0/docs/Data-Profunctor-Product-TH.html

Not sure I understand everything therein, but here's the intuition I have. The `Default` instance for a polymorphic record is defined as a `Default` instance on each individual field in the record, irrespective of the type of the field. So, if a concrete type is using fields that have `Default` instances, it will work. If any field doesn't have a `Default` instance, the type-checker will complain.

**Comment by tomjaguarpaw** [comment]
Yes, you are exactly right.

**Comment by saurabhnanda** [comment]
Can I continue this a little more? I now have questions for the Hask->PG (writing) side of things.

**Comment by tomjaguarpaw** [comment]
Sure!

**Comment by saurabhnanda** [comment]
In the insert function given below, I now understand the following:

* If the first argument is `Table TenantPGWrite TenantPGRead`, then the second argument `[columnsW]` can be a list of `TenantPGWrite` **records**
* If the third argument `(columnsR -> returned)` is `id`, then the `QueryRunner` magic will kick-in and I will get a `[Tenant]` (Haskell type) back, with the caveat that something should constrain the return type to `[Tenant]` (else the compiler won't know).

My question: Is it possible to define an instance of some other typeclass (is it `Constant`) and pass a `[Tenant]` instead of a `[TenantPGWrite]` in the second argument?

```
runInsertManyReturning ::
  product-profunctors-0.7.1.0:Data.Profunctor.Product.Default.Class.Default
    QueryRunner returned haskells =>
  Connection
  -> Table columnsW columnsR
  -> [columnsW]
  -> (columnsR -> returned)
  -> IO [haskells]
```

**Comment by tomjaguarpaw** [comment]
Yes, you can use `Opaleye.Constant.constant` to convert some Haskell write type `haskellW` to `columnsW`, picking up a `Default Constant haskellW columnsW` constraint.  Then you would have

````haskell
runInsertManyReturningConstant ::
  (Default QueryRunner returned haskells,
    Default Constant haskellW columnsR) =>
  Connection
  -> Table columnsW columnsR
  -> [haskellW]
  -> (columnsR -> returned)
  -> IO [haskells]
````

I think it would be

````haskell
runInsertManyReturningConstant conn table recs returning =
    runInsertManyReturning conn table (constant recs) returning
````

but I haven't checked this.

**Comment by saurabhnanda** [comment]
Any reason for not having the "write" APIs behave similar to the "read" APIs? i.e. if the read APIs can automagically convert PG -> Haskell types, why don't the write APIs also automagically convert Haskell -> PG types?

**Comment by tomjaguarpaw** [comment]
The difference between writing and reading is that writes *can* be done from PG types (because we can create constant PG types from Haskell) but reading *can't* be done to PG types (because there's no way to safely unwrap a PG type).

It's reasonable to make the case that inserts and updates should be done starting from Haskell types.  That would be more consistent and probably less confusing.  I would certainly be happy if you used `runInsertManyReturningConstant` as defined above and shared your experiences.

**Comment by tomjaguarpaw** [comment]
I just want to say thanks again for all the probing questions.  They're really helping me understand how best to design the library.

**Comment by saurabhnanda** [comment]
> I just want to say thanks again for all the probing questions. They're really helping me understand how best to design the library.

In that case, here's some more :)

What's the rationale for the following names: `Default` and `Constant`? If I need to define a function to map my Haskell-type to a PG-type, why do I need to define an instance of type-class `Default`? What's the "default" here? And why is the conversion function called `constant`? Because it's not really returning a constant value - the output of the function depends on the input!

Why not simply have a typeclass called `toPG` or `toSQL` or `toRow` or `toColumns` which is absolutely self-explanatory?

**Comment by tomjaguarpaw** [comment]
It's called `Default` because `Default p a b` gives you a "blessed" "default" value of type `p a b`, i.e. the unique one that is considered sensible.  So in this case there is a unique way of converting an `Int` to a `PGInt4` that is considered sensible.

Regarding `Constant`, it's so called because the name was inherited from [HaskellDB](https://hackage.haskell.org/package/haskelldb-2.2.4/docs/Database-HaskellDB-Query.html#v:constant).  The value created by `constant` is "constant" with respect to the database, i.e. it doesn't depend on running any queries.  On the other hand, your naming suggestions do seem better and perhaps I should do away with this historical abberation.

I've opened an issue about this: https://github.com/tomjaguarpaw/haskell-opaleye/issues/229

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.

**Comment by noxecane** [comment]
It's been great reading this thread(if I can call it one). Big thumbs up to @tomjaguarpaw for having a listening ear and patience and @saurabhnanda for continuously pushing to help me understand this better.

**Comment by tomjaguarpaw** [comment]
Hi @noxecane, I'm glad you got some value out of it!  If I can help with anything further then feel free to comment or open a new issue.
