### ISSUE TITLE
Provide a binary operator for `IS DISTINCT FROM`

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#23]
I would imagine:

``` haskell
isDistinctFrom :: Column (Nullable a) -> Column (Nullable a) -> Column PGBool
```

with the same semantics as http://www.postgresql.org/docs/current/static/functions-comparison.html

**Comment by tomjaguarpaw** [comment]
I'm actually inclined to use `IS DISTINCT FROM` in the definition of `.==` and have a differently-named function of the type `Column (Nullable a) -> Column (Nullable a) -> Column (Nullable PGBool)`.  Thoughts?

**Comment by bergmark** [comment]
Pros:
* More like haskell equality
* Better semantics in theory

Cons:
* Not like sql equality (makes porting queries more error prone)
* Semantically breaking change, may introduce bugs

If you want to do this change it should be a major bump to opaleye, possibly with a deprecation cycle or rename of the operator.

**Comment by tomjaguarpaw** [comment]
@bergmark Fair point.  I will leave it as it is.

@ocharles I'm happy to accept a patch for this.  It will need to be implemented like `Opaleye.Operators.like`.

**Comment by ocharles** [comment]
> I'm actually inclined to use IS DISTINCT FROM in the definition of .== and have a differently-named function of the type Column (Nullable a) -> Column (Nullable a) -> Column (Nullable PGBool). Thoughts?

`IS DISTINCT FROM` will never hit an index in PostgreSQL, just wanted to provide one more point in favour of keeping `==.` to actually mean `=`

**Comment by tomjaguarpaw** [comment]
I'm closing this issue since it has not been active for a long time and is not a bug.  Feel free to reopen if necessary.

**Comment by ocharles** [comment]
Yep, I'll re-open with a PR if we need it in the future.
