### ISSUE TITLE
Right way to define tables with foreign keys?

### ISSUE THREAD

**Issue by jsermeno** [tomjaguarpaw/haskell-opaleye#231]
What's the recommended way to model foreign key relationships in Opaleye? Many times you'll want to create your record before you know what the foreign key is, but if you wrap the type in `Maybe` then you're forced specify the foreign key with `optional`. For example:

```
data Child' a b c = Child 
  { primary_key :: a
  , foreign_key :: b
  , value :: c
  }
type Child = Child' (Maybe Int) (Maybe Int) Int
type ChildColumnWrite = Child' 
  (Maybe (Column PGInt4)) 
  (Maybe (Column PGInt4)) 
  (Column PGInt4)
type ChildColumnRead = Child'
  (Column PGInt4)
  (Column PGInt4)
  (Column PGInt4)
$(makeAdaptorAndInstance "pChild" ''Child')
childTable :: Table ChildColumnWrite ChildColumnRead
childTable = Table
  "child"
  (pChild Child
    { primary_key = optional "id"
    , foreign_key = optional "fk_id"
    , value = required "value"
    })
```

Is the best way to use nested types?

```
data ChildK' a = ChildK
  { primary_key :: a
  , foreign_key :: b
  , child_val :: c
  }
data Child' a b c = Child 
  { value :: c
  }
type Child = Child' Int
type ChildK = ChildK' (Maybe Int) Int Child
type ChildColumnWrite = ChildK' 
  (Maybe (Column PGInt4)) 
  (Column PGInt4) 
  (Child' (Column PGInt4))
type ChildColumnRead = ChildK'
  (Column PGInt4)
  (Column PGInt4)
  (Child' (Column PGInt4))
$(makeAdaptorAndInstance "pChildK" ''ChildK')
$(makeAdaptorAndInstance "pChild" ''Child')
childTable :: Table ChildColumnWrite ChildColumnRead
childTable = Table
  "child"
  (pChildK ChildK
    { primary_key = optional "id"
    , foreign_key = required "fk_id"
    , child_val = (pChild Child { val = required "value" })
    })
```

The second way seems like it would work, though it's verbose. Thoughts?

I'm assuming that if you have a `Child` then you'd perform a `runInsertManyReturning` on the parent to retrieve the `id`. Then you'd create a `ChildK` using the retrieved id as `foreign_key` with your original `Child`.

I ask this question because I couldn't find much documentation or many issues regarding foreign keys, and want to make sure I'm doing things in the best way. I just found this [stackoverflow question](http://stackoverflow.com/questions/9234205/safe-modelling-of-relational-data-in-haskell), which looks to require having the `foreign_key` before creating the `Child`.

**Comment by tomjaguarpaw** [comment]
> Many times you'll want to create your record before you know what the foreign key is

What do you mean?  Do you mean you want to insert the record before knowing what the foreign key is?  In that case it should be nullable.

> Is the best way to use nested types?

The second way would work fine, but you can define `Child` with only one type parameter

````haskell
data Child' a = Child 
  { value :: a
  }
````

**Comment by jsermeno** [comment]
> The second way would work fine, but you can define Child with only one type parameter

Thanks, I removed the extra type parameters in the example above.

> What do you mean? Do you mean you want to insert the record before knowing what the foreign key is? In that case it should be nullable.

I meant before the insert. During the insert, all my foreign keys have a `NOT NULL` constraint. For example, I'm parsing a file. Each file contains data for many records, and many tables. While I'm still parsing, I haven't begun inserting, yet I want to have record types to hold and structure the data. Ideally, I'd be able to use these record types for inserting into the database, or easily construct them into types that I can insert into the database. I'm not sure, but I think what I was looking for is similar to the `Entity` type mentioned in https://github.com/tomjaguarpaw/haskell-opaleye/issues/213, except as a method to be able to work with your data before you know what the foreign key is, instead of your primary key. If nested records are the best way to handle this, then I think I'm all set.

**Comment by tomjaguarpaw** [comment]
I don't think nested record types are needed for this.  This is one of the advantages of keeping the record polymorphic.  If you don't know a value yet, just fill it in with `()`.

**Comment by jsermeno** [comment]
Thanks! I didn't realize how easy it was to perform conversions between polymorphic records.

**Comment by tomjaguarpaw** [comment]
Closing this.  Feel free to reopen or file a new issue if you need more help.
