### ISSUE TITLE
Join lets you compare fields that represent different Haskell types.

### ISSUE THREAD

**Issue by sras** [tomjaguarpaw/haskell-opaleye#242]
This code compiles file, eventhough I am comparing a type of ProductId with TenantId,

```
getProductsWithTenants :: IO [(Product, Tenant)]
getProductsWithTenants = do
  conn <- connect defaultConnectInfo { connectDatabase = "scratch"}
  runQuery conn $ proc () ->
    do
      product@ Product { product_id = p_id, product_tenant_id = p_tid} <- queryTable productTable -< ()
      tenant@ Tenant {tenant_id = t_id } <- queryTable tenantTable -< ()
      restrict -< (p_id .== t_id)  
      returnA -< (product, tenant)
```

I know that this happens because both the values are `Column PGInt4` at this point. But is there no way to enforce this?

**Comment by saurabhnanda** [comment]
I'd like to give additional context by way of [this Reddit thread](https://www.reddit.com/r/haskell/comments/4vtpj9/do_persistent_and_opaleye_provide_any_benefits/) on which you commented:

> Why do we want to write SQL in Haskell? Haskell provides us with all sorts of benefits over other languages which I summarise with the slogan "typesafety and composability". What does this slogan imply? It means that we have a very convenient ecosystem built around polymorphism, higher order constructs and precise data modelling which leads to easy sharing of code, easy refactoring, building interfaces that are hard or impossible to use incorrectly. Haskell is far better on these dimensions than languages like Java and Python. Java and Python on their part are far better on these dimensions than SQL. SQL is simply a bad, bad, language. We want to program SQL with all the benefits of Haskell. Programming SQL in SQL gets us all the benefits of SQL, which is to say none[1].

At that time when I was reading that reply, my *assumption* was that while raw SQL will allow `tenants.id` to be compared with `products.id`, writing something similar in the Opalaye DSL  will result in a compile-time error.

This design goal explicitly stated by [ephrion in this comment](https://www.reddit.com/r/haskell/comments/4vtpj9/do_persistent_and_opaleye_provide_any_benefits/d61bfbk/) I know it's someone else and not you - but what else is meant by "typesafety" in this context? Also, the fact that Persistent already does this. Hence this expectation from Opaleye as well.

**Comment by tomjaguarpaw** [comment]
> I know that this happens because both the values are Column PGInt4 at this point. But is there no way to enforce this?

To enforce it you have to make them different types!

**Comment by tomjaguarpaw** [comment]
I'd recommend using

````haskell
data TenantId' a = TenantId { tenantId :: a }

type TenantId = TenantId' Int
type TenantIdColumn = TenantId' (Column PGInt4)

$(makeAdaptorAndInstance "pTenantId" ''TenantId')
````

You can then use `.===` (a generalised version of `.==`) to compare tenant IDs.

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.
