### ISSUE TITLE
How can I make a value of type Column PGNumeric

### ISSUE THREAD

**Issue by sras** [tomjaguarpaw/haskell-opaleye#243]
It seems that there are function to make pgType values from Haskell values [here](https://hackage.haskell.org/package/opaleye-0.5.2.2/docs/Opaleye-PGTypes.html).  But it seems that no such function exist for PGNumeric, ie there is no function that can take a value like Ratio or Scientific and return a (Column PGNumeric) value. Why is this and how can I implement a Default instance for storing a value of type Scientific in a postgresql column of type numeric.

**Comment by tomjaguarpaw** [comment]
Duplicate of: https://github.com/tomjaguarpaw/haskell-opaleye/issues/230

**Comment by tomjaguarpaw** [comment]
The only reason it doesn't exist is that nobody bothered implementing it yet.  Please try and if you have any difficulty let me know.
