### ISSUE TITLE
Column with phantom type

### ISSUE THREAD

**Issue by lippling** [tomjaguarpaw/haskell-opaleye#248]
I'm trying to model the following:

For every table `t` we have an additional table `t_history` and a view `t_with_history` (union of both).

```haskell
table :: Table EntityColumnsW EntityColumnsR
table = table' tableName

tableWithHistory :: Table EntityColumnsW EntityColumnsR
tableWithHistory = table' $ tableName ++ "_with_history"

table' :: TableName -> Table EntityColumnsW EntityColumnsR
table' name =
    mkTable name $ pEntity Entity
        { contentId = Content.pId (Content.Id $ required contentIdName)
        , questionTypeId = QuestionType.pId (QuestionType.Id $ required questionTypeIdName)
        , visibility = required forTestsOnlyName
        , period = pPeriod $ (Period $ optionalReadonly "sys_period")
        }

tableName :: TableName
tableName = "questions"
```

I thought about adding a phantom type to every column and entity to encode where it is coming from.

E.g.:
```haskell
data Current
data CurrentWithHistory
...
...
newtype Id'' src a = Id { unId :: a } deriving (Eq, Show)
type Id' = Id'' Current
type IdH' = Id'' Current
```

But when I try to use `makeAdaptorAndInstance` it gives me the error `That doesn't look like a data or newtype declaration to me`, because it doesn't work with type aliases.

Any idea how this could be solved in a type-safe manner?

**Comment by tomjaguarpaw** [comment]
Can't you use `makeAdaptorAndInstance` on `Id''`?

**Comment by lippling** [comment]
```haskell
$(makeAdaptorAndInstance "pId" ''Id'')
```
results in
```haskell
Expecting one more argument to ‘Id''’
    The first argument of ‘Newtype’ should have kind ‘* -> *’,
      but ‘Id''’ has kind ‘* -> * -> *’
    In the instance declaration for ‘Newtype Id''’
```

**Comment by tomjaguarpaw** [comment]
Yeah, the TH is not particularly sophisticated.  It could be fixed, but it's probably easier just to write your own adaptors and instances along the lines in the docs here: https://hackage.haskell.org/package/product-profunctors-0.7.1.0/docs/Data-Profunctor-Product-TH.html

**Comment by lippling** [comment]
I tried to fix it directly in Data.Profunctor.Product.TH but I failed. But I didn't try it with `Id''` so maybe it's possible to fix the Newtype instance generation, I don't know.

I could write my own instances, but that would require much boilerplate (I have many types: nearly 100 Entities * Columns).

**Comment by tomjaguarpaw** [comment]
It is possible to fix `newtype` instance generation so it works with your cases, but the TH is very hairy.

Perhaps you can use

    data Current a = Current a
    data CurrentWithHistory = CurrentWithHistory a

run `makeAdaptorAndInstance` on both of those, and then use

    type Id' a = Current (Id'' a)
    type IdH' a = CurrentWithHistory (Id'' a)

**Comment by tomjaguarpaw** [comment]
I would say this is a more principled approach than a phantom type anyway.

**Comment by lippling** [comment]
Mmh, I tried it, but it caused several problems. So I'm forced to do it in a non-type-safe way.

Thanks anyway.
