### ISSUE TITLE
Call to runInsertReturning causes an exception with 'unknown' value for errSQLType

### ISSUE THREAD

**Issue by sras** [tomjaguarpaw/haskell-opaleye#250]
This code compiles fine by produces the following exception at runtime..

```
*** Exception: Incompatible {errSQLType = "unknown", errSQLTableOid = Nothing, errSQLField = "?column?", errHaskellType = "Text", errMessage = "types incompatible"}
```

Code

```
insertRowReturning :: Connection -> User -> IO [User]
insertRowReturning conn u = do
  runInsertReturning conn userTable (constant u) cb
  where
    cb :: UserPR -> UserPR
    cb User {id = id'} = (constant u::UserPW) {id = id'}
```

This results in the following query being sent to the postgres

```
INSERT INTO "users" ("id",
                             "name",
                             "email")
        VALUES (DEFAULT,
                E'Max',
                E'max@mail.com')
        RETURNING "id",
                  E'Max',
                  E'max@mail.com’
```

What I was trying, was to make Opaleye return just the id of the new row, instead of the whole row. 
The error seems to be cause by the constants present in the RETURNING clause, and failure to infer correct field types for them. I am not sure though....

**Comment by tomjaguarpaw** [comment]
That's interesting.  Is it valid SQL?  If not I wonder why not.

**Comment by tomjaguarpaw** [comment]
It does seem to be valid SQL.  Can you please use `psql` or whatever favourite way you have of connecting to your database and run that SQL fragment directly?  The postgresql-simple error message is hard to understand and it would be better to see a clearer one.

**Comment by tomjaguarpaw** [comment]
It would also be helpful to see your definitions for `User`, `UserPW` and `UserPR`.

**Comment by tomjaguarpaw** [comment]
By the way, If you really just want the id, why not

````haskell
insertRowReturning :: Connection -> User -> IO [Int]
insertRowReturning conn u = do
  runInsertReturning conn userTable (constant u) id
````

(although `id` is a *really* bad name for an id column, because it clashes with Haskell's built in `id` identity function).

**Comment by sras** [comment]
@tomjaguarpaw here they are

```
data UserPoly id name email = User { id :: id, name :: name, email :: email }
type UserPW = UserPoly (Maybe (Column PGInt4)) (Column PGText) (Column PGText)
type UserPR = UserPoly (Column PGInt4) (Column PGText) (Column PGText)
```

The sql fragment when run directly does not result in an error, and the row gets inserted correctly returning the expected result.. 

```
benchmark=# INSERT INTO "users" ("id",
                             "name",
                             "email")
        VALUES (DEFAULT,
                E'Max',
                E'max@mail.com')
        RETURNING "id",
                  E'Max',
                  E'max@mail.benchmarkcoma'
benchmark-# ;
  id   | ?column? |        ?column?
-------+----------+------------------------
 16008 | Max      | max@mail.benchmarkcoma
(1 row)

```

I think the problem is with the two string literals in the "returning" clause. We already know that the FromField instance of the String checks the field type to see if the field is of type varchar or char. In this case the column type is unknown, (because of the string literals) and it errors out. If you can add type annotation to the generated query so that it becomes..

```
benchmark=# INSERT INTO "users" ("id",
                             "name",
                             "email")
        VALUES (DEFAULT,
                E'Max',
                E'max@mail.com')
        RETURNING "id",
                  E'Max'::varchar,
                  E'max@mail.benchmarkcoma'::varchar;

```

It might work.

**Comment by sras** [comment]
@tomjaguarpaw 

```
insertRowReturning :: Connection -> User -> IO [Int]
insertRowReturning conn u = do
  runInsertReturning conn userTable (constant u) id
```

This results in "No instance for (Default QueryRunner UserPR Int)" error.

**Comment by tomjaguarpaw** [comment]
That's a problem with the clashing `id` identifiers.  Can you maybe change things to

````haskell
data UserPoly id name email = User { id_ :: id, name :: name, email :: email }

insertRowReturning :: Connection -> User -> IO [Int]
insertRowReturning conn u = do
  runInsertReturning conn userTable (constant u) id_
````

**Comment by saurabhnanda** [comment]
@sras my suggestion -- in Haskell-land don't call it `id` in the first place. Just rename to `key`.

**Comment by sras** [comment]
@tomjaguarpaw Yes. That was the problem. It works now. 

@saurabhnanda Yes. will use key for id fields now on. The exception is also gone now. Probably because the problematic FromField instances are never invoked...

**Comment by tomjaguarpaw** [comment]
> The exception is also gone now. Probably because the problematic FromField instances are never invoked...

Yes, but thanks for the bug report nonetheless.

**Comment by tomjaguarpaw** [comment]
In fact, it would be helpful if you can revert to your old version and see if `unsafeCast` fixes the exception:

https://hackage.haskell.org/package/opaleye-0.5.2.2/docs/Opaleye-Column.html#g:3

**Comment by sras** [comment]
@tomjaguarpaw 

I was able to add the casts in the values section, which unsurprisingly does not fix the exception.

INSERT INTO "users" ("id",
                             "name",
                             "email")
        VALUES (DEFAULT,
                CAST(E'Max' AS varchar),
                CAST(E'max@mail.com' AS varchar))
        RETURNING "id",
                  E'Max',
                  E'max@mail.com' 

I am not sure how to do it for the literals in the returning clause....

**Comment by tomjaguarpaw** [comment]
As an aside, how did you get `constant u::UserPW` to work?  Have you got an extra instance for mapping the `Maybe`s?

**Comment by tomjaguarpaw** [comment]
I guess I'd need to see your `type User` definition to understand that.

**Comment by tomjaguarpaw** [comment]
````haskell
insertRowReturning :: Connection -> User -> IO [User]
insertRowReturning conn u = do
  runInsertReturning conn userTable (constant u) cb
  where
    cb :: UserPR -> UserPR
    cb User {id_ = id'} = cu { id_   = id'
                             , name  = unsafeCast "varchar" (name cu)
                             , email = unsafeCast "varchar" (email cu)
                             }

      where cu = constant u::UserPW
````

Can you try this?

**Comment by tomjaguarpaw** [comment]
You could even try

````haskell
insertRowReturning :: Connection -> User -> IO [User]
insertRowReturning conn u = do
  runInsertReturning conn userTable (constant u) cb
  where
    cb :: UserPR -> UserPR
    cb User {id_ = id'} = User { id_   = id'
                               , name  = "Max"
                               , email = "max@mail.com"
                               }
````

**Comment by sras** [comment]
@tomjaguarpaw

The first one using unsafeCast works and generates the required sql. 

```
INSERT INTO "users" ("id",
                             "name",
                             "email")
        VALUES (DEFAULT,
                E'Max',
                E'max@mail.com')
        RETURNING "id",
                  CAST(E'Max' AS varchar),
                  CAST(E'max@mail.com' AS varchar) 
```

But the last one errors out with message

    No instance for (Data.String.IsString (Column PGText))
      arising from the literal ‘"Max"’

**Comment by tomjaguarpaw** [comment]
Thanks, that's great to know.

The second one should work if you use `name  = constant "Max"` or turn on `OverloadedStrings`, but it's not so necessary to test that anymore now we have a working version.

I'm actually really surprised that postgresql-simple can't decode literal varchar without a type cast.

**Comment by tomjaguarpaw** [comment]
Since the immediate issue seems to have been solved I'm migrating this here:

https://github.com/lpsmith/postgresql-simple/issues/199#issuecomment-265153393

@sras @saurabhnanda Feel free to reopen this ticket if you need.
