### ISSUE TITLE
Some Default instances for lists and maybes

### ISSUE THREAD

**Issue by duairc** [tomjaguarpaw/haskell-opaleye#254]
Hi, this is sort of related to my pull request tomjaguarpaw/product-profunctors#23. I would submit this a pull request myself, except I'm not sure what module it would be best to put these instances in. Would you have any interest in upstreaming these orphan instances I have in my code?

    instance (Profunctor p, Default p (Column (Nullable a)) (Maybe b)) =>
        Default p (Maybe (Column a)) (Maybe b)
      where
        def = lmap (maybe null toNullable) def

    instance (Profunctor p, Default p (Column (PGArray a)) [b], IsSqlType a) =>
        Default p [Column a] [b]
      where
        def = lmap (pgArray id) def

**Comment by tomjaguarpaw** [comment]
Thanks.  It'll be a while before I can look at these due to the holiday season, etc.. Feel free to ping me if you think I'm leaving this for too long.

**Comment by duairc** [comment]
Pretty sure I don't need this anymore. Sorry for the noise!
