### ISSUE TITLE
Constant instance for haskell to (Maybe (Column sql)) ?

### ISSUE THREAD

**Issue by balajirrao** [tomjaguarpaw/haskell-opaleye#256]
Does this make sense ?

```
instance Default Constant haskell (Column sql) => Default Constant haskell (Maybe (Column sql)) where
  def = Constant (Just . constant)
```

**Comment by tomjaguarpaw** [comment]
Yes, it makes sense.  I guess this is for inserts or updates with columns that can be omitted?

**Comment by balajirrao** [comment]
Yes. Does it make sense to be included in opaleye ? I can send a PR.

**Comment by tomjaguarpaw** [comment]
I think that behaviour would be too implicit for my liking.  This branch probably solves most of the problems you are trying to fix with this instance:

https://github.com/tomjaguarpaw/haskell-opaleye/commit/bf625fb0b3d4093f76078d14f170ac1236b85f99

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.
