### ISSUE TITLE
Supporting date_trunc?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#257]
What's the easiest way to convert the following SQL into Opaleye? I'm assuming that `date_trunct` is not supported right now. What's the easiest way to extend Opaleye to support `date_trunc`, specifically, and other such operators, in general?

```
select date_trunc('week', created_at), count(id)
from itinerary_bookings ib
where ib.state='confirmed'
group by 1
order by 1;
```

**Comment by tomjaguarpaw** [comment]
Use the same method by which any Postgres function is exposed to Opaleye, for example:

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Operators.hs#L295

**Comment by saurabhnanda** [comment]
@tomjaguarpaw what's the first few files that one needs to change, after which the compiler is going to pretty-much guide us?

**Comment by tomjaguarpaw** [comment]
You only need to add one definition!

Hint, it's this:

````haskell
dateTrunc :: Column something -> Column somethingelse -> Column something3
dateTrunc (Column a) (Column b) = Column (HPQ.FunExpr "date_trunc" [a, b])
````

You'll have to judiciously choose the types of your columns though.

**Comment by tomjaguarpaw** [comment]
The types are `PGText`, `PGTimestamp` and `PGTimestamp` according to

https://www.postgresql.org/docs/9.1/static/functions-datetime.html

**Comment by tomjaguarpaw** [comment]
So the full solution should be

````haskell
dateTrunc :: Column PGText -> Column PGTimestamp -> Column PGTimestamp
dateTrunc (Column a) (Column b) = Column (HPQ.FunExpr "date_trunc" [a, b])
````

Not scary, is it?

**Comment by saurabhnanda** [comment]
@tomjaguarpaw is it advisable to go with `PGText` or should one be using an ADT like: 

`data DatePrecision = MicroSec | MilliSec | Second | Minute | Hour | Day | Week | Month | Quarter | Year | Decade | Century | Millenium`

**Comment by tomjaguarpaw** [comment]
The ADT would be very cool!

**Comment by tomjaguarpaw** [comment]
... although that would mean you can't choose the truncation period based on other parts of the query.

**Comment by tomjaguarpaw** [comment]
So, for example, you couldn't look up the truncation period in a table.

**Comment by saurabhnanda** [comment]
[This comment](https://github.com/tomjaguarpaw/haskell-opaleye/issues/257#issuecomment-269192988) makes it seem like we don't really need to *extend* Opaleye. We can simply write this in our app and use it, right?

**Comment by saurabhnanda** [comment]
> So, for example, you couldn't look up the truncation period in a table. So, for example, you couldn't look up the truncation period in a table.

Have two versions?

```
dateTrunc :: Column PGDatePrecision -> Column PGTimestamp -> Column PGTimestamp
dateTruncUnsafe :: Column PGText -> Column PGTimestamp -> Column PGTimestamp
```

**Comment by tomjaguarpaw** [comment]
> This comment makes it seem like we don't really need to extend Opaleye. We can simply write this in our app and use it, right?

Sure, but please submit it anyway so that others can use it!

**Comment by tomjaguarpaw** [comment]
If you like.  However, it would be

    dateTrunc :: DatePrecision -> Column PGTimestamp -> Column PGTimestamp

With and ADT you wouldn't use a `Column`.

**Comment by tomjaguarpaw** [comment]
I'd advise to go with the original `PGText` version in your code and see how it goes.  Then contribute it back.

**Comment by saurabhnanda** [comment]
Okay - so this is the basic template to use for any simple PG function that we need? What about complicated functions that return sets OR consume sets? eg. https://www.postgresql.org/docs/9.1/static/functions-srf.html

**Comment by saurabhnanda** [comment]
The original dashboard requires us to LEFT JOIN two queries:

1. One which generates the week series (one week in each row)
2. And the other one, which uses `GROUP BY` to aggregate the actual data

This ensures that even in weeks where no transaction was present, the week will show up in the result-set with a `NULL` against it (which we will convert to `0` using `COALESCE`)

**Comment by tomjaguarpaw** [comment]
> What about complicated functions that return sets OR consume sets

I don't have time to look at that now, but ...

Returning sets should be fairly straightforward.  You can see this ticket for details:  https://github.com/tomjaguarpaw/haskell-opaleye/issues/181  We haven't got that working quite flawlessly though.

I've never looked at consuming sets.

**Comment by saurabhnanda** [comment]
Thanks for the help. Let us start with basic functions first and come to complicated functions later.

**Comment by tomjaguarpaw** [comment]
Seems like you got what you wanted with this.

1. If you have something working please contribute it back.
2. Please reopen if you need any more help.
