### ISSUE TITLE
Best practices for complicated Opaleye queries

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#259]
I'm writing a complicated dashboard in Opaleye and have a "building block" query which has the following type-sig:

`clientAndBillingPlan :: Query (Column PGText, Column PGText, Column PGText, Column PGTimestamptz, Column PGTimestamptz)`

There are 3 text columns and 2 timestamp columns. What represents what? It's very easy to lose track when we return only tuples from queries. Is there any way to associated label/names with each column in a query?

**Comment by saurabhnanda** [comment]
In SQL every column has a name, even intermediate result sets. That information seems to be getting lost in Opaleye.

**Comment by tomjaguarpaw** [comment]
> There are 3 text columns and 2 timestamp columns. What represents what? It's very easy to lose track when we return only tuples from queries. Is there any way to associated label/names with each column in a query?

Yeah, use a record type!

**Comment by tomjaguarpaw** [comment]
````haskell
data ClientAndBillingPlan =
    ClientAndBillingPlan { clientName    :: Column PGText
                         , clientAddress :: Column PGText
                         , planName      :: Column PGText
                         , planStart     :: Column PGTimestamptz
                         , planEnd       :: Column PGTimestamptz
                         }

````

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.
