### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#260]
I got the following error. What is the best way to debug this?

```
*** Exception: SqlError {sqlState = "42703", sqlExecStatus = FatalError, sqlErrorMsg = "column \"name\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
```

Copy-pasting the generated SQL in `psql` command-line generates a more helpful error message, pointing out the exact line + character, along with the column alias.

**Comment by saurabhnanda** [comment]
And another one:

```
*** Exception: Incompatible {errSQLType = "timestamp", errSQLTableOid = Just (Oid 78669), errSQLField = "result4_3", errHaskellType = "UTCTime", errMessage = ""}
```

**Comment by saurabhnanda** [comment]
And yet another one:

```
*** Exception: UnexpectedNull {errSQLType = "varchar", errSQLTableOid = Just (Oid 78725), errSQLField = "result2_3", errHaskellType = "Text", errMessage = ""}
```

**Comment by tomjaguarpaw** [comment]
The error messages are generated by postgresql-simple, so you'll have to complain [over there](https://github.com/lpsmith/postgresql-simple/issues).

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.
