### ISSUE TITLE
Easier left joins and aggregates?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#261]
I have two tables `clients` and `trips` and need to left join them and get the number of trips for each client. The left join is necessary because some client may not have any trips at all. Here's what I have till now, and I'm close to giving up!

```
clientAndTrips :: LocalTime -> LocalTime -> Query (Column PGInt8, Column (Nullable PGInt8))
clientAndTrips st en = proc () -> do
  (client, nTrip) <- ljoinQuery -< ()
  returnA -< (client ^. key, nTrip ^. key)
  where
    ljoinQuery :: Query (ClientPGRead, TripPoly (Column (Nullable PGInt8)) (Column (Nullable PGTimestamp)) (Column (Nullable PGTimestamp)) (Column (Nullable PGInt8)) (Column (Nullable PGText)) (Column (Nullable PGText)))
    ljoinQuery = leftJoin (queryTable clientTable) (queryTable tripTable) (\ (client, trip) -> (client ^. key) .== (trip ^. clientId))
  ```

Firstly I was irritated that after all the boilerplate related to `TripPGRead`, `TripPGWrite` and `tripTable`, I had to define **yet another** type for "nullable trip" to enable a left join. And that's not all. To do a simple `sum(trips.id)` over this left-join query, the [tutorial tells me that I need to create yet another "aggregate" type?!](https://github.com/tomjaguarpaw/haskell-opaleye/blob/7e97198a270cd3e32de40bf7516bc6e96388661f/Doc/Tutorial/TutorialBasic.lhs#L595-L607)

I shudder at the thought of ever changing the schema of my tables!

**Comment by tomjaguarpaw** [comment]
Have you tried `FunctionalJoin`?  It should make left joins a bit easier.

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/FunctionalJoin.hs

**Comment by tomjaguarpaw** [comment]
I'm afraid I don't have the time right now to work on anything else or give suggestions for anything other than the most basic stuff, sorry.

**Comment by saurabhnanda** [comment]
Are functional joins covered in any tutorial?

**Comment by tomjaguarpaw** [comment]
Not yet.

**Comment by saurabhnanda** [comment]
Any code snippet showing usage of functional joins?

**Comment by tomjaguarpaw** [comment]
I hope the docs themselves give you enough info to work out what's going on:

https://www.stackage.org/haddock/nightly-2016-11-09/opaleye-0.5.2.1/Opaleye-FunctionalJoin.html

**Comment by tomjaguarpaw** [comment]
Does this help?

````haskell
leftJoinReselt = leftJoinF whenMatch whenNoMatch condition queryL queryR
````

**Comment by tomjaguarpaw** [comment]
> the tutorial tells me that I need to create yet another "aggregate" type?!

No it doesn't.  There's no need to create another type.  You can aggregate over a tuple with no problems.

**Comment by tomjaguarpaw** [comment]
> > the tutorial tells me that I need to create yet another "aggregate" type?!

> No it doesn't. There's no need to create another type. You can aggregate over a tuple with no problems.

Probably best to use `fromNullable` to get rid of the `Nullable` and then aggregate using

````haskell
foo :: Query (Column PGInt8, Column PGInt8)
foo = ...

aggregateFoo :: Query (Column PGInt8, Column PGInt8)
aggregateFoo = aggregate (p2 (groupBy, Opaleye.sum))
````

This groups by the first component of the tuple and sums the second component (NB there is a function called `sum` in `Prelude` so you need to qualify Opaleye's `sum` or hide the `Prelude` one).

**Comment by saurabhnanda** [comment]
So, the new profunctor is required only if I want a record. However, if I
keep using tuples, I will quickly lose track of which tuple-value
represents which column. If I use records, I need more boilerplate.

Is there no way to make all of this easier to use once I set up the table
mapping? Using either TH or generics or anything else?

**Comment by saurabhnanda** [comment]
```
aggregateFoo :: Query (Column PGInt8, Column PGInt8)
aggregateFoo = aggregate (p2 (groupBy, Opaleye.sum))
```

Why does one need to define a separate `aggregate` query? Why is it not possible to do something similar to:

```
restrict -< tableA ^. col .== (constant value)
groupBy -< tableA ^. col2
returnA -< (tableA ^. col2, count $ tableA ^. key)
```

**Comment by tomjaguarpaw** [comment]
> Why does one need to define a separate aggregate query? Why is it not possible to do something similar to ...

Because then you could write

> returnA -< (tableA ^. col2, avg $ sum $ count $ tableA ^. key)

which would be nonsense.  Type safety!

**Comment by tomjaguarpaw** [comment]
> the new profunctor is required only if I want a record

No.  No need for a new "profunctor".  Not sure where you got that idea from.

**Comment by tomjaguarpaw** [comment]
Oh, I think I see what you mean.  No, you don't need a polymorphic record.  See

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/Doc/Tutorial/TutorialBasicMonomorphic.lhs#L213

and replace `(,,,,)` there with the constructor of your (monomorphic) record.

**Comment by tomjaguarpaw** [comment]
In fact, in that document, I'm pretty sure this would have worked:

````haskell
aggregateWidgets :: Query WidgetColumn
aggregateWidgets = aggregate (WidgetColumn <$> P.lmap style    groupBy
                                     <*> P.lmap color    groupBy
                                     <*> P.lmap location count
                                     <*> P.lmap quantity sum
                                     <*> P.lmap radius   avg)
                             (queryTable widgetTable)
````

Look!  Completely monomorphic!

**Comment by tomjaguarpaw** [comment]
By the way, this

````haskell
aggregateFoo :: Query (Column PGInt8, Column PGInt8)
aggregateFoo = aggregate (p2 (groupBy, Opaleye.sum))
````

should have been this

````haskell
aggregateFoo :: Query (Column PGInt8, Column PGInt8)
aggregateFoo = aggregate (p2 (groupBy, Opaleye.sum)) foo
````

I missed off the `foo` by accident.

**Comment by saurabhnanda** [comment]
>>  returnA -< (tableA ^. col2, avg $ sum $ count $ tableA ^. key)

> which would be nonsense. Type safety!

Is `avg $ sum $ count $ tableA ^. key` a problem due to *type-safety* or because *conceptually* it doesn't make sense?

**Comment by tomjaguarpaw** [comment]
Right, conceptually it doesn't make sense, and if you generated SQL for it the SQL would be rejected. Therefore code for it must not be generated, therefore a typesafe library must forbid it.  That's why Opaleye can't do aggregation by something that looks like

    returnA -< (tableA ^. col2, avg $ sum $ count $ tableA ^. key)

and we have a separate `aggregate` primitive instead.

**Comment by saurabhnanda** [comment]
If I'm working with tuples, which have the advantage of not forcing me to define intermediate type for every sub-query, how do I get rid of counting underscores in tuple pattern matching? And, what is the best way to do a multi-way left join (because the solution that I've come-up with below, will easily go out of hand -- I have 6 more left joins left to do!)

```
flattenTuple6_1 (a0, a1, a2, a3, a4, a5) (b0) = (a0, a1, a2, a3, a4, a5, b0)
flattenTuple7_1 (a0, a1, a2, a3, a4, a5, a6) (b0) = (a0, a1, a2, a3, a4, a5, a6, b0)


finalReport :: Connection -> LocalTime -> LocalTime -> IO [
  (
    Int64 -- clientId
  , T.Text -- client name
  , Maybe T.Text -- client domain
  , T.Text -- bp name
  , LocalTime -- bp start
  , LocalTime -- bp end
  , Int64 -- createdAt trip count
  , Int64 -- updatedAt trip count
  )]
finalReport conn st en = runQuery conn $ filtered
  where
    reportQuery1 = leftJoinF
      (\bpClient (_, tc) -> flattenTuple6_1 bpClient tc)
      (\bpClient -> flattenTuple6_1 bpClient (constant (0::Int64)))
      (\(bpClientId, _, _, _, _, _) (tripClientId, _) -> (bpClientId .== tripClientId))
      (clientAndBillingPlan st)
      (tripCount createdAt st en)

    reportQuery2 = leftJoinF
      (\prev (_, tc) -> flattenTuple7_1 prev tc)
      (\prev -> flattenTuple7_1 prev (constant (0::Int64)))
      (\(cId, _, _, _, _, _, _) (tripClientId, editCount) -> (cId .== tripClientId))
      reportQuery1
      (tripCount updatedAt st en)

    filtered = proc () -> do
      r@(_, _, _, _, _, _, _, c) <- reportQuery2 -< ()
      restrict -< (c .> (constant (0::Int64)))
      returnA -< r
```

**Comment by tomjaguarpaw** [comment]
> how do I get rid of counting underscores in tuple pattern matching

Perhaps you could use the `_1`, `_2` lenses instead of pattern matching?

> what is the best way to do a multi-way left join

I'm sorry, there's really not a good way right now.  See https://github.com/tomjaguarpaw/haskell-opaleye/issues/237

**Comment by saurabhnanda** [comment]
> Perhaps you could use the _1, _2 lenses instead of pattern matching?

Thanks for the tip. Pretty handy!

Any other tips on how to solve the tuple-flattening problem when doing chained left-joins?

Also, is there **any way** to give each column in a `Query` an ad-hoc name, by which it can be accessed? Otherwise a miscount and I'll end-up writing `row ^. _7` instead of `row ^. _8` which will mean completely different things!

**Comment by tomjaguarpaw** [comment]
> any way to give each column in a Query an ad-hoc name

Yes, use records!

**Comment by tomjaguarpaw** [comment]
I don't see why you think records will force you to define intermediate types for every sub query.

**Comment by saurabhnanda** [comment]
I am left-joining the following queries:

```
clientAndBillingPlan :: LocalTime -> Query (Column PGInt8, Column PGText, Column (Nullable PGText), Column PGText, Column PGTimestamp, Column PGTimestamp)
tripCount :: (Getting (Column PGTimestamp) TripPGRead (Column PGTimestamp)) -> LocalTime -> LocalTime -> Query (Column PGInt8, Column PGInt8)
```

How do I use records?

**Comment by tomjaguarpaw** [comment]
````haskell
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE FlexibleContexts      #-}
{-# LANGUAGE UndecidableInstances  #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE MultiParamTypeClasses #-}

import Opaleye
import Data.Profunctor.Product.TH
import Data.Profunctor.Product.Default
import Data.Profunctor.Product
import Data.Profunctor
import GHC.Int

-- Dummies
data LocalTime
data Getting a b c
data TripPGRead

clientAndBillingPlan :: LocalTime
                     -> Query ClientAndBillingPlan
clientAndBillingPlan = undefined

tripCount :: (Getting (Column PGTimestamp) TripPGRead (Column PGTimestamp))
          -> LocalTime
          -> LocalTime
          -> Query TripCount
tripCount = undefined

createdAt = undefined

-- Data types
data ClientAndBillingPlan =
    ClientAndBillingPlan { bpClientId    :: Column PGInt8
                         , clientName    :: Column PGText
                         , clientAddress :: Column PGText
                         , planName      :: Column PGText
                         , planStart     :: Column PGTimestamptz
                         , planEnd       :: Column PGTimestamptz
                         }

data TripCount =
  TripCount { tripClientId :: Column PGInt8
            , bar          :: Column PGInt8
            }

-- Boilerplate that should be derived by Template Haskell or
-- generics, but it is not implemented yet.
instance ( ProductProfunctor p
         , Default p (Column PGInt8) (Column PGInt8)
         , Default p (Column PGText) (Column PGText)
         , Default p (Column PGTimestamptz) (Column PGTimestamptz) )
         => Default p ClientAndBillingPlan ClientAndBillingPlan where
  def = ClientAndBillingPlan ***$ lmap bpClientId    def
                             **** lmap clientName    def
                             **** lmap clientAddress def
                             **** lmap planName      def
                             **** lmap planStart     def
                             **** lmap planEnd       def

instance ( ProductProfunctor p
         , Default p (Column PGInt8) (Column PGInt8) )
         => Default p TripCount TripCount where
  def = TripCount ***$ lmap tripClientId def
                  **** lmap bar          def


reportQuery1 :: LocalTime
             -> LocalTime
             -> Query (ClientAndBillingPlan, Column PGInt8)
reportQuery1 st en = leftJoinF
      (\bpClient tripClient -> (bpClient, bar tripClient))
      (\bpClient -> (bpClient, constant (0::Int64)))
      (\bpClient tripClient -> (bpClientId bpClient .== tripClientId tripClient))
      (clientAndBillingPlan st)
      (tripCount createdAt st en)
````

You can do something like this.  I'm sorry about the boilerplate!  It can easily be derived by TH or generics but someone's got to implement that first!

**Comment by saurabhnanda** [comment]
Any way to simplify this aggregation:

```
sumOfPaymentAmount :: Query PaymentPGRead -> Query (Column PGFloat4)
sumOfPaymentAmount q = proc () -> do
  sumAmt <- aggregate (p1 (Opaleye.sum)) onlyAmountQuery -< ()
  returnA -< (sumAmt)
  where
    onlyAmountQuery = proc () -> do
      payment <- q -< ()
      returnA -< (payment ^. amount)
```

**Comment by tomjaguarpaw** [comment]
This is crazy verbose!  Firstly you don't need the arrow notation

````haskell
sumOfPaymentAmount :: Query PaymentPGRead -> Query (Column PGFloat4)
sumOfPaymentAmount q = aggregate (p1 (Opaleye.sum)) onlyAmountQuery
  where
    onlyAmountQuery = fmap (^. amount) q
````

Secondly, get rid of onlyAmountQuery

````haskell
sumOfPaymentAmount q = aggregate (p1 (Opaleye.sum)) (fmap (^. amount) q)
````

Thirdly, use `.`

````haskell
sumOfPaymentAmount = aggregate (p1 (Opaleye.sum)) . fmap (^. amount)
````

Fourthly, you don't need `p1`

````haskell
sumOfPaymentAmount = aggregate Opaleye.sum . fmap (^. amount)
````

**Comment by saurabhnanda** [comment]
> This is crazy verbose!

Thanks! I don't *really* understand arrows, pro-functors, or `Query`. It's all magic to me. I'm basically copy-pasting and getting it to compile!

**Comment by saurabhnanda** [comment]
```
-- Data types
data ClientAndBillingPlan =
    ClientAndBillingPlan { bpClientId    :: Column PGInt8
                         , clientName    :: Column PGText
                         , clientAddress :: Column PGText
                         , planName      :: Column PGText
                         , planStart     :: Column PGTimestamptz
                         , planEnd       :: Column PGTimestamptz
                         }
```

This is where the problem starts. It's going to become unmanageable soon if I start defining data-types for every interim query that has a JOIN. I'm wondering, is there no way to map PG tables to extensible records or have "tagged tuples"?

**Comment by tomjaguarpaw** [comment]
But that's a very useful intermediate datatype for your program!  It would be fairly standard practice to define such a thing in Haskell, even without Opaleye.

Yes, you could try any extensible record library that you like.  They should all be compatible with Opaleye although getting the `Default` instances to work might be fiddly.  Not sure.

**Comment by saurabhnanda** [comment]
While `leftJoinF` is certainly easier to use than `leftJoin`, it, unfortunately, results in a explosion of `CASE` statements in the select clause to handle the `whenMatchNotFound` case. It might be better to implement it as a `COALESCE` on the original `SELECT` itself. 

This is also raising another existential question in my head. Isn't Opaleye forcing us to write obvious/common type transformations all over the place (which is probably yhe maon cause for the explosion in boilerplate)? Eg. A left-join will result in a type of same shape, but with each column being nullable. Eg. A TEXT/VARCHAR column will.map to Data.Text in Haskell, ans vice versa (this being thr default behaviour, which can be overridden)

Is it not possible to add these common type transformations to the core library itself, while allowing the user to override the behaviour on a case by case basis?

**Comment by saurabhnanda** [comment]
Can this be implemented by an opinionated queryRunner, which uses the same underlying `Default Constant` and `QueryRunnerColumnDefault` infrastructure, but doesn't force the user to keep providing type annotations to guide the type transformations?

**Comment by saurabhnanda** [comment]
Using tuples & lenses didn't last for long. There is no `_10` (and onwards) lens available in the `Control.Lens` package!

**Comment by ocharles** [comment]
#265 might be relevant here.

**Comment by xnmp** [comment]
I seem to have solved this problem! Write:

```
type family ColToNul (c :: *) :: *
type instance ColToNul (UserP (Column a) (Column b) (Column c)) = 
  UserP (Column (Nullable a)) (Column (Nullable b)) (Column (Nullable c))
```

and just change the type signature of left join replacing ```nullablecolumnsR``` with ```ColToNul(columnsR)``` like so:

```haskell
leftJoinNew  :: (D.Default U.Unpackspec columnsL columnsL,
              D.Default U.Unpackspec columnsR columnsR,
              D.Default J.NullMaker columnsR ColToNul(columnsR))
          => Query columnsL  -- ^ Left query
          -> Query columnsR  -- ^ Right query
          -> ((columnsL, columnsR) -> Column T.PGBool) -- ^ Condition on which to join
          -> Query (columnsL, ColToNul(columnsR)) -- ^ Left join
leftJoinNew = leftJoinExplicit D.def D.def D.def
```

It requires a bit more boilerplate in defining an instance of ```ColToNul```. I'm using Girella [https://github.com/silkapp/girella] so I added this to Girella.TH.Table:

```haskell
coltonulInstance = TySynInstD ''ColToNul
                     (TySynEqn [lhs] rhs)
        where
          coln, nulln, lhs, rhs :: Type
          coln = ConT (mkName "Column")
          nulln = ConT (mkName "Nullable")
          lhs = foldl' AppT (ConT dataName) $ map (AppT coln . VarT) tvars
          rhs = foldl' AppT (ConT dataName) $ map (AppT coln . AppT nulln . VarT) tvars
```

Left joins now infer type!

**Comment by tomjaguarpaw** [comment]
This issue looks stale so I'm closing it.  Feel free to reopen if necessary.
