### ISSUE TITLE
Is there any publicly accessible Haskell codebase that uses Opaleye?

### ISSUE THREAD

**Issue by sras** [tomjaguarpaw/haskell-opaleye#262]

**Comment by tomjaguarpaw** [comment]
No idea!  You're writing the first in-depth tutorial!

**Comment by LightAndLight** [comment]
Hey @sras, not sure exactly what you're looking for but here's a toy project I've been working on using Scotty and Opaleye

https://github.com/lightandlight/humblr

Specifically, https://github.com/LightAndLight/humblr/tree/master/src/Humblr/Database

**Comment by tomjaguarpaw** [comment]
If you need more help with this please reopen.

**Comment by gasi** [comment]
Here’s another example from the (WIP) code that powers http://zoomhub.net: https://github.com/zoomhub/zoomhub/blob/c4db77a1f736b406a1934cd1b8d8cbf08fe1df38/src/ZoomHub/Storage/PostgreSQL.hs
