### ISSUE TITLE
Inline left joins

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#265]
It's possible to write left joins "inline" in arrow syntax.

This is cribbed directly from my [`rel8`](http://github.com/ocharles/rel8) project, but hopefully the idea comes across:

```haskell
inlineLeftJoin
  :: forall a haskell bool.
     (Table a haskell, Predicate bool)
  => O.Query a -> O.QueryArr (a -> Expr bool) (MaybeTable a)
inlineLeftJoin q =
  O.QueryArr $ \(p, left, t) ->
    let O.QueryArr rightQueryF = liftA2 (,) (pure (lit False)) q
        (right, pqR, t') = rightQueryF ((), PrimQuery.Unit, t)
        ((tag, renamed), ljPEsB) =
          O.run
            (O.runUnpackspec
               unpackColumns
               (O.extractLeftJoinFields 2 t')
               right)
    in ( MaybeTable tag renamed
       , PrimQuery.Join
           PrimQuery.LeftJoin
           (case toNullableBool (p renamed) of
              Expr a -> a)
           [] -- (1) Is this safe?
           ljPEsB
           left
           pqR
       , t')
```

Essentially we build a special QueryArr by immediately performing a left join against the new table and everything in the arrow before.

In my case I'm tagging the null row and wrapping it up in some fancy `MaybeTable` thing, but it should be possible with the normal `NullMaker` to have something more idiomatic in `opaleye`.

What do you think? And is this safe? Point (1) in the comment above concerns me, but when generating SQL for the `LeftJoin` node, there's a `SELECT *` anyway, which means the previous `PrimExpr`s still work without renaming through `extractLeftJoinFields`. I *think* this is OK - as long as we just rename the new fields, there shouldn't be a conflict... right?

**Comment by ocharles** [comment]
@tomjaguarpaw, do you have any thoughts on this? We've been using it in production fairly extensively and it seems to work fine.

**Comment by tomjaguarpaw** [comment]
`a -> Expr bool` (which in the Opaleye world would be `a -> Column PGBool`) is *extremely* suspicious to have in the argument type of a `QueryArr`.  Can you explain what this is used for?  I don't get it.

**Comment by ocharles** [comment]
From the `rel8` documentation, you use it like this:

>  Left joins can be introduced with the `leftJoin`, which takes two queries, or using arrow notation with `leftJoinA`. Let's look at the latter, as it is often more concise.

```haskell
   partsAndSuppliersLJ :: Query (Part Expr, MaybeTable (Supplier Expr))
   partsAndSuppliersLJ = proc _ -> do
     part <- queryTable -< ()
     maybeSupplier
       <- leftJoinA queryTable
       -< \supplier -> partCity part ==. supplierCity supplier
     returnA -< (part, maybeSupplier)
```

> This is a little different to anything we've seen so far, so let's break it down. `leftJoinA` takes as its first argument the query to join in. In this case we just use `queryTable` to select all supplier rows. `LEFT JOIN`s also require a predicate, and we supply this as /input/ to `leftJoinA`. The input is itself a function, a function from rows in the to-be-joined table to booleans. Notice that in this predicate, we are free to refer to tables and columns already in the query (as `partCity part` is not part of the supplier table).


Does that help?

**Comment by tomjaguarpaw** [comment]
Hmm, I'm going to have to think through the safety of this one, and it'll be a while before I can get round to it.

**Comment by xnmp** [comment]
Perhaps this would make more sense if it had the type 

`Query (a) -> ((a, b) -> Bool) -> QueryArr (Column b) (Column b, Column (Nullable a))`

The above example would then be 

`partsAndSuppliersLJ = queryTable >>> leftJoinA queryTable (\(part, supplier) -> partCity part .== supplierCity supplier)`

@ocharles could you give something similar to your inlineLeftJoin for vanilla Opaleye? It would be extremely useful.

**Comment by xnmp** [comment]
So I wrote the inline left join that I suggested above in vanilla Opaleye. Note that I have no idea how any of this works, I just modified the source code for ```joinExplicit```.

```haskell
leftJoinOn :: (Default J.NullMaker b nullb, Default O.Unpackspec b b)
  => Query (b) -> ((a, b) -> Column Bool) -> QueryArr (a) (nullb)
leftJoinOn = leftJoinOnExplicit def def

leftJoinOnExplicit :: O.Unpackspec b b -> J.NullMaker b nullb -> Query (b) -> ((a, b) -> Column Bool) -> QueryArr (a) (nullb)
leftJoinOnExplicit uB nB q cond = O.QueryArr f where
  f (col_A, pq_A, t) = (null_col_B, pq_Join, t')
    where
      -- qFunc = O.runQueryArr $ liftA2 (,) (pure $ constant False) q
      (col_B, pq_B, t') = O.runQueryArr q ((), PQ.Unit, t)
      (new_col_B, ljPEsB) = O.run $ O.runUnpackspec uB (J.extractLeftJoinFields 2 t') col_B
      O.Column cond' = cond (col_A, col_B)
      pq_Join = PQ.Join PQ.LeftJoin cond' [] ljPEsB pq_A pq_B
      null_col_B = (J.toNullable nB) new_col_B
```

There seems to be a problem with the tags though, since when I print out the SQL it has a random ```SELECT 0``` in there. Also there's still the type inference problem with ```b``` and ```nullb``` instead of ```b``` and ```Nullable b``` - is there any way to get around this similar to @ocharles 's ```MaybeTable```?

**Comment by mulderr** [comment]
>In my case I'm tagging the null row and wrapping it up in some fancy MaybeTable thing, but it should >be possible with the normal NullMaker to have something more idiomatic in opaleye.

I put together a fork [here](https://github.com/mulderr/haskell-opaleye/blob/420d77013b88e3e0dfb4da8ca972375a70c364f3/src/Opaleye/Join.hs#L52) with @ocharles's `inlineLeftJoin` copied almost verbatim (and with `runUpdateEasy` since I'm using it).

@tomjaguarpaw the idea seems extremely useful if it's correct. I cannot see anything wrong with the code. I've only run a couple basic queries to test but nothing raises any obvious red flags. In fact it works great so far. Maybe it would make sense to let it sit on a branch somewhere for a while and point people there. So at least there is one working version to test available for everyone (doesn't have to be the one above).

**Comment by xnmp** [comment]
Problem is that it isn't all that composable. With the version I have, I can do something like

```haskell
table1 >>> queryarr1 >>> leftJoinA table2 ((a,b) -> column1 a .== column2 b) >>> arr column3
```

Whereas the above is version is less intuitive, and you have to bend over backwards (not sure if the below is right):

```haskell
table1 >>> queryarr1 >>> pure (.== column1) <*> arr column2 >>>  leftJoinA table2 >>> ar column3
```

**Comment by mulderr** [comment]
@xnmp You're probably right. I never noticed - always used the do notation. So I don't really have on opinion on this since it hasn't ever been an issue for me in practice yet. Right now, I guess whatever other people prefer is fine with me.

**Comment by ocharles** [comment]
@mulderr You will need to update your branch with this:

```haskell
leftJoinAExplicit :: U.Unpackspec a a
                  -> J.NullMaker a nullableA
                  -> Query a
                  -> QueryArr (a -> Column T.PGBool) nullableA
leftJoinAExplicit uA nullmaker rq =
  QueryArr $ \(p, left, t) ->
    let QueryArr rightQueryF = rq
        (right, pqR, t') = rightQueryF ((), PQ.Unit, t)
        (renamed, ljPEsB) = PM.run $ U.runUnpackspec uA (J.extractLeftJoinFields 2 t') right
        renamedNullable = J.toNullable nullmaker renamed
        Column cond = p renamed
    in ( renamedNullable
       , PQ.Join
           PQ.LeftJoin
           cond
           [] -- TODO ?
           ljPEsB
           left
           pqR
       , O.next t'
)
```

Note the `O.next t'` on the last line. My colleague just found out that you end up with ambiguous variable names otherwise (as Opaleye renders joins with a `SELECT *`).

**Comment by mulderr** [comment]
@ocharles Thanks! Updated.

**Comment by tomjaguarpaw** [comment]
We want `leftJoinA :: Query a -> QueryArr (a -> Column bool) nullableA`.  Recall that the semantics of `Query` are roughly `[]` and of `QueryArr` are roughly `Kleisli []`.  That means the semantics of `leftJoinA` should be of type `[a] -> (a -> Bool) -> [Maybe a]`.  It seems vaguely plausible that this should exist.  I suppose the idea is that if the predicate is `True` you get `Just` and if `False` you get `Nothing`.

**Comment by tomjaguarpaw** [comment]
Oh no, it's more like

```haskell
leftJoinA xs p =
    case filter p xs of []  -> [Nothing]
                        xs' -> map Just xs'

**Comment by tomjaguarpaw** [comment]
This would be extremely cool if it's semantically safe!

**Comment by tomjaguarpaw** [comment]
The more I think about this the more I want it.  Can anyone besides @ocharles (@xnmp, @mulderr?) attest to its practical value?

**Comment by tomjaguarpaw** [comment]
@ocharles How did you get the idea for this?  It's really quite ingenious!

**Comment by ocharles** [comment]
Ha, that's a bit too far on the philosophical side for Mr! I think when you
understand QueryArr is "just" a state arrow over queries, it becomes easier
to see what's possible.

**Comment by tomjaguarpaw** [comment]
I created a branch with @ocharles's implementation

https://github.com/tomjaguarpaw/haskell-opaleye/tree/inline

**Comment by mulderr** [comment]
@tomjaguarpaw I can't really judge the implementation but having inline joins is necessary in practice for me. Actually, this was probably the one missing future that gave me serious pause when considering `opaleye`.

Databases I usually work with require a mix of at least a couple inner and outer joins to get anything out. We have this Oracle database that is highly normalized and internationalized. Queries that span 15-20 tables or more are not uncommon. Obviously I can't use `opaleye` for that directly but that's just how the data is, and it's not going away so - you get the idea.

**Comment by tomjaguarpaw** [comment]
Does anyone else have any experience to report with inline left joins?  I'd really like to release them soon in 0.6.2.0.

**Comment by tomjaguarpaw** [comment]
I went ahead and merged this to master.
