### ISSUE TITLE
How am I being able to run Haskell code in SQL?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#266]
I'm assuming `runUpdateReturning` would be mapping straight to an `UPDATE` SQL statement. If yes, how is the following possible:

```
runUpdateReturning conn tagTable 
      (
        \ctR -> ClientTag
                {
                  ctKey = Just $ ctR ^. key
                , ctCreatedAt = Just $ ctR ^. createdAt
                , ctUpdatedAt = (pgLocalTime now)
                , ctClientId = ctR ^. clientId
                , ctTags = constant $ nub $ (existingCt ^. tags) ++ [newTag ^. tag]
                }
      )
      (\ctR -> (ctR ^. clientId) .== (pgInt8 $ newTag ^. clientId))
      id
``` 

Particularly the following expression:

```
ctTags = constant $ nub $ (existingCt ^. tags) ++ [newTag ^. tag]
```

`nub` and `++` are Haskell functions, how are they being mapped to SQL? Or are they not? Does this mean that every matching row is read into Haskell, transformed in Haskell, and then written back?

**Comment by ocharles** [comment]
`constant` is lifting the list of Haskell values to a SQL literal. There is no back-and-forth.

**Comment by tomjaguarpaw** [comment]
Notice that `ctTags` doesn't depend on the data in the row that's being updated.  You're creating a list in Haskell, lifting it to a `Column (Array something)` with `constant`, sending it to Postgres as an SQL expression, and then `runUpdateReturning` turns it back into the original Haskell list.  You may as well not send it at all!

**Comment by tomjaguarpaw** [comment]
I hope this answers your question.  If not then please reopen.
