### ISSUE TITLE
Maintainer unavailable until mid-February

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#267]
Hello everyone.  Just to let you know I'm still unavailable to respond to Opaleye issues and I expect that to continue until at least mid-February.

**Comment by gasi** [comment]
@tomjaguarpaw I’ve just started playing around with Opaleye for https://github.com/zoomhub/zoomhub/pull/131 but I am already very impressed. Congrats to all your hard work 👏

**Comment by xldenis** [comment]
Would it be possible to give commit access to someone else? Otherwise we can always just work off a fork for the duration of your absence

**Comment by tomjaguarpaw** [comment]
@xldenis Please start your own fork.  I can merge when I get back.

**Comment by ocharles** [comment]
Also, if you need a co-maintainer, drop me an email - would be happy to help.

**Comment by tomjaguarpaw** [comment]
I'm somewhat more available now, at least for the next few weeks.
