### ISSUE TITLE
No longer possible to enforce foreign key compatibility on the type level(?)

### ISSUE THREAD

**Issue by bergmark** [tomjaguarpaw/haskell-opaleye#27]
This is coming late, but I didn't realize the impact of the PGTypes change that happened a while back. I'm not sure if this can be solved outside of opaleye?

Take this example:

```sql
create table foo (id serial primary key);
create table bar (id serial primary key, foo_id int references foo (id));
```

The opaleye mapping for this would be

```haskell
newtype FooId = FooId Int
data Foo' a = Foo { fooId :: a }
type Foo = Foo' FooId
type FooColumn = Foo (Column PGInt)

newtype BarId = BarId Int
data Bar' a b = Foo { barId :: a,  fooBarId :: b }
type Bar = Bar' BarId FooId
type BarColumn = Foo (Column PGInt) (Column PGInt)
```

If we construct queries joining these tables we might by accident end up with

```haskell
myQuery = proc () -> do
  f <- queryTable fooTable
  b <- queryTable barTable
  restrict -< fooId f .== barId b
  id -< (f,b)
```

yielding something like
```sql
select f.* from foo f inner join bar b on f.id = b.id;
```

This used to be a type error because `fooId f :: Column FooId` and `barId b :: Column BarId`. Now they are both `:: Column PGInt` and there is no protection against doing nonsensical joins.

So in a lot of ways queries are no longer type safe as I'd like them to be, they are only type safe in the sense that the postgres types are the same. You can misplace any column that happens to have the same representation as another one.

**Comment by tomjaguarpaw** [comment]
I don't think `PGTypes` affects this.  If you preferred what you were doing previously there should be no reason you can't still do it.  For example you can define

    type FooColumn = Foo (Column FooId)
    type BarColumn = Foo (Column BarId) (Column FooId)

This may require you to write some instances, but that was also the case previously.

There's a related issue: the type of `(.==)` should be generalised to a typeclass.  We're used to using `(==) :: Bar -> Bar -> Bool` in Haskell.  There's no reason we shouldn't have `(.==) :: BarColumn -> BarColumn -> Column Bool` in Opaleye.  There is a nice easy way to implement this in terms of `Default` but I just haven't bothered to do it yet.  Anyone is welcome to.  (This is in fact mentioned [in the TODO](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/TODO.md).)

**Comment by bergmark** [comment]
Thanks, that makes sense.

I'll play a bit with this. I think for us we never want to deal with PGTypes explicitly because it can cause issues like this.

**Comment by bergmark** [comment]
I managed to fix this for our purposes, https://github.com/silkapp/silk-opaleye/commit/a6b19a325745a5f7f6b721b366214120b5dd8f40 by redefining most operators and using a lot of `unsafeCoerce` :)

 At least it's possible! And good enough for our purposes.

**Comment by tomjaguarpaw** [comment]
I'm confused about this.  What is the rationale for changing `Column PGBool` to `Column Bool` (to take one example of many)?  It doesn't seem like it's actually related to this foreign key issue.

**Comment by bergmark** [comment]
We decided to skip the opaleye types altogether and just use haskell types. We rarely newtype `Bool` in the db so changing the type of operators meant we didn't have to change any other code. If we newtype a Bool we don't want to compare it to a Bool by accident, but instead do an explicit conversion. It's always clear from the context wether a type is "inside" opaleye or not so I didn't see the use of keeping any of the PGTypes.

So you are right that it isn't just about FK's, but rather to make it consistent in the way we want it to be :)

**Comment by tomjaguarpaw** [comment]
That's a reasonable goal, though I suspect a type family would help avoid rewriting all the type signatures:

    type family MyColumn a

    type instance MyColumn Bool = Column PGBool
    type instance MyColumn Int = Column PGInt4
    ....

and then use

    (.||) :: MyColumn Bool -> MyColumn Bool -> MyColumn Bool

etc.
