### ISSUE TITLE
Possible addition: `exactOrder`

### ISSUE THREAD

**Issue by thoughtpolice** [tomjaguarpaw/haskell-opaleye#276]
**Background**: I'm using Opaleye to write queries as a backend for a Haxl data source. Haxl requires me to run a query giving multiple results, and then fill up some `MVars` with the results from the query.

**Problem**: Haxl does *not* order the `MVars` in any specified way, and you cannot depend on an ordering. Haxl gives you a list of MVars. You must always fill the right `MVar` with the right data result, but the order of the list is not specified. As a result, **I need to return a list of results in an arbitrary order, based on the input list**.

For example, if I write some Haxl code like this:

```haskell
k :: GenHaxl () [String]
k = do
  u1 <- getUserNameById 1
  u2 <- getUserNameById 2
  return [u1, u2]
```

I expect the code to give back the name of the first user, and then the name of the second user. **But**, internally, when I fetch from my data source and Haxl calls my backend, **I might get the MVars to fill in a different order than `[u1, u2]`**. In other words: Haxl would give me a list of MVars, with length 2, but the first MVar in the list needs to have the *second* result (`u2`), and the second MVar needs to have the first result (`u1`).

Note that this is an implementation detail: while the above `k` function would, in fact, return the results in the right order you'd expect, it is simply the backend to Haxl that might get the results out of order.

---

More concretely: I want to run a query like this:

```sql
select name from person
  where (id = 2) or (id = 1)
  order by (id=2, id=1) desc;
```

Assuming there are two columns `name :: PGText` and `id :: PGInt4`, with two entries `(1, "Austin")` and `(2, "Tom")`, the above query will actually return them in reverse order (Tom first, then Austin).

The above query can be extended to any general ordering, it doesn't matter; for example, `order by (id=3, id=1, id=2 desc)` will give you the results in the order `[3, 1, 2]`. This is exactly what is needed for Haxl: I need to look over the list, get the parameters for the query, and then order the results according to the list of MVars.

-------

Possible addition:

```haskell
-- | Perform an exact ordering on the result of a query, the
-- ordering determined by the order of the provided @'NL.NonEmpty'@.
exactOrder :: NL.NonEmpty (Column b) -> (a -> Column b) -> Order a
exactOrder xs k = O.Order $ flip fmap k $ \col ->
  let listOrder = O.ListExpr $ flip NL.map xs $ \b ->
        O.BinExpr (O.:==) (O.unColumn col) (O.unColumn b)
  in
  [(O.OrderOp O.OpDesc O.NullsFirst, listOrder)]
```

This roughly translates to the above query, though larger. It has the same style of API as the other order combinators, although it uses a `NonEmpty`, because `ListExpr` requires a `NonEmpty`. Here's an example from a simple database of mine, a live query run with Haxl:

```sql
SELECT "name1_1" as "result1_2"
FROM (SELECT *
      FROM (SELECT *
            FROM (SELECT *
                  FROM (SELECT "id" as "id0_1",
                               "name" as "name1_1",
                               "age" as "age2_1",
                               "address" as "address3_1"
                        FROM "wednesday"."person" as "T1") as "T1"
                  WHERE ((FALSE OR (2 = ("id0_1"))) OR (1 = ("id0_1")))) as "T1"
            ORDER BY (("id0_1") = 2,("id0_1") = 1) DESC NULLS FIRST) as "T1") as "T1"
```

As you can see, Haxl requested I give the results in the order `[2, 1]`.

---

**Notes**: The above query, for me, translates directly to a bitmap scan, though I don't know if this is really significant: the dataset is small (a few dozen rows), and I'm only querying 2-5 IDs at a time right now in a randomly specified order. I don't even have indexes.

The alternative query I've seen floated for the ("I need to order the query results in an arbitrary way") above is this:

```sql
SELECT name FROM person
  LEFT JOIN (VALUES (2,1),(1,2)) as x(id,ordering) on x.id = person.id
  order by x.ordering;
```

This does a clever `LEFT JOIN` over the values: Postgres will turn this into a Hash join. For my queries this is actually slower; but again I'm running over *very* tiny datasets and indexes as I'm learning, so it's entirely possible that the above join will largely win out over this. However, it's also a bit trickier to write and this is literally the first time I've used Opaleye, so, I don't know exactly how you'd like to do this.

**Comment by tomjaguarpaw** [comment]
Hi Austin.  So you want the ability to specify the order in which the results are returned?  `exactOrder` looks fine, although might it not be simpler to just sort the results on the Haskell side?

**Comment by thoughtpolice** [comment]
A few things:

  - I admit, part of it was I wanted to see if I could even do this in Opaleye. I was a bit hesitant about its extensibility when starting (e.g. what if I need to wrap functions offered by extensions, how would I go about it?) and this was the first wall I hit, so I tried doing it "in house". Needless to say, it was fairly easy.
  - Despite point 1, I opened this ticket because I also figured `exactOrder` might be useful beyond my own desires, since it seems general enough. (Admittedly, `asc` and `desc` alone take care of like, 90% of actual `ORDER BY` clauses in practice, I'd bet, so I'm not sure if this is too narrow a use case).
  - I considered doing the sort in Haskell, but one nice part is that `exactOrder` is, in a way, more reusable since I can attach it to any query, I think. In my case: for Haxl, it's likely I'll have several different Haxl APIs backed by Postgres, that need to do something similar. The above example was for only *one* specific query and one API, but at the end of it all, I'm probably going to have 5 to 10 different datasource APIs backed by Postgres, and the queries will vary (but the need for an exact ordering will not).

There's maybe a hand-wavy argument about efficiency in some cases -- the DB can possibly do the sort more intelligently than I can given the result set) but I'm not sure. The main thing, like I said, is how this will work with larger datasets. However, realistically? If you're returning like 40,000 results per query, I imagine ordering the results exactly is going to be something of a pain no matter *where* you do it.

In any case, if you think you might be willing to entertain such an addition, I'll gladly make a PR and write the documentation for you.

**Comment by tomjaguarpaw** [comment]
Yes, I'm very happy to take a PR for `exactOrder`.

Can you explain some things about its semantics?

1. What happens if some rows have columns with values that are not present in the `ORDER BY` list?  For example, if I have `ORDER BY (("id0_1") = 2,("id0_1") = 1) DESC NULLS FIRST` but one of my `id0_1` fields is `3`.

2. What happens if I combine this with another ordering?  Is it valid to say `ORDER BY (("id0_1") = 2,("id0_1") = 1) DESC NULLS FIRST, "anothercolumn" ASC NULLS LAST`

**Comment by thoughtpolice** [comment]
Quick answers:

In general, when using `ORDER BY (id=...)` in the manner above, this ordering only applies *exactly to the specified rows in the order predicate*, of the returned result set, and any further results are returned normally in the way Postgres normally returns rows.

Let's elaborate. Example schema:

```sql
CREATE TABLE person
  ( id SERIAL PRIMARY KEY
  , name TEXT
  , age INT
  , address TEXT
  );
```

Data with some made up stupid names:

```sql
INSERT INTO person (name, age, address) VALUES
  ('Austin',27,'Knowhere'),
  ('Brandon',28,'Knowhere'),
  ('Chad Test',27,'Knowhere'),
  ('Chad Test',29,'Knowhere'),
  ('Chad Test',50,'Knowhere');
```

Now, some queries. First query: the result set is constrained to exactly two results. **Entries in the `ORDER BY` clause that are not returned in the result set are ignored**.

```sql
SELECT name, age from person
  WHERE (id = 1) OR (id = 2)
  ORDER BY (id=2,id=1) DESC NULLS FIRST;

Returns:

Brandon	28
Austin	27

---

SELECT name, age from person
  WHERE (id = 1) OR (id = 2)
  ORDER BY (id=2,id=3,id=1) DESC NULLS FIRST;

Returns:

Brandon	28
Austin	27
```

Thus, `id=3` is ignored in the case it isn't returned.

---

Second query: Exact ordering, without constrained result set via `WHERE`. **Exact ordering with `ORDER BY` returns the specified order as a prefix of the result set, and any other columns are returned "as usual"**.

```sql
SELECT name, age from person
  ORDER BY (id=2,id=1) DESC NULLS FIRST;

Returns:

Brandon	28
Austin	27
Chad Test	27
Chad Test	29
Chad Test	50
```

The first two results are ordered as specified. The remaining results are returned as they would with no specified ordering (in this case, sorted by the primary key)

---

Third query: Exact ordering, with a secondary `ORDER BY` clause. **Exact ordering applies precisely to the specified rows in the clause, as last time -- but other rows are sorted further, by subsequent clauses**.

```sql
SELECT name, age from person
  ORDER BY (id=2,id=1) DESC NULLS FIRST,
           "age" DESC NULLS FIRST;

Returns:


Brandon	28
Austin	27
Chad Test	50
Chad Test	29
Chad Test	27
```

---

Overall, I believe this are roughly the exact semantics you would expect -- no effect on the number of rows returned, only on the prefix of the result set, which can be exactly ordered.
