### ISSUE TITLE
Maybe restrict

### ISSUE THREAD

**Issue by delanoe** [tomjaguarpaw/haskell-opaleye#280]
Starting from example in basic tutorial how to write the Nothing case:

```
youngPeople :: Maybe Int  -> Query (Column PGText, Column PGInt4, Column PGText)

youngPeople maybeAge = proc () -> do
      row@(_, age, _) <- personQuery -< ()
      case maybeAge of
              Nothing -> ????? -- returns all but should be Column PGBool
              Just maybeAge' -> restrict -< age .<= pgInt4 maybeAge'
      returnA -< row
```

Thanks

**Comment by tomjaguarpaw** [comment]
I'm sorry, I don't understand what you are trying to do.  Could you clarify?

**Comment by delanoe** [comment]
Add a filter (or not) according the argument (Maybe Int):
If (Just 1) is given then filter with 1
else (Nothing) do not apply any filter
I am wondering how to write the "do not Opaleye.restrict" if nothing.

**Comment by tomjaguarpaw** [comment]
You actually already know the answer to this, even thought you think you don't :)

````haskell
youngPeople :: Maybe Int  -> Query (Column PGText, Column PGInt4, Column PGText)
youngPeople maybeAge = proc () -> do
      row@(_, age, _) <- personQuery -< ()
      restrict -< maybe (pgBool True) ((age .<=) . pgInt4) maybeAge
      returnA -< row
````

**Comment by delanoe** [comment]
Yes,  I was looking for "pgBool True" and maybe is the right way to write it. Thanks for your help.
