### ISSUE TITLE
Guidance on defining pgType => haskellType conversion

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#281]
I'm planning to polish and publish the [Advance DB mapping chapter](http://haskell.vacationlabs.com/en/latest/docs/opaleye/advanced-db-mapping.html) of the Opalaye tutorial and need some guidance on the following snippet from the API docs:

>If you already have a FromField instance for your haskellType, use fieldQueryRunnerColumn. (This is how most of the built-in instances are defined.)
> If you don't have a FromField instance, use queryRunnerColumn if possible. See the documentation for queryRunnerColumn for an example.
> If you have a more complicated case, but not a FromField instance, write a FieldParser for your type and use fieldParserQueryRunnerColumn. You can also add a FromField instance using this.

Why three difference methods? In which situations is one preferred over the other? It seems to me that the shortest way would be the second one, i.e. `queryRunnerColumn`, but most examples use the first method, which requires defining instances of *two* type-classes. Why?

**Comment by tomjaguarpaw** [comment]
> Why three difference methods?

Only because this area of the API has never been polished.

**Comment by saurabhnanda** [comment]
> Only because this area of the API has never been polished.

**Comment by saurabhnanda** [comment]
> Only because this area of the API has never been polished.

Any use-case for three **internal** APIs (as opposed to a unified external API, which may need polishing)?

**Comment by tomjaguarpaw** [comment]
They're not really APIs at all.  They're just ways it can be done.

**Comment by saurabhnanda** [comment]
What is the core function that Opaleye internally uses to convert pgType to haskellType? 

* fromField
* fieldQueryRunnerColumn
* queryRunnerColumn

**Comment by tomjaguarpaw** [comment]
`runQuery` uses a `QueryRunner` to run the query.  Look at what a `QueryRunner` is:

````haskell
data QueryRunner columns haskells =
  QueryRunner (U.Unpackspec columns ())
              (columns -> RowParser haskells)
              -- We never actually look at the columns except to see
              -- its "type" in the case of a sum profunctor
              (columns -> Bool)
              -- ^ Have we actually requested any columns?  If we
              -- asked for zero columns then the SQL generator will
              -- have to put a dummy 0 into the SELECT statement,
              -- since we can't select zero columns.  In that case we
              -- have to make sure we read a single Int.
````

(https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/RunQuery.hs#L80)

It uses an `Unpackspec` to unpack the column names and a `postgresql-simple` `RowParser` to convert Postgres's output into Haskell values.  You can ignore the `columns -> Bool`.  It's just a technicality.

**Comment by saurabhnanda** [comment]
Wrt the following from the docs (emphasis mine), what's a non-default way to turn a pgType to a haskellType?

> A QueryRunnerColumnDefault pgType haskellType represents the **default way** to turn a pgType result from the database into a Haskell value of type haskellType.

Please validate the following understanding I have:

* Opaleye is primarily bothered about an instance of `QueryRunnerColumnDefault`, which basically means it uses `queryRunnerColumnDefault` internally.
* The type of `queryRunnerColumnDefault` is `QueryRunnerColumn columns haskells` which doesn't really have any direct constructors [1]
* The *smart* constructors to get a `QueryRunnerColumn columns haskells` are `fieldQueryRunnerColumn` (which can convert an existing `FromField` instance to a `QueryRunnerColumn`) and `fieldParserQueryRunnerColumn` (which can convert an existing `FieldParser` to a `QueryRunnerColumn`)

[1] Interestingly, `QueryRunnerColumn columns haskells` have *plurals* in their data-type, which makes it sound like it can convert a complete row, consisting of multiple columns, from pgTypes to haskellTypes. Is this correct? Can one take `(pgType1, pgType2, pgType3)` to `(haskType1, haskType2)`? (note the change in number of fields).

**Comment by tomjaguarpaw** [comment]
> Wrt the following from the docs (emphasis mine), what's a non-default way to turn a pgType to a haskellType?

Any way that you cook up by using a default way plus the `ProductProfunctor` operations by hand.  For example

````haskell
q :: QueryRunner (Column PGInt4) Int
q = rmap (+1) def
````

is a "non-default" way.  It adds `1` to all the integers that Postgres emits for that column!

> Opaleye is primarily bothered about an instance of QueryRunnerColumnDefault, which basically means it uses queryRunnerColumnDefault internally.

I guess so.  Or at least `instance Default QueryRunner (Column a) b` is primarily bothered about `instance QueryRunnerColumnDefault a b`.

> The type of queryRunnerColumnDefault is QueryRunnerColumn columns haskells which doesn't really have any direct constructors

Well, not really.  It's

````haskell
queryRunnerColumnDefault :: QueryRunnerColumnDefault pgType haskellType
                      => QueryRunnerColumn pgType haskellType
````

But yes, `QueryRunnerColumn` doesn't have any direct constructors.

> The smart constructors to get a QueryRunnerColumn columns haskells are fieldQueryRunnerColumn (which can convert an existing FromField instance to a QueryRunnerColumn) and fieldParserQueryRunnerColumn (which can convert an existing FieldParser to a QueryRunnerColumn)

Yep, seems like a reasonable interpretation.

> Interestingly, QueryRunnerColumn columns haskells have plurals in their data-

Where are you seeing that?  That doesn't occur anywhere in the Opaleye source code, as far as I can see.

**Comment by saurabhnanda** [comment]
> Can one take (pgType1, pgType2, pgType3) to (haskType1, haskType2)? (note the change in number of fields).

Use-case for this is mapping (PGText, PGNumeric) representing (Currency, Amount) to a single value in Haskell, like `data Amount = Amount Currency Rational`

**Comment by saurabhnanda** [comment]
> Where are you seeing that? That doesn't occur anywhere in the Opaleye source code, as far as I can see.

Sorry, I mixed up with `data QueryRunner columns haskells`

**Comment by tomjaguarpaw** [comment]
Is your question

> QueryRunner columns haskells have plurals in their data-type, which makes it sound like it can convert a complete row, consisting of multiple columns, from pgTypes to haskellTypes. Is this correct?

Then the answer is, yes, absolutely.  QueryRunners do that most of the time!

> Can one take (pgType1, pgType2, pgType3) to (haskType1, haskType2)? (note the change in number of fields).

Sure.  Use `rmap`.

**Comment by saurabhnanda** [comment]
> Then the answer is, yes, absolutely. QueryRunners do that most of the time!

Please scratch that question I was confused.

Just a general feeling I get whenever I look at this part of Opaleye is that there are **too many** moving parts, type-classes, and instances. What's the motivation behind this design? What does it really buy us?

**Comment by tomjaguarpaw** [comment]
> What's the motivation behind this design? What does it really buy us?

It buys us the ability to run queries type safely!  How would you simplify it?

**Comment by saurabhnanda** [comment]
It seems to me the complexity starts from the following:

> runQuery's use of the Default typeclass means that the compiler will have trouble inferring types. It is strongly recommended that you provide full type signatures when using runQuery.

All the moving parts required to have a default and non-default way of running queries. This also results in requiring type-signatures for every query. Very irritating for things like LEFT JOIN.

So, I'm always wondering, what is this complexity really buying us in return?

**Comment by tomjaguarpaw** [comment]
Well, first tell me a way of doing it with less complexity ...

**Comment by saurabhnanda** [comment]
> Well, first tell me a way of doing it with less complexity ...

I'm thinking aloud here, don't shoot me down :) So, starting from the top, what if the following type-signature were possible for `runQuery` to have some sort of "functional dependency" between `haskells` and `columns`, so that if the compiler inferred one of them, there would be only one possible value for the other type?

```
runQuery :: (haskells -> columns) => Connection -> Query columns -> IO [haskells]
```

**Comment by tomjaguarpaw** [comment]
Good question.  It would be possible to have this functional dependency, but then it wouldn't be possible to convert `PGText` into both `String` and `Text`, and convert both `PGText` and `PGJson` into `String`.

**Comment by saurabhnanda** [comment]
So, your first example is a Haskell quirk that everyone who has ever come in contact with the language, absolutely hates (String vs Text). Is there really a s use-case to keep building infra to support this?

And what's the use-case for converting PGJson into Text? 

What about having Opaleye define a standard set of conversions from either pgType->Haskell or vice versa? Where knowing one automatically identifies the other -- in the default case?  So, for most standard queries, one doesn't event need to provide any additional type information other than the initial Table data type. 

For cases where a String type is to be mapped to a custom ADT, that can be done while defining the Table itself. Thus eliminating the need to keep repeating yourself by providing a type-safety every time you use that column in a query. (And this also takes care of the two examples that you were mentioning). 

This also makes it possible for Opalaye to go from (Column a) to (Column (Nullable a)) with **records** in LEFT JOINs (and their corresponding Haskell types) -- without the need for defining yet another pTable.instance, right?

**Comment by tomjaguarpaw** [comment]
> Is there really a s use-case to keep building infra to support this?

That was just an example.  It could also be something much better. How about converting `PGText` into both `Lazy` and `Strict` `Text`.  The point is, there is not a one-to-one correspondence between PG types and Haskell types.  It's a many-to-many correspondence.

> And what's the use-case for converting PGJson into Text?

Um ... if you want to received JSON from the database and immediately send it over the wire?  Make up your own example ...

> What about having Opaleye define a standard set of conversions from either pgType->Haskell or vice versa? Where knowing one automatically identifies the other

That could be done.  It's what rel8 and silk do.  I have no especially strong objection to including it in Opaleye.  But let's acknowledge that it's not fully general.

> This also makes it possible for Opalaye to go from (Column a) to (Column (Nullable a)) with records in LEFT JOINs (and their corresponding Haskell types) -- without the need for defining yet another pTable.instance, right?

I don't think so.  How did you figure that?

**Comment by tomjaguarpaw** [comment]
Can you address the build error?

**Comment by tomjaguarpaw** [comment]
Oops, wrong thread.

**Comment by saurabhnanda** [comment]
Build error?

**Comment by tomjaguarpaw** [comment]
Yes, I posted on the wrong thread (and deleted the post).

**Comment by saurabhnanda** [comment]
> That could be done. It's what rel8 and silk do. I have no especially strong objection to including it in Opaleye. But let's acknowledge that it's not fully general.

I concede that there can be many cases where you would want to map PGType to different Haskell types. **But**, for the same column, would you really want to change the mapping on a per-query basis? Or, will it be like setting up the mapping once (while defining the tables). Which is my motivation for the following suggestion. What do you think about it?

> For cases where a String type is to be mapped to a custom ADT, that can be done while defining the Table itself. Thus eliminating the need to keep repeating yourself by providing a type-safety every time you use that column in a query. (And this also takes care of the two examples that you were mentioning).

So, there are some default PG=>Haskell mappings that Opaleye can ship with, eg:

* PGText => Text
* Numeric => Rational
* Integer => Int64
* etc

And if you are fine with these mapping, then you shouldn't really need to keep adding type annotations to your Opaleye queries. 

Further, if you want something like an `order_status TEXT` column to map to a `data OrderStatus = Confirmed | Cancelled | Refunded`, then you set it up once while defining the tables. Again, no need to keep adding type annotations to each call-site.

**Comment by saurabhnanda** [comment]
>> This also makes it possible for Opalaye to go from (Column a) to (Column (Nullable a)) with records in LEFT JOINs (and their corresponding Haskell types) -- without the need for defining yet another pTable.instance, right?

> I don't think so. How did you figure that?

This is related to the discussion at https://github.com/tomjaguarpaw/haskell-opaleye/issues/261#issuecomment-269304612 Basically using records with left-joins results in even more type-related boilerplate.

**Comment by saurabhnanda** [comment]
As for the main discussion related to this issue, the following two comments summarize it, right?

https://github.com/tomjaguarpaw/haskell-opaleye/issues/281#issuecomment-284229792 and https://github.com/tomjaguarpaw/haskell-opaleye/issues/281#issuecomment-284230113

I'll finish the tutorial accordingly.

**Comment by tomjaguarpaw** [comment]
> for the same column, would you really want to change the mapping on a per-query basis?

This is a good observation.  I doubt there would be much call for that.

> > >     This also makes it possible for Opalaye to go from (Column a) to (Column (Nullable a)) with records in LEFT JOINs (and their corresponding Haskell types) -- without the need for defining yet another pTable.instance, right?

> >   I don't think so. How did you figure that?

> This is related to the discussion at #261 (comment) Basically using records with left-joins results in even more type-related boilerplate.

Sure, I get the reference.  I don't understand how our discussion here helps though.

> As for the main discussion related to this issue, the following two comments summarize it, right?

> #281 (comment) and #281 (comment)

Yeah, they definitely provide a good summary.

**Comment by tomjaguarpaw** [comment]
Closing as stale.  Feel free to reopen if necessary.
