### ISSUE TITLE
Should groups of columns be called 'Column', 'Columns', 'Row', or something else?

### ISSUE THREAD

**Issue by patrickmn** [tomjaguarpaw/haskell-opaleye#286]
Currently, groups of columns are referred to in most places (e.g. the tutorials) like so:

```haskell
type FooColumn = Foo' (Column PGInt64) (Column PGText)
```

I'm curious what users think about this convention versus

```haskell
type FooColumns = Foo' (Column PGInt64) (Column PGText)
```

or

```haskell
type FooRow = Foo' (Column PGInt64) (Column PGText)
```

or something else?

(This is in reference to PR https://github.com/tomjaguarpaw/haskell-opaleye/pull/285)

**Comment by tomjaguarpaw** [comment]
I think `FooColumns` is a safe option.  `FooRow` might work but will need more consideration.

**Comment by tomjaguarpaw** [comment]
Migrated here: https://github.com/tomjaguarpaw/haskell-opaleye/issues/326
