### ISSUE TITLE
Circular recursive types?

### ISSUE THREAD

**Issue by reygoch** [tomjaguarpaw/haskell-opaleye#289]
Is there a way to nicely map circular recursive types to my database, so that data is lazily retrieved and memoized?

For example, let's say this is my schema :

```
create table category (
    id serial,
    name text,
);

create table item (
    id serial,
    category_id int,
    name text
);
```

And these are my Haskell data types :

```
data Category = Category
    { id :: Int
    , name :: Text
    , items :: [Item]
    }

data Item = Item
    { id :: Int
    , name :: Text
    , category :: Category
    }
```

Basically, when I retrieve category, I also want to get the list of items belonging to that category, and each of those items has reference to that category.

This is a very simple case, but I'm interested in how such relations could be expressed, and batched so that I don't retrieve whole database or get stuck in the loop if evaluation of `category` field is forced.

**Comment by tomjaguarpaw** [comment]
There's no such scheme implemented in Opaleye.  If you come up with a good way please let me know and I can consider adding it.
