### ISSUE TITLE
PrimQuery into separate library?

### ISSUE THREAD

**Issue by kanishka-azimi** [tomjaguarpaw/haskell-opaleye#290]
https://github.com/m4dc4p/haskelldb/pull/28#issuecomment-294364315
https://www.reddit.com/r/haskell/comments/5vxkih/current_libraries_providing_relational_algebra/de5ql24/

I am interested in moving forward with a prototype external DSL that allows users to specify queries, and a simple backend that generates mysql queries. I use HaskellDB's primquery type currently as the backbone. The next step is to switch to using opaleye's primquery type.

Feel free to close this if you are not interested in pursuing this. Thanks for considering.

**Comment by tomjaguarpaw** [comment]
In principle we could do this.  In practice I think it's better if you just fork Opaleye's PrimQuery.  That allows us to use it most effectively for our separate needs and we can look at extracting common parts in the future.

**Comment by kanishka-azimi** [comment]
Sounds good. Thanks for feedback.
