### ISSUE TITLE
Nullable Version for Query Arrows

### ISSUE THREAD

**Issue by xnmp** [tomjaguarpaw/haskell-opaleye#293]
It'd be useful to have a nullable version of QueryArrs so that I don't have to rewrite it every time I'm putting in nullable columns. Something like:

```haskell
nullQAExplicit :: J.NullMaker a nulla -> J.NullMaker b nullb -> QueryArr (a) (b) -> QueryArr (nulla) (nullb)
nullQAExplicit nA nB (O.QueryArr f) = O.QueryArr g where
  g (nulla0, pq, t) = (J.toNullable nB b0, pq', t')
    where 
      (b0, pq', t') = f' (nulla0, pq, t)
      f' = _
```

where ```f'``` gives a null if ```nulla0``` contains any nulls, otherwise if just gives the same result as ```f```. This should be really easy, can anyone help?

**Comment by tomjaguarpaw** [comment]
I don't understand how you would use this.  What do you mean?

**Comment by xnmp** [comment]
I just want to feed the result of a left join into a QueryArr.

**Comment by tomjaguarpaw** [comment]
What do you expect the `QueryArr` to do if it expects non-nullable columns but you give it a `NULL` column?

**Comment by xnmp** [comment]
Give a ```NULL``` column back.

**Comment by tomjaguarpaw** [comment]
In general I don't think this kind of thing is really going to be very
convenient.  I think you're probably better just adapting the QueryArr on a
case-by-case basis.

**Comment by xnmp** [comment]
It seems like the fact that there's no canonical way to turn a (say) ```UserColumn``` into a ```NullableUserColumn``` is the whole reason for the ```NullMaker``` business and why we need to annotate types so much in the first place.

**Comment by xnmp** [comment]
Is there a way to use type magic to do this? I tried 

```haskell
type family ColNul (a :: Column *) :: *
type instance ColNul ('Column a)  = Column (Nullable a)
```

But I get the error 

```
‘Column’ of kind ‘* -> *’ is not promotable
```

This kind of thing is all it would take to add type inference to left joins.

**Comment by xnmp** [comment]
This seems to work, although surely there's a reason why I shouldn't do it...

``` haskell
nullQA :: QueryArr (Column a) (Column b) -> QueryArr (Column (Nullable a)) (Column (Nullable b))
nullQA (O.QueryArr f) = O.QueryArr (O.first3 O.unsafeCoerceColumn . f . O.first3 O.unsafeCoerceColumn)
 ```

**Comment by tomjaguarpaw** [comment]
Closing as stale.  Feel free to reopen by providing more information.
