### ISSUE TITLE
Easy/efficient way to compose query restrictions?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#294]
I have a bunch of restrictions that need to be applied/composed conditionally. Two examples of these restrictions:

```
  applyNameRestriction :: T.Text -> Query Customer -> Query Customer
  applyNameRestriction t q = proc () -> do
    cust <- q -< ()
    restrict -< ((cust ^. fullName) .== (pgStrictText t))
    returnA -< cust

  applyBookingRestriction :: Int -> Query Customer -> Query Customer
  applyBookingRestriction cnt q = proc () -> do
    cust <- q -< ()
    restrict -< ((cust ^. bookingCount) .> (pgInt cnt))
    returnA -< cust
```

I believe, this will result in a nested query (i.e. sub-query), right? Is there a better way to compose these restrictions? 

Also, because we are passing the entire query to the function, it can do anything it wants with it. It would be great (although a secondary goal), if the type signature could somehow ensure that the "query transformation" is just a `restrict` clause.

**Comment by tomjaguarpaw** [comment]
> I have a bunch of restrictions that need to be applied/composed conditionally.

I don't see how those restrictions are conditional.  What do you mean?

> It would be great (although a secondary goal), if the type signature could somehow ensure that the "query transformation" is just a restrict clause.

Why don't you just use functions of type `Customer -> PGBool` then?

**Comment by saurabhnanda** [comment]
> I don't see how those restrictions are conditional. What do you mean?

Each of these restrictions depends on user-input. Think of an "advanced Search" form on the UI, which has a number of these restrictions. Only the restrictions enabled by the user are applied. 

> Why don't you just use functions of type Customer -> PGBool then?

And if a restriction/filter is not enabled, the corresponding function will always return a `True`?

On downside of this approach is that it would be hard to cater to complex restrictions, which need another table.to be joined if they happen to be applied.

**Comment by tomjaguarpaw** [comment]
> And if a restriction/filter is not enabled, the corresponding function will always return a True?

Correct.

> need another table.to be joined if they happen to be applied.

Can you give me an example of such a restriction?

In the meantime, you might find these better than what you already have in the sense that the types are more restrictive:

````haskell
  applyNameRestriction :: T.Text -> QueryArr Customer Customer
  applyNameRestriction t = proc cust -> do
    restrict -< ((cust ^. fullName) .== (pgStrictText t))
    returnA -< cust

  applyBookingRestriction :: Int -> QueryArr Customer Customer
  applyBookingRestriction cnt = proc cust -> do
    restrict -< ((cust ^. bookingCount) .> (pgInt cnt))
    returnA -< cust
````

**Comment by tomjaguarpaw** [comment]
> Can you give me an example of such a restriction?

In fact preferably a few.  It's very hard to generalise from zero examples and still quite tricky to generalise from one!

**Comment by tomjaguarpaw** [comment]
Is this still unresolved?

**Comment by saurabhnanda** [comment]
Thanks for the help @tomjaguarpaw We'll come back to this problem again in some time. If no approach works well, I'll reopen the issue.
