### ISSUE TITLE
Function analogous to fieldQueryRunnerColumn?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#298]
Is there any helper function analogous to `fieldQueryRunnerColumn` that can use whatever code has been written for the `ToField` instance or the `ToJSON` instance?

Sample code:

```
data EventOperation = Insert | Update | Delete
  deriving (Eq, Show, Generic)

instance FromJSON EventOperation where
  parseJSON = genericParseJSON $ (aesonPrefix snakeCase){constructorTagModifier=(camelTo2 '_')}

instance ToJSON EventOperation where
  toJSON = genericToJSON $ (aesonPrefix snakeCase){constructorTagModifier=(camelTo2 '_')}

instance QueryRunnerColumnDefault EventOperation EventOperation where
  queryRunnerColumnDefault = fieldQueryRunnerColumn

instance FromField EventOperation where
  fromField = fromJSONField

instance Default Constant EventOperation (Column EventOperation) where
  def = undefined -- WHAT'S THE EASIEST WAY TO WRITE THIS?
``

**Comment by saurabhnanda** [comment]
Btw, this is the best I've got till now, and it's **very ugly**

```
instance Default Constant EventOperation (Column EventOperation) where
  def = Constant converter
    where
      converter x = let withQuotes = toS $ encode x
                    in (IPT.literalColumn . HPQ.StringLit) $ P.take ((P.length withQuotes) - 2) $ P.drop 1 $ withQuotes
```

**Comment by tomjaguarpaw** [comment]
Before we go any further, what you have is neater as

````Haskell
withoutQuotes s = P.take (P.length s - 2) (P.drop 1 s)
...
converter = IPT.literalColumn . HPQ.StringLit . withoutQuotes . toS . encode
````

**Comment by tomjaguarpaw** [comment]
Secondly, I don't understand what you're doing.  Are you trying to store the JSON representation of `EventOperation` in the database?  Why?  Why not some enumeration?

**Comment by saurabhnanda** [comment]
> Secondly, I don't understand what you're doing. Are you trying to store the JSON representation of EventOperation in the database? Why? Why not some enumeration?

Not trying to store a JSON representation in the DB *per se*. `EventOperation` is stored as `PGText`, and I already have the ToJSON instance which is doing a similar conversion. There is no reason for the Text representation of `EventOperation` to be different between DB & JSON.

**Comment by tomjaguarpaw** [comment]
It seems extremely clunky to take the `ToJSON` representation and then strip the quotes off it.  Instead I'd suggest

````Haskell
instance ToJSON EventOperation where
    toJSON s = "\"" ++ show s + "\""
````

and for `Default Constant EventOperation (Column EventOperation)` use a combination `show`, `pgString` and `unsafeCoerceColumn`.  I haven't checked this, but it's probably

````Haskell
converter = unsafeCoerceColumn . pgString . show
````

**Comment by tomjaguarpaw** [comment]
(NB `pgString = IPT.literalColumn . HPQ.StringLit` which already makes your earlier code sample a lot nicer)

**Comment by saurabhnanda** [comment]
> It seems extremely clunky to take the ToJSON representation and then strip the quotes off it. Instead I'd suggest

Haskell<>Text conversion is already covered by the ToJSON/FromJSON instances. One usually doesn't fiddle with `Show` instances because god knows what else that might impact.

Do you know which function should be used to encode a string value (via Aeson) without the surrounding quotes?

**Comment by saurabhnanda** [comment]
Also, taking a cue from PG-Simple itself. There's a `fromJSONField` and `toJSONField` to help define `FromField` and `ToField` instances. Would it make sense to have Opaleye follow the same convention?

**Comment by tomjaguarpaw** [comment]
> Haskell<>Text conversion is already covered by the ToJSON/FromJSON instances

But it isn't!  Haskell to *JSON* is covered by the `ToJSON` instance.  Haskell to text (or `Text` or `String`) is something else entirely and may or may not happen to look similar by coincidence.

> One usually doesn't fiddle with Show instances because god knows what else that might impact.

My suggestion does not involve fiddling with a `Show` instance.  It involves *using* a `Show` instance.

> Do you know which function should be used to encode a string value (via Aeson) without the surrounding quotes?

There probably isn't one and there shouldn't be one.  There's no guarantee that the result of `toJSON` is a JSON string rather than an object, array or numeric literal.  That's exactly why I'm suggesting a different approach.

> Also, taking a cue from PG-Simple itself. There's a fromJSONField and toJSONField to help define FromField and ToField instances. Would it make sense to have Opaleye follow the same convention?

Opaleye already has `pgJSON` and `QueryRunnerColumnDefault PGJson String`.  You can use `dimap`, [`queryRunnerColumn`](https://hackage.haskell.org/package/opaleye-0.5.3.0/docs/Opaleye-RunQuery.html#v:queryRunnerColumn), `unsafeCoerceColumn`, `fromJSON` and `toJSON` to do what you want.  If you find a recipe that you are using more than three times let me know and I'll consider adding it to Opaleye.

However, as you will see from my earlier comments I really don't think you should be using `toJSON` to store your values in a Postgres `text` column.  Why not use a Postgres `json` column instead?

**Comment by saurabhnanda** [comment]
I just realised that `fromJSONField` doesn't do what I thought it did. It read the field from the DB as `Value` first and then converts it to a Haskell value. I tried running this code and it throws the following runtime error:

```
Exception: Incompatible {errSQLType = "varchar", errSQLTableOid = Just (Oid 78687), errSQLField = "result9_2", errHaskellType = "Value", errMessage = ""}
```

I think what I need is https://stackoverflow.com/questions/44193630/how-to-customise-show-read-instances-on-the-lines-of-fromjson-tojson

**Comment by tomjaguarpaw** [comment]
There are quite a few ways you could approach something like this, but I'll reiterate my previous comment because I don't understand why you're not going that way: Why not use a Postgres `json` column instead?

**Comment by tomjaguarpaw** [comment]
Is this issue still unresolved?

**Comment by saurabhnanda** [comment]
Yes. I'm trying the approach given at https://stackoverflow.com/a/44195842/534481 to come up with generic methods to convert sum types with zero constructors to textual representation, and back. Would like to post my solution here so that it can help others as well.

**Comment by tomjaguarpaw** [comment]
Did you make any progress on this?  If so, please report back.  If not, I'll close the issue as stale.

**Comment by tomjaguarpaw** [comment]
Closing as stale.  Feel free to reopen if neccessary.
