### ISSUE TITLE
Allow inserting multiple values at once

### ISSUE THREAD

**Issue by hesselink** [tomjaguarpaw/haskell-opaleye#30]
Postgres allows you to insert multiple values in a single insert statement:

```
silk=# create table t (id integer primary key not null);
CREATE TABLE
silk=# insert into t values (1), (2), (3);
INSERT 0 3
```

It would be nice if this could also be done from Opaleye, but it looks like currently you can only insert a single row at a time.

**Comment by tomjaguarpaw** [comment]
> it looks like currently you can only insert a single row at a time

You're right that this should be fixed.  I expect it to be fairly straightforward so hopefully I can get out a fix soon.

**Comment by tomjaguarpaw** [comment]
Please see if `runInsertMany` suits your needs.

https://github.com/tomjaguarpaw/haskell-opaleye/commit/1ed9ee3d1947771cce0da2538efed3bc9c498953

**Comment by hesselink** [comment]
That looks perfect, I'll try it out in a week and let you know. Looking at the diff, it seems you could completely remove the `SqlInsert` constructor (or change it to have the non-empty list) since it's just a special case of `SqlInsertMany`, right? It compiles to the same SQL.

**Comment by tomjaguarpaw** [comment]
I've thought of a bug that this will have to do with defaulting columns.  Hopefully I'll fix it before you try it out!

**Comment by tomjaguarpaw** [comment]
OK, the bug I thought of should be fixed now, so looking forward to hearing how you get on with this!

**Comment by tomjaguarpaw** [comment]
Feel free to reopen if the above-mentioned patch does not suit your needs.
