### ISSUE TITLE
Why doesn't Opaleye compile on HEAD?

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#302]
Opaleye doesn't compile on HEAD.  Some complaint about needing time-1.8.

https://travis-ci.org/tomjaguarpaw/haskell-opaleye/jobs/238495263

**Comment by tomjaguarpaw** [comment]
The problem seems to be that no version of `unix` on Hackage supports `base-4.10`.  `unix-2.7.2.2` seems to come from @hvr's Ubuntu repository but is built against `time-1.8`.  I guess I should just bump Opaleye's dependency.

**Comment by tomjaguarpaw** [comment]
I think there was some reason I didn't want to bump `time`.  Something to do with `time-local-compat`.  Anyway, we'll soon see.

**Comment by tomjaguarpaw** [comment]
There appears to be a `time` bug the fix for which hasn't made it into @hvr's Ubuntu HEAD packages:

https://github.com/haskell/time/commit/c29513e6f79f6f8cefc69663c34e780570bef34a

**Comment by tomjaguarpaw** [comment]
@hvr's HEAD packages are on 1.8.0.1 (as you can see in the log from https://travis-ci.org/tomjaguarpaw/haskell-opaleye/jobs/238495263) and the fix is in 1.8.0.2.

**Comment by hvr** [comment]
Fwiw, I've triggered a new snapshot build of `ghc-head`, but I'm afraid it will still use 1.8.0.1 (it looks like GHC hasn't yet updated its `time` submodule to include the `time` fix)

**Comment by tomjaguarpaw** [comment]
OK, thanks for the update.

**Comment by tomjaguarpaw** [comment]
Looks like it's fine now

https://github.com/tomjaguarpaw/haskell-opaleye/commit/1ed1d4448ddacb07aa2cbecb89fc346c68b0bb04

https://travis-ci.org/tomjaguarpaw/haskell-opaleye/jobs/248263657
