### ISSUE TITLE
Full Monadic API

### ISSUE THREAD

**Issue by xnmp** [tomjaguarpaw/haskell-opaleye#306]
Haskell Relational Record (HRR) uses a monadic API for its queries. As far as I know, this only fails when you start aggregating, because the columns that are there before aggregation are "destroyed" and can't be referred to anymore. 

My question is: what's stopping us from treating tables as if they were Haskell lists? I've written a Monad instance for QueryArr but of course it falls apart when you start aggregating. But surely if it's syntactically correct for lists then it should work for queries too? One could write something like the following to return the first visit time for each user:

```haskell
visits user = filterQ (\v -> v.user_id .== user.user_id) visits

firstvisits = do
  u <- users
  return $ minQ (fmap visit_timestamp $ visits u)
```

where minQ just becomes a function 

```haskell
minQ :: PGOrd a => Query a -> a
```

This would translate directly into:

```sql
select min(transaction_timestamp)
from users u, visits v
where u.user_id = v.visit_id
group by u.user_id
```

Something that can do this already is PonyORM for Python (https://ponyorm.com/), but it lacks composability. As far as I can see, the only problem at the moment is that the query generator has to be smart enough to figure out that when you bind a function that aggregates, you need to change the filter condition to a group by. Would this require a complete rehaul of the guts of Opaleye? It'd be helpful enough for me to write myself, but I don't want to reinvent the wheel.

**Comment by tomjaguarpaw** [comment]
Firstly, It's very important to note that an `Arrow` API does not limit the queries that can be expressed.  There are no valid Opaleye queries that could be written monadically but that cannot be written with `Arrow`. (In general this is not true, of course, but with Opaleye it is).

> because the columns that are there before aggregation are "destroyed" and can't be referred to anymore

That's not the reason.  The reason is that in SQL subqueries cannot depend on columns from previous inner joins. For example, you can't write

````sql
(SELECT foo FROM table1)
INNER JOIN
(SELECT bar FROM table2
WHERE foo = bar)
````

When there is no aggregation we can write this as

````sql
((SELECT foo FROM table1)
INNER JOIN
(SELECT bar FROM table2))
WHERE foo = bar
````

But if there is aggregation, things are more difficult, for example

````sql
(SELECT foo FROM table1)
INNER JOIN
(SELECT min(bar) FROM table2
WHERE foo = quux)
````

A monadic API makes it difficult to avoid creating this invalid code.  If you can combine functions of type `Column a -> Query b` into your SQL then it's hard to prevent injecting a column reference into somewhere it shouldn't be allowed.

Opaleye chooses to not have a monadic API since, as noted above, there is no reduction in expressivity.  On the other hand, [Selda](http://hackage.haskell.org/package/selda-0.1.7.0/docs/Database-Selda.html#g:5) has a monadic API but prevents invalid column leakage with a phantom type parameter.

There are basically three options

1. Arrow API: Full expressivity but unfamiliar.

2. Naïve monadic API: More familiar but can write crashing queries, and no gain in expressivity.

3. Selda-style monadic API: More familiar and cannot write crashing queries, but no gain in expressivity.

Given that option 3 exists, option 2 is basically pointless.  I'm tempted to eventually migrate Opaleye to option 3 but given that it's only a question of familiarity not correctness it won't be for a couple of major versions.

**Comment by xnmp** [comment]
I don't quite understand that there's no reduction in expressivity, other than that any query you can write with a monadic API you can also write with an Arrow API. In my example above you can incorporate aggregation naturally into a do block, and the `Query` actually does behave as if it were an in-memory list, which is extremely intuitive. 

Going back to the example, suppose we have a function for the first visit of a user to the website

```haskell
firstvisit :: Column Int -> Query (Column LocalTime)
firstvisit uid = aggregate min $ fmap visit_timestamp (User.query >>> where_ (\v -> v.user_id .== uid))
```

which generates the SQL:

```sql
SELECT min(visit_timestamp) 
FROM visittable
where visitable.user_id = uid
```

I'm just asking if there's a way so that when we bind it to a whole table of users (`userttable >>= firstvisit`), the SQL generator is smart enough to make this instead:

```sql
SELECT min(visit_timestamp) 
FROM visittable, usertable
where visitable.user_id = usertable.user_id
group by usertable.user_id
```

**Comment by tomjaguarpaw** [comment]
> I don't quite understand that there's no reduction in expressivity, other than that any query you can write with a monadic API you can also write with an Arrow API.

Right, that's what I mean.  I don't mean "it's equally convenient to type out the code".

> In my example above you can incorporate aggregation naturally into a do block, and the Query actually does behave as if it were an in-memory list,

Does it actually behave like that?  Are you actually generating SQL?  If so, can you show me how?  In general SQL is a very much restricted subset of operations that you can perform on lists, and not all list operations are expressible in it.

> Going back to the example ...

This is a good suggestion and I think there must either be a simple reason it doesn't work, or it will work!  Let me have a think about it ...

**Comment by xnmp** [comment]
Not all list operations are expressible - but it seems like everything that we need is covered except for aggregation where we still need to look at the query as a whole instead of thinking one element at a time like we can with QueryArrs. I'm not generating SQL but I'm saying that it'd be nice if that hypothetical code did generate valid SQL. 

Even better would be if `firstvisit` was a `Column Int -> Column LocalTime`, and you'd be able to write `visit.visit_timestamp .== user.firstvisit` as a `Column Bool`, which would generate a correlated subquery.

Pony ORM already does something like this, for example if I write

```python
select((u.user_id, min(u.visits.visit_timestamp)) for u in User)
```

Then the generated SQL is 

```sql
SELECT "u"."user_id", MIN("visit"."visit_timestamp")
FROM "users" "u"
  LEFT JOIN "visits" "visit"
    ON "u"."user_id" = "visit"."user_id"
GROUP BY "u"."user_id"
```

However its default behaviour is by grouping by all columns that aren't aggregated, so it's not really understanding what's happening. 

If I write 

```
select(v.page_name for v in visits if v.visit_timestamp = min(v0.timestamp for v0 in v.user_id.visits))
```

Then I get

```sql
SELECT DISTINCT "v"."page_name"
FROM "visits" "v"
WHERE "v"."visit_timestamp" = (
    SELECT MIN("v0"."visit_timestamp")
    FROM "visits" "v0"
    )
```

So here `min` actually is behaving like a function that takes a list and returns the minimum.

**Comment by tomjaguarpaw** [comment]
> Even better would be if firstvisit was a Column Int -> Column LocalTime

Yeh, but that's extremely misleading because it looks like it's "pure" when in fact it depends on the state of the database.

**Comment by tomjaguarpaw** [comment]
Let's have another look at your example

````haskell
firstvisit :: Column Int -> Query (Column LocalTime)
firstvisit uid = aggregate min $ fmap visit_timestamp (User.query >>> where_ (\v -> v.user_id .== uid))
````

For the purposes of this comment let's express this as

````haskell
firstvisit :: Column Int -> Query (Column LocalTime)
firstvisit uid = aggregate min $ proc () -> do
    u <- User.query -< ()
    restrict -< (u.user_id .== uid)
    returnA -< visit_timestamp u
````

If we want a monadic list version we can write

````haskell
firstvisit :: Int -> [LocalTime]
firstvisit uid = minimum $ do
    u <- User.query
    guard (u.user_id .== uid)
    return (visit_timestamp u)
````

Your claim that the postulated monadic Opaleye version would behave like the list code, but I've now realised why it won't.  Suppose that `firstvisit 1 = ["12pm today"]` and `firstvisit 2 = ["1pm yesterday"]`.  Now suppose `usertable = [1, 2]`.  Then `usertable >>= firstvisit = ["12pm today", "1pm yesterday"]`.

By contrast, you want the monadic Opaleye version to act like

````sql
SELECT min(visit_timestamp) 
FROM visittable, usertable
where visitable.user_id = usertable.user_id
group by usertable.user_id
````

Note that it will only ever return one row, and in particular `usertable >>= firstvisit = ["1pm yesterday"].

The list monad has the nice property that `(t1 ++ t2) >>= f = (t1 >>= f) ++ (t2 >>= f)` (indeed, by definition).  Opaleye Arrows have the corresponding property that `(union t1 t2) >>> f = union (t1 >>> f) (t2 >>> f)`.  If you switch to a monadic API you end up allowing things of the form `a -> Query b` to be aggregated, not just things of the form `Query b`.  It turns out to be very hard to preserve those nice union semantics with the former.

Ultimately, to get the behavior you are looking for, you take

````haskell
firstvisit :: QueryArr (Column Int) (Column LocalTime)
````

turn it into

````haskell
firstvisitQ :: Query (Column Int) -> Query (Column LocalTime)
firstvisitQ q = q >>> firstvisit
````

and then aggregate it

````haskell
firstvisitusers :: Query (Column LocalTime)
firstvisitusers = aggregate min (firstVisitQ usertable)
````

and nothing of value was lost!

**Comment by xnmp** [comment]
```
SELECT min(visit_timestamp) 
FROM visittable, usertable
where visitable.user_id = usertable.user_id
group by usertable.user_id
```

This query gives more than one row. It still groups by `user_id` even though you aren't selecting the `user_id`. 

I don't see how `a-> Query b` can be aggregated. My understanding is that basically the one thing you can't do is refer to a column inside an aggregate query when you're outside of the aggregate query. Selda also prevents you from doing the opposite, even though it would be legal (giving a correlated subquery), but it prevents nothing else. 

Also I don't think `firstvisit` can be made into a `QueryArr` at all, this is the main problem I'm trying to address.

**Comment by tomjaguarpaw** [comment]
> Also I don't think firstvisit can be made into a QueryArr at all, this is the main problem I'm trying to address.

What's wrong with `firstvisitQ` as I defined above?

**Comment by xnmp** [comment]
How does one define 

``` firstvisit :: QueryArr (Column Int) (Column LocalTime)```?

You can't aggregate a `QueryArr` so the below doesn't work:

```
firstvisit = aggregate minGrouped $ proc uid0 → do
    vis0 ← Vis.query ⤙ ()
    restrict ⤙ vis0.user_id .== uid0
    returnA ⤙ vis0.visit_timestamp
```

**Comment by tomjaguarpaw** [comment]
> I don't see how `a-> Query b` can be aggregated.

It can be aggregated by composing it with `aggregate`.

**Comment by tomjaguarpaw** [comment]
> How does one define
> 
> `firstvisit :: QueryArr (Column Int) (Column LocalTime)`?

One doesn't define it, neither in Opaleye nor in SQL.  Instead one uses something in the style of `firstvisitQ`.  Is `firstvisitQ` insufficient for your purposes?

**Comment by xnmp** [comment]
How does one define `firstVisitQ`? It's defined in terms of `firstvisit`.

**Comment by tomjaguarpaw** [comment]
Oh sorry, I see why you're confused!  I meant something like "`visits`" which gets all visits, not `firstvisit`.  Let's do this from scratch:

````Haskell
visits :: QueryArr (Column Int) (Column LocalTime)
visits = proc uid0 → do
    vis0 ← Vis.query ⤙ ()
    restrict ⤙ vis0.user_id .== uid0
    returnA ⤙ vis0.visit_timestamp

visitsQ :: Query (Column Int) -> Query (Column LocalTime)
visitsQ q = q >>> visits

firstvisitQ :: Query (Column Int) -> Query (Column LocalTime)
firstvisitQ = aggregate min . visitsQ
````

**Comment by tomjaguarpaw** [comment]
(Unrelated question: What are you using that `vis0.visit_timestamp` works?)

**Comment by xnmp** [comment]
Then `firstvisitQ tableofusers` gets the first visit of all the users, not the first visits per user. You have to do something like:

```haskell
visits :: QueryArr (Column Int) (Column Visit)
visits = proc uid0 → do
    vis0 ← Vis.query ⤙ ()
    restrict ⤙ vis0.user_id .== uid0
    returnA ⤙ vis0

visitsQ :: Query (Column Int) -> Query (Column Visit)
visitsQ q = q >>> visits

firstvisitQ :: Query (Column Int) -> Query (Column LocalTime)
firstvisitQ = fmap (\(a,b) -> a) . aggregate (liftA2 (,) (lmap user_id groupBy_) (lmap visit_timestamp min)) . visitsQ
```

which is quite verbose, and you have to define it separately to the function getting the first visit for a single user, whereas in my example you get it for free. 

For the question: I just made `(.) = flip ($)` so that the syntax looks more like SQL. For function composition I have UnicodeSyntax and the little circle. 

Also, is there a way to have a `returnAgg` or something so that I can just write 
```
visits = proc () → do
    uid0 ← fmap user_id User.query ⤙ () 
    vis0 ← Vis.query ⤙ ()
    restrict ⤙ vis0.user_id .== uid0
    returnAgg ⤙ (groupby (vis0.user_id), min (vis0.visit_timestamp))
```
instead of 
```
visits = aggregate (liftA2 (,) (lmap user_id groupBy_) (lmap visit_timestamp min)) $ proc () → do
    uid0 ← fmap user_id User.query ⤙ () 
    vis0 ← Vis.query ⤙ ()
    restrict ⤙ vis0.user_id .== uid0
    return ⤙ ((vis0.user_id), min (vis0.visit_timestamp))
```

**Comment by tomjaguarpaw** [comment]
> firstvisitQ tableofusers gets the first visit of all the users, not the first visits per user

Well sure, but the example you gave me was `userttable >>= firstvisit`.  If you would like me to explain a different example then I'll be happy to.

> Also, is there a way to have a `returnAgg`

No, not in Opaleye.  Selda's aggregate is more like this though.

**Comment by tomjaguarpaw** [comment]
Oh, wait, I misunderstood again.  Yes, you need to `groupBy`.  But with Haskell's abstraction power I don't think this is too bad.  I'm sure you can rewrite your `firstvisitQ` to be neater.

**Comment by xnmp** [comment]
But `userttable >>= firstvisit` is meant to get the first visits for every user. This is exactly what this SQL query gives:

```
SELECT min(visit_timestamp) 
FROM visittable, usertable
where visitable.user_id = usertable.user_id
group by usertable.user_id
```

It does NOT give one row.

**Comment by tomjaguarpaw** [comment]
Yes, see my later comment.

**Comment by tomjaguarpaw** [comment]
OK, now I understand more clearly what you are trying to do.

I take back my comment about the semantics not being the same as the list semantics, because for what you want they are indeed the same.  However, in general, no, you can't do this with a monad.  You need to be able to group by all the columns returned by `usertable`  but you can't know parametrically what columns it contains.  You'd have to restrict the type of `>>=` to something like `GroupByAble a => Query a -> (a -> Query b) -> Query b` which would put it out of the scope of Haskell's `Monad`.

**Comment by xnmp** [comment]
Couldn't we just tweak the way `QueryArr` works? We just have to check if the `PrimExpr` inside the `Column` is an `Aggregate`... or something? Right?

**Comment by tomjaguarpaw** [comment]
I don't think so.  If you want a research project feel free to give it a try though!

**Comment by tomjaguarpaw** [comment]
If you'd like more help writing queries with Opaleye the way it is then I'm happy to help.

If you'd like to explore a new monadic API for Opaleye then you are welcome but it's a rather open-ended research project and I'm afraid I don't have time to join you.

**Comment by xnmp** [comment]
I have a dream for an API so composable, type safe, concise, and intuitive that nobody ever needs to write SQL again.

**Comment by tomjaguarpaw** [comment]
Me too!  But then I have the same dream for programming languages ...

**Comment by tomjaguarpaw** [comment]
One good way to turn the dream into reality is to consider what the denotational semantics are of your API.  One good way to judge if an API has a good chance of turning into your dream is to ask the author what its denotational semantics are.

**Comment by xnmp** [comment]
Perhaps it'd be easier if finding the min was just interpreted as joining to a table of all the mins. So the bind operation I talked about before would turn the first visits for each user query into this:

```sql
select visit_timestamp
from 
(SELECT user_id, min(visit_timestamp) visit_timestamp
FROM visittable
group by user_id) firstvisits, usertable 
where firstvisits.user_id = usertable.user_id
```

We can already do this in Opaleye by writing 

```haskell
firstvisit = joinOn (aggregate (lmap groupBy_ (view _1) &&& lmap min_ (view _2) $ visittable >>> arr user_id &&& arr visit_timestamp) (view _1)
```

But this is a lot more verbose than the "ideal" semantics matching those for a list, where `min_` is just a function `min_ :: Ord a => Query a -> a`, whence `firstvisit = min . visits`.

**Comment by tomjaguarpaw** [comment]
Closing as stale.  Feel free to reopen if necessary.
