### ISSUE TITLE
Cannot specify ordering of NULLs in ORDER BY

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#31]
PostgreSQL allows one to specify whether `null` should be sorted before or after non-`null` values: http://www.postgresql.org/docs/9.4/static/queries-order.html. Could Opaleye be extended to support this?

**Comment by tomjaguarpaw** [comment]
Yes, I think this should be an easy extension to @hesselink's sorting code.  I'll give it a go when I have some time.  Alternatively anyone else is welcome to bash it out.

**Comment by tomjaguarpaw** [comment]
Can you check out the latest master?

https://github.com/tomjaguarpaw/haskell-opaleye/commit/26b0d597a39a75327b5a1a83932b3f4df6bb5540

**Comment by tomjaguarpaw** [comment]
Feel free to reopen if the above-mentioned patch does not suit your needs.
