### ISSUE TITLE
Easy ad-hoc querying of subsets of columns from the same underlying table?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#310]
Suppose I have a table with a large number of columns, where the column usage is highly correlated. I.e. the list of columns can be divided into subgroups that are almost always used together.

For example, consider a table called `customers` with the following fields:

```
id, createdAt, updatedAt -- all are NOT NULL
name, email, phone -- all are NOT NULL
address, zip, city, country -- with a CHECK CONSTRAINT saying that either all should be NULL, or all should be NOT NULL
cardLastDigits, cardToken -- with a CHECK CONSTRAINT saying that either all should be NULL, or all should be NOT NULL
```

Instead of defining a single `Customer` record with all the fields, where a bunch of them will be forced to be `Maybe`, can we define something like the following...

```
data CustomerDB = CustomerDB
  {
    custId :: CustomerId
  , custCreatedAt :: UTCTime
  , custUpdatedAt :: UTCTime
  }

data CustomerEssentials = CustomerEssentials
  {
    custName :: Text
  , custEmail :: Text
  , custPhone :: Text
  }

data CustomerProfile = CustomerProfile
  {
    custAddress :: Text
  , custZip :: Text
  , custCity :: Text
  , custCountry :: Text
  }
  
data CustomerCardDetails = CustomerCardDetails
  {
    custCardLastDigits :: Text
  , custCardToken :: Text
  }
```

... and have an easy way to query the underlying table in any combination, i.e.

```
funkyQuery2 :: a -> b -> c -> (CustomerDB, CustomerEssentials)
funkyQuery2 :: a -> b -> c -> (CustomerDB, CustomerCardDetails)
funkyQuery3 :: a -> b -> c -> (CustomerDB, CustomerEssentials, CustomerCardDetails)
funkyQuery4 :: a -> b -> c -> (CustomerDB, CustomerEssentials, CustomerProfile, CustomerCardDetails)
```

There is another advantage of being able to do this. Almost every table needs to be mapped to two variants of basically the same record on the Haskell side -- one variant with `(id, createdAt, updatedAt)` and one without. This structure will allow us to very easily have record creation functions with the following pattern:

```
createMyRecord :: MyRecordEssentials -> IO (MyRecordDB, MyRecordEssentials)
```

Have I been able to explain this properly?

**Comment by tomjaguarpaw** [comment]
Do you mean that if `CustomerEssentials` is null then `CustomerProfile` must be null too?  And if `CustomerProfile` is null then `CustomerCardDetails` must be null too?

**Comment by saurabhnanda** [comment]
> Do you mean that if CustomerEssentials is null then CustomerProfile must be null too? And if CustomerProfile is null then CustomerCardDetails must be null too?

Once a record is in the DB, `CustomerEssentials` can never be null. However, all the columns in `CustomerProfile` will be null or not null together. Same for `CustomerCardDetails`. There is no relationship between `CustomerProfile` and `CustomerCardDetails`. The only relationship is **within all the fields** of `CustomerProfile` and **within all the fields** of `CustomerCardDetails`

**Comment by tomjaguarpaw** [comment]
I don't understand, because the schema says

    name, email, phone -- with a CHECK CONSTRAINT saying that either all should be NULL, or all should be NOT NULL

**Comment by saurabhnanda** [comment]
Sorry, copy-paste error.

**Comment by saurabhnanda** [comment]
Changed the original description with the correct text.

**Comment by tomjaguarpaw** [comment]
Got it, thanks.  What do you expect this to do?

> funkyQuery3 :: a -> b -> c -> (CustomerDB, CustomerEssentials, CustomerCardDetails)

What if there are no customer card details?

**Comment by saurabhnanda** [comment]
>> funkyQuery3 :: a -> b -> c -> (CustomerDB, CustomerEssentials, CustomerCardDetails)

> What if there are no customer card details?

**Comment by saurabhnanda** [comment]
> What if there are no customer card details?

Hmm... in that case the signature would have to be - 

> funkyQuery3 :: a -> b -> c -> (CustomerDB, CustomerEssentials, Maybe CustomerCardDetails)

**Comment by tomjaguarpaw** [comment]
Right, I think so.  Don't you want the fully general form of this function to be

````Haskell
funkyQuery4 :: a -> b -> c -> (CustomerDB, CustomerEssentials, Maybe CustomerProfile, Maybe CustomerCardDetails)
````

**Comment by tomjaguarpaw** [comment]
This issue looks stale so I'm closing it.  Feel free to reopen if necessary.
