### ISSUE TITLE
How to get the SQL generated for insert, delete, and update statements?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#311]
Tried looking at https://www.stackage.org/haddock/nightly-2017-03-01/opaleye-0.5.3.0/Opaleye-Sql.html and https://www.stackage.org/haddock/nightly-2017-03-01/opaleye-0.5.3.0/Opaleye-Manipulation.html , but couldn't find what I was looking for.

**Comment by tomjaguarpaw** [comment]
You can use the `arrange...` functions in the `Manipulation` module you linked above.  It's not really supported and the interface is a bit odd.  If you really need a permanent supported version of this let's discuss your use case and I'll work out what we can do.

**Comment by tomjaguarpaw** [comment]
This issue looks stale so I'm closing it.  Feel free to reopen if necessary.
