### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by ocharles** [tomjaguarpaw/haskell-opaleye#313]
My `rel8` project could be released, but it depends on a couple of changes to opaleye that are only in Git.

**Comment by tomjaguarpaw** [comment]
Sure!  Please check if this is satisfactory for you, and if so close the issue.  If not, let me know what else you need.

https://hackage.haskell.org/package/opaleye-0.5.3.1

**Comment by ocharles** [comment]
Thanks, I'll try and check that next week.

**Comment by tomjaguarpaw** [comment]
Any update?

**Comment by tomjaguarpaw** [comment]
Closing as stale.  Feel free to reopen if necessary.
