### ISSUE TITLE
Why export the contructors of Table?

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#317]
I don't know why I made the constructors of `Table` accessible.  Maybe just a lack of foresight.

https://github.com/tomjaguarpaw/haskell-opaleye/blob/dbc149d8a603499442b249ffa2094e1256ff8ef8/src/Opaleye/Table.hs#L61

Can anyone chip in with a good reason to keep them accessible?  Or should I hide them?

Maybe @ocharles @k0001 @bergmark @hesselink @tstat?

**Comment by bergmark** [comment]
We are using the constructor in our TH here https://github.com/silkapp/girella/blob/f2fbbaaa2536f1afc5bc1a493d02f92cec81da18/src/Girella/TH/Table.hs#L126

**Comment by tomjaguarpaw** [comment]
@bergmark: I'm planning to replace `Table` and `TableWithSchema` with functions `table` and `tableWithSchema` which I think will be sufficient for you.  If not then the constructors will be available from the `Internal` module anyway.

**Comment by ocharles** [comment]
I'm sure I use these in rel8, but those smart constructors sound fine.

**Comment by hesselink** [comment]
I think with smart constructors and an Internal module, there should not be any issues.
