### ISSUE TITLE
Module ‘Opaleye’ does not export ‘tableColumn’

### ISSUE THREAD

**Issue by vimalloc** [tomjaguarpaw/haskell-opaleye#330]
Hey guys, new user here so sorry in advance if I am just missing something.

I'm trying to get something going using the [basic tutorial](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/Doc/Tutorial/TutorialBasic.lhs) with `opaleye == 0.5.4.0`, and am running into the following errors:

```
Module ‘Opaleye’ does not export ‘table’
Module ‘Opaleye’ does not export ‘tableColumn’
```

Based on the git log for the basic tutorial, it looks like those were recently added. Are they not in the 0.5.4.0 version of opaleye? Or am I just doing something stupid here?

Thanks!

**Comment by vimalloc** [comment]
I looked through the git log on that tutorial and in my project replaced `tableColumn` with `required`, and `table` with `Table` (importing `Table(Table)` instead of `Table` and `table`). Seems to be happy now.

**Comment by tomjaguarpaw** [comment]
Opaleye `master` is different from 0.5.4.0.  If you want the 0.5.4.0 tutorial, it is here

https://github.com/tomjaguarpaw/haskell-opaleye/blob/version_0.5.4.0/Doc/Tutorial/TutorialBasic.lhs

(but it will probably just say what you already discovered yourself).

**Comment by vimalloc** [comment]
Thanks. :)

For what it's worth, the link to this page on hackage points to master instead of the v0.5.4 tag. Not a huge deal, but I think that's what tripped me up. 

Thanks for all hard work on this project!
