### ISSUE TITLE
QueryRunnerColumnDefault instance for PGTimestamptz to ZonedTime conversion

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#331]
I've been sucked into time-related arithmetic yet again, so please let me know if this is just my confused brain talking. 

Should `PGTimestamptz` be mapped to [`ZonedTime`](https://www.stackage.org/haddock/lts-9.0/time-1.6.0.1/Data-Time-LocalTime.html#t:ZonedTime) which is "A local time together with a TimeZone". If we are converting a `PGTimestamptz` to a `UTCTime`, aren't we throwing-away the TZ information on the Haskell-side?

**Comment by saurabhnanda** [comment]
For anyone else who's struggling with these issues, here's a helpful code snippet to treat a `PGTimestamp` as a `UTCTime` if you need it for a badly designed database:

```
import Data.Time.LocalTime (localTimeToUTC, utc)

instance QueryRunnerColumnDefault PGTimestamp UTCTime where
  queryRunnerColumnDefault = (localTimeToUTC utc) <$> (queryRunnerColumnDefault :: QueryRunnerColumnDefault PGTimestamp LocalTime)
```

**Comment by tomjaguarpaw** [comment]
This looks like an oversight on my part.  Could you file and issue and/or
submit a PR?

The list of FromField instances gives a good basis of correspondances to
work from.

    https://hackage.haskell.org/package/postgresql-simple-0.5.3.0/docs/Database-PostgreSQL-Simple-FromField.html#t:FromField

**Comment by saurabhnanda** [comment]
Have changed the title of this issue. PR can be submitted against this itelf.
