### ISSUE TITLE
Default Constant a (Maybe (Column a)) ?

### ISSUE THREAD

**Issue by saurabhnanda** [tomjaguarpaw/haskell-opaleye#332]
Is there a reason for not having a standard way to convert an `a` to `Maybe (Column a)`? If one tries to define it, it starts overlapping with `Default Constant (Maybe a) (Maybe (Column a))`. What are the consequences of allowing this via `OverlappingInstances`?

**Comment by tomjaguarpaw** [comment]
> Is there a reason for not having a standard way to convert an `a` to
> `Maybe (Column a)`?  If one tries to define it, it starts overlapping with
> `Default Constant (Maybe a) (Maybe (Column a))`.  What are the
> consequences of allowing this via `OverlappingInstances`?

The standard way ought to be

    Just . constant

Is that not satisfactory for your use case?

**Comment by tomjaguarpaw** [comment]
Closing this as stale.  Feel free to reopen if necessary.
