### ISSUE TITLE
Running QueryArr

### ISSUE THREAD

**Issue by Superpat** [tomjaguarpaw/haskell-opaleye#339]
So I'm a little confused as to how to use QueryArr. It's really easy to compose queries with it, but what if I want to run one of my parts? I cant use runQuery because it only runs Query so am I right in thinking that you cant directly run a QueryArr?

Do the following queries make sense, and if I want to run userByIdQuery directly with something similar to runQuery, do I have to wrap it in a Query first?
```
accountByLoginQuery :: QueryArr (Column PGText) AccountColumn
accountByLoginQuery = proc lgn -> do
    account <- accountsQuery -< ()
    restrict -< accountLogin account .== lgn
    returnA -< account

userByIdQuery :: QueryArr (Column PGUuid) UserColumn
userByIdQuery = proc uuid -> do
    user <- usersQuery -< ()
    restrict -< userId user .== uuid
    returnA -< user

userByLoginQuery :: QueryArr (Column PGText) UserColumn
userByLoginQuery = proc lgn -> do
    account <- accountByLoginQuery -< lgn
    user <- userByIdQuery -< accountUser account
    returnA -< user
```

**Comment by tomjaguarpaw** [comment]
> am I right in thinking that you cant directly run a QueryArr?

You are right.

> Do the following queries make sense

Yes, they make sense.  If you want to *run* `userByIdQuery` you need to give it a user id to run it on!  How about

```Haskell
uuid :: UUID
uuid = ...

query :: Query UserColumn
query = userByIdQuery <<< pure (pgUUID myUuid)
```

and then you can happily use `runQuery query`.

**Comment by Superpat** [comment]
That seems to have done it! It compiles now, I'll adapt the rest of the code to use it. Thanks, this makes a lot of the power of opaleye  a lot more evident.

**Comment by tomjaguarpaw** [comment]
You also like to know the arrow notation version of this in case you prefer it.

```haskell
uuid :: UUID
uuid = ...

query :: Query UserColumn
query = proc () -> do
    userByIdQuery -< pgUUID uuid
```
