### ISSUE TITLE
when offset and limit are used together the behavior is different depending on the order of the calls

### ISSUE THREAD

**Issue by sras** [tomjaguarpaw/haskell-opaleye#341]
```
  offset 100 $ limit 100 $ queryTable bookingTable
```

Ends up with this query

```
SELECT "id0_1" as "result1_2",
	       "total_amount1_1" as "result2_2",
	       "pending_amount2_1" as "result3_2",
	       "currency3_1" as "result4_2"
	FROM (SELECT *
	      FROM (SELECT *
	            FROM (SELECT *
	                  FROM (SELECT *
	                        FROM (SELECT *
	                              FROM (SELECT "id" as "id0_1",
	                                           "total_amount" as "total_amount1_1",
	                                           "pending_amount" as "pending_amount2_1",
	                                           "currency" as "currency3_1"
	                                    FROM "booking" as "T1") as "T1") as "T1"
	                        LIMIT 100) as "T1") as "T1"
	            OFFSET 100) as "T1") as "T1"
```

While 

```
limit 100 $ offset 100 $ queryTable bookingTable
```

End up with query

```
SELECT "id0_1" as "result1_2",
	       "total_amount1_1" as "result2_2",
	       "pending_amount2_1" as "result3_2",
	       "currency3_1" as "result4_2"
	FROM (SELECT *
	      FROM (SELECT *
	            FROM (SELECT *
	                  FROM (SELECT *
	                        FROM (SELECT *
	                              FROM (SELECT "id" as "id0_1",
	                                           "total_amount" as "total_amount1_1",
	                                           "pending_amount" as "pending_amount2_1",
	                                           "currency" as "currency3_1"
	                                    FROM "booking" as "T1") as "T1") as "T1"
	                        OFFSET 100) as "T1") as "T1"
	            LIMIT 100) as "T1") as "T1"
```

The OFFSET/LIMIT locations are swapped, which results in the surprising behavior where former query returning zero number of rows, while the latter returning 100 rows as expected.

A raw postgresql query behaves as expected..

```
scratch=# select * from booking offset 10 limit 10;
 id | total_amount | pending_amount | currency
----+--------------+----------------+----------
 11 |           10 |              5 | INR
 12 |           10 |              5 | INR
 13 |           10 |              5 | INR
 14 |           10 |              5 | INR
 15 |           10 |              5 | INR
 16 |           10 |              5 | INR
 17 |           10 |              5 | INR
 18 |           10 |              5 | INR
 19 |           10 |              5 | INR
 20 |           10 |              5 | INR
(10 rows)

scratch=# select * from booking limit 10 offset 10;
 id | total_amount | pending_amount | currency
----+--------------+----------------+----------
 11 |           10 |              5 | INR
 12 |           10 |              5 | INR
 13 |           10 |              5 | INR
 14 |           10 |              5 | INR
 15 |           10 |              5 | INR
 16 |           10 |              5 | INR
 17 |           10 |              5 | INR
 18 |           10 |              5 | INR
 19 |           10 |              5 | INR
 20 |           10 |              5 | INR
(10 rows)
```

I am seeing this behavior in the latest release (0.6.0.0) as well as the 0.5.3.0 release where I originally observed it,

**Comment by tomjaguarpaw** [comment]
This is intended behaviour but I can see how it is confusing for someone who is used to writing `OFFSET` and `LIMIT` in the same `SELECT`.  I opened [an issue](https://github.com/tomjaguarpaw/haskell-opaleye/issues/342) to document this better.

In short, `limit 100 $ offset 100 $ query` takes query, then jumps to row 101, then takes the first 100 rows starting from there.  `offset 100 $ limit 100 $ query` takes query, takes the first 100 rows, and then jumps to row 101 and returns the rest of the rows.  Since there are only 100 it returns nothing!

It seems that in practice you probably only ever want to use the `limit 100 $ offset 100 $ query` version.

**Comment by sras** [comment]
> It seems that in practice you probably only ever want to use the limit 100 $ offset 100 $ query version.

Wouldn't it then be better to provide a single function, something like `offset_and_limit offset limit:: Int -> Maybe Int -> Query a`, as it is an easy mistake to get the call order wrong.

**Comment by tomjaguarpaw** [comment]
> Wouldn't it then be better to provide a single function

This is definitely worth thinking about.

The counter arguments are that

* One would need `offset_and_limit offset Nothing` and `offset_and_limit 0 limit` frequently enough that it would make sense to provide separate `offset` and `limit` versions, and we'd be back to square one.

* `offset` and `limit` correspond very nicely to Haskell's `drop` and `take` functions, and nobody's suggesting that we merge them into one.

**Comment by tomjaguarpaw** [comment]
This issue is now explicitly documented.  If you think we still need the additional function then feel free to reopen the issue.
