### ISSUE TITLE
Do we need stack.yaml and if so how do we keep it up to date?

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#345]
@WillSewell @mitchellwrosen I don't use Stack so I don't know the purpose of [stack.yaml](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/stack.yaml).  You two are the only contributors.

**Comment by tomjaguarpaw** [comment]
It's [been pointed out to me that it is out of date](https://github.com/tomjaguarpaw/haskell-opaleye/pull/343#issue-271466540).  Do we still need this file?  Why can't it be autogenerated by Stack?  If we do really need it how to we go about keeping it up to date with `opaleye.cabal`?

**Comment by tomjaguarpaw** [comment]
@mitchellwrosen Thanks for the info.  Is it normal for Haskell packages to have a `stack.yaml` in their git repo?

**Comment by mitchellwrosen** [comment]
Yeah, if it exists, it should be committed to the repo, same as a `cabal.project.freeze` file.

**Comment by tomjaguarpaw** [comment]
Can I skip ahead to the latest LTS and get rid of the extra-deps section?

**Comment by saurabhnanda** [comment]
Do you want me to fix this in a PR? I need to anyways build opaleye on my
machine.

On 07-Nov-2017 4:03 AM, "tomjaguarpaw" <notifications@github.com> wrote:

Can I skip ahead to the latest LTS and get rid of the extra-deps section?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomjaguarpaw/haskell-opaleye/issues/345#issuecomment-342310647>,
or mute the thread

**Comment by tomjaguarpaw** [comment]
> Do you want me to fix this in a PR? I need to anyways build opaleye on my
machine.

Yes, if you know how to fix it please do!

**Comment by mitchellwrosen** [comment]
@tomjaguarpaw Almost :)

**Comment by mitchellwrosen** [comment]
Here you go #346 

FYI, here's all I did to fix it: 

- set the resolver to `lts-9.12`
- try `stack build`
- it complained that `product-profunctors-0.8.0.3` is out of range for `opaleye-sqlite`
- add `product-profunctors-0.7.1.0` to `extra-deps`
- try `stack build`
- :tada:

**Comment by tomjaguarpaw** [comment]
Fixed by https://github.com/tomjaguarpaw/haskell-opaleye/commit/bdeb800242738dcbd5f03de0307e94f89700f295
