### ISSUE TITLE
Select non-null

### ISSUE THREAD

**Issue by mitchellwrosen** [tomjaguarpaw/haskell-opaleye#351]
Hello! It's my first time using opaleye and I'm having trouble figuring out how to select non-NULL columns. Does this `QueryArr` exist somewhere?

```haskell
notNull :: QueryArr (Column (Nullable a)) (Column a)
```

Thanks. (And apologies if this is not the proper channel for this kind of question).

**Comment by tomjaguarpaw** [comment]
That's a really good idea.  This is the equivalent of `catMaybes`.  I think you can write it like this

    restrictNotNull :: QueryArr (Column (Nullable a)) (Column a)
    restrictNotNull = proc na -> do
        restrict -< Opaleye.not (null na)
        return -< unsafeCoerceColumn na

Please try it out and let me know how it goes!

> And apologies if this is not the proper channel for this kind of question

It's definitely the right channel!  Feel free to ask any questions about Opaleye by opening an issue.

**Comment by asheshambasta** [comment]
@tomjaguarpaw just a correction, you probably mean `O.isNull na` instead of `O.null na` in your snippet above.

**Comment by tomjaguarpaw** [comment]
Thanks!

**Comment by tomjaguarpaw** [comment]
This looks closed.  @mitchellwrosen feel free to reopen if necessary.
