### ISSUE TITLE
LATERAL JOIN support?

### ISSUE THREAD

**Issue by iand675** [tomjaguarpaw/haskell-opaleye#359]
I was wondering if there were any plans to support lateral joins.

 I've got some complex data aggregation queries that have proven to be very difficult to express as I'd like without access to lateral join functionality.

**Comment by tomjaguarpaw** [comment]
This would be pretty easy to add.  You would need to add a lateral join type to `PrimQuery` and expose

    lateralJoin :: Query a -> (a -> Query b) -> Query b

which should be easy to write.  (If this looks like a monad bind operator there's a good reason for that!).

**Comment by ocharles** [comment]
I have a feeling this might also be the definition of `ArrowApply` for `QueryArr`, if you want to write it in a slightly different form.

**Comment by tomjaguarpaw** [comment]
Yes indeed. They are both essentially monadic interfaces.  See https://www.stackage.org/haddock/lts-13.21/base-4.12.0.0/Control-Arrow.html#t:ArrowApply.
