### ISSUE TITLE
`Default` is unfortunately named.

### ISSUE THREAD

**Issue by bitemyapp** [tomjaguarpaw/haskell-opaleye#366]
I thought it meant `data-default` (which was also confusing in-context)

Some warning/indication for the provenance would be helpful, such as in the tutorial where it's used in the definition of `printSql` with no qualification.

**Comment by tomjaguarpaw** [comment]
(NB `Default` is defined in [product-profunctors](https://github.com/tomjaguarpaw/product-profunctors) but I'm happy to keep this ticket here.)

I'm certainly happy to change the documentation if you suggest something you'd prefer to see.  I can add a short explanition near `printSql` if you like.  In principle I'm also happy to consider changing the name, but there's an important caveat:  `Data.Profunctor.Product.Default` serves almost exactly the same purpose except specifically for things with two type parameters.  Therefore it's hard to know what a better name would be (perhaps `Default2`?) and I'm personally quite happy to let the module name disambiguate.

**Comment by bitemyapp** [comment]
I greatly appreciate your reply and how open it is to trying to ameliorate this. Thank you.

>(NB Default is defined in product-profunctors but I'm happy to keep this ticket here.)

At the time I filed the ticket I figured the proximal cause was more attributable to docs/lack of module qualification in Opaleye and therefore more actionable there unless I can convince you to change the name.

Do you need a whole typeclass for this? `data-default` is on my list of libraries I tell clients I'm contracting with to purge immediately. I don't yet know a reason why I wouldn't put `Data.Profunctor.Product.Default` in the same category and you seem to have said as much in your reply. Can it get eliminated and replaced with ordinary values that are passed around? Alternately, can it get added to a more domain-specific typeclass? If not, why not?

**Comment by tomjaguarpaw** [comment]
> At the time I filed the ticket I figured the problem was more attributable to docs/lack of module qualification in Opaleye and therefore more actionable there

How about importing `Data.Profunctor.Product.Default` in the tutorial as fully qualified?

> unless I can convince you to change the name.

That seems unlikely but happy to discuss further.

> I don't yet know a reason why I wouldn't put Data.Profunctor.Product.Default in the same category

I would urge you to not jump to any conclusions on `Data.Profunctor.Product.Default`.  It is an *extremely* useful typeclass which is used, essentially, as a type-level `fmap`.  It fulfils an important role in Opaleye in a lightweight way.  Please take some time to understand how it is used and its benefits.  You may find it useful to continue this conversation in the context of [Default Explanation](
https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/Doc/Tutorial/DefaultExplanation.lhs) (which I hope helps your understanding, but could itself do with some improvement).

> you seem to have said as much in your reply

I hope I didn't!  I sympathise with your feelings about `Data.Default` but I didn't mean to imply that `Data.Profunctor.Product.Default` has exactly the same *purpose*.  Rather it has the same structure but uses it to a much more sophisticated end at kind `* -> * -> *`.

> Can it be eliminated and replaced with ordinary values that are passed around?

Yes!  That's what the `...Explicit` functions are for.  But `Default` saves you a lot construction such ordinary values. There's only one such sensible value in each type.

> Alternately, can it get added to a more domain-specific typeclass?

Ah!  Good question.  Well, yes.  But there are between five and ten such "domain-specific typeclasses" in Opaleye and Default abstracts them all.

> this isn't sufficient in itself unless you mention the full module

What do you mean "mention the full module"?  The body of that ticket *does* say  "Explain in the Haddock that `Data.Profunctor.Product.Default` is like `Data.Default`, just with a couple of type parameters.".  The title "Explain Default is like Default" is just an abbreviation, and partialy a joke!

**Comment by tomjaguarpaw** [comment]
Closing as stale.
