### ISSUE TITLE
Make TutorialManipulation clearer

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#369]
@bitemyapp was misled by TutorialManipulation.  He seemed not to realise that the `arrange...` functions are for debugging/info only and than the `run...` functions are for production.  The corresponding section in the tutorial should be more prominent.

https://github.com/tomjaguarpaw/haskell-opaleye/blob/3ba290e51abb4bcf4b85b777bb2f41b43542ab8b/Doc/Tutorial/TutorialManipulation.lhs#L150

https://twitter.com/bitemyapp/status/966809119712739328

**Comment by bitemyapp** [comment]
The ability to turn a database action into a string shouldn't be directly available to the user period except as something very clearly labeled "debug"/"unsafe".

If I ever get around to making `rawSql` available from Esqueleto in a more accessible form it'll almost certainly be with a name comparable to ByteString's `accursedUnutterablePerformIO`.

**Comment by tomjaguarpaw** [comment]
> The ability to turn a database action into a string shouldn't be directly available to the user period except as something very clearly labeled "debug"/"unsafe".

I'm afraid I'm unable to intuit your rationale for such a categorical statement.  Could you please expand?

> If I ever get around to making rawSql available from Esqueleto in a more accessible form it'll almost certainly be with a name comparable to ByteString's accursedUnutterablePerformIO.

FYI the [difficulty of generating](https://stackoverflow.com/questions/20435797/how-can-i-get-esqueleto-to-generate-an-sql-string-for-me) a raw SQL string was one of the minor reasons I was put off Esqueleto.

**Comment by tomjaguarpaw** [comment]
The `arrange...` functions were removed in

https://github.com/tomjaguarpaw/haskell-opaleye/commit/91c8896ec1678dea6b2d778257e1aeda3bb5216e#diff-bac8cd364e8b820bb8d100103ae631a5
