### ISSUE TITLE
Is there an implementation for ArrowChoice QueryArr?

### ISSUE THREAD

**Issue by cscalfani** [tomjaguarpaw/haskell-opaleye#372]
I'd like to put an `if` statement in my arrow code for my query to minimize boilerplate. And when I do  I get an error saying there's no instance for `(ArrowChoice QueryArr)`.

Ideally, I'd like to know how to implement this if it's easy.

Thanks.

**Comment by tomjaguarpaw** [comment]
That's interesting.  I don't think anyone has tried to do that before.  Can you share the kind of query you're trying to write?  I suspect something like the following will work.

```haskell
instance Arr.ArrowChoice QueryArr where
  left f = QueryArr g
    where g (e, primQ, t0) = case e of
            Left a -> first3 Left (runQueryArr f (a, primQ, t0))
            Right b -> (Right b, primQ, t0)
```

Please try it and let me know!

**Comment by tomjaguarpaw** [comment]
I pushed that implementation to this branch https://github.com/tomjaguarpaw/haskell-opaleye/tree/arrowchoice

**Comment by cscalfani** [comment]
This works great!! Hopefully, this can make it in the next release.

This is a query where I want the cell phone or email of the user depending on the destination. The rest of the query is identical.

WITHOUT ArrowChoice:
```hs
  rows <-
    case destination of
      Text ->
        liftIO $ withResource (pool env) $ \conn ->
          runUserQuery conn $ proc () -> do
            row@User{..} <- userQuery -< ()
            restrictAccessAllowed -< _accessAllowed
            restrictNotNull -< _cell
            restrict -< (_guid .== constant userIdGuid)
            returnA -< row
      Email ->
        liftIO $ withResource (pool env) $ \conn ->
          runUserQuery conn $ proc () -> do
            row@User{..} <- userQuery -< ()
            restrictAccessAllowed -< _accessAllowed
            restrictNotNull -< _email
            restrict -< (_guid .== constant userIdGuid)
            returnA -< row
```

With (SO MUCH CLEANER):
```hs
  rows <-
    liftIO $ withResource (pool env) $ \conn ->
      runUserQuery conn $ proc () -> do
        row@User{..} <- userQuery -< ()
        restrictAccessAllowed -< _accessAllowed
        case destination of
          Text -> restrictNotNull -< _cell
          Email -> restrictNotNull -< _email
        restrict -< (_guid .== constant userIdGuid)
        returnA -< row
```

**Comment by tomjaguarpaw** [comment]
Nice.  I'd be happy to include this in the next release.  I just have to convince myself it's not going to create invalid queries.  I think it's fine though.

**Comment by cscalfani** [comment]
I can't think of how I could create an invalid query. The compiler really won't let me. All it's really doing is allowing me to have an `if` or a `case` in the arrow computation. What I do within the `if` or `else` still has to be valid.

Thanks again for the quick response!!

**Comment by tomjaguarpaw** [comment]
By the way, you don't actually need `ArrowChoice` for this example.  I think the following is sufficient.

```haskell
  rows <-
    liftIO $ withResource (pool env) $ \conn ->
      runUserQuery conn $ proc () -> do
        row@User{..} <- userQuery -< ()
        restrictAccessAllowed -< _accessAllowed
        restrictNotNull -< case destination of { Text -> _cell; Email -> _email }
        restrict -< (_guid .== constant userIdGuid)
        returnA -< row
```

Could you try that one too?

**Comment by tomjaguarpaw** [comment]
> Thanks again for the quick response!!

You're welcome.  Thank you too!

**Comment by tomjaguarpaw** [comment]
You only need `ArrowCase` if you want to change the `QueryArr` in the branches of the case.  Since both of your branches are `restrictNotNull` you don't need it here.

**Comment by cscalfani** [comment]
I think you're right. I'm pretty new to Haskell so I didn't think of this solution. I still think `ArrowChoice` is worth putting for those other cases.

I'll try this with 0.6.0.0 and get back to you.

**Comment by cscalfani** [comment]
Compiles and works.

I suspect, however, that before I'm done developing my backend server, I'll find a good use for `ArrowChoice`.

Thanks again.

**Comment by tomjaguarpaw** [comment]
Great stuff.  If you do use the `ArrowChoice` instance please come and report back with an example.  I'm sure it would be helpful for other users.

**Comment by cscalfani** [comment]
Will do.
