### ISSUE TITLE
Invalid query from pgRange due to nested casts

### ISSUE THREAD

**Issue by BlackBrane** [tomjaguarpaw/haskell-opaleye#377]
I'm writing a query for a table with a `PGRange PGTimestamptz` column, that returns rows whose range encompasses a supplied timestamp. It seems that the `pgRange` function is broken for cases where the provided column-making function itself uses a cast.

Here's a minimal example:

```haskell
data User' a b =
    User { key       :: a
         , sysPeriod :: b
         } deriving (Show, Generic, Eq, Ord)

$(makeAdaptorAndInstance "pUser" ''User')

type User  = User' Int64           (PGSR.PGRange UTCTime)
type UserR = User' (Column PGInt8) (Column (PGRange PGTimestamptz))
type UserW = User' (Column PGInt8) (Maybe (Column (PGRange PGTimestamptz)))

table :: Table UserW UserR
table = Table "users" $ pUser User
    { key       = required "id"
    , sysPeriod = optional "sys_period"
    }

queryAt :: UTCTime -> Query UserR
queryAt t = proc () -> do
    row <- queryTable table -<  ()
    restrict -< sysPeriod row `overlap` pgRange pgUTCTime (Inclusive t) (Inclusive t)
    returnA -< row

```

The generated SQL is:
```sql
SELECT "id0_1" as "result1_2",
       "sys_period1_1" as "result2_2"
FROM (SELECT *
      FROM (SELECT "id" as "id0_1",
                   "sys_period" as "sys_period1_1"
            FROM "users" as "T1") as "T1"
      WHERE (("sys_period1_1") && (CAST('[CAST('2018-03-12T15:04:22.230544Z' AS timestamptz),CAST('2018-03-12T15:04:22.230544Z' AS timestamptz)]' AS tstzrange)))) as "T1"
```
This leads to the error message `syntax error at or near "2018"`.

The query is fixed if I eliminate the inner casts.

**Comment by tomjaguarpaw** [comment]
Hello and thank you for the bug report.  That's interesting.  It seems we need to use function-style range construction rather than cast-style.  Perhaps the latter only works for literals.  This would be fine:

```sql
tstzrange(CAST('2018-03-12T15:04:22.230544Z' AS timestamptz),CAST('2018-03-12T15:04:22.230544Z' AS timestamptz), '[]')
```

http://sqlfiddle.com/#!17/9eecb/11157

@BlackBrane Do you want to have a go at implementing that?

**Comment by BlackBrane** [comment]
Thanks for the quick response @tomjaguarpaw!

I'd like to have a go. 

I'm not too familiar with the internals just yet, but this seems like it should be reasonably straightforward.
