### ISSUE TITLE
Review indexed records and inferrable join API

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#388]
@saurabhnanda I would be extremely grateful if you could review [the latest indexed records and inferrable join API](https://github.com/tomjaguarpaw/haskell-opaleye/blob/7cb6639f3c02adb7f04b81669ffb2244b0977c84/Doc/Tutorial/TutorialBasicTypeFamilies.lhs).  It provides two innovations.  If you like this then I aim to add it to the next release.

# Indexed records

It provides the ability to index records using a single higher-order parameter rather than one parameter for each field in the record.

Instead of 

```haskell
data Widget' a b c d e = Widget { style    :: a
                                , color    :: b
                                , location :: c
                                , quantity :: d
                                , radius   :: e
                                }

type WidgetHaskells = Widget ...
type WidgetColums = Widget ...
type WidgetNullableColums = Widget ...
type WidgetW = Widget ...
```

you can just say

```haskell
data Widget f = Widget { style    :: TableField f String SqlText   NN Req
                       , color    :: TableField f String SqlText   NN Req
                       , location :: TableField f String SqlText   NN Req
                       , quantity :: TableField f Int    SqlInt4   NN Req
                       , radius   :: TableField f Double SqlFloat8 NN Req
                       }
```

and then use

```haskell
Widget H
Widget O
Widget Nulls
Widget R
```

# Inference

The outer join functions have a type family which provides inference in one direction across the function call.  It allows writing things like

```haskell
O.fullJoinInferrable (O.fullJoinInferrable
                birthdayQuery
                (queryTable widgetTable)
                (const (O.pgBool True)))
           birthdayQuery
           (const (O.pgBool True))
```

without providing a type signature.

If you like this then the next step is to infer types for `Constant` and `QueryRunner`, but that's harder because we have to make some arbitrary choices about what Haskell types correspond to SQL types.

**Comment by ocharles** [comment]
I see we're all converging on HK-data types then :)

**Comment by tomjaguarpaw** [comment]
Yup it's a pretty convenient approach.  I'd be interested to hear your thoughts on it too.

**Comment by ocharles** [comment]
I'm very much on board with it, it's primarily how Rel8 is structured - though I've worked hard to try and make sure nothing assumes it. The latter is actually a primary difference to Beam, which does make a lot of assumptions that tables are essentially of kind `(* -> *) -> *`

**Comment by tomjaguarpaw** [comment]
I have released this on Hackage.  It's sort of a "prerelease" of version 0.7.  I'd be grateful for any testing and comments.

https://hackage.haskell.org/package/opaleye

**Comment by saurabhnanda** [comment]
> If you like this then the next step is to infer types for Constant and QueryRunner, but that's harder because we have to make some arbitrary choices about what Haskell types correspond to SQL types.

Here's my take on this (off the top-of-my-head; haven't thought this through) -- there should be **two** version of the `runQuery` function.  

- The "default" behaviour of `runQuery` should take into account sensible defaults for pg-type <=> haskell-type mappings. This is what most newcomers expect when they first try the library. This is the path of least resistance.
- Another `runQueryWith` function should allow you to pick the pg-type <=> haskell-type mappings either via type-class machinery (i.e. the current design of Opaleye), or by providing a hand-written function (for the entire low), like pg-simple's `queryWith`

**Comment by saurabhnanda** [comment]
In fact with the type-family machinery, we are almost there. We just need to ship a pre-existing type-family that has sane pg <=> haskell-type mappings. The user can always use his/her own type-family if something else is required.

**Comment by saurabhnanda** [comment]
https://github.com/tomjaguarpaw/haskell-opaleye/blob/7cb6639f3c02adb7f04b81669ffb2244b0977c84/Doc/Tutorial/TutorialBasicTypeFamilies.lhs#L142-L144

Would you be interested in a PR that contains a code-gen script? We have written a code-gen script that looks at `pg_catalog` tables, can be tweaked via a YAML config file, and generates all the Opaleye boilerplate code.

**Comment by saurabhnanda** [comment]
> https://github.com/tomjaguarpaw/haskell-opaleye/blob/7cb6639f3c02adb7f04b81669ffb2244b0977c84/Doc/Tutorial/TutorialBasicTypeFamilies.lhs#L154-L158

I've always wondered if `pBirthday` is required for anything else other than defining `Default . def` ? If not, would you consider removing it from the tutorials/examples and replacing it with  (IMO) easier to understand code, eg:

```
data TagPoly id clientId name colourCode createdAt updatedAt = TagPoly 
  { _tagId :: id
  , _tagClientId :: clientId
  , _tagName :: name
  , _tagColourCode :: colourCode
  , _tagCreatedAt :: createdAt
  , _tagUpdatedAt :: updatedAt
  } deriving (Eq, Show, Generic)

instance ( ProductProfunctor p
         , Applicative (p (TagPoly id0 clientId0 name0 colourCode0 createdAt0 updatedAt0))
         , Default p id0 id1
         , Default p clientId0 clientId1
         , Default p name0 name1
         , Default p colourCode0 colourCode1
         , Default p createdAt0 createdAt1
         , Default p updatedAt0 updatedAt1) 
         => Default p (TagPoly id0 clientId0 name0 colourCode0 createdAt0 updatedAt0) 
                      (TagPoly id1 clientId1 name1 colourCode1 createdAt1 updatedAt1) where
  def = TagPoly <$> P.lmap _tagId def <*> P.lmap _tagClientId def <*> P.lmap _tagName def <*> P.lmap _tagColourCode def <*> P.lmap _tagCreatedAt def <*> P.lmap _tagUpdatedAt def
```

**Comment by saurabhnanda** [comment]
> https://github.com/tomjaguarpaw/haskell-opaleye/blob/7cb6639f3c02adb7f04b81669ffb2244b0977c84/Doc/Tutorial/TutorialBasicTypeFamilies.lhs#L165-L169

`required` and `optional` not needed any more?

**Comment by tomjaguarpaw** [comment]
> Is this the same approach that rel8 and beam are taking?

Yes, reasonably similar I think.

> there should be two version of the runQuery function

Agreed.

> Would you be interested in a PR that contains a code-gen script?

I would love to see that!  How does it differ from `opaleye-gen`?

> I've always wondered if `pBirthday` is required for anything else other than defining `Default . def`

It's never *required* because you can always replace it with its definition in terms of `$***` and `****` (or `<$>` and `<*>`, as in the example you provide).  Personally I thought that

```haskell
pTag { _tagId = tableColumn "id"
     , _tagClientId = tableColumn "clientId"
     , _tagName = tableColumn "name"
     ...
}
```

was easier to understand than

```haskell
TagPoly <$> tableColumn "id" <*> tableColumn "clientId" <*> tableColumn "name" ...
```

but if others think the latter is simpler I can avoid mentioning `pBirthday`.  In any case, `pBirthday` and the instance should be automatically generated by *something* so one would never see their definitions.

> `required` and `optional` not needed any more?

They're not needed in the sense that `tableColumn` is a typeclass-polymorphic version that subsumes them.  If you want to avoid specifying the type signature then you would still need to use them though.
