### ISSUE TITLE
Sum aggregation returns empty results

### ISSUE THREAD

**Issue by WraithM** [tomjaguarpaw/haskell-opaleye#390]
This issue is kind of similar to https://github.com/tomjaguarpaw/haskell-opaleye/issues/138 and https://github.com/tomjaguarpaw/haskell-opaleye/issues/159.

I'm doing several sum aggregations over different tables and comparing the sums. If any of the sub-queries return no results, the query returns no results.

Here's a dummy example:

```haskell
difference = proc () -> do
    x <- aggregate sum q1 -< ()
    y <- aggregate sum q2 -< ()
    returnA -< y - x
```

If `q1` or `q2` don't have any results, the total query becomes null. I've tried doing `fromNullable (constant 0)`, and I've also tried replacing `aggregate sum` with something kind of similar to your `countRows` construction from #159. Those compiled but also returned null. If I do `showSql` on my query with `fromNullable`, which produces `CASE` statements on the results of the sum queries, and remove the `GROUP BY COALESCE(0)`, then things work. I also noticed that if I did `COALESCE(<sum query>, 0)`, that also worked.

I would like to have this all be one query rather than breaking up the sums into individual queries and checking if the individual sums are empty.

Do you have any recommendations?

**Comment by tomjaguarpaw** [comment]
Does `aggregate sum (q1 `union` pure 0)` work?

**Comment by WraithM** [comment]
I actually got this to work, sort of:
```Haskell
sum' :: Query (Column PGInt8) -> Query (Column PGInt8)
sum' = fmap (fromNullable 0 . snd) . (\q -> O.leftJoin (pure ()) (aggregate O.sum q) (const (O.pgBool True)))
```

I get this issue: `Incompatible {errSQLType = "numeric", errSQLTableOid = Nothing, errSQLField = "result1_17", errHaskellType = "Int64", errMessage = "types incompatible"}`

I'll try the `union pure 0` in a sec because I like that a lot more than this sum thing.

**Comment by tomjaguarpaw** [comment]
Doing a left join is a clever idea.  I wonder why we get the SQL type error though.  Somehow the result of the query is being upcast to a `numeric`.

**Comment by WraithM** [comment]
I think Opaleye is smarter than me. If I'm summing a bunch of `int8`s, then the sum could be larger than `int8`, hence `numeric`, so I need to use `Integer` for my sum 👍 . I'm converting the result to use `Integer` now. (Thanks for the live debugging).

I totally stole the `leftJoin` idea from your `countRows`!

I think I'm going to go with the `union` for simplicity.

Thank you so much for your help! This was a little counter intuitive, but it makes sense once you get into it.

**Comment by tomjaguarpaw** [comment]
> I totally stole the leftJoin idea from your countRows!

I totally forgot I had done that!

**Comment by tomjaguarpaw** [comment]
> the result is an error, so maybe I closed this prematurely.

Can you be precise about your code and what error you're seeing?

**Comment by WraithM** [comment]
Sure. Unfortunately, I can't share the exact code, but this is an accurate representation.

```haskell
q1 :: Query (Column PGInt8)
q2 :: Query (Column PGInt8)

sumOfSums :: Query (Column PGInt8)
sumOfSums = proc () -> do
    x <- aggregate sum (q1 `union` pure 0) -< ()
    y <- aggregate sum (q2 `union` pure 0) -< ()
    returnA -< y + x

runSum :: Connection -> IO (Maybe Int64)
runSum conn = listToMaybe <$> runQuery conn difference
```

`q1` and `q2` query `int8` columns. If you sum them, and sum them, the result is a `Column PGInt8`. Therefore, I try to read it as an `Int64`. This code compiles. However, if you run `runSum` you get: `Incompatible {errSQLType = "numeric", errSQLTableOid = Nothing, errSQLField = "result1_17", errHaskellType = "Int64", errMessage = "types incompatible"}`.

As you said, the sum of sums gets upcast to `numeric`. So, this code compiles, but results in an error. I fixed this with an explicit cast on the `returnA` line, and then everything works resulting in the correct answer on the Haskell side.

**Comment by tomjaguarpaw** [comment]
Thanks.  Yes, this is a known (but not documented) issue.  The type of `sum` is wrong.  There should probably be a typeclass or type family to map the input type to the output type.

I opened an issue for it here: https://github.com/tomjaguarpaw/haskell-opaleye/issues/391

**Comment by ocharles** [comment]
Rel8 uses such a type class for aggregations, if you want to refer against
that:
https://github.com/ocharles/rel8/blob/master/Rel8/Internal/Aggregate.hs

**Comment by WraithM** [comment]
Okay, cool. Let's close this then.
