### ISSUE TITLE
want runDeleteReturning

### ISSUE THREAD

**Issue by mherzl** [tomjaguarpaw/haskell-opaleye#399]
The [comments by](http://hackage.haskell.org/package/opaleye-0.6.7001.0/docs/Opaleye-Manipulation.html#v:runDelete_) `runDelete_` suggest filing an issue if `runDeleteReturning` is desired.

I would be interested in having a `runDeleteReturning` to use instead of `runDelete_`.
For one reason, this would make tests of my delete functions simpler as the deleted values would be more readily available for validation.

**Comment by tomjaguarpaw** [comment]
Hello Matthew,

I don't have time to implement this myself right now, but if you want to have
a go you can try implenting it the same way that UPDATE RETURNING is
implemented.  See, for example, this line, and work back from there:

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Manipulation.hs#L316

**Comment by mherzl** [comment]
Sounds good I'll give it a shot.

**Comment by mherzl** [comment]
Delete returning functionality now added by [this pull request](https://github.com/tomjaguarpaw/haskell-opaleye/pull/408); closing.
