### ISSUE TITLE
Add a function to create a column from a literal

### ISSUE THREAD

**Issue by ndmitchell** [tomjaguarpaw/haskell-opaleye#40]
Add a function of type `toColumn :: a -> Column a`. Useful for creating values from newtype'd columns

**Comment by tomjaguarpaw** [comment]
Very similar to https://github.com/tomjaguarpaw/haskell-opaleye/issues/28

**Comment by tomjaguarpaw** [comment]
Done https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Constant.hs
