### ISSUE TITLE
Is it possible to get multiple columns from rReturning on insertion?

### ISSUE THREAD

**Issue by csasarak** [tomjaguarpaw/haskell-opaleye#403]
I'm wondering if it's possible to return two columns after insert
using rReturning.

I suspect I'd need a function like: (Column a, Column b) -> Column (a,
b) and then a function that could take the pair and turn it into
haskells, but don't see an obvious way to do this that doesn't involve writing a QueryRunner instance for column pairs. 

If there's a simpler method, I'd like to document it in the manipulation tutorial after work
sometime.

Is it possible to use product-profunctors to compose a function that
would do something like this? I've been thinking about how the
instances of QueryRunner could be used but not coming up with a
solution.

**Comment by tomjaguarpaw** [comment]
You can return any number of columns using `rReturning`.  For example you could change [the example in the Manipulation Tutorial](https://github.com/tomjaguarpaw/haskell-opaleye/blob/e2c9de884717475834ec32ea155c21c39fc68017/Doc/Tutorial/TutorialManipulation.lhs#L156) to

```haskell
insertReturning :: Insert [(Int, Double, Double, String)]
insertReturning = Insert
  { iTable      = myTable
  , iRows       = [(Nothing, 4, 5, sqlString "Bye")]
  , iReturning  = rReturning id
  , iOnConflict = Nothing
  }
```

to return all the columns.

**Comment by csasarak** [comment]
Sorry, I'm thinking of the situation where you're writing a record type (that's already been set up to work with opaleye) to the database. I've tried writing accessors like 

`insertReturning :: Insert [(Int, Double)]
insertReturning = Insert
  { iTable      = myTable
  , iRows       = [MyStruct { f1 = Nothing, f2 = 4, f3 = 5, f6 = sqlString "Bye"}]
  , iReturning  = rReturning 
  , iOnConflict = Nothing
  }
  where extractor = MyStruct { f1 = f1, f2 = f2 } = (f1, f2)`
But get a type mismatch error because `f1 :: Column PGInt4` and `f2 :: Column PGDouble`

That's my understanding of the problem anyhow, maybe I'm missing something like a type annotation?

**Comment by tomjaguarpaw** [comment]
Can you please post the exact code that you are trying?

**Comment by tomjaguarpaw** [comment]
Sounds like it works for you now.  If so, great!

You may be able to generalise your function like this

```haskell
writeItems :: (QueryRunner c d) => Table a b -> (b -> c) -> Connection -> [a] -> IO [d]
```

(but I haven't tested it)

**Comment by csasarak** [comment]
ah, I was able to make something close typecheck:
```haskell
writeItems :: (Default QueryRunner c d) => Table a b -> (b -> c) -> Connection -> [a] -> IO [d]
```
I was using the wrong instance declaration. Initially I was also trying to get ds out by composing multiple functions together like (f1 &&& f2), which probably obscured things. This construction works with your version. Thank you again!

**Comment by tomjaguarpaw** [comment]
Seems like this is resolved.  Please reopen with more information if not.
