### ISSUE TITLE
Remove all/most of the Internal modules

### ISSUE THREAD

**Issue by ndmitchell** [tomjaguarpaw/haskell-opaleye#41]
They confuse things, bloat the interface, and should never be used anyway. Take feature requests for the ones that are in use, or Google for the module names.

**Comment by tomjaguarpaw** [comment]
I'm not sure what you mean.  I want every single implementation detail exposed in case it is useful to someone.  I've lost count of the number of times I've been bitten by packages that didn't expose some internal I needed access to.

**Comment by ndmitchell** [comment]
As a user, having 1000's of functions I "probably won't need but might" is a real pain. It massively increases the API, adding a lot of "chaff" for exceptionally little "wheat". That said, if all the good stuff is in a single module, then I can find it easily. Even with that, I can't help but feel exposed modules (even Internal ones) with no module header are probably a bad idea.

**Comment by tomjaguarpaw** [comment]
I can see the benefit of what you suggest.  One fairly left-field solution to kill two birds would be to have an opaleye-internal package, and then an opaleye package which exists purely to reexport the public API into the `Opaleye` namespace.

**Comment by ndmitchell** [comment]
That works for me - although seems more effort for you. If there was only one "public" module for Opaleye it becomes a much less severe problem.

**Comment by tomjaguarpaw** [comment]
Also, do we agree that at root this is a documentation tooling issue and the suggested fixes are just workarounds?

**Comment by ndmitchell** [comment]
I think there is some value to restricting the API - I certainly never expose internal modules. But I can see that you want to, and once #42 is fixed, I think we could close this "who cares" - it has no real impact on users.

**Comment by ndmitchell** [comment]
BTW, never trust users not to abuse your internals if you put them on display... I can tell you stories of people who used to work in teams you now work in who totally abused internal details which took months to get rid of and thus make essential changes to the internal details they abused.

**Comment by ocharles** [comment]
Oh my, please don't *remove* these modules! I've written multiple new interfaces on top of `opaleye` that would be impossible without the `Internal` modules! I would however be ok if it got re-namespaced to be clearly different in the Haddocks. `Z.Opaleye.Internal` is a hack but at least gets it all out of the way ;)

**Comment by tomjaguarpaw** [comment]
@ocharles I'd be interested to know which internal bits you have been using.  My aim is that Opaleye should be perfectly extensible without need to access anything in `Internal`.  If it's not I'd like to fix that.

**Comment by ocharles** [comment]
Tom, might be easiest if you just check out the rel8 repository and see the
modules there for imports. Not a huge amount of code

**Comment by tomjaguarpaw** [comment]
Closing this as stale.  I don't think I'm ever going to remove the `Internal` modules.
