### ISSUE TITLE
`singletonArray` fails when used at `PGInt8` type

### ISSUE THREAD

**Issue by zyla** [tomjaguarpaw/haskell-opaleye#410]
The query expression `pure (O.singletonArray (O.pgInt8 1))` generates the following SQL:

```
SELECT
array_prepend(1,CAST(ARRAY[] AS bigint[])) as "result1_1"
FROM (SELECT 0) as "T1"
```

It is rejected by Postgres with the error message `function array_prepend(integer, bigint[]) does not exist`.
Seems that the literal `1` is interpreted as an `integer`.

The solution could be adding a cast somewhere, but I don't know the best place to do it.

Here's a full test case that reproduces the problem:

```diff
diff --git a/Test/Test.hs b/Test/Test.hs
index 53c37b5..da6dcda 100644
--- a/Test/Test.hs
+++ b/Test/Test.hs
@@ -872,6 +872,11 @@ testArrayIndexOOB = it "returns Nothing when the index is out of bounds" $
   testH (A.pure $ O.pgArray O.pgInt4 [5,6,7] `O.index` O.pgInt4 8)
         (`shouldBe` ([Nothing] :: [Maybe Int]))
 
+testSingletonArray :: Test
+testSingletonArray = it "constructs a singleton PGInt8 array" $
+  testH (A.pure $ O.singletonArray (O.pgInt8 1))
+        (`shouldBe` ([[1]] :: [[Int64]]))
+
 type JsonTest a = SpecWith (Query (Column a) -> PGS.Connection -> Expectation)
 -- Test opaleye's equivalent of c1->'c'
 testJsonGetFieldValue :: (O.SqlIsJson a, O.QueryRunnerColumnDefault a Json.Value) => Query (Column a) -> Test
@@ -1145,6 +1150,7 @@ main = do
         testFloatArray
         testArrayIndex
         testArrayIndexOOB
+        testSingletonArray
       describe "joins" $ do
         testLeftJoin
         testLeftJoinNullable
```

On my machine fails with:

```
  Test/Test.hs:876:22: 
  1) arrays constructs a singleton PGInt8 array
       uncaught exception: SqlError
       SqlError {sqlState = "42883", sqlExecStatus = FatalError, sqlErrorMsg = "function array_prepend(integer, bigint[]) does not exist", sqlErrorDetail = "", sqlErrorHint = "No function matches the given name and argument types. You might need to add explicit type casts."}
```

**Comment by tomjaguarpaw** [comment]
Thanks for finding this bug and for the test case!  I think what we want is 

```haskell
singletonArray :: T.IsSqlType a => Column a -> Column (T.SqlArray a)
singletonArray x = arrayPrepend (unsafeCast (showSqlType (Just x)) x) emptyArray
```

Do you want to give it a try?

**Comment by tomjaguarpaw** [comment]
Although now I come to think of it I'm not sure why one wouldn't just use `sqlArray` instead.

**Comment by zyla** [comment]
Thanks for the fast response!

Your proposed solution fixes this particular test case, but doesn't fix the real problem - the original definition of `singletonArray` (`arrayPrepend x emptyArray`) is also sensible code that you might want to write, and it hits the same bug.

So there are two options left: 1) the cast should be in `arrayPrepend`, or 2) the cast should be in the PGInt8 literal. For me option 2 makes most sense - after all, if Postgres considers `1` to have type `integer`, then Opaleye shouldn't generate the SQL `1` for `pgInt8 1 :: Column PGInt8`.

**Comment by zyla** [comment]
> Although now I come to think of it I'm not sure why one wouldn't just use sqlArray instead.

Exactly - I'd implement `singletonArray x` using `pgArray id [x]`.

But that's another problem - the real bug is in `arrayPrepend`.

**Comment by tomjaguarpaw** [comment]
I agree that option 2 makes sense and I have been thinking about that for a couple of years (https://github.com/tomjaguarpaw/haskell-opaleye/issues/253)!  Perhaps we should just go ahead and do it.

**Comment by tomjaguarpaw** [comment]
I'm not sure when I can get round to it but feel free to have a go if you like!

**Comment by zyla** [comment]
Fixed by https://github.com/tomjaguarpaw/haskell-opaleye/pull/412
