### ISSUE TITLE
How to do the array version of <@

### ISSUE THREAD

**Issue by ProofOfKeags** [tomjaguarpaw/haskell-opaleye#417]
I found the operator `<@` for the jsonb type but I would like if I could use the equivalent one (even if named differently for array types). How hard would this be? Is there an alternative, even if less ergonomic that would allow me to write the following query

```
SELECT SUM(u2.amount) from (SELECT DISTINCT ON (u.id) u.id, u.amount FROM u INNER JOIN t ON array[(u.a, u.b)::custom_type] <@ t.c WHERE t.d in ('val1', 'val2')) u2;
```

the main issue here is the expression `INNER JOIN t ON array[(u.a, u.b)::custom_type] <@ t.c`

Is this possible?

**Comment by tomjaguarpaw** [comment]
What would the type of the array one be?

**Comment by tomjaguarpaw** [comment]
You can probably just implement it as

```haskell
(..<@) :: F.Field ... -> F.Field ... -> F.Field T.SqlBool
(..<@) = C.binOp (HPQ.:<@)
```

when you decide what the type should be.  `..<@` is maybe a silly name for an operator but we don't have a good story for the overloading of Postgres operators, except having special typeclasses.  I don't like the special typeclasses very much but maybe they're the best way.

**Comment by CaptJakk** [comment]
Agreed on the special typeclasses thing, I'm not opposed to the silliness of that operator. The array type would be whatever the nominal PGArray type is represented as right? or am I missing the question you're asking?

**Comment by tomjaguarpaw** [comment]
It's not a trick question, I'm just not familiar with that operator!  Perhaps it's

```
(..<@) :: F.Field (T.PGArray a) -> F.Field (T.PGArray a) -> F.Field T.SqlBool
(..<@) = C.binOp (HPQ.:<@)
```

**Comment by fieldstrength** [comment]
As Tom noted, it would definitely be easy to implement this other version of that operator, especially as we already have it in the internal expression type. What you want is quite similar to [this tiny PR](https://github.com/tomjaguarpaw/haskell-opaleye/pull/380/files) I made earlier.

This operator does a few things in Postgres. As referenced above, it is also used to implement `liesWithin` function, which checks if a value is inside a range, and that function name seems to roughly correspond to the assortment of things this operator supports. PG also uses these operators [for the text search type](https://www.postgresql.org/docs/11/functions-textsearch.html)`tsquery` and [geometric types](https://www.postgresql.org/docs/11/functions-geometry.html).

For what its worth, it seems reasonable to me to implement `<@`, `@>` as typeclass methods, for ease of use and discovery. It would need to use either a functional dependency or type family. In terms of fundeps, the instances would look something like:

```haskell 
class PGContains xs x | xs -> x

instance                  PGContains SqlJsonb            SqlJsonb
instance                  PGContains (Field (PGArray a)) (Field (PGArray x)) 
instance IsRangeType a => PGContains (Field (PGRange a)) (Field a)
``` 

If we want to avoid the backwards compatibility issues with `.<@`, is there any reason not to just call the operators `<@` and `@>`? Besides other database libraries, I see those operators are used in the `comonads` package but I don't imagine that would cause many issues.

**Comment by tomjaguarpaw** [comment]
We already have a similar typeclass for JSON operations

https://github.com/tomjaguarpaw/haskell-opaleye/blob/0578c89bc3b19c76a091409f4fceb4889b579396/src/Opaleye/Operators.hs#L251

Some operators can't be written as I'd want to because they clash with existing Haskell identifiers (e.g. `<`, `==`, etc.).  Maybe the other ones should never have been prefixed with `.` in the first place.  I'm not sure.
