### ISSUE TITLE
TRUE does not exist in SQLite

### ISSUE THREAD

**Issue by ndmitchell** [tomjaguarpaw/haskell-opaleye#43]
At the moment you output TRUE, should be 1 or 0.

**Comment by bergmark** [comment]
I'm confused about these sqlite issues, opaleye is explicitly postgres only, `1` is an invalid boolean in postgres.

**Comment by ndmitchell** [comment]
@bergmark - there is an SQLite branch in the repo :)

**Comment by tomjaguarpaw** [comment]
Please pull the latest.

**Comment by tomjaguarpaw** [comment]
It seems I fixed this here: https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/opaleye-sqlite/src/Opaleye/SQLite/Internal/HaskellDB/Sql/Default.hs#L197

Please reopen if necessary.
