### ISSUE TITLE
UnionAll increases showSQL time exponentially

### ISSUE THREAD

**Issue by csasarak** [tomjaguarpaw/haskell-opaleye#434]
I use `unionAll` to collect results in multiple ranges which I then aggregate. As the number of unioned subqueries increase the time it takes to generate the SQL that gets sent to postgresql seems to increase exponentially. I've made a gist here with results and the code used to generate them: https://gist.github.com/csasarak/310499e138943d430031befd8fbf94b8

Bench.html is generated by criterion and shows graphs of the behavior.  It's unfortunately at the top, the Haskell used to generate it is lower down. It takes quite a few iterations before it becomes a problem, but with heavier sub-queries it takes less.

I'm notice that `showSQL` and `formatAndShowSqlExplicit` generate Strings. I'm wondering if some kind of append operation for each sub-query is the culprit? Maybe using bytestring's Builder module might alleviate some of this? If you have some other recommendation for writing queries I'd also work with that. For now I will be doing the segmentation/aggregation in my Haskell process rather than in the database.

**Comment by tomjaguarpaw** [comment]
Thanks for the report.  Can you link me to the actual web page rather than the source?

**Comment by csasarak** [comment]
@tomjaguarpaw I found a site that renders HTML in gists, you can view the full report here: https://bl.ocks.org/csasarak/raw/310499e138943d430031befd8fbf94b8/
Alternatively you can download the raw HTML and open in a browser.

Yesterday I was able to do a bit more profiling and from the .prof it looks like the majority of the time is spend in the `removeEmpty` function, specifically the `product` part of the PrimQuery fold.

**Comment by tomjaguarpaw** [comment]
Thanks for digging into this further.  I will take a look.

One workaround, if you want one, might be to use a fold to build the condition you feed to `restrict` rather than to build a query with `unionAll`.

**Comment by csasarak** [comment]
Ah! I will look into if that will work. Thanks! 

On June 29, 2019 10:38:09 AM EDT, tomjaguarpaw <notifications@github.com> wrote:
>Thanks for digging into this further.  I will take a look.
>
>One workaround, if you want one, might be to use a fold to build the
>condition you feed to `restrict` rather than to build a query with
>`unionAll`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tomjaguarpaw/haskell-opaleye/issues/434#issuecomment-506961645

-- 
Chris

**Comment by tomjaguarpaw** [comment]
My experiment with your criterion code shows that one doesn't even need to `restrict` to see this exponential slowdown!

**Comment by tomjaguarpaw** [comment]
If I `deepseq` the result of `show`ing `runQueryArrUnpack` then it's linear, so I guess there's something exponential in the pretty-printing.

**Comment by tomjaguarpaw** [comment]
Oh no, as you said there's definitely something going on in `removeEmpty`.  It calls itself!  It shouldn't because it's already in explicit folding form!

**Comment by tomjaguarpaw** [comment]
Can you check that this fixes it:

https://github.com/tomjaguarpaw/haskell-opaleye/tree/rc

**Comment by csasarak** [comment]
Hey Tom, this appears to fix the problem! I plan to do some more testing with the project I found the bug in though. For completeness, I have added the new profiling data to the benchmarks gist, though bl.ocks doesn't seem to be displaying it yet. The new graph shows a linear increase which is much better!

I was wondering if you're amenable to a PR which adds a benchmarking target? Or maybe it's not that important.

**Comment by csasarak** [comment]
If I had a try at doing a bytestring version (I will preserve the doc version) for rendering, would you be interested in merging it?

**Comment by tomjaguarpaw** [comment]
Let's migrate the discussion to https://github.com/tomjaguarpaw/haskell-opaleye/issues/435.  This issue will be closed when my commit is merged to master.

**Comment by tomjaguarpaw** [comment]
No need to close manually.  It'll be closed when the relevant commit is merged.
