### ISSUE TITLE
Custom Type ToFields instance behavior changes between lts-13.25 and 13.26

### ISSUE THREAD

**Issue by csasarak** [tomjaguarpaw/haskell-opaleye#437]
I have a custom enumerated type that I was using in postgres with opaleye 0.6.7003.1 which no longer works with opaleye-0.6.7004.0, I'm wondering if you can advise how it needs to be changed. Example code is [here.](https://github.com/csasarak/opaleye-bench/blob/error-test/src/error/Main.hs)

The piece I don't understand, is that if I build against 13.25 and run it works, then if I edit stack.yaml to say 13.26 *without* rebuilding and then `stack exec error-test` I get:

`error-test: SqlError {sqlState = "42804", sqlExecStatus = FatalError, sqlErrorMsg = "column \"screen_type\" is of type screen_types but expression is of type text", sqlErrorDetail = "", sqlErrorHint = "You will need to rewrite or cast the expression."}`

At first I thought maybe a shared library was changing between the two versions, but neither  `postgresql-simple` nor `postgresql-libpq` appear to have changed between those resolvers.

I'm looking at the changes between the two versions of opaleye and it looks like there were a number of new aliases defined, but I'm not seeing anything that would cause this. Is there some other thing I need to add to make this work properly again?

**Comment by tomjaguarpaw** [comment]
That's very strange.   I can't see why it would work in one version of
Opaleye and not another.  One thing that may fix the problem is if you use
`unsafeCast` to "screen_types" in your `Constant` instance.

Give that a go.  If it still doesn't work then come back to me.

**Comment by csasarak** [comment]
Oddly, when I switch between versions using cabal there is no difference. Only with stack. In any case, thanks for the tip, that was exactly what it needed.

**Comment by asheshambasta** [comment]
I think there's some regression on some underlying level going on. I'm also reliably able to reproduce this with lts-14.25. 
I'm not sure if `unsafeCast` can be used repeatedly for a number of enum rows.

**Comment by tomjaguarpaw** [comment]
It would be good if you can come up with a minimal example that reproduces the problem.
