### ISSUE TITLE
Generate 1.0 for doubles, not 1

### ISSUE THREAD

**Issue by ndmitchell** [tomjaguarpaw/haskell-opaleye#44]
In SQLite that results in a type error when unmarshalling. Make sure doubles are printed correctly.

**Comment by tomjaguarpaw** [comment]
Please pull the latest.

**Comment by tomjaguarpaw** [comment]
I presume this is fixed here: https://github.com/tomjaguarpaw/haskell-opaleye/blame/master/opaleye-sqlite/src/Opaleye/SQLite/PGTypes.hs#L80

Please reopen if necessary.
