### ISSUE TITLE
Need some help with a custom TypeFamily

### ISSUE THREAD

**Issue by pjones** [tomjaguarpaw/haskell-opaleye#443]
First off, I love Opaleye!  It's my favorite way to write database code in Haskell.

I'm trying to write a custom type family similar to how Beam and rel8 do things.  I need a custom type family because I want better control over my data types and more code reuse.

For example, I'm trying to write something like this:

```haskell
data Account f = Account
  { pk :: C f AccountId SqlUuid 'ReadOnly
  , created_at :: C f UTCTime SqlTimestamptz 'ReadOnly
   -- more fields here...
  }
```

Most of the time I'd like my `C` type family to simply reduce to the `A` type family in Opaleye.  But I'd like a couple of custom types to behave differently.  Specifically, when a user supplies an `Account UserInput` value I want the `ReadOnly` columns to reduce to `()` (i.e., they can't be given a value).  My validation function would turn the `Account UserInput` to an `Account W` for inserting into the database.

My biggest problem is getting my `C` type family to work with the `ProductProfunctor` code, for example:

```haskell
pAccount
  :: PP.ProductProfunctor p
  => Account (p :<$> a :<*> b)
  -> p (Account a) (Account b)
```

This doesn't work because `f` is an `'S` from `Arr` and I can't for the life of me figure out how to map it correctly in my type family.

In the simplest case (which works) I have:

```haskell
--------------------------------------------------------------------------------
data WriteMode
  = ReadOnly
  | Required
  | Optional
  | Nullable

--------------------------------------------------------------------------------
type family OENullable f where
  OENullable 'ReadOnly = NN
  OENullable 'Required = NN
  OENullable 'Optional = NN
  OENullable 'Nullable = N

--------------------------------------------------------------------------------
type family OEOptional f where
  OEOptional 'ReadOnly = Opt
  OEOptional 'Required = Req
  OEOptional 'Optional = Opt
  OEOptional 'Nullable = Req

--------------------------------------------------------------------------------
type C f h d m = TableRecordField f h d (OENullable m) (OEOptional m)
```

In which case `C` isn't a type family but just an alias.  Of course this only works if `f` is an `Arr`.  So I can't use my custom `UserInput` type.  If I try to make this a type family:

```haskell
data Id
data Write
data View

type family C f h d m where
  C Id h d m = TableRecordField ('H HT) h d (OENullable m) (OEOptional m)
  C Write h d m = TableRecordField ('H WT) h d (OENullable m) (OEOptional m)
  C View h d m = TableRecordField ('H OT) h d (OENullable m) (OEOptional m)
``` 

Then I get stuck with the `pAccount` function not working with `(:<$>)`, which I'm afraid the SKI stuff is way over my head so I don't know how to glue this all together.

I'm hoping someone can help me achieve my end goal whether or not it looks anything at all like the code I've posted here.

Thanks!

**Comment by tomjaguarpaw** [comment]
A solution which apes the implementation of `TableRecordField` seems to work fine.  Then you just need type synonyms for `'H Id`, `'H Write` and `'H View` like [appear in `Opaleye.Internal.TypeFamiles`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/TypeFamilies.hs#L76-L80).

It's unlikely that there's a more direct style using `:<$>` and `:<*>` because `OEOptional` and `OENullable` are type families and can't be partially applied.  If you'd written them too in this "defunctionalised" style then we probably could use `:<$>` and `:<*>`.  However, I doubt that is worth it.

Please let me know how you get on.

```haskell
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE DataKinds     #-}
{-# LANGUAGE GADTs         #-}
{-# LANGUAGE PolyKinds     #-}
{-# LANGUAGE TypeFamilies  #-}
{-# LANGUAGE TypeOperators #-}

import Opaleye hiding (Nullable, View)
import Opaleye.Internal.TypeFamilies
import Data.Profunctor as P
import Data.Profunctor.Product as PP
import Data.Time (UTCTime)

data WriteMode
  = ReadOnly
  | Required
  | Optional
  | Nullable

type family OENullable f where
  OENullable 'ReadOnly = NN
  OENullable 'Required = NN
  OENullable 'Optional = NN
  OENullable 'Nullable = N

type family OEOptional f where
  OEOptional 'ReadOnly = Opt
  OEOptional 'Required = Req
  OEOptional 'Optional = Opt
  OEOptional 'Nullable = Req

data Idx
data Write
data View

data Foo a = Foo (a, a, WriteMode)

type instance A ('H Idx)   ('Foo '(h, d, m)) = TableRecordField ('H HT) h d (OENullable m) (OEOptional m)
type instance A ('H Write) ('Foo '(h, d, m)) = TableRecordField ('H WT) h d (OENullable m) (OEOptional m)
type instance A ('H View)  ('Foo '(h, d, m)) = TableRecordField ('H OT) h d (OENullable m) (OEOptional m)

type Cx f a b c = A f ('Foo '(a, b, c))

data AccountId

data Account f = Account
  { pk :: Cx f AccountId SqlUuid 'ReadOnly
  , created_at :: Cx f UTCTime SqlTimestamptz 'ReadOnly
     -- more fields here...
  }

pAccount
  :: PP.ProductProfunctor p
  => Account (p :<$> a :<*> b)
  -> p (Account a) (Account b)
pAccount w = Account PP.***$ P.lmap pk         (pk w)
                     PP.**** P.lmap created_at (created_at w)

pAccount' :: PP.ProductProfunctor p
          => Account (p :<$> ('H Idx) :<*> ('H Write))
          -> p (Account ('H Idx)) (Account ('H Write))
pAccount' = pAccount
```

**Comment by pjones** [comment]
This is fantastic @tomjaguarpaw!  Thank you so much!

The next thing on my list is to encode the column names as type level strings similar to what is shown in #425.  Then I can use Generics or TH to generate the `Table` and `Default` code.

@0xd34df00d would you be willing to share the code you wrote to make #425 compile?

**Comment by pjones** [comment]
I'm going to go ahead and close this.  Any discussion about column names in type families probably belongs on #425 

Thanks again Tom.

**Comment by tomjaguarpaw** [comment]
You're welcome!

**Comment by pjones** [comment]
@tomjaguarpaw For what it's worth, [this is what I came up with](https://github.com/pjones/iolaus/blob/master/opaleye/src/Iolaus/Database/Table.hs).

Thanks again for all your help and most of all, Opaleye!
