### ISSUE TITLE
Insert with a join operation

### ISSUE THREAD

**Issue by delanoe** [tomjaguarpaw/haskell-opaleye#448]
Hello,
again many thanks for Opaleye!

Just was wondering if you would have an example of an insert using a join? 
For instance:

insert into table things (name_id)
 SELECT name.id  FROM input
 INNER JOIN name ON name.text = input.text

(I have not seen such case in code or documentation or tutorials)
Thanks in advance for your answer

**Comment by tomjaguarpaw** [comment]
Hi Alexandre, at the moment this use case is not supported.  You will have to run the select, get a list of rows in Haskell, and then run in insert to insert them.

**Comment by delanoe** [comment]
Ok thanks for the clear answer. Closing the the issue then.
