### ISSUE TITLE
PGEmail -> PGText

### ISSUE THREAD

**Issue by asheshambasta** [tomjaguarpaw/haskell-opaleye#449]
Relevant code: https://gist.github.com/asheshambasta/c4fb56fd85a07ff4c15b771ccd9ade82#file-types-hs-L124 (see the highlighted function)

So, currently, we have 2 ways of achieving type-safety over similarly SQL's typed columns: 
1. Newtypes 
2. The approach I've described in #137 (see the last comment) 

Also, as pointed out in #137, newtypes result in quite some mess with Maybes being wrapped inside the newtype. The types are isomorphic and can be handled using lenses quite easily, however, for types with some nesting etc. this can get hairy quite fast.

---

My approach here has been to define my own `PG*` types and instances for it. 

But that presents another issue: in this case, I have a `PGEmail` type, and have columns using this type. This is nothing but a `PGText` in disguise. 

Now, I'd like to be able to use the `ilike` (`ilike :: Column PGText -> Column PGText -> Column PGBool`) operator on a `PGEmail` type (treating it as a text). 
So I'd like to be able to go from `PGEmail` to `Column PGText`, but I cannot seem to see how.

How can something like this be tackled? (if it can?)

---

Possibly beneficial: https://github.com/tomjaguarpaw/haskell-opaleye/issues/274

**Comment by tomjaguarpaw** [comment]
>  So I'd like to be able to go from `PGEmail` to `Column PGText`, but I cannot seem to see how.

I assume you mean `Column PGEmail` to `Column PGText` (or as we say in the [new nomenclature](https://github.com/tomjaguarpaw/haskell-opaleye/issues/326) `Field SqlEmail` to `Field SqlText`).  If my assumption is correct, will `unsafeCoerceColumn` not do the job?

**Comment by asheshambasta** [comment]
@tomjaguarpaw ah cool; that had slipped under my radar. Closing this since it solves the issue. 
Thanks a ton!

**Comment by tomjaguarpaw** [comment]
You're welcome @asheshambasta! Feel free to get in touch any time with questions.
