### ISSUE TITLE
Prefer non-PG specific types

### ISSUE THREAD

**Issue by ndmitchell** [tomjaguarpaw/haskell-opaleye#45]
Generally, people should be using Column Bool, Column Int etc, and not Column PGBool. In SQLite columns for types such as Bool don't really exist, so must be implemented as Column SLInt. That's not enough type specificity, so should not be the preferred format.

**Comment by tomjaguarpaw** [comment]
This is not going to happen per se but there have been proposals of similar things, oten using type families.  See, for example, https://github.com/tomjaguarpaw/haskell-opaleye/issues/22
