### ISSUE TITLE
Composing a series of filters.

### ISSUE THREAD

**Issue by jhickner** [tomjaguarpaw/haskell-opaleye#46]
Hello! I've been very impressed with opaleye and I'm looking into using it on a project where I need to be able to compose a dynamic set of filters in order to build a query. It's going well but I have a couple of questions.

So, fist some setup. Given a query that returns users:
`usersQuery :: Query UserColumn`

I need to be able to compose an assortment of filters in order to get the final set of users. My filters all basically have this form: 1.) accept some users 2.) apply some filter to the users 3.) pass the filtered users along. Like this:   

    hasFeature featureID value = proc user -> do
        fv <- featureValuesQuery -< ()
        restrict -< (fvUserID .== uID user) 
                .&& (fvFeatureID .== featureID) 
                .&& (fvValue .== value)
        returnA -< user

And this all composes nicely like this:

`usersQuery >>> hasFeature 1 (pgString "foo") >>> hasFeature 2 (pgString "bar")`

So far so good. My questions are: 

1.) Is this a reasonable approach to the problem? As in, will it generate terribly inefficient SQL? Looking at the output of `printSql` it actually looks pretty reasonable.
2.) I'm currently doing this to compose my list of filters: `foldl' (>>>) usersQuery [f1, f2...]`. Is there a more idiomatic way to fold over a bunch of arrows?

Thank you!

EDIT: Also, how would I use `count` to get the number of rows returned?
I'm currently doing this but it seems cumbersome and specific to the type of row I'm counting: `aggregate count (usersQuery >>^ uID)`

**Comment by tomjaguarpaw** [comment]
1.) It seems reasonable.  Each application of `hasFeature` should just add conditions to the WHERE clause of the existing SELECT.

2.) I don't think there's an obviously better way.  Your `foldl'` seems compact and clear.

There's currently no way of doing a general count.  I opened this issue: https://github.com/tomjaguarpaw/haskell-opaleye/issues/47

**Comment by jhickner** [comment]
Thank you!
