### ISSUE TITLE
Do we really need BinarySpec?

### ISSUE THREAD

**Issue by duairc** [tomjaguarpaw/haskell-opaleye#462]
I've been doing some experiments with Postgres and i noticed this;

```sql
(select column1 as bar from ( values (4), (5) ) "T") UNION ALL (select column1 as foo from ( values (1), (2) ) "T");
 bar 
-----
   4
   5
   1
   2
(4 rows)
```

Basically, binary operations (`UNION`, `INTERSECT`, `EXECPT`) seem to take their column names from the left operand by default.

If I'm not completely mistaken, this means `sameTypeBinopHelper` could be rewritten as:

```haskell
sameTypeBinOpHelper :: PQ.BinOp -> Q.Query columns -> Q.Query columns -> Q.Query columns
sameTypeBinOpHelper binop q1 q2 = Q.simpleQueryArr q where
  q ((), startTag) = (columns1, newPrimQuery, T.next endTag)
    where (columns1, primQuery1, midTag) = Q.runSimpleQueryArr q1 ((), startTag)
          (columns2, primQuery2, endTag) = Q.runSimpleQueryArr q2 ((), midTag)
          newPrimQuery = PQ.Binary binop [] (primQuery1, primQuery2)
```

The nice thing about this is means that `unionAll` would no longer need a `Default` constraint. This opens up the possibility of making an `Alternative` (or at least `Alt`) instance for `Query`l

**Comment by tomjaguarpaw** [comment]
`BinarySpec` is needed not to conjure up the names of the output columns but to generate SQL which links the column names in `columns1` to column names in `columns2`.  `primQuery1` and `primQuery2` can contain entirely different column names.  They are not identified by position (or if they are that is accidental) but by name.  Something needs to say "the column called `bar` in `primQuery1` is the same one as (i.e. should be binop-ed with) the column called `foo` in `primQuery2`".  It's possible we could simplify the constraint, but I think that removing it entirely is impossible.

**Comment by duairc** [comment]
Are you sure, do you have a source for that? I haven't read the SQL spec or anything, but at least empirically that doesn't seem to be true, unless I'm misunderstanding.

If we take these two queries:

```sql
=> select column1 as foo, column2 as bar from ( values ('foo', 'bar'), ('foo', 'bar') ) "T";
 foo | bar 
-----+-----
 foo | bar
 foo | bar
(2 rows)
```

and

``` sql
=> select column1 as bar, column2 as foo from ( values ('foo', 'bar'), ('foo', 'bar') ) "T")
 bar | foo 
-----+-----
 foo | bar
 foo | bar
(2 rows)
```

If I'm understanding you correctly, you're saying the result should be:

```
 foo | bar 
-----+-----
 foo | bar
 foo | bar
 bar | foo
 bar | foo
(4 rows)
```

But for me it's:

```sql
=> (select column1 as foo, column2 as bar from ( values ('foo', 'bar'), ('foo', 'bar') ) "T") UNION ALL (select column1 as bar, column2 as foo from ( values ('foo', 'bar'), ('foo', 'bar') ) "T");
 foo | bar 
-----+-----
 foo | bar
 foo | bar
 foo | bar
 foo | bar
(4 rows)
```

That is, position seems to be the only thing that matters.

**Comment by tomjaguarpaw** [comment]
I mean that Opaleye doesn't keep track of columns by position. It only uses their names, in `Column`s (or `Field`s, as they're now called).  I believe that makes your suggestion infeasible, but happy to be proved wrong, as it would be a nice API improvement.

**Comment by tomjaguarpaw** [comment]
To be more specific, `map fst q` and `map snd q` are distinct queries but they only differ in the values of their `columns`, i.e. the first component of the triple.  Since your proposed implementation doesn't use `columns2` I don't think it can be correct.

**Comment by duairc** [comment]
Ah, right, I see the issue now. Yeah, I can't think of a way around this!
