### ISSUE TITLE
What is the unique best Haskell type to map Postgres text to?

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#477]
I am adding inferrable instances for running queries so that, for example, if you have a `(Field SqlInt4, Field SqlFloat8)` it can be inferred that running the query returns you an `(Int, Double)`.

What should [Postgres `text`](https://www.postgresql.org/docs/9.1/datatype-character.html) map to? I'm guessing either `String` (for simplicity) or strict `Text` (for speed) and leaning towards the latter.

This is a fairly important decision as it can only be changed by introducing a whole new product profunctor to attach the inferrable `Default` instances to, and writing out the instances all over again!

cc @ocharles @duairc @saurabhnanda

**Comment by saurabhnanda** [comment]
My vote is for `Text` from the top of my head.

**Comment by ocharles** [comment]
I second the suggestion to use (strict) Text

**Comment by saurabhnanda** [comment]
Does this mean opaleye is getting more opinionated and will get better at
type inference of query results?

**Comment by tomjaguarpaw** [comment]
Yes indeed. I added `runSelectI` that has much better inference properties.  There's also 'toFieldsI` for doing the same for creating `Field`s.

https://hackage.haskell.org/package/opaleye-0.6.7006.0/docs/Opaleye-RunSelect.html#v:runSelectI

https://hackage.haskell.org/package/opaleye-0.6.7006.0/docs/Opaleye-ToFields.html#v:toFieldsI
