### ISSUE TITLE
Possible to use SelectArr with arguement in monadic style?

### ISSUE THREAD

**Issue by jaredramirez** [tomjaguarpaw/haskell-opaleye#482]
Given the query:
```haskell
proc () -> do
  row1 <- Opaleye.selectTable Table1.table -< ()
  Opaleye.restrict -< ...
  maybeRow2 -< Opaleye.optionalRestrict (Opaleye.selectTable Table2.table) <-  (\row2 -> row2.fkId .=== row1.id)                                                                                                            
  returnA -< (row1, maybeRow2)
```
Can I use `optionalRestrict` in the monadic style? I don't really understand Arrows. I can figure out how to use them, but I don't get how they work exactly. My best guess is that I need to somehow use `app :: a (a b c, b) c ` from `ArrowApply` based on the [docs](https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Arrow.html#t:ArrowApply) where it says `Such arrows [that implement ArrowApply] are equivalent to monads`.
I gave it a shot:
```haskell
do
  row1 <- Opaleye.selectTable Table1.table
  Opaleye.where_ (...)
  maybeRow2 <-
     app
       (Opaleye.optionalRestrict (Opaleye.selectTable Table2.table))
       (\row2 -> row2.fkId .=== row1.id)
       -- ??? Clearly wrong, I don't quite understand the app type sig either
  pure (row1, maybeRow2)
```

Thanks for the great library. Excited for monadic style to reduce the Arrow learning curve in Opaleye!

**Comment by tomjaguarpaw** [comment]
Do you want

```haskell
viaLateral (optionalRestrict (selectTable table)) (\row2 -> row2.fkId .=== row1.id)
```

https://hackage.haskell.org/package/opaleye-0.7.1.0/docs/Opaleye-Lateral.html#v:viaLateral

You might find it easier to use `optional` though, which would be something liek

```haskell
optional $ do
    row2 <- Opaleye.selectTable table
    viaLateral restrict (row2.fId .=== row1.id)
    pure row2
```    

> Thanks for the great library. Excited for monadic style to reduce the Arrow learning curve in Opaleye!

Cool, glad you're enjoying it!

**Comment by jaredramirez** [comment]
`viaLateral` is exactly what I was looking for, thank you!
