### ISSUE TITLE
How to get column names and types

### ISSUE THREAD

**Issue by limick** [tomjaguarpaw/haskell-opaleye#485]
First of all, thanks for such a great library. It's been extremely reliable so far.

That said, my main issue is keeping the types in sync with the actual tables in the DB when the latter evolve. I'd like to create a tool that uses `information_schema.columns` (table_name, column_name, is_nullable, data_type) to check if my description in terms of types matches with reality. This would also be required for automatic migrations.

I managed to get the column names from a value of type `Table w r` using `collectPEs`, but after a few hours of struggling with Profunctors and `Unpackspec`, I haven't found a way to get the PostgreSQL types (`bigint`, `boolean`, `text`, etc.). I guess I need to apply `showSqlType` somewhere, but I'm not sure how.

Any pointers for how to go about that?

**Comment by tomjaguarpaw** [comment]
> thanks for such a great library. It's been extremely reliable so far.

Great! I'm glad to hear it's working well for you.

In this situation it's generally best to define a new product profunctor to do exactly what you want to do rather than try to reuse any of the existing ones that weren't designed for it. Does the function `fieldsAndTypes` below do what you want? Beware though: Opaleye never actually stores the column names or types (although it may do so in the future because without doing so it can't generate schema generation code, which is a bit sad). The best we can do (at the moment) is hope that the `Table`s read columns are indeed the Postgres base table's column names and column types. If not then you will get the behaviour of `example2`.

```hs
-- Requires Opaleye 0.7.1.0

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE MultiParamTypeClasses #-}

module Example where

import Opaleye
import Opaleye.Internal.Column
import Opaleye.Internal.Helpers
import Opaleye.Internal.Table
import Opaleye.Internal.HaskellDB.PrimQuery
import Data.Profunctor
import Data.Profunctor.Product
import Data.Profunctor.Product.Default

data SqlType = SqlInt4
             | SqlFloat8
             deriving Show

-- Define a product profunctor for doing the job.  Instances are
-- boilerplate (see below).
data NameAndType a b =
  NameAndType { unNameAndType ::  a -> [(Maybe String, SqlType)] }

-- Define a helper function for the Default instance and the Default
-- instances below.
sqlField :: SqlType -> NameAndType (Field a) b
sqlField t = NameAndType (pure . withType . column . unColumn)
  where withType x = (x, t)
        column = \case
          BaseTableAttrExpr s -> Just s
          _ -> Nothing

instance Default NameAndType (Column SqlInt4) (Column SqlInt4) where
  def = sqlField SqlInt4

instance Default NameAndType (Column SqlFloat8) (Column SqlFloat8) where
  def = sqlField SqlFloat8

-- Define the explicit version of the function that uses NameAndType,
-- and its implicit (typeclass parametric) version below.
fieldsAndTypesExplicit :: NameAndType r a
                       -> Table w r
                       -> [(Maybe String, SqlType)]
fieldsAndTypesExplicit n = unNameAndType n . columnsOfTable
  where -- May need updating in future versions of Opaleye
        columnsOfTable :: Table w r -> r
        columnsOfTable = \case
          Table _ (TableFields _ (View v)) -> v
          TableWithSchema _ _ (TableFields _ (View v)) -> v

fieldsAndTypes :: Default NameAndType r r
               => Table w r
               -> [(Maybe String, SqlType)]
fieldsAndTypes = fieldsAndTypesExplicit (atSameType def)

-- Some examples.  Beware of example2!

exampleTable :: Table (Field SqlInt4, Field SqlFloat8)
                      (Field SqlInt4, Field SqlFloat8)
exampleTable = table "table_name" (p2 (tableField "int_col",
                                       tableField "float_col"))

example1 :: [(Maybe String, SqlType)]
example1 = fieldsAndTypes exampleTable

-- > example1
-- [(Just "int_col",SqlInt4),(Just "float_col",SqlFloat8)]

example2 :: [(Maybe String, SqlType)]
example2 = fieldsAndTypes ((fmap . fmap) (+1) exampleTable)

-- > example2
-- [(Just "int_col",SqlInt4),(Nothing,SqlFloat8)]

-- Once we have chosen the implementation of NameAndType these are
-- boilerplate
instance Profunctor NameAndType where
  dimap f _ (NameAndType g) = NameAndType (dimap f id g)

instance Functor (NameAndType a) where
  fmap f = dimap id f

instance Applicative (NameAndType a) where
  pure _ = NameAndType mempty
  NameAndType f <*> NameAndType g = NameAndType (\a -> f a ++ g a)

instance ProductProfunctor NameAndType where
  purePP = pure
  (****) = (<*>)
```

**Comment by limick** [comment]
Thank you for your very generous answer. If this was some kind of homework I would be far into cheating territory now.
If I manage to create a potentially useful tool I hope to at least publish it in a gist or something.
