### ISSUE TITLE
Dummy Columns?

### ISSUE THREAD

**Issue by remeike** [tomjaguarpaw/haskell-opaleye#492]
Ok, so this may very well be a terrible idea, but I was wondering if it's possible to create a `TableFields` value that doesn't actually correspond to a table column. 

This came to mind because sometimes I find that it would be convenient to have polymorphic data types include more fields than their corresponding tables. So in this example we have the field, `hats`, for which there's no column in the table, so it's just a unit. But then maybe I want to be able to fill that in later, perhaps via a join.

```
data PersonT a b c =
  Person
    { name :: a
    , age  :: b
    , hats :: c
    }

type WritePerson =
  PersonT
    (Field SqlText)
    (Field SqlInt4)
    ()

type ReadPerson =
  PersonT
    (Field SqlText)
    (Field SqlInt4)
    ()

type ReadHattedPerson =
  PersonT
    (Field SqlText)
    (Field SqlInt4)
    (Field SqlInt4)

type HattedPerson =
  PersonT
    Text
    Int
    Int

makeAdaptorAndInstance "pPerson" ''PersonT

personsTable :: Table WritePerson ReadPerson
personsTable =
  Table "persons" . pPerson $
    Person
      { name = requiredTableField "name"
      , age  = requiredTableField "age"
      , hats = ????
      }
```

Obviously I can get by just fine by creating an entirely different data type for `HattedPerson` but I was just wondering if this sort of thing was possible as a convenience.

**Comment by tomjaguarpaw** [comment]
Yes, you should be able to do the following.  I'd be interested in learning how well it works for you!

```haskell
personsTable :: Table WritePerson ReadPerson
personsTable =
  Table "persons" . pPerson $
    Person
      { name = requiredTableField "name"
      , age  = requiredTableField "age"
      , hats = pure ()
      }
```

**Comment by remeike** [comment]
Omg, of course. That works! Thanks again. I now close this issue in shame!

**Comment by tomjaguarpaw** [comment]
Nothing to be ashamed about.  I dove into the source code of `Opaleye/Internal/Table.hs` before I realised what it should be!
