### ISSUE TITLE
`null` conflicts with the Prelude export

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#5]
Perhaps rename `null` to `nullColumn`

First reported by bergmark here: https://github.com/karamaan/karamaan-opaleye/issues/75

**Comment by hesselink** [comment]
Some packages (e.g. [blaze-html](http://hackage.haskell.org/package/blaze-html-0.8.1.1/docs/Text-Blaze-Html5-Attributes.html#v:class_)) use trailing underscores for identifiers that are keywords or clash with the prelude, so you'd get `null_`, `not_`, `sum_` etc.

**Comment by tomjaguarpaw** [comment]
I'm closing this because it's very old and I don't have any concrete plans to address it.  If you think it still needs addressing or have any further details to add then please reopen or file a new issue.
