### ISSUE TITLE
Example of parameterised select

### ISSUE THREAD

**Issue by uliSchuster** [tomjaguarpaw/haskell-opaleye#503]
Maybe this is a trivial question, but I am stuck on simple parameterised queries.

With the update to V 0.7, it seems that arrow notation has been replaced by more friendly monadic do notation. However, I am now at loss how to pass in query parameters. It would be great to have a simple example in the tutorial.

E.g., if the max. age in the [birthday example](https://github.com/tomjaguarpaw/haskell-opaleye/blob/326a7d2469c3fcbdff5de393ea67f57d4dcde7fc/Doc/Tutorial/TutorialBasic.lhs#L253) would be passed as a parameter, how would the `SelectArr` look like? And how would that query need to be run using `runSelect`?

**Comment by tomjaguarpaw** [comment]
Looks like this is solved. Feel free to open a new issue if you have any more questions.
