### ISSUE TITLE
Add Shane @duairc as backup maintainer

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#507]
@duairc, would you be willing to be a backup maintainer for Opaleye in the same way as Ollie, i.e. as described [in the README](https://github.com/tomjaguarpaw/haskell-opaleye/tree/326a7d2469c3fcbdff5de393ea67f57d4dcde7fc#backup-maintainers)? Hopefully, and most likely, you wouldn't have to do anything at all. I just think it would be helpful to the Opaleye community to have another backstop.

If you would be willing, would you also be willing to have your surname mentioned in the README, and could you let me know your Hackage user name, so I can assign you maintainer rights?

**Comment by duairc** [comment]
Sure. My surname is O'Brien and my Hackage username is ShaneOBrien.

**Comment by tomjaguarpaw** [comment]
Thanks! Will get this sorted out soon.

**Comment by tomjaguarpaw** [comment]
You are now a maintainer on the Github repo and Hackage. Thanks!

**Comment by tomjaguarpaw** [comment]
Hi @duairc the invitation to the repository is still outstanding. Could you accept it so we can be sure you have access?
