### ISSUE TITLE
Adding `now()` function support

### ISSUE THREAD

**Issue by njaremko** [tomjaguarpaw/haskell-opaleye#508]
Would a PR adding support for the `now()` function be welcomed? Maybe it's just me, but I use it frequently, so it's absence from opaleye has been a pain in the butt :)

**Comment by tomjaguarpaw** [comment]
Sure, go for it!

**Comment by basvandijk** [comment]
I see there already is a [now](https://hackage.haskell.org/package/opaleye-0.7.3.0/docs/Opaleye-Operators.html#v:now) function.

**Comment by tomjaguarpaw** [comment]
Yes, we can close this. Thanks for noticing.
