### ISSUE TITLE
Question/typo for insert example in tutorial

### ISSUE THREAD

**Issue by chris-martin** [tomjaguarpaw/haskell-opaleye#515]
Why does `id` get set to `DEFAULT` in this query?

https://github.com/tomjaguarpaw/haskell-opaleye/blob/2f82b7d085053d59275e36737284f7b20cfd006d/Doc/Tutorial/TutorialManipulation.lhs#L140

**Comment by tomjaguarpaw** [comment]
Good catch. It doesn't!

```
*TutorialManipulation Opaleye.Internal.Manipulation> putStrLn $ case update of Update {..} -> arrangeUpdateSql uTable uUpdateWith uWhere
UPDATE "tablename"
SET "id" = "id",
    "x" = ("x") + ("y"),
    "y" = ("x") - ("y"),
    "s" = "s"
WHERE (("id") = (CAST(5 AS integer)))
```

Thanks for the report. I'll get this fixed at some point, unless you want to submit a PR. Just requires changing `SET "id" = DEFAULT,` to `SET "id" = "id",`.

**Comment by chris-martin** [comment]
Thanks, that's what I hoped :smile: PR submitted.
