### ISSUE TITLE
Release of 0.8 imminent

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#534]
The release of 0.8 is imminent. It might be worth checking that nothing horrendously breaks for you.  See [the CHANGELOG](https://github.com/tomjaguarpaw/haskell-opaleye/blob/rc2/CHANGELOG.md#0800). It's mostly deprecations and removals of previous deprecations. It does *not* contain `Column` -> `Field`. I keep putting that off.

cc @ocharles @duairc

**Comment by ocharles** [comment]
Thanks for the ping. This is probably going to break quite a bit of Rel8 as we still use a lot of internals, but I'm sure we can get that adapted quick enough. I'd say press on whenever you're ready, we'll catch up!

**Comment by tomjaguarpaw** [comment]
Published as https://hackage.haskell.org/package/opaleye-0.8.0.0

I think breakage should be minimal for anyone not using deprecated identifiers.
