### ISSUE TITLE
Insert a user defined record type?

### ISSUE THREAD

**Issue by jhickner** [tomjaguarpaw/haskell-opaleye#54]
Given these types:

    data User' a b = User {uID :: a, uEmail :: b} deriving (Show)
    type User = User' Int Text
    type UserColumn = User' (Column PGInt4) (Column PGText)

I can run a query and get back `IO [User]` rather than `IO [UserColumn]` which is great. But is there any way to insert a `User` without first manually converting it to a `UserColumn`?

**Comment by tomjaguarpaw** [comment]
Not currently, but it's often been asked for so I'll bump it up my list of priorities.

This is basically https://github.com/tomjaguarpaw/haskell-opaleye/issues/28

**Comment by tomjaguarpaw** [comment]
Done.  Use `constant`.  Regrettably this will typicall require explicit types.  Please file an new issue if that is inconvenient.

https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Constant.hs
