### ISSUE TITLE
More type safety with same field type in a table

### ISSUE THREAD

**Issue by stevemao** [tomjaguarpaw/haskell-opaleye#570]
I can put createdAt in place of updatedAt and this can cause a bug without compilation errors

- I have a table with `createdAt` and `updatedAt`. 
- They are both `SqlTimestamptz`

Here is what I got to fix the problem:

```haskell
newtype CreatedAt
  = CreatedAt { unCreatedAt :: UTCTime }
  deriving (PSG.FromField)

newtype PGCreatedAt
  = PGCreatedAt O.PGTimestamptz

pgUTCTime' :: Time.ISO8601 t => t -> O.Field a
pgUTCTime' = IPT.unsafePgFormatTime "timestamptz"

instance O.DefaultFromField PGCreatedAt CreatedAt where
  defaultFromField = O.fromPGSFromField

instance Default O.ToFields CreatedAt (O.Column PGCreatedAt) where
  def = O.toToFields (pgUTCTime' . unCreatedAt)

now' :: O.Field a
now' = O.Column $ HPQ.FunExpr "now" []

nowCreatedAt :: O.Field PGCreatedAt
nowCreatedAt = now'
```

This way PGCreatedAt can be only mapped from CreatedAt

Is this the correct way to do it? 
If so, I can submit a PR to add more polymorphic functions such as `pgUTCTime'` and `now'`

**Comment by tomjaguarpaw** [comment]
Actually, I'd suggest

```hs
newtype CreatedAt a
  = CreatedAt { unCreatedAt :: a }
```

and then use `CreatedAt UTCTime` and `CreatedAt SqlTimestamptz`. There's even a module [`Data.Profunctor.Product.Newtype`](https://hackage.haskell.org/package/product-profunctors-0.11.1.1/docs/Data-Profunctor-Product-Newtype.html) to help with that.

Let me know if that helps or if you'd like more guidance.

**Comment by stevemao** [comment]
Thanks so much! 

It's very clean and we don't need to change in the library

I had to update GHC to the latest version to make this work.

`instance Default O.FromFields SqlCreatedAt HCreatedAt` doesn't seem necessary and it's already defined in `$(makeAdaptorAndInstance "pCreatedAt" ''CreatedAt)`

When defining table fields, you just need to do

```
entityCreatedAt = pNewtype $ requiredTableField "created_at"
```

**Comment by tomjaguarpaw** [comment]
Ah yes, nice!

**Comment by tomjaguarpaw** [comment]
Pasting the complete simplest version, for posterity:

```.hs
{-# LANGUAGE TypeSynonymInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TemplateHaskell #-}

import Opaleye as O
import Data.Profunctor.Product.TH
import Data.Aeson
import Data.Time

newtype CreatedAt a
  = CreatedAt { unCreatedAt :: a }
  deriving (ToJSON)

$(makeAdaptorAndInstance "pCreatedAt" ''CreatedAt)

type HCreatedAt
  = CreatedAt UTCTime

type SqlCreatedAt
  = CreatedAt (O.Field O.SqlTimestamptz)

nowCreatedAt :: SqlCreatedAt
nowCreatedAt = CreatedAt O.now
```
