### ISSUE TITLE
disallow `orderAggregate` with `distinctAggregator`

### ISSUE THREAD

**Issue by stevemao** [tomjaguarpaw/haskell-opaleye#587]
Using `orderAggregate` with `distinctAggregator` will generate something like this

```sql
ARRAY_AGG(DISTINCT "inner2_5" ORDER BY "a" ASC NULLS LAST) as "result2_5"
```

Which will cause 

```
SqlError {sqlState = \"42P10\", sqlExecStatus = FatalError, sqlErrorMsg = \"in an aggregate with DISTINCT, ORDER BY expressions must appear in argument list\", sqlErrorDetail = \"\", sqlErrorHint = \"\"}
```

The correct way to do it is to use `distinctOn` [in the inner sql](https://stackoverflow.com/questions/25180418/ordering-distinct-column-values-by-first-value-of-other-column-in-aggregate-fu/25181698#25181698)

However, based on the current type system is might be hard to create a type error. It might be possible to create a warning?

**Comment by stevemao** [comment]
Or perhaps we can deprecate `distinctAggregator` in favour of `distinctOn`? I can't think any case `distinctAggregator` can do but `distinctOn` can't

**Comment by tomjaguarpaw** [comment]
Can you please share a small example that generates this crashing code?

**Comment by stevemao** [comment]
Yes, just clone https://github.com/stevemao/opaleye-order-distinct-aggregator and run `docker compose up`.

**Comment by tomjaguarpaw** [comment]
Thanks. I believe this will be fixed by https://github.com/tomjaguarpaw/haskell-opaleye/pull/586. Perhaps you'd like to try it.

**Comment by stevemao** [comment]
@tomjaguarpaw still the same error https://github.com/stevemao/opaleye-order-distinct-aggregator/tree/aggregate

**Comment by tomjaguarpaw** [comment]
Could you double check? This works fine, for example: https://github.com/tomjaguarpaw/haskell-opaleye/commit/a9e6fe209a088d90996d4a2cbf03dd4b42036b1a

(I don't have the ability to run Docker here)

**Comment by tomjaguarpaw** [comment]
(And see here for the test run: https://github.com/tomjaguarpaw/haskell-opaleye/actions/runs/7669040691)

**Comment by tomjaguarpaw** [comment]
If you still think there's a problem, could you come up with a failing test case that I can add to `Test.hs`?

**Comment by stevemao** [comment]
My bad. it is indeed working now https://github.com/stevemao/opaleye-order-distinct-aggregator/actions/runs/7676483130/job/20924091643

**Comment by tomjaguarpaw** [comment]
Great, glad it works for you.
