### ISSUE TITLE
Allow for bytestring >=0.12 in cabal file

### ISSUE THREAD

**Issue by tysonzero** [tomjaguarpaw/haskell-opaleye#596]
I think I'm technically already using `bytestring-0.12.1.0` and it seems to be working fine, but if I explicitly add `bytestring >=0.12` to the cabal file it no longer builds with nix+cabal as it can't find a working build plan.

Doesn't seem very logical to me as I don't think it ever actually uses the older bytestring version it presumably found to satisfy the build plan, but that's outside the scope of this repo.

**Comment by tomjaguarpaw** [comment]
Hackage revision -r1 made: https://hackage.haskell.org/package/opaleye-0.10.3.1/revisions/
