### ISSUE TITLE
Generalize `in_`

### ISSUE THREAD

**Issue by tysonzero** [tomjaguarpaw/haskell-opaleye#602]
The current type is:

```
in_ :: (Functor f, Foldable f) => f (Field a) -> Field a -> Field SqlBool
```

But it seems like a nicer type would be:

```
in_ :: (Default EqPP fields fields, Foldable f) => f fields -> fields -> Field SqlBool
```

We can drop the `Functor` as the mapping is/can-be done after the `toList`/`foldr` type stuff, and we take advantage of the `Default EqPP` machinery that `.===` uses since `IN` seems to work just fine in PostgreSQL on products/tuples.

This should close #404, #406, #419 and the issue is mentioned in open issues #431 and #599.

**Comment by tomjaguarpaw** [comment]
This seems like a good idea. Is it a breaking change? If so it would prefer to introduce it under a new name first, but I'm struggling to think of any code that could be broken by this.

**Comment by ocharles** [comment]
Anything that wraps `in_` and has a type signature (`myIn = in_`) would break, because the type has changed. It's hypothetical, but probably a better path than trying to find a threshold of "realistic" breaks

**Comment by ocharles** [comment]
Oh wait, maybe I'm wrong because `Field a` has that instance? Might be worth checking that one,

**Comment by tysonzero** [comment]
Yes `Field a` does have that instance. Should be a strict generalization, so only breakage I can think of would be if it leads to type ambiguity or if someone's using TypeApplications on it.

**Comment by tomjaguarpaw** [comment]
@tysonzero: can you confirm whether this does the job? https://github.com/tomjaguarpaw/haskell-opaleye/pull/604

**Comment by tomjaguarpaw** [comment]
Oh yeah, thanks. Please take another look: https://github.com/tomjaguarpaw/haskell-opaleye/pull/604

(Regarding performance, let's leave that as a potential future optimization. I don't want to get into the weeds of that.)

**Comment by tysonzero** [comment]
Then yes that seems reasonable!

**Comment by tomjaguarpaw** [comment]
Thanks for your input. If Opaleye contains blockers for you or even stuff that you find just unergonomic then please keep prompting me about it.
