### ISSUE TITLE
Could not deduce Default from context (runSelect)

### ISSUE THREAD

**Issue by xave** [tomjaguarpaw/haskell-opaleye#605]
I am using Opaleye with a DB Connection Pool stored in an environmental context like so:  `WithDB env m`. Therefore, I access that `env` to get a `DBPool` that has already been set up by the time my functions want to use it.

Because of the type signature of the `runSelect`, `runUpdate`, etc. commands, I have wrapped them in a function that gets the context and passes it through. This type of function works fine:

```
runInsertWithPool :: WithDB env m 
                  => O.Insert haskells -> m haskells
runInsertWithPool insert = do
    pool <- grab @DBPool  -- asks the MonadReader for this value
    liftIO $ withResource pool $ \conn -> O.runInsert conn insert
```

However, the `Select` variant gives an error related to specializing a type signature. That function is: 
```
runSelectWithPool :: (WithDB env m, Default (Inferrable O.FromFields) fields haskells) 
                  => O.Select fields -> m [haskells]
runSelectWithPool select = do
    pool <- grab @DBPool
    liftIO $ withResource pool $ \conn -> O.runSelectI conn select
```

When run in the `App` monad like so

```
func  = do
    _runTheSelect <- runSelectWithPool $ (selectUserByLoginName "testName") 
    ...
```
this gives an error of the style:
```
Couldn't match type: [haskells]
                           with  MyDataTypeT
                                         Int
                                         Text
                                         Text
```
---

While it seems that the answer is to specialize each Select query, I am having trouble doing that with the generic functionality of `runSelectWithPool`. And of course, part of that genericness is because I need to pass my connection pool in rather than one single connection.         

Regarding the type signature, I can probably get away with just:
`runSelectWithPool :: (WithDB env m) =>  O.Select fields -> m [haskells]`

but `ghc` complains about that `Default` fields regardless.

**Comment by xave** [comment]
[This sort of stackoverflow answer](https://stackoverflow.com/questions/39305513/opaleye-query-by-string-to-maybe) is helpful, but specializing the function that wraps it seems like a slightly different thing.

**Comment by xave** [comment]
Perhaps the issue is that I am not actually *using* the Select for anything, which makes it hard for the compiler to infer the type.

**Comment by xave** [comment]
Hmmm...sure enough. Doing this kind of thing made the type checker happy

func  = do
    _runTheSelect <- runSelectWithPool $ (selectUserByLoginName "testName") 
    let foo = fmap myRecordField _runTheSelect
    ...

**Comment by tomjaguarpaw** [comment]
> Perhaps the issue is that I am not actually using the Select for anything, which makes it hard for the compiler to infer the type.

It looks like you _were_ using the (result of the) `Select` for something, specifically something that required a `MyDataTypeT Int Text Text`, but `runSelectWithPool` returns a list, so it couldn't possibly match.

**Comment by xave** [comment]
Interesting. I am using `web-inv-routes`, so this is all happening in a `RouteAction`.

The function this is in has this type signature:

```
func ::  RouteAction () (App Response)
func =  <route setup stuff> `RouteAction`  \() -> do
    ...
   _runTheSelect <- runSelectWithPool $ (selectUserByLoginName "testName") 
    let foo = fmap myRecordField _runTheSelect
    ...
    returnResponseForThisRoute
```

At the time of the post, I was trying to get the `Select` to work, so in my mind I was not yet using it for anything (until defining `foo`.  But the compiler may see things differently.

**Comment by xave** [comment]
A brief crash course on `web-inv-route`:


In `func ::  RouteAction () (App Response)`, the first `()` means that the route takes no input params. So this route could be something like a `GET mysite.com`.  And then in the lambda after the `RouteAction`, it is expecting the same (zero, in this case) amount of params.

**Comment by tomjaguarpaw** [comment]
So how did `MyDataTypeT Int Text Text` arise, in the case where you used `runSelectWithPool` but did not use the return value for anything?

**Comment by tomjaguarpaw** [comment]
And, what happens if you take the version that you have working now, and add another call

```.hs
   _runTheSelect2 <- runSelectWithPool $ (selectUserByLoginName "testName") 
```

in there somewhere? Can you reproduce the problem?

**Comment by xave** [comment]
The `selectByLoginName :: Text -> Select MyDataTypeTableR`

But I guess that's all *in medias res*, so...

```
data MyDataTypeT a b c = MyDataType
    {id ::a 
    , username :: b
    , pass ::c
    } 
    deriving (Show)

type MyDataType = MyDataTypeT 
    Int
    Text
    Text

type MyDataTypeTableR = 
    MyDataType 
        (Field SqlInt8)
        (Field SqlText)
        (Field SqlText)
```

Then we get to the `Select` definition above, using `MyDataTypeTableR`.

**Comment by xave** [comment]
Philosophically, it does make sense that I should actually use a select's output, otherwise, why run it at all? But if this seems to not be an issue I should run into, I am happy to keep troubleshooting. At the moment, I can select and print to stdout the output of a select, which was my goal. I just had to do something with it in order for the compiler to be happy. 

So as of now, if nothing changes, I would read a `Could not deduce Default from context` type message as "Hey! You made a select, but you didn't actually use it anywhere. That's just work for no reason."

**Comment by xave** [comment]
I just ran a second select as you suggested. The compiler was not happy with either in the same was as with just one. 

I did remove the `foo` to do this.

So its just 
```
_runTheSelect <- ...
_runTheSelect2 <-...
returnResponseForThisRoute
```

**Comment by tomjaguarpaw** [comment]
> I just ran a second select as you suggested. The compiler was not happy with either in the same was as with just one.

Thanks. Is it exactly the same error message, i.e. the one below, or a different one?

```
Couldn't match type: [haskells]
                           with  MyDataTypeT
                                         Int
                                         Text
                                         Text
```

> Philosophically, it does make sense that I should actually use a select's output, otherwise, why run it at all? But if this seems to not be an issue I should run into, I am happy to keep troubleshooting.

Yeah, I agree, but it still should not be an issue, so I'm quite surprised it's happening. It would be good to try to get to the bottom of this if we can.

> The main point being that many tutorials do things both ways, so it is challenging to figure out a best practices path when you are deviating from the way one does it. So defining things as I have above has seemed to make sense from a step-by-step standpoint of getting my application to work.

Yeah, there are different ways of doing things, and I guess different places explain it differently. Would you mind linking a couple of places that do it different ways, so I can see what you mean?

**Comment by xave** [comment]
Yes, these are four repos I have used for inspiration:

1. [Vacation Labs](https://github.com/vacationlabs/haskell-webapps/blob/7cbc95646693e105798b7bc0ce64602ef91be196/doc/docs/opaleye/code/opaleye-readonly.hs#L276)
2. [Funky Thunks](https://github.com/funky-thunks/valdaro/blob/d6acea73da532ba0e9408acb1b771fb98d216be7/server/src/Valdaro/Security/Password.hs)
3. [HaskellTutorials](https://www.haskelltutorials.com/opaleye/instant-gratification.html)
4. Opaleye official (this repo)
5. [William Yaoh tutorials and repo](https://gitlab.com/williamyaoh/haskell-orm-comparison/-/blob/master/opaleye-impl/app/Main.hs?ref_type=heads)

[1] establishes a `readOnly` pattern for id/primary key columns. This can be useful, but that `()` can make using `updateEasy` a challenge. So far I have not found a way to use that pattern and `updateEasy` at the same time. At the moment I have elected to not use `updateEasy` with a `TODO` to write a version that works with `readOnly` pattern.

[2]  Wraps a password hash in a data type. Could be useful for changing the underlying transformation (asciiText, ByteString, etc.) without changing the interface. But this necessitates adding instances of things. Between [1] and [2] I have a notion of using `DefaultFromFields` type things, but so far have not actually needed them. Regardless, trying to make instances for this custom `PasswordHash` has not gone smoothly. Since it is not necessary for me now, again, it is a `TODO`.

[3] I think [3] and [1] are the same people. They have put lots of work into creating a tutorial, but it is a lot of surface area to cover. Lots of things are out of date (`optional` instead of `optionlTableField`). 

[3] and [5] use that polymorphic type pattern versus raw profunctors as in the Opaleye tutorial.

**Comment by xave** [comment]
> Is it exactly the same error message

If I define `runSelectWithPool` as :

`runSelectWithPool :: (WithDB env m) => O.Select fields -> m [haskells]`

I get an error at the definition of `runSelectWithPool`

```
Could not deduce (Default
                          (Inferrable O.FromFields) fields haskells)
        arising from a use of ‘O.runSelectI’
      from the context: WithDB env m
        bound by the type signature for:
                   runSelectWithPool :: forall env (m :: * -> *) fields haskells.
                                        WithDB env m =>
                                        O.Select fields -> m [haskells]
```

If I add that constraint back, it pushes the error to the call site: 

```
Ambiguous type variable ‘haskells1’ arising from a use of ‘runSelectWithPool’
      prevents the constraint ‘(product-profunctors-0.11.1.1:Data.Profunctor.Product.Default.Class.Default
                                  (Opaleye.Internal.Inferrable.Inferrable
                                     Opaleye.Internal.RunQuery.FromFields)
                                  MyDataTypeTableR
                                  haskells1)’ from being solved.
      Probable fix: use a type annotation to specify what ‘haskells1’ should be.
      Potentially matching instance:
        instance (product-profunctors-0.11.1.1:Data.Profunctor.Product.Class.ProductProfunctor
                    p,
                  product-profunctors-0.11.1.1:Data.Profunctor.Product.Default.Class.Default
                    p a1_0 a1_1,
                  product-profunctors-0.11.1.1:Data.Profunctor.Product.Default.Class.Default
                    p a2_0 a2_1,
                  product-profunctors-0.11.1.1:Data.Profunctor.Product.Default.Class.Default
                    p a3_0 a3_1,
                  product-profunctors-0.11.1.1:Data.Profunctor.Product.Default.Class.Default
                    p a4_0 a4_1) =>
                 product-profunctors-0.11.1.1:Data.Profunctor.Product.Default.Class.Default
                   p
                   (MyDataTypeT a1_0 a2_0 a3_0 a4_0)
                   (MyDataTypeT a1_1 a2_1 a3_1 a4_1)
          -- Defined in ‘Entities.MyDataType’
    • In the first argument of ‘($)’, namely ‘runSelectWithPool’
      In a stmt of a 'do' block:
        _selectUserJohhny2 <- runSelectWithPool
                                $ (selectUserByLoginName "johhny")
```

This error is identical for the two calls except for `haskells0` vs `haskells1`

**Comment by tomjaguarpaw** [comment]
Thanks, when I get some time I hope to look through the tutorials.

You should definitely include the `Default (Inferrable O.FromFields) fields haskells` constraint on `runSelectWithPool`. It sounds like you need the instance

**Comment by tomjaguarpaw** [comment]
Thanks, when I get some time I hope to look through the tutorials.

You should definitely include the `Default (Inferrable O.FromFields) fields haskells` constraint on `runSelectWithPool`. 

I think perhaps you are using `makeAdaptorAndInstance`, and to be inferrable you need to use `makeAdaptorAndInstanceInferrable`. (I suppose I need to update the documentation!)

**Comment by xave** [comment]
I'll try out `makeAdaptorAndInstanceInferrable`. This has been a great practical reason to explore profunctors. So I am learning patterns and best practices.

**Comment by tomjaguarpaw** [comment]
I'll make sure I recommend `makeAdaptorAndInstanceInferrable` in the next version. I realised I will still recommending the old one. See https://github.com/tomjaguarpaw/haskell-opaleye/commit/144ffe7fe5ada76baa2df2d6b6cb477fa2617557

**Comment by xave** [comment]
It does not error now, though I have to say that it was useful to have the unused `Select` blow up, even if the message is a bit gnarly. Could be nice to add functionality in explicitly (warning). I cannot imagine someone running an expensive `Select` only to not use it.

**Comment by tomjaguarpaw** [comment]
Cool! I'm glad we got that sorted out. Thank you for reporting this. It will make the docs better.

Regarding erroring out on an unused select, well, that's a wider-ranging problem, and Haskell has some solutions:

```
-Werror=unused-do-bind
-Werror=unused-binds
```

**Comment by xave** [comment]
I think that works for me. Thank you!
