### ISSUE TITLE
Runtime error when using Prelude.read (Inet/IP)

### ISSUE THREAD

**Issue by xave** [tomjaguarpaw/haskell-opaleye#609]
I am trying to write a Haskell representation of a postgres `inet`.

This type checks and compiles:

```
import Data.IP 

instance Default ToFields IP (Field SqlText) where
    def = toToFields $ toFields . show . ipv4

instance DefaultFromField SqlText IP where
    defaultFromField = fmap (IPv4 . read) fromPGSFromField
```

The `read` and `show` are from `Data.IP` instances of `IP`.

I read the values from a `Wai.Request`. At runtime, I get a `Prelude.read` error. There seems to be many ways of handling this:

1. https://github.com/CyberFlameGO/ihp/blob/86cb981fb3580f7c220e130af7d85abf1b160c6d/IHP/Postgres/Inet.hs#L6
2. https://github.com/circuithub/rel8/blob/06af0eac53f7c882ad34d6b58be852c2d22b759e/src/Rel8/Type.hs#L461

Not sure what the best way is. I aimed for simplicity with my solution, but that seems to not be enough.

**Comment by tomjaguarpaw** [comment]
How about try this, and then at least when it fails it will tell you what it couldn't read.

```.hs
{-# LANGUAGE GHC2021 #-}

import Data.IP 
import Text.Read
import Opaleye
import Data.Profunctor.Product.Default

instance Default ToFields IP (Field SqlText) where
    def = toToFields $ toFields . show . ipv4

instance DefaultFromField SqlText IP where
  defaultFromField = fmap (IPv4 . read) fromPGSFromField
    where
      read' s = case readMaybe s of
        Nothing -> error ("Couldn't read: " ++ s)
        Just r -> r
```

**Comment by xave** [comment]
Thank you. I mixed up two troubleshooting steps it seems. Yet overall, I have the same main problem which is an inability to write to `inet` type on postgres side. 

Initially, I had a `"localhost:3000" :: Text`, but had written a check to change that value to `"127.0.0.1" :: Text`. So we have two layers of failures. The first is a rightfully presented parse error on the first string. That error no longer appears. 

However, the actual issue is

```
SqlError {sqlState = "42804", sqlExecStatus = FatalError, sqlErrorMsg = "column \"ip_address\" is of type inet but expression is of type text", sqlErrorDetail = "", sqlErrorHint = "You will need to rewrite or cast the expression."}
```

I would prefer to have Haskell-side output this is a way that postgres likes rather than casting it on the database side.

**Comment by xave** [comment]
I guess these above instances do what I designed, which is transform between `IP` and `SqlText`. Perhaps a bit more baffling on my end is the best way to create a `SqlInet`.

**Comment by tomjaguarpaw** [comment]
Maybe this?

```.hs
{-# LANGUAGE GHC2021 #-}

import Data.IP
import Text.Read
import Opaleye
import Data.Profunctor.Product.Default

data SqlInet

instance Default ToFields IP (Field SqlInet) where
    def = toToFields $ unsafeCast "inet" . toFieldsI . show . ipv4

instance DefaultFromField SqlInet IP where
  defaultFromField = fmap (IPv4 . read) fromPGSFromField
```

**Comment by xave** [comment]
```
error:  Not in scope: type constructor or class ‘SqlInet’
...
(Field SqlInet) 
```
which is a bit odd to me as that's how the other `SqlInt2`, etc. are defined.

**Comment by xave** [comment]
Hmm...worked when I put it above everything in the file.

**Comment by tomjaguarpaw** [comment]
Yeah, `SqlInet` doesn't exist in Opaleye already. It's literally defined right there in the snippet.

**Comment by xave** [comment]
For some reason, I had to put the definition in a specific spot in the file. Above the Entity type declaration is what I did. Which is strange since Haskell should be declarative.

In any case, this did work. I wrote to the DB.

Thank you!

**Comment by tomjaguarpaw** [comment]
Oh, you probably have some TH splices in the file. You can't see future declarations across a top-level TH splice.

**Comment by xave** [comment]
That's what I was thinking. I usually avoid TH. But it seems useful for the `Opaleye` use case.
