### ISSUE TITLE
Move "unpack columns" functionality to `Unpackspec` module

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/haskell-opaleye#61]
Currently the functionality for unpacking columns is trapped inside `runQueryArrUnpack`.  Move it to the `Unpackspec` module.

    runQueryArrUnpack :: U.Unpackspec a b
                      -> Query a -> ([HPQ.PrimExpr], PQ.PrimQuery, Tag)
    runQueryArrUnpack unpackspec q = (primExprs, primQ, endTag)
      where (columns, primQ, endTag) = runSimpleQueryArrStart q ()
            f pe = ([pe], pe)
            primExprs :: [HPQ.PrimExpr]
            (primExprs, _) = U.runUnpackspec unpackspec f columns

**Comment by tstat** [comment]
Is this issue solved by [this](https://github.com/tomjaguarpaw/haskell-opaleye/pull/60/files#diff-5e4ff25d7678f2e5198a5b61b86c9b59R30), or is it talking about something different?

**Comment by tomjaguarpaw** [comment]
Ah amazing, thank you!  I've been putting off reading PRs until the weekend so I didn't even see it.

**Comment by tstat** [comment]
No problem!
