### ISSUE TITLE
Test cases broken

### ISSUE THREAD

**Issue by hesselink** [tomjaguarpaw/haskell-opaleye#67]
I wanted to add tests for #58 and found that the test cases on current master are broken. Here is the output:

```
opaleye-0.3.1.2: test (suite: test)
NOTICE:  table "TABLE2" does not exist, skipping
*** Failed! Exception: 'SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "syntax error at or near \"FROM\"", sqlErrorDetail = "", sqlErrorHint = ""}' (after 1 test):
A permutation
SELECT "column10_1" as result1_2
FROM (SELECT *
      FROM (SELECT *
            FROM (SELECT *
                  FROM (SELECT "column1" as column10_1,
                               "column2" as column21_1
                        FROM "table1" as T1) as T1) as T1
            LIMIT 71) as T1) as T1
test: Failed
opaleye-0.3.1.2: test (suite: tutorial)
Test suite failure for package opaleye-0.3.1.2
    test:  exited with: ExitFailure 1
Logs printed to console
```

**Comment by tomjaguarpaw** [comment]
Is this an error you got running the test suite locally?  If so are you running on 9.3?  It's probably this bug https://github.com/tomjaguarpaw/haskell-opaleye/issues/62 which I should get time to fix this weekend.  It will, unfortunately, prevent you testing locally unless you get a 9.4 server up.

**Comment by bergmark** [comment]
Yeah we're on 9.3

**Comment by tomjaguarpaw** [comment]
Apologies for the breakage on 9.3.  9.4 has a very convenient syntax that allows you to do a `SELECT` of zero columns.  This change didn't actually make anything *more* broken on 9.3 as the older version had a bug anyway.  Just make sure you don't select zero columns until I fix it!

**Comment by hesselink** [comment]
Good to know, I'll close this one then as it's a duplicate of #62.
