### ISSUE TITLE
Compare two newtype columns

### ISSUE THREAD

**Issue by coubeatczech** [tomjaguarpaw/haskell-opaleye#75]
When I have wrap an id in a newtype, then I need to unwrap it every time when I need to do something useful with it.

    newtype CompanyId' id = CompanyId { getCompanyId :: id }
    type CompanyId = CompanyId' Int
    makeAdaptorAndInstance "pCompanyId" ''C.CompanyId'

Then I need to do the unwrapping everytime:

    restrict -< C.getCompanyId companyPK .== (pgInt4 . C.getCompanyId) companyId

Whereas I'd like to write:

    restrict -< companyPK .== companyId

Does anyone have some nice solution for this?

**Comment by tomjaguarpaw** [comment]
Yes, please try with the `ppEq` branch and report your experience.  (This only solves half of your problem.  The other half needs https://github.com/tomjaguarpaw/haskell-opaleye/issues/28)

https://github.com/tomjaguarpaw/haskell-opaleye/blob/ppEq/src/Opaleye/Operators.hs#L31

**Comment by coubeatczech** [comment]
Thanks!

Yes, solving the other part would help greatly, too.

**Comment by tomjaguarpaw** [comment]
You might want to have a go at implementing #28, by the way.  Given what you've done already it should be easy for you.  It needs a product profunctor `LiftConstant` (or whatever) with `Default` instances

* `Default LiftConstant Int (Column PGInt4)`
* `Default LiftConstant Text (Column PGText)`
* `Default LiftConstant String (Column PGText)`

etc.. To get the nullable types to combine nicely with the instance you could use a trick like `QueryRunnerColumn` https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Internal/RunQuery.hs#L63

**Comment by tomjaguarpaw** [comment]
In fact it should probably just be `newtype LiftConstant a b = LiftConstant (a -> b)` but you'll probably want to check that in case I made a mistake.

**Comment by coubeatczech** [comment]
Which problem are you trying to solve with having the non-productprofunctor `QueryRunnerColumn`? I'm able to make it work for both nullable and non-nullable type with no extra data/typeclass.

    instance D.Default LiftConstant String (Column PGText) where
    instance D.Default LiftConstant Int (Column PGInt4) where
    -- other instances
    instance 
      (D.Default LiftConstant a (Column b)) =>
      D.Default LiftConstant (Maybe a) (Column (IC.Nullable b)) where

    newtype LiftConstant haskell pgType = LiftConstant { runLiftConstant :: haskell -> pgType }

The thing which I'm a bit worried about is the type inference when the user create the data using literals:

      lifted :: (Column PGInt4, Column PGFloat8, Column PGText, Column (IC.Nullable PGText))
      lifted = liftHaskell (3 :: Int, 5.0 :: Double, "Hi!", Nothing :: Maybe String)

I don't see an obvious way how to avoid it, especially typing `Nothing :: Maybe String` is not very convenient. It won't probably be the usual use case, I think that usually the user will have a record of known types that was created somewhere in the application and now he just wants to insert it into db.

**Comment by bergmark** [comment]
We implemented this by accident in our wrapper library ;-) I don't understand your use case I think.

We have since removed it in order to explicitly disallow comparing different newtypes. It doesn't make sense to e.g. join a `User.Id` with an `Article.Id`, it's a bug even, and we want a type error if that happens.

**Comment by coubeatczech** [comment]
@bergmark 
I definitely don't want to compare two different newtypes, but this issue is aiming at having the possibility to compare two values wrapped in the same newtype. Can you do it now without unwrapping them beforehand?

**Comment by bergmark** [comment]
Ah good :-)

We use https://github.com/silkapp/silk-opaleye/blob/master/src/Silk/Opaleye/ShowConstant.hs

The caveat with our approach is that a haskell type can only have one opaleye representation, but it's not an issue for us.

**Comment by coubeatczech** [comment]
It looks like what you are doing is aimed more at:
* not having to specify the type when running the query and not using the field - in that that case the inferencer can't see the haskell type so it can't find the instance
* being able to use the `constant` function for any conversion from haskell to pgtype and not think about if it's called `pgInt4` or `pgStrictText` etc.

What I'd like to have here is a function `MyNewtypeWrapper Int -> MyNewtypeWrapper PGInt4`.

I don't see a way how to do it with `constant` function, the approach drafted here is using the `Default` instance generated by running the `makeAdaptorAndInstance` on the newtype, which enables to change the type under the newtype.

**Comment by tomjaguarpaw** [comment]
I can't remember what exactly when wrong without `QueryRunnerColumn`.  One thing is that I don't like generating instances for `Default LiftConstant (Maybe (Maybe a)) (Column (Nullable (Nullable b))` since they are unnecessary, but perhaps they're not a big deal.  Besides that I thought there was some problem with overlapping instances, but perhaps I'm misremembering.

**Comment by tomjaguarpaw** [comment]
@coubeatczech I'm going to add the "lift constant" functionality soon because Neil Mitchell wants it.

**Comment by tomjaguarpaw** [comment]
> Which problem are you trying to solve with having the non-productprofunctor QueryRunnerColumn?

Now that I'm looking at it again it seems that `QueryRunnerColumn` doesn't even solve the `Default LiftConstant (Maybe (Maybe a)) (Column (Nullable (Nullable b))` problem.

**Comment by tomjaguarpaw** [comment]
Now added https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/Constant.hs
