### ISSUE TITLE
Why was literalColumn moved to Internal?

### ISSUE THREAD

**Issue by bergmark** [tomjaguarpaw/haskell-opaleye#76]
```
In the use of ‘literalColumn’ (imported from Opaleye.PGTypes):
    "'literalColumn' has been moved to Opaleye.Internal.PGTypes"
```

We use this for [our ShowConstant](https://github.com/silkapp/silk-opaleye/blob/master/src/Silk/Opaleye/ShowConstant.hs#L138)

**Comment by tomjaguarpaw** [comment]
I think this is right to be in `Internal`.  Normal users shouldn't use it.  For your `ShowConstant` you need access to the internals so it makes sense to import it from there.

**Comment by bergmark** [comment]
Actually we don't! We can just do e.g. `unsafeCoerce . pgString` instead, much better since we don't have to duplicate the conversion logic then. Not sure how that escaped me before.

**Comment by bergmark** [comment]
Cheers!
