### ISSUE TITLE
arrangeInsertSql PGText ?

### ISSUE THREAD

**Issue by delanoe** [tomjaguarpaw/haskell-opaleye#78]
Hello,
following manipulation tutorial. Int4 insertion works fine but what about inserting PGText ?
let be this:
import Opaleye as O
table' :: O.Table (Maybe (Column O.PGInt4), Column O.PGText, Column O.PGText)
                             (Column O.PGInt4, Column O.PGText, Column O.PGText)
O.arrangeInsertSql table' (Nothing, "ABC", "TEST")
gives:
    Couldn't match expected type ‘Column PGText’
                with actual type ‘[Char]’
    In the expression: "ABC"
and:
    Couldn't match expected type ‘Column PGText’
                with actual type ‘[Char]’
    In the expression: "TEST"

So, I have to change type of "ABC" into 'Column PGText'

I suppose there is an easy way to do it already.
If not tell me, maybe I could patch it.

Cheers,
anoe

**Comment by tomjaguarpaw** [comment]
[`pgString`](https://github.com/tomjaguarpaw/haskell-opaleye/blob/master/src/Opaleye/PGTypes.hs#L59)

**Comment by delanoe** [comment]
Indeed, works fine with:
O.arrangeInsertSql table' (Nothing, O.pgString "ABC", O.pgString "TEST")
Thanks.
