### ISSUE TITLE
runInsertReturning :: [..] -> IO [haskells] ?

### ISSUE THREAD

**Issue by delanoe** [tomjaguarpaw/haskell-opaleye#82]
Hello,
following the Manipulation Tutorial, I can arrangeInsertReturningSql very well on my tables but I can hardly find how to manage the returning types of runInsertReturning.

Suppose the tutorial example:
> insertReturning :: String
> insertReturning = arrangeInsertReturningSql def' table (Nothing, 4, 5)
>                                             (\(id_, _, _) -> id_)
>                   where def' :: U.Unpackspec (Column a) (Column a)
>                         def' = def 

Since I have:
 :t O.arrangeInsertReturningSql 
O.arrangeInsertReturningSql
  :: Unpackspec returned ignored
     -> Table columnsW columnsR
     -> columnsW
     -> (columnsR -> returned)
     -> String

I suppose that I would have:
testInsertReturnging  = runInsertReturning conn table (Nothing, 4, 5)
                                            (\(id_, _, _) -> id_) where
                                                 conn <- PGS.connect confidentialInfo

since
O.runInsertReturning  :: Default O.QueryRunner returned haskells =>
     PGS.Connection
     -> Table columnsW columnsR
     -> columnsW
     -> (columnsR -> returned)
     -> IO [haskells]

What does IO [haskells] mean ? Do you have an example of usage ?

let id = testInsertReturning
How to manage/print id ?
Thanks for help for this basic question I guess.
anoe

**Comment by tomjaguarpaw** [comment]
Please give me some example input (input table, data to write, and function
to return) and I will tell you how to express the type.

**Comment by tomjaguarpaw** [comment]
Please give me some example input (input table, data to write, and function to return) and I will tell you how to express the type.

**Comment by delanoe** [comment]
Ok, thanks.

I keep the example on the TutorialManipulation.lhs in order to feed it incrementally.

Suppose this table1:
> table1 :: Table (Maybe (Column PGInt4), Column PGFloat8, Column PGFloat8)
>                (Column PGInt4, Column PGFloat8, Column PGFloat8)
> table1 = Table "tablename1" (p3 (optional "id", required "x", required "y"))

Suppose this table2:
> table2 :: Table (Maybe (Column PGInt4), Column PGInt4, Column PGFloat8)
>                (Column PGInt4, Column PGInt4, Column PGFloat8)
> table2 = Table "tablename2" (p3 (optional "id", required "id_from_table1", required "z"))

Then I insert data in table1:
testInsertReturnging = runInsertReturning conn table1 (Nothing, 4, 5)
((id_, , _) -> id) where
conn <- PGS.connect confidentialInfo

I would like to insert in table2: 
runInsert conn table2 (Nothing, id_from_table1, 3)

How do you write it please ?
Thanks again.
anoe

**Comment by tomjaguarpaw** [comment]
What problem did you have with this?  Your code works almost exactly as it is.  Did you not know how to read a value of type `haskells` out?  In this case it is just an `Int`.

    table1 :: Table (Maybe (Column PGInt4), Column PGFloat8, Column PGFloat8)
                    (Column PGInt4, Column PGFloat8, Column PGFloat8)
    table1 = Table "tablename1" (p3 (optional "id", required "x", required "y"))
    
    table2 :: Table (Maybe (Column PGInt4), Column PGInt4, Column PGFloat8)
                    (Column PGInt4, Column PGInt4, Column PGFloat8)
    table2 = Table "tablename2" (p3 (optional "id", required "id_from_table1", required "z"))
    
    
    -- Works with or without either of these type signatures
    --
    -- testInsertReturning
    --  :: Opaleye.Internal.RunQuery.QueryRunnerColumnDefault
    --       PGInt4 haskells =>
    --     Connection -> IO [haskells]
    --
    -- testInsertReturning
    --   :: Connection -> IO [Int]
    testInsertReturning conn = runInsertReturning conn table1 (Nothing, 4, 5)
                                                               (\(id_, _, _) -> id_)
    
    -- Works with or without this type signature
    --
    -- testInsert :: Connection -> Column PGInt4 -> IO GHC.Int.Int64
    testInsert conn id_ = runInsert conn table2 (Nothing, id_, 3)
    
    main = do
      conn <- connect undefined -- Whatever
    
      [id_] <- testInsertReturning conn
    
      testInsert conn (pgInt4 id_)

**Comment by delanoe** [comment]
in fact try this:
[id_] <- testInsertReturning conn

I get:
<interactive>:5:10:
    No instance for (Opaleye.Internal.RunQuery.QueryRunnerColumnDefault
                       PGInt4 haskells0)
      arising from a use of ‘O.runInsertReturning’
    The type variable ‘haskells0’ is ambiguous
    Note: there is a potential instance available:
      instance Opaleye.Internal.RunQuery.QueryRunnerColumnDefault
                 PGInt4 Int
        -- Defined in ‘Opaleye.Internal.RunQuery’
    In the first argument of ‘GHC.GHCi.ghciStepIO ::
                                IO a_a6mZ -> IO a_a6mZ’, namely
      ‘O.runInsertReturning
         conn table1 (Nothing, 4, 5) (\ (id_, _, _) -> id_)’
    In a stmt of an interactive GHCi command:
      [id_] <- GHC.GHCi.ghciStepIO :: IO a_a6mZ -> IO a_a6mZ
               (O.runInsertReturning
                  conn table1 (Nothing, 4, 5) (\ (id_, _, _) -> id_))

I can hardly debug it (maybe it is obvious but I do not see how).
Thanks for help.

**Comment by tomjaguarpaw** [comment]
You need to use `id_` in a way that tells the compiler what type it is.  If you use it as an argument to `pgInt4` then that will be sufficient.  If you don't, you can try something like

      [id_] <- testInsertReturning conn
      let _ = id_ :: Int

**Comment by delanoe** [comment]
In fact, he script works well when I runghc (synonym of runhaskell on Debian) it but it does not in ghci.
To test it in ghci, I had to call main. (Calling "[id_] <- testInsertReturning conn" gives the error above).
Thanks for taking the time to indicate me the right way to use IO [haskells].

**Comment by tomjaguarpaw** [comment]
If you want to use ghci then you can try

      [id_] <- (testInsertReturning conn :: IO [Int])

**Comment by delanoe** [comment]
2015/07/25 14:24, tomjaguarpaw:
> If you want to use ghci then you can try
>   [id_] <- (testInsertReturning conn :: IO [Int])

Ok, thanks.

-- 
Alexandre Delanoë
