### ISSUE TITLE
Saving PGTimestamptz with milliseconds

### ISSUE THREAD

**Issue by bitc** [tomjaguarpaw/haskell-opaleye#84]
It seems that when I save a `PGTimestamptz` using the `pgUTCTime` function, the milliseconds are stripped out and not saved to the PostgreSQL database.

**Comment by tomjaguarpaw** [comment]
Thanks for the report.  Can you tell me whether it works with this branch: https://github.com/tomjaguarpaw/haskell-opaleye/tree/pgUTCTimeMicroseconds

**Comment by bitc** [comment]
Thanks, I tried it. It works perfectly!

**Comment by bitc** [comment]
btw, How about also giving the same treatment to `PGTimestamp` / `pgLocalTime` ?

**Comment by tomjaguarpaw** [comment]
Yes, those should be done too.

**Comment by tomjaguarpaw** [comment]
Fixed by https://github.com/tomjaguarpaw/haskell-opaleye/commit/88a60c92fb899e8b3d606980cd56668ef5479075
