### ISSUE TITLE
Add complete example for ORDER BY, OFFSET, LIMIT

### ISSUE THREAD

**Issue by bitc** [tomjaguarpaw/haskell-opaleye#93]
It would be nice if there was a complete example for how to use these, since it is not clear from the docs

**Comment by tomjaguarpaw** [comment]
Hi @bitc.  What would you like to see by way of example for `orderBy` besides [that which is already in the docs](http://hackage.haskell.org/package/opaleye-0.4.0.0/docs/Opaleye-Order.html)?

I can certainly add examples for `offset` and `limit` but again a hint from you about what sort of thing you are looking for would be useful.

**Comment by bergmark** [comment]
I typically use them like this:
```
maybe id limit (mlim :: Maybe Int) . orderBy (contramap fst $ desc (arr createdTime) <> desc (arr id_)) $ query
```

**Comment by tomjaguarpaw** [comment]
Why do you use `arr`?  Is that a hang over from the old `ExprArr` days?  It shouldn't be needed anymore.

**Comment by bergmark** [comment]
Yeah, probably!

**Comment by tomjaguarpaw** [comment]
Also you can do `desc (createdTime . fst)` rather than using `contramap`.  It probably reads a bit nicer.

**Comment by bitc** [comment]
For example, I can't figure out how to do something like the following query:


```
CREATE TABLE thetable (
  name text,
  num int
);

INSERT INTO thetable
    SELECT 'John',
    (SELECT num FROM thetable ORDER BY num DESC LIMIT 1) + 1;
```

**Comment by bergmark** [comment]
@tomjaguarpaw the reason I use contramap is that I can pull out the ordering so it works for all queries involving this table:
```
timeIdOrder :: Order (To Column InviteEvent)
timeIdOrder = desc createdTime <> desc id'
```

**Comment by tomjaguarpaw** [comment]
I don't understand.  How does the `contramap` help with that.  It seems to me that `contramap fst $ desc (arr createdTime)` and `desc (createdTime . fst)` should be the same.

**Comment by bergmark** [comment]
It's a matter of taste, but I think it makes everything clearer incl. the type signature of the ordering, compare:

```haskell
query1 = orderBy (contramap fst timeIdOrder) $ q1 &&& q2
query2 = orderBy timeIdOrder $ q1
timeIdOrder :: Order (To Column InviteEvent)
timeIdOrder = desc createdTime `mappend` desc id'
```

vs

```haskell
query1 = orderBy (timeIdOrder fst) $ q1 &&& q2
query2 = orderBy (timeIdOrder id) $ q1
timeIdOrder :: (a -> To Column InviteEvent) -> Order a
timeIdOrder f = desc (createdTime . f) `mappend` desc (id' . f)
```

**Comment by tomjaguarpaw** [comment]
Oh right, I didn't notice the `contramap` applied to both `desc`s!

**Comment by bergmark** [comment]
sorry for hijacking the thread @bitc!

**Comment by tomjaguarpaw** [comment]
@bitc, You can do it in one of two ways.  They both amount to the same thing, but one uses Arrow notation and the other doesn't.  Do you find either of these easy to understand?  If not let's keep working to clarify it so I can write a good example for the docs.

    {-# LANGUAGE Arrows #-}
    
    import Opaleye
    import Data.Profunctor.Product
    import Control.Arrow
    
    theTable :: Table (Column PGText, Column PGInt4)
                      (Column PGText, Column PGInt4)
    theTable = Table "theTable" (p2 ( required "text", required "int"))
    
    biggestNum :: Query (Column PGInt4)
    biggestNum = (fmap (+1)
                  . limit 1
                  . orderBy (desc id)
                  . fmap snd
                  . queryTable)
                 theTable
    
    biggestNum' :: Query (Column PGInt4)
    biggestNum' = proc () -> do
      num <- limit 1 $ (orderBy (desc id) $ proc () -> do
        (_, num) <- queryTable theTable -< ()
        returnA  -< num) -< ()
    
      returnA -< (num + 1)

**Comment by tomjaguarpaw** [comment]
By the way, those example just make queries that return the row 1 + maximum from the database.  Insert will have to be done separately.

**Comment by bitc** [comment]
Thanks, those both make sense. My trouble was that I was trying to do the insert and the select in a single query. So Opaleye is not capable of creating such queries?

**Comment by tomjaguarpaw** [comment]
Not currently, though it has been requested https://github.com/tomjaguarpaw/haskell-opaleye/issues/29

It's not high up my personal list of priorities, but I'm happy to work with anyone who wants to add it.

**Comment by tomjaguarpaw** [comment]
Closing this as what was wanted seems to be slighly different.  I've added a comment to the `Manipulation` Haddock (to be pushed soon) that explains you cannot insert or update with selects.
