### ISSUE TITLE
Add more documentation for "Newtypes"

### ISSUE THREAD

**Issue by bitc** [tomjaguarpaw/haskell-opaleye#96]
I hope it's ok that I'm posting such issues here. There doesn't seem to be any other appropriate place to ask Opaleye questions, and learning to use Opaleye is very difficult given that the internals are very scary.

1. In the TutorialBasic.lhs example there is a newtype example with WarehouseId. It explains that using the `.==` operator will fail when comparing to an invalid field. But it doesn't explain how to compare to a valid field. For example, this fails to compile: `wId w .== wId w`

2. Guidance on how to have a newtype field be "Nullable" would be appreciated. How does one make the WarehouseIdColumn nullable here:

``` haskell
type GoodWarehouseColumn = Warehouse' WarehouseIdColumn
                                      (Column PGText)
                                      (Column PGInt4)
```

Chaning the column to `(Nullable WarehouseIdColumn)` doesn't seem to work.

**Comment by bergmark** [comment]
I'm not familiar with the tutorial, but I can give this a shot:

1. What type does `wId w` have for you? `(.==) :: Column a -> Column a -> Column PGBool` so any type in a column can be compared for equality.

2. You need something of type `Column (Nullable a)`, the ordering of Column vs Nullable must be like this since Nullable doesn't mean anything outside of a Column. So if `type WarehouseIdColumn = Column WarehouseId` or similar it won't work.

**Comment by tomjaguarpaw** [comment]
Hi @bitc.  I'd prefer questions to be asked [on the mailing list](https://lists.sourceforge.net/lists/listinfo/opaleye-users) but here is also fine.

1. Yes, I can see this is much more awkward than it needs to be.  For now you need to unwrap the `Column`s from inside the `WarehouseIdColumn` and then apply `.==`, sorry!

2. To make a newtype field nullable you need to put the `Nullable` all the way inside the column.  So you need something like

    newtype WarehouseIdColumn = WarehouseIdCoulmn (Column (Nullable PGInt4))

**Comment by bitc** [comment]
Thanks, if I have any more questions in the future I'll use the mailing list.

But a quick followup regarding 2: Which corresponding type should go the other part of the table definition for the corresponding column? `(Maybe WarehouseId)` doesn't seem to work. What does seem to work is `(WarehouseId' (Maybe Int))` but that seems pretty cumbersome. Is that the correct way?

**Comment by tomjaguarpaw** [comment]
Yes, `(WarehouseId' (Maybe Int))` is the correct way, at least for now or unless @bergmark can help you out with some of Silk's secret sauce for dealing with this stuff.

**Comment by bergmark** [comment]
It's not secret :-) https://github.com/silkapp/silk-opaleye but it's also not documented outside of haddocks yet.

What I found helpful in the beginning was to write the types out explicitly without type aliases, lots of boilerplate but then you get an idea of how you can abstract it.

**Comment by tomjaguarpaw** [comment]
1. Is now fixed.  You can use `.===` to compare through `newtypes`.  (This may be unifed with `.==` in a later version).

**Comment by tomjaguarpaw** [comment]
This seems to be resolved.  If there are any more issues feel free to reopen or file a new issue.
